### ISSUE TITLE
Ideas and progress

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/PyO3#1]
1. Seems rust-cpython is on hold right now, no changes, pr hangs without attention for months.
2. as I have now enough experience with rust_cpython py_class implementation, I think it is not good solution. It is separate language within rust. it is very hard to understand and extend.

I work on new py class implementation based on procedural macros and specialization, but that requires rust nightly. should be ready in several days.

**Comment by fafhrd91** [comment]
new code will look something like this

```rust

#[py_class]
struct TestClass {
    data: Cell<bool>
}

#[py_impl]
impl TestClass {

  #[method]
   fn test_method(&self, val: PyObject) {}
}

#[py_impl]
impl PyObjectProtocol for TestClass {

    fn __call__(&self, args: PyTuple, kwargs: PyDict) -> PyResult<> {
    }

   ...
}

#[py_impl]
impl PyAsyncProtocol for TestClass {
   fn __await__(&self) -> PyResult<PyObject> {}
}
```

**Comment by fafhrd91** [comment]
@1st1 @asvetlov  would you like guys to participate in design work?

**Comment by fafhrd91** [comment]
py_class may accept parameters,

```rust

#[py_class(MyFuture, base=asyncio::Future)]
struct PyFut {}

```

**Comment by fafhrd91** [comment]
big question at the moment how to parse arguments, especially `*,`

**Comment by ohanar** [comment]
I agree that rust-cpython's class design isn't ideal. I would prefer to be able to not tie this library to the nightly compiler, if instead this functionality could be done through a custom derive. Something along the lines of the following:

```rust
#[derive(PythonClass)]
#[py_methods(my_method(u64, String), my_other_method)]
#[py_traits(PyFunction(PyTuple, ())]
struct MyClass(...);

impl MyClass {
    fn my_method(&self, x: u64) -> PyResult<String> {
        ...
    }
    fn my_other_method(&self) {
        ...
    }
}

impl PyFunction for MyClass {
    fn __call__(&self, y: PyTuple) -> PyResult<()> {
        ...
    }
}
```
It obviously isn't as nice as what you get with custom attributes (and maybe you could do better than this with some hackery, haven't really thought about it too much), but it should work with stable rust.

**Comment by fafhrd91** [comment]
problem is how to define special methods, like PyAsyncMethods of PyNumberMethods. you need access to impl block, and you need to enumerate and generate description during macro expansion.

I couldn't find any other way :)

**Comment by fafhrd91** [comment]
right now, special method implementation is very simple, for example sequence protocol https://github.com/PyO3/PyO3/blob/master/src/class/sequence.rs#L19
btw sequence protocol is not implemented by rust-cpython properly, because of ambiguity of method definitions

**Comment by fafhrd91** [comment]
added methods and properties implementation

```rust

#[class]
struct MyClass {}

#[methods]
impl MyClass {

  fn method(&self, py: Python, arg: PyObject) -> PyResult<()> {
     Ok(())
  }

  #[getter]
  fn get_prop1(&self, py: Python) -> PyResult<PyObject> {...}

  #[setter]
  fn set_prop1(&self, py: Python, value: PyObject) -> PyResult<()> {...}

  #[getter(prop2)]
  fn get_some_prop(&self, py: Python) -> PyResult<PyObject> {...}

  #[setter(prop2)]
  fn set_some_prop(&self, py: Python, value: PyObject) -> PyResult<()> {...}

}
```

next is "#[class]" macro and argument parsing

**Comment by ohanar** [comment]
One thing that I like about `rust-cpython` is that I don't have to manually convert each argument and return result (although I can if I want to). Also, I don't like that there are currently dangling methods when you implement protocols. What about something like this:

```rust
trait PySequenceProtocol {
    fn __len__(&self, py: Python) ->Self::Result where Self: PySequenceLenProtocol;
    fn __getitem__(&self, py: Python, key: Self::Key) -> Self::Result where Self: PySequenceGetItemProtocol;
    ...
}

trait PySequenceLenProtocol: PySequenceProtocol {
    type Result: IntoPyResult<Target=usize>; 
}

trait PySequenceGetItemProtocol: PySequenceProtocol {
    type Key: From<isize>; // or maybe something like TryFrom<isize, Err=Self::Result>
    type Result: IntoPyResult<Target=()>;
}
```

I'll try to prototype something along these lines latter tonight.

**Comment by fafhrd91** [comment]
arg parser is next after `#[class]`

regarding dangling methods, those are visible only in rust code, python code does not see unimplemented methods. I don't know how to make method signature explicit and optional at the same time

**Comment by fafhrd91** [comment]
`py_class!` is dropped, `#[class]` is implemented.

**Comment by ohanar** [comment]
Unfortunately I didn't have as much time as I would like tonight to work on this. I pushed what I did tonight here: 49c35026a09eb3872e3ef93dcedfc5bc9958160a. The idea is to make rust's trait system do most of the heavy lifting. I haven't touched the attribute macros yet, but all that it should need to do for slotted methods is take something like the following:

```rust
#[py_impl]
impl PyMappingProtocol for MyClass {
    fn __len__(&self, py: Python) -> usize {
        ...
    }

    fn __getitem__(&self, py: Python, key: String) -> PyResult<i32> {
        ...
    }
}
```
And add the following marker trait impls:
```rust
impl PyMappingLenProtocol for MyClass {
    type Success = usize;
    type Result = usize;
}

impl PyMappingGetItemProtocol for MyClass {
    type Key = String;
    type Success = i32;
    type Result = PyResult<i32>;
}
```
After that is done, then some corresponding Impl traits will wrap the methods appropriately, and bundle them up into a `PyMappingMethods` struct (with null pointers in any slot that hasn't had it's marker trait impl'ed).

I'll try to work more on this over the next couple of days.

**Comment by fafhrd91** [comment]
That's awesome. I'll play with this idea too

**Comment by fafhrd91** [comment]
@ohanar 
it is not possible partially implement protocol, for example if I need inly `__getitem__` method, nothing else, with this approach, I have to implement all methods. imaging something like PyNumberProtocol.
but I really like you idea! maybe we can somehow adjust implementation in attribute macro?

**Comment by fafhrd91** [comment]
we can add default method implementation with attribute macro

**Comment by ohanar** [comment]
Yes, I noticed that right after writing my post, and added a default implementation: 3be2c9c1041da02d3c33cf17a390b03ad3be4b49. Because of the marker traits, those methods don't really exist unless you implement the corresponding marker trait (the rust compiler just won't let you call them), so the method is more or less unchanged.

**Comment by fafhrd91** [comment]
that is so awesome! I love rust :)

**Comment by fafhrd91** [comment]
@ohanar I implemented mapping interface with your idea! https://github.com/PyO3/PyO3/commit/2eea45e9faed47acff0f6685e048c51cdbbb5f7e

**Comment by ohanar** [comment]
Very cool! I'm glad the macro code is as straightforward I hoped (admittedly I haven't yet written any macros using syn+quote, but I've read through their docs, and it seemed like it would be straightforward).

Now we just need macros to generate all of the traits and their impl's :).

**Comment by fafhrd91** [comment]
yes, that will take some time

**Comment by ohanar** [comment]
FYI, I'm working on a macro to help with this.

**Comment by fafhrd91** [comment]
@ohanar very good!

could you check this code https://github.com/PyO3/PyO3/blob/master/src/conversion.rs#L136
we don't really need to implement `ToPyObject` for new classes,
 `impl<T> ToPyObject for T where T: PythonObject` should provide default implementation. but I can not make it work because we have another 
`impl <'a, T: ?Sized> ToPyObject for &'a T where T: ToPyObject`
I am not sure how to resolve conflict or if it event possible.

**Comment by ohanar** [comment]
This can't currently be resolved. The issue is rust doesn't know which impl to use for an `&T where T: ToPyObject, &T: PythonObject`. Obviously we know that these shouldn't exist, but there is no way to encode that in rust. Unfortunately, specialization (currently) doesn't help us either, since it is restricted to specializing subsets (and neither one of these is a subset of the other).

I personally think that the impl for `T PythonObject` is more useful, since if you have a ref `&T` and you call `to_py_object` on it, rust should automatically deref it and see the implementation for the underlying `T`. (This doesn't work with `into_py_object` since that consumes `T` and derefing only allows you to use `&self` or potentially `&mut self` methods.)

**Comment by ohanar** [comment]
I pushed my work in progress of the boilerplate generator to my fork. I probably won't have time to work on it much more for a couple of days.

It needs a little more work on the parsing side of things (mainly needs to handle special edge cases, like __setitem__/__getitem__, and quite a bit more work on the code generation side. Right now it just generates the public facing traits, so long as all of the arguments and the return type are python objects.

**Comment by fafhrd91** [comment]
I came to similar conclusion on `ToPyObject`. In any case trait get generated by macros, it could wait

**Comment by fafhrd91** [comment]
I added ability to specify py methods in protocol, some protocol fn needs to be py methods and not slots, i.e. `__aenter__` but open opportunity to extent protocols beyond just slots. We can add `keys`, `items` etc to PyMappingProtocol

**Comment by wdv4758h** [comment]
This fork is interesting !

I'm new to `rust-cpython`, and still trying to figure out what things has done by the macro. In my trying, I start to think it should be a better way, and you guys look like already working on it !!! 👍 😃

**Comment by fafhrd91** [comment]
@ohanar i am not sure how to use reference in assitiated type without attaching lifetime everywhere

**Comment by fafhrd91** [comment]
ok, figured this out myself.

**Comment by fafhrd91** [comment]
it seems it is not possible to use associated types for protocol implementation if type needs to be generic over lifetime (references), we need HKT for this.

am I wrong?

**Comment by ohanar** [comment]
I haven't had the chance to look at your pyptr branch in depth enough to see why things are failing, but I'm not sure that we need HKTs for this. I think my original signature was a slightly off; I think it should be something more like this:
```rust
trait PyMappingProtocol: ... {
    fn __setitem__<'a, 'b>(&self, /* py: Python */, key: Self::Key, value: Self::Value) -> Self::Result
        where Self: PyMappingSetItemProtocol<'a, 'b>
    { unimplemented!() }

   ....
}

trait PyMappingSetItemProtocol<'a, 'b>: PyMappingProtocol {
    type Key: FromPyObject<'a>;
    type Value: FromPyObject<'b>;
    type Success: ToPyObject;
    type Result: Into<PyResult<Self::Success>>;
}
```
That is methods should be generic over a lifetime for each python object argument. If you still run into issues with this, we could always remove the lifetime parameter from `FromPyObject` and make it dual to `ToPyObject` in the sense that it always will clone data. (I think the only place where an actual borrow happens at the movement is if you try to convert a python utf8 string into a rust `&str` or `Cow<str>`. The only other place that I think you might be able to do that is converting a python bytearray into a rust `&[u8]` or `Cow<[u8]>`.)

**Comment by fafhrd91** [comment]
I already removed `<'a>` from `FromPyObject`. And if you need access to bytearray, it is possible just to downcast into PyBytesArray and use data directly.

**Comment by fafhrd91** [comment]
experimenting with multiple lifetimes

**Comment by ohanar** [comment]
It's important the lifetimes be on the methods and method traits, not on the protocol traits.

**Comment by fafhrd91** [comment]
I am closing this ticket. all ideas get merged into master
