### ISSUE TITLE
Link errors when compiling on Windows 7 x64 (gnu and msvc)

### ISSUE THREAD

**Issue by Waelwindows** [PyO3/pyo3#1000]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: `Windows 7 Ultimate Service Pack 1 Build 7601`
 - Your python version: `Python 5.8.2`
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Windows installer
 - Your Rust version (`rustc --version`): `rustc 1.46.0-nightly (6bb3dbfc6 2020-06-22)`
 - Your PyO3 version: `master`

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the Rust code and the Python.

Please also write what exact flags are required to reproduce your results.

Doing `cargo test` on master, fails to build on both `x86_64-windows-pc-gnu` and `x86_64-windows-pc-msvc` for me, in CI and in a real machine, with link errors

gnu: `ld: cannot find -lpython38`
msvc:: `note: LINK : fatal error LNK1181: cannot open input file 'python38.lib'`

PyO3 also errors out with the same errors when [compiling my crate on CI](https://ci.appveyor.com/project/Waelwindows/objset/builds/33697954)

**Comment by davidhewitt** [comment]
Can you make sure that your installed `python.exe` is on your `PATH`? The CI error in particular suggests this is the problem.

**Comment by Waelwindows** [comment]
On my local machine, I already had python's install directory in my path. I tried adding the .exe by itself just in case and there's no change on my end

**Comment by davidhewitt** [comment]
Ok. I might put together a script to help diagnose what is wrong with your installation.

@ethanhs did you decide to start writing an implementation of #870 ? Otherwise I'll put this script somewhere which would be useful for that.

**Comment by ethanhs** [comment]
@davidhewitt I haven't had time. Go ahead!

**Comment by davidhewitt** [comment]
No worries! @Waelwindows I'll post back here with a diagnostic tool by the end of the weekend!

**Comment by davidhewitt** [comment]
@Waelwindows as a starting point can you check out the following repository and paste here the output of the `python_info` example:

https://github.com/davidhewitt/python-config

**Comment by Waelwindows** [comment]
Ok so I tried the  `print_info` example, and here's what I got 
```
interpreter version: CPython 3.8
interpreter path: C:\Program Files\Inkscape\bin\python.exe
libdir: Some("C:\\Program Files\\Inkscape/lib")
shared: true
base prefix: C:\Program Files\Inkscape
ld_version: 3.8
pointer width: 8
```
I'm guessing that it's picking up the python from Inkscape instead of my base install (I did install it afterwards) ?

**Comment by davidhewitt** [comment]
Sorry misclick by me! Yes can you try editing your PATH so it picks up the other python (not inkscape's) first?

**Comment by Waelwindows** [comment]
Ok so I prepended python to my system path to make it first, and here's what I got 
```
interpreter version: CPython 3.8
interpreter path: C:\Users\waelwindows\AppData\Local\Programs\Python\Python38-32\python.exe
libdir: None
shared: false
base prefix: C:\Users\waelwindows\AppData\Local\Programs\Python\Python38-32
ld_version: 3.8
pointer width: 4
```
Looks like it's picking up my system install this time. So I tried building this time, and I got a more sensible error
```
Error: "Your Rust target architecture (64-bit) does not match your python interpreter (32-bit)"
```
And after installing 64-bit python and properly setting the path. It compiles!

Thanks for helping me this much. And I guess I'll figure out how to fix CI on my own then..

**Comment by davidhewitt** [comment]
Great, glad to hear and happy to help!
