### ISSUE TITLE
 pyo3::ffi::Py_SetPythonHome takes a *mut?

### ISSUE THREAD

**Issue by gilescope** [PyO3/pyo3#1017]
Is there any reason that pyo3::ffi::Py_SetPythonHome takes a *mut? I can't imagine that the function changes the contents of the wide string? Can it just take a non-mutable pointer instead?

https://github.com/PyO3/pyo3/blob/a9357ef8a11048b349b777f83aeae1a856fb4cb1/src/ffi/pythonrun.rs

**Comment by kngwyu** [comment]
I confirmed that it is certainly declared with `const wchar_t*`: https://github.com/python/cpython/blob/3.8/Include/pylifecycle.h#L38
It should be `* const`.
