### ISSUE TITLE
Why does PyString::as_bytes insist on valid unicode?

### ISSUE THREAD

**Issue by vorner** [PyO3/pyo3#1018]
Hello

I'm reading through the documentation of 0.11.1 and I'm a bit confused about the purpose behind https://docs.rs/pyo3/0.11.1/pyo3/types/struct.PyString.html#method.as_bytes. Why it returns bytes but still returns `&[u8]` slice?

On one hand, if it returns the slice, there doesn't seem to be any particular need for refusing invalid unicode. On the other hand, if it already is checked for valid unicode, why not have `as_str` and return it as (more convenient) `&str`? Or, would it make sense to have both, one that returns the raw (potentially broken unicode) data as `[u8]` and the other that does the checking and returns `&str`?

Or is the documentation simply stale about the returned error? It seems the low-level function doesn't explicitly say what happens if there's *invalid* utf8 inside.

**Comment by kngwyu** [comment]
As noted in #479, this is the replication of this behavior:
```python
In [3]: s = "\ud800"                                                                                                                                        

In [4]: s.encode("utf-8")                                                                                                                                   
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-4-51974f9e3bbe> in <module>
----> 1 s.encode("utf-8")

UnicodeEncodeError: 'utf-8' codec can't encode character '\ud800' in position 0: surrogates not allowed
```

I agree that it's confusing, but I don't know any way to get 'bytes' from `PyString`.

**Comment by vorner** [comment]
So, can it still happen that the returned byte sequence is not accepted by `str::from_utf8`? If not, is there a good reason not to call it `as_str` instead and return `str::from_utf8_unchecked` from there?

**Comment by kngwyu** [comment]
> So, can it still happen that the returned byte sequence is not accepted by str::from_utf8?

I'm not sure, though it sounds good to rename it `as_str`.

**Comment by davidhewitt** [comment]
`PyUnicode_AsUTF8AndSize` is guaranteeing that this is a UTF-8 encoded byte slice, so definitely should be `&str` return value.

If I were to make a suggestion, I think the methods here should use name and signature of `std::ffi::CStr`:

```
pub fn to_str(&self) -> PyResult<&str>
pub fn to_string_lossy(&self) -> Cow<str>
```
