### ISSUE TITLE
Class method that returns a PyDict/PyList

### ISSUE THREAD

**Issue by bovee** [PyO3/pyo3#102]
I'd like to write a class that directly returns a PyDict (instead of a HashMap<...> so I can have heterogeneous values), but I can't find a nice way to do this. I tried this:
```
#[py::methods]
impl ExampleStruct {
    fn example_method<'p>(&mut self, py: Python<'p>) -> PyResult<&'p PyList> { ... }
}
```

This throws undeclared lifetime errors (presumably from inside the autogenerated code) on compile. If I leave the `'p` lifetime out, the borrow checker complains "data from py is returned" and it has a different lifetime though.

I've searched through the issues and read through (hopefully most) of the documentation, but I can't find an example of how to do this using `py::methods`/`pyfn` or if there's an alternative non-macro-based way I should be using.

**Comment by fafhrd91** [comment]
you can return `PyObject` or `Py<PyList>`. 

somthing like:

```rust
fn example_method(&mut self, py: Python<'p>) -> PyResult<PyObject> {
   let l: &PyList = PyList::new(...);
   return l.into()
}
```

**Comment by bovee** [comment]
Reformated slightly in case anyone needs this for future reference:
```
fn example_method(&mut self, py: Python) -> PyResult<PyObject> {
   let l: &PyList = PyList::empty(py);
   Ok(l.into())
}
```

That works great! Thanks for the fast response and the wonderful library!
