### ISSUE TITLE
Remove `Python::register_any`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1023]
#1020 is set to remove the last internal use case of `register_any`. IMO it adds complexity and now doesn't have a clear use case, should we remove this API (or mark deprecated)?

_Originally posted by @davidhewitt in https://github.com/PyO3/pyo3/pull/1020/files_

Quick github search suggests that @programmerjake is using `register_any` to allow conversion of `&T` for a special case:

https://github.com/programmerjake/algebraics/blob/fefb5a60922a6fa1d1dcb7bd0409c5a0a0e66515/src/python.rs#L30

I don't see any other uses on the whole of github :smile:

**Comment by programmerjake** [comment]
feel free to remove it since you're doing a major version bump anyway, I'll be refactoring `algebraics`'s API when I get around to updating it to PyO3 0.11 or later.

**Comment by kngwyu** [comment]
Thank you for the feedback!

**Comment by kngwyu** [comment]
Closed via #1020
