### ISSUE TITLE
Unable to specify keyword-only arguments

### ISSUE THREAD

**Issue by sunjay** [PyO3/pyo3#1025]
### 🌍 Environment

 - Your operating system and version: Linux Mint 19.3
 - Your python version: Python 3.6.9
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Using apt, no virtualenv
 - Your Rust version (`rustc --version`): rustc 1.44.1 (c7087fe00 2020-06-17)
 - Your PyO3 version: 0.11.1
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: yes

### 💥 Reproducing

Minimal reproduction:

```rust
#[pyfunction("*", a, b)]
fn sum(a: usize, b: usize) -> usize {
    a + b
}
```

This is valid and should be allowed. The arguments `a` and `b` are keyword-only, which means that this function needs to be called as `sum(a=3, b=3)`.

Compiling this produces the error:

```
error: Positional argument or varargs(*) is not allowed after *
   --> src/lib.rs:3:19
    |
  3 | #[pyfunction("*", a, b)]
    |                   ^

error: aborting due to previous error
```

The equivalent Python code that works with Python 3:

```python
def sum(*, a, b):
    return a + b
```

I think this is related to #790 and the subsequent changes made in #792.

**Comment by kngwyu** [comment]
Thank you for reporting!
It looks like I misunderstood this syntax :sweat:

**Comment by dvermd** [comment]
If nobody's already taken this one, I'll give it a try

**Comment by davidhewitt** [comment]
@dvermd please do! I'm happy to answer any questions and review your PR 👍

**Comment by dvermd** [comment]
I'm thinking of replacing the booleans `has_kw`, `has_varargs` and `has_kwargs` in `pyfunctions.rs`  by an enum or a state machine. This part is defining the function.
Is there also any code validating the parameters when calling a function ?

**Comment by davidhewitt** [comment]
Sounds good

>  Is there also any code validating the parameters when calling a function ?

I think you're looking for [`parse_fn_args`](https://github.com/PyO3/pyo3/blob/63ea36fb9060be1a526ff4241509994a4fa22866/src/derive_utils.rs#L34)

**Comment by kngwyu** [comment]
Thanks.

> I'm thinking of replacing the booleans has_kw, has_varargs and has_kwargs in pyfunctions.rs by an enum or a state machine. This part is defining the function.

The current code is already a state machine and I don't think abstracting it more is so meaningful.
What we need is just to treat arguments after `*` as keyword-only arguments in [add_work](https://github.com/PyO3/pyo3/blob/master/pyo3-derive-backend/src/pyfunction.rs#L92)
