### ISSUE TITLE
mod_wsgi and pyo3 module usage in different WSGIApplicationGroup

### ISSUE THREAD

**Issue by kushaldas** [PyO3/pyo3#1028]
If we create a Python module using pyo3, that has to run in the first subinterpreter while using in a web app via mod_wsgi. Otherwise the `import modulename` statement goes into a dead lock.

The `mod_wsgi`  documentation says:
>The consequences of attempting to use a C extension module for Python which is implemented against the simplified API for GIL state management in any sub interpreter besides the first, is that the code is likely to deadlock or crash the process.

This makes impossible to use any module written in `pyo3` in web app which needs to run in different application groups. In the usecases I am thinking `security` is the reason behind different application groups. 

Upstream mod_wsgi documentation: <https://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api>

Is there any solution to this?

**Comment by birkenfeld** [comment]
AFAIK subinterpreters are not (yet) separated enough for mod_wsgi's usage of them to be anything but security by obscurity.

In case this is hard to fix in PyO3: It is well documented in the mod_wsgi docs how to circumvent this problem, and for now I don't think this would be worth a degrading of PyO3 API or performance.

**Comment by kushaldas** [comment]
@birkenfeld Thank you for the input. I am closing this issue, and I can safely point to the above comment in the related discussions.

**Comment by birkenfeld** [comment]
Note that I'm not a developer of PyO3, just a user, so don't take this as gospel :)
