### ISSUE TITLE
Replace ob_type with Py_TYPE

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#1033]
CPython is phasing out using `ob_type` directly in favor of `Py_TYPE`, which is currently a macro but will afaik eventually become a function. Structs with `ob_type` will become opaque. See https://bugs.python.org/issue39573,  https://github.com/python/cpython/pull/21433 and PEP 620 for more details . pyo3 doesn't use `ob_type` in too many places: https://github.com/PyO3/pyo3/search?q=ob_type&unscoped_q=ob_type.

**Comment by davidhewitt** [comment]
Thanks for notifying!
