### ISSUE TITLE
Question: How to convert Python Exception (PyErr) into string for logging

### ISSUE THREAD

**Issue by rohitjoshi** [PyO3/pyo3#1034]
I have a python script which raises exception. How do I print this in the rust log?

**Comment by davidhewitt** [comment]
I'm afraid that there's no good API to format the exception as a Rust string at the moment.

In PyO3 `0.12` I hope that you'll just be able to write something like:

```
log::error!("A Python exception occurred: {}", e.display())
```

or something very similar to this.

**Comment by rohitjoshi** [comment]
Thanks @davidhewitt appreciate your quick response and looking forward to display() function.

In meantime, any other work around? I am even open to using eval() to retrieve from python module

**Comment by davidhewitt** [comment]
I think the best you might be able to do is something like

```
e.restore(py);
let s: String = py.eval(r#"
import traceback
traceback.format_exception()
"#)?.extract(py)?;
let _ = PyErr::fetch();
log::error!("{}", s);
```

I've typed this out on my phone, so might have errors.
