### ISSUE TITLE
Running the examples from their folders produces an error

### ISSUE THREAD

**Issue by matt-keibler** [PyO3/pyo3#105]
I apologize if this is obvious to people that are more experienced with python, but I ran into the following problem when trying out the examples:

```
> python
Python 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from word_count import search
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "word_count/__init__.py", line 4, in <module>
    from ._word_count import search, search_sequential
ImportError: No module named _word_count
```

My rudimentary understanding is that python attempts to import from the word_count folder, which overrides the package that was installed. Running the example from a different folder behaves as expected. If you think it is appropriate, I would like to open a PR that adds some wording to the examples' README.md files to help other people avoid the same mistake that I made.

**Comment by fafhrd91** [comment]
what command did you use for package installation?

what works for me:
```
cd examples/word_count/
python ./setup.py develop
python -c "from word_count import search"
```

**Comment by matt-keibler** [comment]
I copy/pasted from the [README](https://github.com/PyO3/pyo3/blob/master/examples/word-count/README.md), so I ran `python setup.py install` and then ran the python REPL.

**Comment by fafhrd91** [comment]
could you create repo, I'd like to check

**Comment by matt-keibler** [comment]
I created an example repo with steps to reproduce [here](https://github.com/matt-keibler/pyrust-example). Let me know if there is anything else you would like me to do to clarify.

**Comment by fafhrd91** [comment]
intersting, but it works for me. could you check python's site-packages directory for pyrust directories.

do you use virtualenv or system python?

**Comment by fafhrd91** [comment]
also I am on osx, I get pyrust_example-0.1.0-py2.7-macosx-10.12-x86_64.egg directory in site-packages after install

**Comment by matt-keibler** [comment]
I use virtualenv and I have tried this on both OSX and Linux, with the same behavior. I did try it with the Mac's system python and was able to reproduce my issue. On the mac, I see the pyrust_example egg as the last item in the sys.path, but it contains the current working directory as the first entry and I think that is overriding the import.

```
> python -m site
sys.path = [
    '/Users/mkeibler/code/rust/pyrust-example',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python27.zip',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/plat-darwin',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/plat-mac',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/plat-mac/lib-scriptpackages',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/lib-tk',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/lib-old',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/lib-dynload',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
    '/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/site-packages',
    '/Users/mkeibler/.virtualenvs/pyrust-example/lib/python2.7/site-packages/pyrust_example-0.1.0-py2.7-macosx-10.12-x86_64.egg',
]
USER_BASE: '/Users/mkeibler/.local' (exists)
USER_SITE: '/Users/mkeibler/.local/lib/python2.7/site-packages' (exists)
ENABLE_USER_SITE: False
```

I also temporarily renamed the pyrust_example/__init__.py* files and then was able to import the module. Based on that and what I saw before with switching to /tmp, I think that python is searching my current directory for python packages and finding the local one that doesn't include the rust library (it only has the two .py/.pyc files). Does your site-package list also contain the current directory as the first entry?

**Comment by atgiovannini** [comment]
@matt-keibler  I think you are running python from root path of your project. 
And as I understand, when you execute `import pyrust_example` first match could be the same path (or working directory), meaning `"."` or `$(pwd)` if you are running Linux.

Has well when python try to import pyrust_example, at your path, found `pyrust_example/__init__.py`, that contains an import to `from ._pyrust_example ...` at this point I think python it's trying to read a file un your path like that `pyrust_example/_pyrust_example.so` or similar, but the installed and compiled file is under `site-packages/pyrust_example......egg..../pyrust_example/_pyrust_example`.

I suggest doing, 
`cd ..`, or `cd ~`, any command that get you out of you project folder. And will work.

**Comment by matt-keibler** [comment]
@atgiovannini Yes, that was my original issue and I mentioned that I could cd out of the folder to successfully run the example. I was asking if it would be useful to update the documentation to make that more clear to rust developers who might be unfamiliar with the way python handles its packaging system (like I was). Currently, the [Usage](https://github.com/PyO3/pyo3/blob/master/examples/word-count/README.md#usage) section of the examples' README files doesn't specify that it needs to be run outside of the directory that the user is currently in when running the Build section's command.
