### ISSUE TITLE
Get a mutable reference from other objects

### ISSUE THREAD

**Issue by atgiovannini** [PyO3/pyo3#106]
Hi,

I'm migrating some core parts of a python project to Rust, but at some point got blocked trying to get a mutable reference (of another own object) in method signatures.

As an example, while this is compiling.

```
fn content(&self, _py: Python, other: &MyOtherClass) -> PyResult<String> {
        Ok(other.value.clone())
}
```

This wouldn't.

```
fn content(&self, _py: Python, other: &mut MyOtherClass) -> PyResult<String> {
     Ok(other.value.clone())
}
```

How do I express the intention of mutating a reference to an object?

**Comment by fafhrd91** [comment]
It does s not possible at the moment. You have to get `Py<MysOtherClass>` and then as_mut

**Comment by fafhrd91** [comment]
https://pyo3.github.io/pyo3/pyo3/prelude/trait.AsPyRef.html#tymethod.as_mut

**Comment by atgiovannini** [comment]
Do you have any example of which traits MyOtherClass should implement in order to extract the PyObject?

So far compiler claims that FromPyObject isn't implemented. Any example is welcome.

**Comment by fafhrd91** [comment]
Sorry for delay, I am traveling at the moment and my availability limited at the moment.

As I understand MyOtherClass is your custom class? It should be annotated with `[py::class]`?

**Comment by atgiovannini** [comment]
Yes, it is. (And also with GC support)

It looks like this:

```
#[py::class(gc)]
struct MyOtherClass {
    value: String,
    token: PyToken,
}
#[py::methods]
impl MyOtherClass {
    #[new]
    fn __new__(obj: &PyRawObject) -> PyResult<()> {
        obj.init(|token| MyClass {
            token: token,
            value: "MyOwnedClass".to_owned(),
        })
    }
}
```

**Comment by fafhrd91** [comment]
I fixed Py<T> impl in master

you should be able to do this:

```rust
fn content(&self, py: Python, other: Py<MyOtherClass>) -> PyResult<String> {
     Ok(other.as_mut(py).value.clone())
}
```

I'll try to add `&mut Class` support and then will make new release

**Comment by fafhrd91** [comment]
mut refs should work now, you should be able to do

```rust
fn content(&self, _py: Python, other: &mut MyOtherClass) -> PyResult<String> {
     Ok(other.value.clone())
}
```

I will release new version of pyo3 shortly.

**Comment by fafhrd91** [comment]
pyo3 0.2.4 is released
