### ISSUE TITLE
Question: Set struct attributes from async task

### ISSUE THREAD

**Issue by Gelbpunkt** [PyO3/pyo3#1062]
## 🌍 Environment

 - Your operating system and version:
 - Your python version: 3.8.3
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: system-wide fedora 32
 - Your Rust version (`rustc --version`): rustc 1.46.0-nightly (2f517ce6f 2020-06-28)
 - Your PyO3 version: 0.11.1
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: no

### Usecase

I have a struct like this:
```rust
#[pyclass]
struct Connection {
    address: String,
    __connection: Option<net::RedisConnection>,
}
```
The idea is that I have a `__new__` that takes the address argument and sets `__connection` to an initial None and a `connect` method that is asynchronous will set the attribute.
```rust
    fn connect(mut self: PyRefMut<Self>) -> PyResult<PyObject> {
        let (fut, res_fut, loop_): (PyObject, PyObject, PyObject) = {
            let gil = Python::acquire_gil();
            let py = gil.python();
            let loop_ = get_loop(py)?;
            let fut: PyObject = loop_.call_method0(py, "create_future")?.into();
            (fut.clone_ref(py), fut, loop_.into())
        };

        task::spawn(async move {
            let res = net::RedisConnection::from_address(&self.address).await;
            match res {
                Ok(conn) => {
                    self.__connection = Some(conn);
                }
                Err(e) => {
                    let gil = Python::acquire_gil();
                    let py = gil.python();
                    ConnectionError::py_err("error when connecting to redis").print(py);
                    return;
                }
            }
            let gil = Python::acquire_gil();
            let py = gil.python();
            if let Err(e) = set_fut_result(loop_, fut, py.None()) {
                e.print(py);
            }
        });

        Ok(res_fut)
    }
```
I have also tried `&mut self` which gave me issues that conn would be outliving the closure.
With this, I get 
```rust
error: future cannot be sent between threads safely                 
   --> src/lib.rs:135:9
    |
135 |         task::spawn(async move {
    |         ^^^^^^^^^^^ future created by async block is not `Send`
    | 
   ::: /home/jens/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/spawn.rs:28:29
    |
28  |     F: Future<Output = T> + Send + 'static,
    |                             ---- required by this bound in `async_std::task::spawn::spawn`
    |
    = help: within `pyo3::pycell::PyCellInner<Connection>`, the trait `std::marker::Sync` is not implemented for `std::cell::Cell<pyo3::pycell::BorrowFlag>`
note: captured value is not `Send`
   --> src/lib.rs:136:59
    |
136 |             let res = net::RedisConnection::from_address(&self.address).await;
    |                                                           ^^^^ has type `pyo3::pycell::PyRefMut<'_, Connection>` which is not `Send`


error: future cannot be sent between threads safely                   
   --> src/lib.rs:135:9
    |
135 |         task::spawn(async move {
    |         ^^^^^^^^^^^ future created by async block is not `Send`
    | 
   ::: /home/jens/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.2/src/task/spawn.rs:28:29
    |
28  |     F: Future<Output = T> + Send + 'static,
    |                             ---- required by this bound in `async_std::task::spawn::spawn`
    |
    = help: within `pyo3::pycell::PyCellInner<Connection>`, the trait `std::marker::Sync` is not implemented for `std::cell::UnsafeCell<Connection>`
note: captured value is not `Send`
   --> src/lib.rs:136:59
    |
136 |             let res = net::RedisConnection::from_address(&self.address).await;
    |                                                           ^^^^ has type `pyo3::pycell::PyRefMut<'_, Connection>` which is not `Send`
```
This is using async-std.

How do I properly set an attribute on the struct itself and access the attributes? There is no documentation on it from what I can see and searching the issues did not give me usable results. The struct itself should be thread-safe as I'm not using unsendable?

Any help would be appreciated :)

**Comment by davidhewitt** [comment]
I think if you convert `self` from `PyRefMut<Self>` to `Py<Self>` then you should be able to move it inside the closure?

`Py<Self>` is both `Send + 'static`.

**Comment by Gelbpunkt** [comment]
@davidhewitt many thanks, I got that working. If you don't mind, I have another question: Suppose I have a PyClass like this:
```rust
#[pyclass]
pub struct Connection {
    __connection: ReConnection,
}
```
where ReConnection is a pure rust struct (`the trait bound ReConnection: pyo3::PyClass is not satisfied`), it is possible to do things like:
```rust
#[pymethods]
impl Connection {
    #[new]
    fn new() -> Self {
        Self { __connection: some_func_that_returns_re_connection() }
    }

    fn foo(&self) -> PyResult<PyObject> {
        Ok(self.__connection.some_func_that_returns_a_string_for_example())
    }
}
```
but I want to initialize a class instance of Connection with a struct value. If I had some_func_that_returns_re_connection, I would be able to that like this:
```rust
let gil = Python::acquire_gil();
let py = gil.python();
let typeobj = py.get_type::<Connection>();
let inst = typeobj.call((), None).unwrap();
```

but I only have the ReConnection object itself at the point where I need to do this.
For clarification: `__connection` is meant to be readable by Rust code but not Python code.
I would love to be able to do something like `let inst = Connection { __connection: my_re_connection_object }.to_object(py);`

Is there anything quite like that?
```

**Comment by davidhewitt** [comment]
I think you might be looking for `let inst: PyObject = Connection { __connection: my_re_connection_object }.into_py(py)`.

**Comment by Gelbpunkt** [comment]
You're a lifesaver - that worked :) 
Many thanks for your help!
