### ISSUE TITLE
Can't cross-compile for Raspberry Pi (probably general cross-compile breakage)

### ISSUE THREAD

**Issue by spease** [PyO3/pyo3#107]
```
cargo build --target=armv7-unknown-linux-gnueabihf
...
  = note: /usr/lib/libpython3.6m.so: file not recognized: File format not recognized
          collect2: error: ld returned 1 exit status
```

**Comment by fafhrd91** [comment]
I guess you need cross compiled python?

**Comment by spease** [comment]
Yeah. It looks like the build.rs just links to the system Python. I think what other Rust libraries do is build the library in a -sys crate that they’re providing wrappers for so that it gets treated (linked) the same as if it were a Rust library. I’m not sure how practical that is to do that with the Python library.

**Comment by spease** [comment]
Example:
https://docs.rs/rdkafka-sys/0.11.1-0/rdkafka_sys/

**Comment by fafhrd91** [comment]
ok, I'll take a look

**Comment by konstin** [comment]
I'm pretty sure this is can be fixed with a cross compiled python
