### ISSUE TITLE
Importing tensorflow causes a crash on exit

### ISSUE THREAD

**Issue by rmarru** [PyO3/pyo3#1073]
### 🌍 Environment

 - Your operating system and version: Ubuntu 18.04.4 LTS (Bionic Beaver)
 - Your python version: Python 3.7.8
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Installed via apt. No virtualenv.
 - Your Rust version (`rustc --version`): 1.45.0
 - Your PyO3 version: 0.11.1
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: Yes

### 💥 Reproducing

Tensorflow version: 2.1.0, installed via pip: `pip3 install tensorflow==2.1.0`

Minimal reproduction:

```rust
use pyo3::prelude::*;

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();

    let _mod = PyModule::import(py, "tensorflow").unwrap();
}
```
On exit:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
          Running `target/debug/pyo3`
corrupted double-linked list
[1]    4387 abort      cargo run
```
or

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
          Running `target/debug/pyo3`
corrupted size vs. prev_size
[1]    5299 abort      cargo run
```

Running import tensorflow directly in python (and exiting the interpreter) exits normally.

Looks like a similar issue to [Importing mxnet causes a segfault on exit #1044](https://github.com/PyO3/pyo3/issues/1044#issue-657897568).

If I comment out `libc::atexit(finalize)` as @kngwyu suggested in [comment](https://github.com/PyO3/pyo3/issues/1044#issuecomment-660464673), the error does not happen and the process exits successfully.

**Comment by davidhewitt** [comment]
#1355 has now merged - we decided to disable finalizing by default because as we see it can lead to weird crashes like this.
