### ISSUE TITLE
Generated extension functions are weakly typed

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [PyO3/pyo3#108]
Consider the README example:
```rust
[pyfn(m, "sum_as_string")]
fn sum_as_string_py(a:i64, b:i64) -> PyResult<String>
```

Here is what happens when this function is called with non-int arguments:

```python
>>> from rust2py import sum_as_string
>>> sum_as_string(1, 2)  # good
'3'

>>> sum_as_string(10**100, 2)  # good
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: int too big to convert

>>> sum_as_string([], [])  # good
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

>>> sum_as_string('1', 2)  # bad
'3'

>>> sum_as_string(1.9, 2.9)  # bad
'3'
```

Generally Python functions that expect int argument raise TypeError when fed strings or floats. This helps to catch some programming errors.
```python
>>> range('42')  # good
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer

>>> range(42.9)  # good
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

I think it would be more consistent if generated extension functions behaved the same way.

**Comment by fafhrd91** [comment]
thanks! this is definitely bug.

**Comment by Vlad-Shcherbina** [comment]
So it seems relevant that I'm running this example on Windows (target_pointer_width="64", target_os="windows"), and that the argument type is `i64` and not, say, `i32`.

The problem appears to be here: https://github.com/PyO3/pyo3/blob/63a2066a39a6389f24ed1d5acda322425ade0937/src/objects/num3.rs#L121-L130

`PyLong_Check(x)` is roughly equivalent to `isinstance(x, int)`, and [`PyNumber_Long(x)`](https://github.com/python/cpython/blob/8ff53564730f7ba503f5ad94418c309c48e8516d/Include/abstract.h#L728) is analagous to `int(x)`, hence the frivolous conversion.

This code was there since it was written in https://github.com/dgrunwald/rust-cpython/commit/55ea6cc85b53566494ae550020b3dcea03de1fc0#diff-2eab662fc2799e2bdab71b4844e11090R155

I wonder if this whole `else` branch should just return `TypeError` instead.

**Comment by fafhrd91** [comment]
but `ffi::PyLong_Check(ptr)` should fail for string, I guess

**Comment by Vlad-Shcherbina** [comment]
`PyLong_Check()` returns `0` on a string, and then `PyNumber_Long()` attempts to parse it.

**Comment by fafhrd91** [comment]
Unexpected :)

**Comment by Vlad-Shcherbina** [comment]
Found another similar instance of weak-typedness that happens for a different reason:
```rust
#[pyfn(m, "take_i32")]
fn take_i32(a: i32) -> PyResult<()> {
    println!("my arg is {}", a);
    Ok(())
}
```
```python
>>> take_i32(42)  # good
my arg is 42

>>> take_i32('42')  # good
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: an integer is required (got type str)

>>> take_i32(42.9)  # bad
my arg is 42
```

This happens because in https://github.com/PyO3/pyo3/blob/63a2066a39a6389f24ed1d5acda322425ade0937/src/objects/num3.rs#L48-L57
, the call to [`PyLong_AsLong()`](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong) is equivalent to calling `__int__()` method on an object. Strings don't have it but floats do.

**Comment by fafhrd91** [comment]
@Vlad-Shcherbina i think this should be fixed now?

**Comment by Vlad-Shcherbina** [comment]
Yes, it's fixed for Python 3.
