### ISSUE TITLE
extension-module should link libpython for Android and Cygwin

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1082]
When browsing documentation earlier this morning I came across a note suggesting that `libpython` should be linked on both `android` and `cygwin` targets (see last paragraph [here](https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build)).

At the moment this is not the case.

We should change `build.rs` so that even with `extension-module` set (or whatever mechanism might replace `extension-module`) we always link to `libpython` on these targets.

**Comment by Progdrasil** [comment]
Not really sure what target `cygwin` would correspond to in the [target platforms], `x86_64-pc-windows-gnu`?

[target platforms]: https://forge.rust-lang.org/release/platform-support.html

**Comment by davidhewitt** [comment]
> Not really sure what target cygwin would correspond to in the target platforms, x86_64-pc-windows-gnu?

Good question. I can't see evidence that Rust provides a target for cygwin. I think if it existed it might be `x64_64-pc-cygwin`, which is based on briefly trawling the internet and finding [this stackoverflow post](https://stackoverflow.com/questions/32624082/how-to-use-clang-in-cygwin).

IMO cygwin is increasingly redundant with WSL anyway, so I think let's ignore support for it for now until somebody comes along asking.

**Comment by Progdrasil** [comment]
fair enough, makes dealing with one less exception :smile:

**Comment by davidhewitt** [comment]
#1095 solved this for android, and at the moment there is no Rust cygwin target (afaik), so closing this issue for now.
