### ISSUE TITLE
Question about `with_gil` in pyo3

### ISSUE THREAD

**Issue by CholoeMoretz** [PyO3/pyo3#1101]
My operating system is macOS Catalina 10.15.6
 Python version: anaconda python 3.7.6
Python installed through anaconda
 rustc 1.46.0-nightly
 PyO3 version: 0.11.1

I was trying to use Python in Rust and wants to use a uqer package to get some finacial data, due to security reason, this has to be done in Rust. I was running the example code in the homepage that shows the version of Python. However, this leads to this problem 

> error[E0599]: no function or associated item named `with_gil` found for struct `pyo3::Python<'_>` in the current scope

I was tring to solve this, but no proper answer for this situation.

I guess the reason might be the anaconda installed python changed the system enviroment viriable setting, which leads to this crate cannot find a right python. Following is my enviroment variable setting in system:

> COLORFGBG='7;0'
COLORTERM=truecolor
CONDA_DEFAULT_ENV=base
CONDA_EXE=/opt/anaconda3/bin/conda
CONDA_PREFIX=/opt/anaconda3
CONDA_PROMPT_MODIFIER='(base) '
CONDA_PYTHON_EXE=/opt/anaconda3/bin/python
CONDA_SHLVL=1
HOME=/Users/chenbowen
ITERM_PROFILE=Default
LANG=zh_CN.UTF-8
LC_TERMINAL=iTerm2
LC_TERMINAL_VERSION=3.3.12
LOGNAME=chenbowen
OLDPWD=/Users/chenbowen
PATH=/opt/anaconda3/bin:/opt/anaconda3/condabin:/Library/PostgreSQL/12/bin:/Users/chenbowen/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/chenbowen
SHELL=/bin/zsh
SHLVL=1
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.3.12
TERM_SESSION_ID=w0t0p1:A443C399-AEB5-4B2A-BA74-75F99B427A42
USER=chenbowen
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_CE_CONDA=''
_CE_M=''
__CF_USER_TEXT_ENCODING=0x0:25:52

**Comment by kngwyu** [comment]
The README example is for the latest master. In released version, there's no `with_gil` and you can use
```rust
let gil = Python::acquire_gil();
let py = gil.python();
```
instead.
