### ISSUE TITLE
PyO3 doesn't build on musl targets (Alpine linux)

### ISSUE THREAD

**Issue by alex** [PyO3/pyo3#1109]
>   error: cannot produce cdylib for `cryptography-rust v0.1.0 (/tmp/pip-req-build-oczfn6un/src/rust)` as the target `x86_64-unknown-linux-musl` does not support these crate types

This was previously reported as #599, however that referred to a different failure, that proc-macro wasn't supported on musl targets. The corresponding Rust issue was closed, and indeed there's now a new error message. I'm hoping to understand where the blocker to moving this ball forward is, and how I can help!

### 🌍 Environment

 - Your operating system and version: Alpine Linux 3.12.0
 - Your Rust version (`rustc --version`): rustc 1.45.2 (d3fb005a3 2020-07-31)
 - Your PyO3 version: 0.11.1
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: Not yet

### 💥 Reproducing

https://github.com/pyca/cryptography/pull/5410 see the failing Alpine build https://travis-ci.org/github/pyca/cryptography/jobs/718454323

**Comment by alex** [comment]
Discovery: Building with `RUSTFLAGS="-C target-feature=-crt-static"` resolves this. Does this sound like the _correct_ solution to folks? If yes, I'll work up a PR to setuptools-rust to do this automatically when targeting musl. If no... back to the drawing board I guess? :-)

**Comment by alex** [comment]
Well, I submitted a PR for that approach: https://github.com/PyO3/setuptools-rust/pull/80

**Comment by kngwyu** [comment]
Thank you for reporting,

> RUSTFLAGS="-C target-feature=-crt-static"

Any link or document where you find this solution?
I don't know why it works for musl...

**Comment by konstin** [comment]
This is explained somehow in https://github.com/rust-lang/rust/issues/59302#issuecomment-509025297, while the reference has some background information (https://doc.rust-lang.org/reference/linkage.html#static-and-dynamic-c-runtimes). I have the same problem with maturin (https://github.com/PyO3/maturin/issues/154) and it appears that `target-feature=-crt-static` is all you can (and need) to do.

**Comment by davidhewitt** [comment]
Thanks for reporting & investigating! As we've pushed issues to both of the packaging tools, let's close this one out? I think anyone building software for the musl target regularly probably will know about this `target-feature=-crt-static` flag.
