### ISSUE TITLE
Error when importing any non-system default packages

### ISSUE THREAD

**Issue by PosoSAgapo** [PyO3/pyo3#1111]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version:OSX Catalina
 - Your python version:3.7.3
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:  anaconda
 - Your Rust version (`rustc --version`):rustc 1.46.0-nightly (346aec9b0 2020-07-11)
 - Your PyO3 version:0.11.0
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`:No

### 💥 Reproducing

I was tring to import some other packages to finish my project, therefore I have to use a package that was installed by a package manager like pip or anaconda, however, when I was trying to import these packages like below, error happens

> use pyo3::prelude::*;
fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let _mod = PyModule::import(py, "pandas").unwrap();
}

The python that I used with Rust cannot import any other non-system-default packages, but the default packages like `sys` is working fine, importing a non-system-default packages would trigger the error below:

> UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: Py(0x1052570c0, PhantomData) }', src/adapter/uqer_adapter.rs:40:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

To be noticed, importing these packages is working well when I use the python in terminal which is the same python that running in rust, I also checked the `sys.path` to makesure that they have the same import directory

**Comment by birkenfeld** [comment]
Does PyO3 do the equivalent of `import site`? This is required, I think, for the egg/wheel path magic to kick in.

To check it, you could try doing `PyModule::import(py, "site")` before the pandas import...

**Comment by PosoSAgapo** [comment]
> Does PyO3 do the equivalent of `import site`? This is required, I think, for the egg/wheel path magic to kick in.
> 
> To check it, you could try doing `PyModule::import(py, "site")` before the pandas import...

Sorry for the late reply, importing `site` seems work well, importing `pandas` causing troubles, is `site` package important for python to import non-default packages?

**Comment by PosoSAgapo** [comment]
> Does PyO3 do the equivalent of `import site`? This is required, I think, for the egg/wheel path magic to kick in.
> 
> To check it, you could try doing `PyModule::import(py, "site")` before the pandas import...

Also I the first post that I report this bug, it says I need to check whether mkl-service is installed or not, I am sure that the mkl-serivece is installed.

**Comment by davidhewitt** [comment]
As there has been no response on this question for some time, I'm going to close it. Thank you for the discussion.
