### ISSUE TITLE
call_method*() crashes when the method does not exist

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [PyO3/pyo3#113]
```rust
extern crate pyo3;

use pyo3::{Python, ObjectProtocol};

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let a = py.eval("42", None, None).unwrap();
    a.call_method0("__str__").unwrap();  // ok
    a.call_method0("nonexistent_method").unwrap();  // crashes
}
```

Ideally should produce `AttributeError` or something.

-------

This happens because in https://github.com/PyO3/pyo3/blob/30baa990f8d1ec68bf60354eef0151c9c07ce269/src/objectprotocol.rs#L329-L340 and several similar places, `ptr` could be `NULL`.

**Comment by fafhrd91** [comment]
we should return PyErr if ptr is null,

https://github.com/PyO3/pyo3/blob/master/src/err.rs#L239

**Comment by fafhrd91** [comment]
fixed in master
