### ISSUE TITLE
test_unsendable in test_class_basics is not run

### ISSUE THREAD

**Issue by alex** [PyO3/pyo3#1144]
https://github.com/PyO3/pyo3/blob/3c24d27a66b9fd8fb6a3b2c7ed1e0d45eb098084/tests/test_class_basics.rs#L198-L225

it's missing `#[test]`. I think this is probably a mistake, since there's no comment explaining it.

**Comment by davidhewitt** [comment]
It's used in the two tests directly below it, but maybe a better name / comment is a good idea.

**Comment by alex** [comment]
Well. That's embarrassing!
