### ISSUE TITLE
Documentation is not uploaded to GitHub Pages

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [PyO3/pyo3#115]
From Travis logs:
```
cargo install mdbook
...
...
error: linking with `cc` failed: exit code: 1
...
...
  = note: cc: error: ./specs: Is a directory
```

It's probably https://github.com/google/pulldown-cmark/issues/122

------------

Also, there was no alert that it was broken.
I don't know if Travis alerts on failures in `after_success` step.
But even if it does, currently there is a single large `after_success` command both to build documentation and to upload coverage data, so the successful result of the latter masks the failure of the former.

**Comment by fafhrd91** [comment]
Hmm, that is strange. My other projects work fine

**Comment by Vlad-Shcherbina** [comment]
Maybe they don't use mdbook? The failure is because mdbook does not build.

**Comment by fafhrd91** [comment]
Work for this one https://github.com/actix/actix-web

Same flow, mdbook, then go-pages

**Comment by Vlad-Shcherbina** [comment]
Then perhaps it works because `LIBRARY_PATH` was not modified there.

**Comment by Vlad-Shcherbina** [comment]
Ok, it works now, but I just checked and Travis seems to ignore failures in the `after_success` step. Maybe it's better to move documentation building to the `script` step...

**Comment by fafhrd91** [comment]
You can move it, up to you
