### ISSUE TITLE
Improve proc-macro errors & error spans

### ISSUE THREAD

**Issue by sebpuetz** [PyO3/pyo3#1158]
~~~Rust
error[E0106]: missing lifetime specifier
 --> src/lib.rs:1:1
  |
1 | use pyo3::prelude::*;
  | ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `module` or `_fun`
help: consider introducing a named lifetime parameter
  |
1 | <'a>u<'a>se pyo3::prelude::*;
  | ^^^^^
~~~

triggered by:

~~~Rust
use pyo3::prelude::*;
[...]

#[pyfunction(pass_module)]
fn foo(module: &PyModule, fun: &PyFunction) -> PyResult<&PyString> {
    module.add_function(&|_| Ok(fun))?;
    fun.name()
}
~~~

(This is not currently possible on master, but I'm pretty sure that the incorrect `Span` for the lifetime is not due to `PyFunction`.)

I think there are more cases where `Span`s are just created through `call_site()` where we can probably provide better feedback than just highlighting the attribute.

**Comment by davidhewitt** [comment]
A related one to this is that we probably want to change most existing uses of `quote!` to be `quote_spanned!` instead.

**Comment by davidhewitt** [comment]
As a follow up, I've the example above with PyO3 0.13.1 and Rust 1.49.0, and I get error messages with correct spans.

Over time we've slowly improved a few of these cases, so I'm going to close this issue as fixed and we can resolve individual cases in the future if we should come across more.
