### ISSUE TITLE
How to declare custom class with optional argument in constructor?

### ISSUE THREAD

**Issue by temoto** [PyO3/pyo3#117]
Hello.

First, thank you very much for doing pyo3.

I need to export a class that will be instantiated in Python. It's created like `Hub()` or `Hub(clock=time.clock)`, so I need to parse arguments. Trying simple syntax as in free function declaration produces error:

```
  --> src/lib.rs:35:1
   |
35 | #[py::methods]
   | ^^^^^^^^^^^^^^ the trait `pyo3::PyTypeInfo` is not implemented for `pyo3::PyObject`
   |
   = note: required because of the requirements on the impl of `pyo3::FromPyObject<'_>` for `&pyo3::PyObject`
```

I think Python `__new__` does not accept arguments like `__init__`, which explains error, but then I don't know how to accept arguments at class create (from Python).

Code:
```
#![feature(proc_macro, specialization, const_fn)]
extern crate pyo3;

use pyo3::prelude::*;

#[py::class(name=Hub)]
struct Hub {
    token: PyToken,
}

#[py::methods]
impl Hub {
    #[new]
    fn __new__(obj: &PyRawObject
// uncomment to get error
//, clock:&PyObject
) -> PyResult<()> {
        obj.init(|token| {
            Hub {
                token: token,
            }
        })
    }
}

#[py::modinit(eventlet_rusthub)]
fn init(py: Python, m: &PyModule) -> PyResult<()> {
    Ok(())
}
```

**Comment by fafhrd91** [comment]
try ```clock: PyObject```

**Comment by fafhrd91** [comment]
this error means, that there is no `pyo3::FromPyObject<&'p PyObject>` for `&pyo3::PyObject`
which should be probably be fixed

**Comment by temoto** [comment]
Now it says
```
    10 | #[py::class(name=Hub)]
       | ^ expected lifetime parameter
```

**Comment by temoto** [comment]
Can pyo3 show full generated source to compiler, so it shows error in context?

**Comment by fafhrd91** [comment]
it can not for now. it depends on rustc proc macro.

but you can expand macros with "cargo expand"
https://github.com/dtolnay/cargo-expand

**Comment by fafhrd91** [comment]
i'll check later today

**Comment by temoto** [comment]
Sorry it was my mistake.

```
#[py::class(name=Hub)]
struct Hub {
    token: PyToken,
    // greenlet: &PyObject,   // uncomment to get error: lifetime parameter expected
```

`clock:PyObject` in new works. Thank you very much. Amazing response time.

**Comment by fafhrd91** [comment]
let's keep this ticket open, i'll check what i can do for &PyObject

**Comment by temoto** [comment]
Just for history, this compiles as intended optional argument in constructor.

```
#[py::methods]
impl Hub {
    #[new]
    fn __new__(obj: &PyRawObject, clock: Option<PyObject>) -> PyResult<()> {
```

The `Option<>` makes magic. And it's obvious and readable too. I am happy like a little boy getting a toy plane.
