### ISSUE TITLE
method argument Vec<&Texture> causing problems after moving from pyo3 v0.8 to v0.11.1

### ISSUE THREAD

**Issue by paddywwoof** [PyO3/pyo3#1177]
This might be just clarification needed in the documentation.

Previously I could make a list of instances of pyo3 class Texture in python and pass that list to a method as Vec<&Texture>. Now however I have to impl Clone for Texture and define the method argument as Vec<Texture> otherwise I get a compiler error
```
the trait pyo3::FromPyObject<'_> is not implemented for `std::vec::Vec<&core::Texture>
````
But this scrambles the behavior. Texture is a pyo3 wrapper for a rust struct containing a large array of pixels as well as OpenGL references. By passing the ownership into the class method the GL ref gets dropped then reused by other Textures. If I don't pass the Texture references in as a list but individually it all works fine. I tried defining the method argument as &PyList but that doesn't help (see question [here](https://users.rust-lang.org/t/pyo3-switch-to-stable-now-gives-error-for-method-arguments-vec-mypyclass/48491/2))

Is there a straightforward way to do this or do I have to refactor my code by ref counting Textures or such like?

**Comment by davidhewitt** [comment]
Can you try using `Vec<PyRef<Texture>>`? I believe that should work. To make pyo3's APIs safe in the face of python's share mutability model a refcell-like mechanism has been added.

In the future, if you don't ever need `Texture` instances to be mutated from Python then I'd like to provide a way to opt-out of the pycell system so you can have `Vec<&Texture>` again - see #1068

**Comment by paddywwoof** [comment]
@davidhewitt That's exactly what I needed. It works fine and is more explicit about what actually going on than the Vec<&

In this instance the extra overhead unpacking a pycell is low as the GL Texture2D ref is passed relatively infrequently (If it needed to be unpacked for every draw on every buffer on every frame then that would be more of an issue)

Thanks so much for you prompt help.

Paddy
