### ISSUE TITLE
how to use imported (at modinit) python modules in class methods

### ISSUE THREAD

**Issue by temoto** [PyO3/pyo3#119]
Or, rephrased, how to access `m&PyModule` within class method?

I'm trying various approaches with lazy_static, mutex protected ref variable and nothing works because I suck at Rust at this time. Please have patience.

Repeating `py.import()` in class method will work, I wonder if there's a better approach. It has a problem that if for some reason imported module will loose last reference, then next method call will not simply go to `sys.modules` but incur actual `__import__` mechanism which is very fragile when executed not at module level.

**Comment by fafhrd91** [comment]
You can not keep &PyModule, I bound to GIL. But you can keep Py<PyModule>

**Comment by fafhrd91** [comment]
Check this code https://github.com/PyO3/tokio/blob/master/src/utils.rs

**Comment by temoto** [comment]
Thank you, it contains exactly what I needed:

```rust
struct GlobalState {
    mod_sys: Py<PyModule>,
// ...
}

lazy_static!{
    static ref global_state:GlobalState = {
        let gil = Python::acquire_gil();
        let py = gil.python();
        GlobalState{
            mod_sys:py.import("sys").unwrap().into(),
// ...
        }
    };
}

#[py::methods]
impl Hub {
    #[new]
    fn __new__(obj: &PyRawObject, py: Python, clock: Option<PyObject>) -> PyResult<()> {
        let msys = global_state.mod_sys.as_ref(py);
// ...
```
