### ISSUE TITLE
Add support for logical comparison (e.g. `__gt__`) to `PyNumberProtocol`

### ISSUE THREAD

**Issue by jorgecarleitao** [PyO3/pyo3#1219]
Specifically,

```python
operator.__lt__(a, b)
operator.__le__(a, b)
operator.__eq__(a, b)
operator.__ne__(a, b)
operator.__ge__(a, b)
operator.__gt__(a, b)
```

(from [here](https://docs.python.org/3/library/operator.html))

This seems to be a small task, as the boilerplate code already exists; it is mostly a matter of implementing these in the trait as `unimplemented!`.

**Comment by kngwyu** [comment]
You can implement those functionalities by `PyObjectProtocol::__richcmp__`.
See https://github.com/PyO3/pyo3/blob/master/tests/test_arithmetics.rs#L412 for example.
