### ISSUE TITLE
Cross-compiling wasm32-unknown-unknown on 64bit debian

### ISSUE THREAD

**Issue by jruiss** [PyO3/pyo3#1221]
## 🐛 Bug Reports

When cross-compiling pyo3s build.rs fails on two places without any pointers on what lines, but rather just "Error: NotPresent", 

The guilty lines in build.rs:
https://github.com/PyO3/pyo3/blob/master/build.rs#L157, env::var("CARGO_CFG_TARGET_FAMILY") is not set
https://github.com/PyO3/pyo3/blob/master/build.rs#L433, env::var("CARGO_CFG_TARGET_FAMILY") is not set

After that, a custom python 32bit compilation requires PYO3_CROSS_INCLUDE_DIR which is only set for windows in fn cross_compilings https://github.com/PyO3/pyo3/blob/master/build.rs#L150

And finally, Include/pyconfig.h doesn't exists in https://www.python.org/downloads/release/python-379/
Which is required at https://github.com/PyO3/pyo3/blob/master/build.rs#L414

pyconfig.h gets generated when using ./configure and ends up in the root dir.

Also, when python is configured without --enable-shared and such, options retrieved from config_map crashes instead of defaulting to false, dunno if there's a reason for that. https://github.com/PyO3/pyo3/blob/master/build.rs#L415 but unwrap_or(false) might be better than current solution?

Accidently posted this issue before successfully compiling, will update on progress

**update:**
Well, seem to have gotten rid of all errors in build.rs, it seems to find all neccessary files and and so on but now I get about 100 errors regarding libc.

Using wasm32-wasi instead pulls the errors down to only 3 regarding wchar_t in libc. Seems to be a problem with libc and wasm32 target from here on out. 
```
cargo build --release --target wasm32-wasi
pyo3 git:(master) ✗ cargo build --release --target wasm32-wasi           
   ...
   Compiling libc v0.2.79
   Compiling pyo3 v0.12.1 (/home/cfr/workspace/clones/pyo3)
   ...
error[E0432]: unresolved import `libc::wchar_t`
 --> src/ffi/unicodeobject.rs:3:5
  |
3 | use libc::wchar_t;
  |     ^^^^^^^^^^^^^ no `wchar_t` in the root

error[E0432]: unresolved import `libc::wchar_t`
 --> src/ffi/pylifecycle.rs:2:5
  |
2 | use libc::wchar_t;
  |     ^^^^^^^^^^^^^ no `wchar_t` in the root

error[E0432]: unresolved import `libc::wchar_t`
 --> src/ffi/sysmodule.rs:3:5
  |
3 | use libc::wchar_t;
  |     ^^^^^^^^^^^^^ no `wchar_t` in the root

error: aborting due to 3 previous errors

```

### 🌍 Environment

 - Your operating system and version: Linux debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linu
 - Your python version: 3.7.9 (default, Oct 10 2020, 16:39:07) [GCC 8.3.0] ('32bit', 'ELF')
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Compiled from source
 - Your Rust version (`rustc --version`): rustc 1.49.0-nightly (38d911dfc 2020-10-09)
 - Your PyO3 version: Cloned from git master today
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: yupp

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the Rust code and the Python.

Please also write what exact flags are required to reproduce your results.

Compiled Python 3.7.9 with
```
CFLAGS=-m32 LDFLAGS=-m32 ./configure --enable-shared
make
```

Setup PYO3_CROSS flags
```
export PYO3_CROSS_PYTHON_VERSION=3.7
export PYO3_PYTHON=/home/Python-3.7.9/python
export PYO3_CROSS_INCLUDE_DIR=/home/Python-3.7.9/Include
export PYO3_CROSS_LIB_DIR=/home/Python-3.7.9/build/lib.linux-x86_64-3.7
```

**lib.rs**
```rust
use wasm_bindgen::prelude::*;

use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

// Called when the wasm module is instantiated
#[wasm_bindgen(start)]
pub fn main() -> Result<(), JsValue> {
    // Use `web_sys`'s global `window` function to get a handle on the global
    // window object.
    let window = web_sys::window().expect("no global `window` exists");
    let document = window.document().expect("should have a document on window");
    let body = document.body().expect("document should have a body");

    // Manufacture the element we're gonna append
    let val = document.create_element("p")?;

    Python::with_gil(|py| {
        main_(py).map_err(|e| {
          // We can't display Python exceptions via std::fmt::Display,
          // so print the error here manually.
          e.print_and_set_sys_last_vars(py);
    	  val.set_inner_html("Hello from Python!");
        })
    });

    body.append_child(&val)?;

    Ok(())
}

#[wasm_bindgen]
pub fn add(a: u32, b: u32) -> u32 {
    a + b
}

fn main_(py: Python) -> PyResult<()> {
    let sys = py.import("sys")?;
    let version: String = sys.get("version")?.extract()?;
    let locals = [("os", py.import("os")?)].into_py_dict(py);
    let code = "os.getenv('USER') or os.getenv('USERNAME') or 'Unknown'";
    let user: String = py.eval(code, None, Some(&locals))?.extract()?;
    println!("Hello {}, I'm Python {}", user, version);
    Ok(())
}
```

**Cargo.toml**
```
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "*"
pyo3 = {path="/home/cfr/workspace/clones/pyo3"}

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
```

Build command
```
wasm-pack build --target web
```

**Comment by davidhewitt** [comment]
@e0gs wow, this is an interesting project! I think you're the first person I'm aware of trying to use pyo3 to put Python on the web 😄 

Thanks for investigating the build script. Sorry that there's been some issues with it. If you've got time to put those fixes in a PR I can review and merge them.

I have a few general questions about how this works - you're compiling python from source to wasm? And then you're using wasm-pack to link in against the Python library? I have to confess I have absolutely no knowledge about the current state of linking C libraries from Rust code in the wasm world...

**Comment by e0gs** [comment]
Thought I'd see how far I can get with using youtube-dl via pyo3 and web assembly for a browser extension :)

Almost, atm I'm trying with https://github.com/e0gs/cpython-emscripten (added wasm32-wasi cross-compiling) for a python wasm32-wasi build and https://github.com/e0gs/pyo3 and then simply trying to create the a web assembly example with 

```rust
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

#[no_mangle]
pub extern fn execute() -> i32 {
	Python::with_gil(|py| {
        main_(py).map_err(|e| {
          e.print_and_set_sys_last_vars(py);
        })
    });

	100
}


fn main_(py: Python) -> PyResult<()> {
    let sys = py.import("sys")?;
    let version: String = sys.get("version")?.extract()?;
    let locals = [("os", py.import("os")?)].into_py_dict(py);
    let code = "os.getenv('USER') or os.getenv('USERNAME') or 'Unknown'";
    let user: String = py.eval(code, None, Some(&locals))?.extract()?;
    println!("Hello {}, I'm Python {}", user, version);
    Ok(())
}
```
```
cargo build --target wasm32-wasi
```


Some helpful resources have been

https://stackoverflow.com/questions/44761748/compiling-python-to-webassembly/47739532#47739532

https://github.com/rustwasm/team/issues/179

**Comment by davidhewitt** [comment]
Wow, very cool 🤤 

> with a renamed libpython3.5m.a copy in it, cpython-emscripten creates a static libpython3.5.so next to the lib dir

Both of those contain wasm machine code? I'm totally guessing at random, wondering if that's where the wrong machine type error is coming from.

Afraid I'm not going to be much use with that error, though feel free to keep asking questions and I'll try to be any use I can. And naturally as you progress do please consider opening PRs or sending links to blog posts / examples - would be really cool to document this for the community to use!

**Comment by dalcde** [comment]
I have managed to get `pyo3` to compile to `wasm32-unknown-unknown`, intended for use with https://github.com/iodide-project/pyodide. What I did was
1. Create a mock `libc` library that provides the necessary functions and definitions.
2. Disable `check_target_architecture` when cross-compiling. Not sure what the real effect is; why do we perform this check?
3. Run the following build script:
  ```
  export PYO3_CROSS_PYTHON_VERSION=3.8
  export CARGO_CFG_TARGET_FAMILY=unix
  export PYO3_CROSS_LIB_DIR=/pyodide_root/cpython/installs/python-3.8.2/lib/python3.8
  export PYO3_CROSS_INCLUDE_DIR=/pyodide_root/cpython/installs/python-3.8.2/include/python3.8
  export RUSTFLAGS="-C relocation-model=pic -C link-arg=-shared -C link-arg=--imported-memory -C link-arg=--no-fatal-warnings'"
  cargo +nightly build -Z build-std --target wasm32-unknown-unknown
  ```
  The first four lines are PYO3 configuration. The rest of the settings are needed to generate a dynamic wasm library. It currently doesn't work for me due to https://github.com/rust-lang/rust/issues/80685 , but the pyo3 part is working well, and replacing the last two lines with a normal cargo build produces a reasonable-looking `.so` file.

I would like to upstream these changes, but I think it is better to gather some input from maintainers first

**Comment by davidhewitt** [comment]
Thanks for the detailed write-up and for the PRs! It would be nice to get wasm support working - I've put a couple of comments on your PRs. I'm looking forward to trying this myself when I get a chance...

**Comment by programmerjake** [comment]
@dalcde  I don't know if you mentioned it, but you should be aware that rust doesn't actually use the same ABI as C/C++ on wasm32-unknown-unknown, this can make it crash in weird ways or fail to link, if you want it to work you'd probably want to use wasm32-wasi or wasm32-unknown-emscripten.

**Comment by programmerjake** [comment]
> @dalcde I don't know if you mentioned it, but you should be aware that rust doesn't actually use the same ABI as C/C++ on wasm32-unknown-unknown, this can make it crash in weird ways or fail to link, if you want it to work you'd probably want to use wasm32-wasi or wasm32-unknown-emscripten.

turns out that only wasm32-unknown-emscripten was fixed:
https://github.com/WebAssembly/tool-conventions/issues/130
https://github.com/rust-lang/rust/issues/71871

**Comment by dalcde** [comment]
On Wed, Jan 06, 2021 at 09:49:51AM -0800, Jacob Lifshay wrote:
>> @dalcde I don't know if you mentioned it, but you should be aware that rust doesn't actually use the same ABI as C/C++ on wasm32-unknown-unknown, this can make it crash in weird ways or fail to link, if you want it to work you'd probably want to use wasm32-wasi or wasm32-unknown-emscripten.

I assumed they would be compatible because both use LLVM, but I guess
I'm wrong. I was running into other difficulties, which is why I marked
this as draft

**Comment by davidhewitt** [comment]
See https://github.com/PyO3/pyo3/issues/1522#issuecomment-922248534
