### ISSUE TITLE
Add a way to access the `StopIteration` exception value

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1224]
The `StopIteration` exception raised by a generator object can contain a value (which is what the generator returned, if anything).

It could be nice to add an API to PyO3 to access this value. We can only do this when not using the limited API (as it'll rely on us knowing the layout of the `StopIteration` exception.)

**Comment by mejrs** [comment]
How accurate is this one year later?



Users can already access it, it could be nicer though:

```rust
use pyo3::exceptions::PyStopIteration;
use pyo3::prelude::*;

fn main() {
    Python::with_gil(|py| {
        let module = PyModule::from_code(
            py,
            "def generator():
			yield 1
			return 2",
            "",
            "",
        )
        .unwrap();

        let generator = module.getattr("generator").unwrap().call0().unwrap();
        generator.call_method0("__next__").unwrap();
        let e = generator
            .call_method0("__next__")
            .unwrap_err()
            .into_instance(py);

        let final_value: &PyAny = e
            .as_ref(py)
            .downcast::<PyStopIteration>()
            .unwrap()
            .getattr("value")
            .unwrap();

        dbg!(final_value);
    });
}
```

> It could be nice to add an API to PyO3 to access this value.

I think we'd want 
- something to turn a PyErr into specific exceptions? Something like `PyErr::downcast<'py, T: ???> (&'py self, py: &'py Python> -> Result<&'py T, PyDowncastError>`? 
- while we can just `get_attr(...)` to get the values I guess an actual "values" getter would be nice. Same for the other exception structs with fields.

**Comment by davidhewitt** [comment]
`PyErr::downcast` would probably be useful - it'd be like `PyErr::instance` with a typecheck first, I guess.

> How accurate is this one year later?

Yeah I think given that no user has upvoted or asked for this ever, I'd be quite happy for us to close this rather than add extra API nobody seems to want?

It's quite edge-casey; I think getting the value from `StopIteration` was more common back in days before Python had `async`/`await`, when coroutines were implemented by generators.
