### ISSUE TITLE
Give a method a different name from it's signature

### ISSUE THREAD

**Issue by alvitawa** [PyO3/pyo3#1242]
I have been looking around the documentation but I have not found a way to specify a different name for a class method than the rust function signature.

According to the docs you can do this for a standard function like so:
```
#[pymodule]
fn rust2py(py: Python, m: &PyModule) -> PyResult<()> {

    #[pyfn(m, "sum_as_string")]
    fn sum_as_string_py(_py: Python, a:i64, b:i64) -> PyResult<String> {
        Ok(format!("{}", a + b))
    }

    Ok(())
}
```

(rust function is called 'sum_as_string_py', but in python you call 'sum_as_string'

I would love to be able to do something similar for a classes' methods:

```
#[pymethods]
impl Dataset {
    #[pyname = "add_feature"]
    fn add_feature_py(&mut self, matrix: &PyArray1<bool>) -> PyResult<()> {
        Ok(())
    }
}
```

This way you can give functions in the rust interface the same name as their python counterparts:

```
impl Dataset {
    fn add_feature(&mut self, matrix: Vec<bool>) -> { }
}
```

**Comment by kngwyu** [comment]
You can do
```rust
#[pymethods]
impl Dataset {
    #[name = "add_feature"]
    fn add_feature_py(&mut self, matrix: &PyArray1<bool>) -> PyResult<()> {
        Ok(())
    }
}
```

**Comment by cmyr** [comment]
Pardon the bump but just found this when I had the same question. Maybe it would be helpful if the available annotations were listed in the guide?

**Comment by davidhewitt** [comment]
@cmyr no problem at all, I agree there's a documentation issue here. I've been trying to start solving this problem by making the attribute syntax more uniform: #1567 

The idea being that the attribute will become `#[pyo3(name = "...")]`, and we'll document all the options that the `#[pyo3(...)]` attribute will support.

If you have a moment to read through that PR, I'd welcome your opinion on the design proposal.
