### ISSUE TITLE
`SIGSEGV: invalid memory reference` in tests, but not main

### ISSUE THREAD

**Issue by Yoshanuikabundi** [PyO3/pyo3#1257]
Hi!

I'm trying to write Rust bindings for an important Python library in my field and a simple test case crashes with `SIGSEGV: invalid memory reference`. However, when I was constructing a MVCE I found that the crash only occurs in tests, and not when the code is run normally. I tried messing with profiles but to no avail. I couldn't find any resources explaining differences between test and run apart from the profiles so I'm stuck.

The library can be found here: <https://github.com/choderalab/pymbar>. The library is just a big complicated computation built with Numpy with a small section in C. I went through with my trusty print statements and found that the line that crashes is just a simple `H = W.T.dot(W)` (line 177 of [mbar_solvers.py](https://github.com/choderalab/pymbar/blob/master/pymbar/mbar_solvers.py))

### 🌍 Environment

 - Your operating system and version: Ubuntu 19.10
 - Your python version: 3.7.8
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Conda, which uses a virtualenv internally (I think)
 - Your Rust version (`rustc --version`): 1.47.0 and 1.49.0-nightly (31530e5d1 2020-10-20)
 - Your PyO3 version: 0.12.3
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: Yes, same error

#### main.rs:
```rust
fn mcve() {
    pyo3::Python::with_gil(|py| {
        let code = r##"
from pymbar import MBAR
u_kn = [
    [1.4, 2.3, 3.7, 4.1, 7.7, 9.1],
    [-1.6, -2.3, 9.7, 34.1, 27.7, 19.1],
    [4.4, 7.3, 9.7, 8.1, 4.7, 3.1],
]
n_k = [2, 2, 2]
mbar = MBAR(u_kn, n_k)
print(u_kn, n_k, mbar)
        "##;
        py.run(code, None, None).unwrap();
    });
}

fn main() {
    mcve();
}

#[cfg(test)]
mod tests {
    #[test]
    fn mcve_test() {
        super::mcve();
    }
}
```

#### Cargo.toml:
```toml
[package]
name = "pyo3-mcve"
version = "0.1.0"
edition = "2018"

[dependencies]
pyo3 = { git = "https://github.com/PyO3/pyo3" } # "0.12.3"
```

`cargo test` and `cargo test --release` crash with 

```
running 1 test
error: test failed, to rerun pass '--bin pyo3-mcve'

Caused by:
  process didn't exit successfully: `/home/joshmitchell/Projects/pyo3-mcve/target/release/deps/pyo3_mcve-c9ce3636aaa6b782 mcve_test` (signal: 11, SIGSEGV: invalid memory reference)
```

Whereas `cargo run` or `cargo run --release` or, on nightly,  `cargo run --profile test -Z unstable-options` all produce the correct output:
```
[[1.4, 2.3, 3.7, 4.1, 7.7, 9.1], [-1.6, -2.3, 9.7, 34.1, 27.7, 19.1], [4.4, 7.3, 9.7, 8.1, 4.7, 3.1]] [2, 2, 2] <pymbar.mbar.MBAR object at 0x7fcefee06e10>
```

Running the code in Python produces correct output without crashing:
```python
from pymbar import MBAR
u_kn = [
    [1.4, 2.3, 3.7, 4.1, 7.7, 9.1],
    [-1.6, -2.3, 9.7, 34.1, 27.7, 19.1],
    [4.4, 7.3, 9.7, 8.1, 4.7, 3.1],
]
n_k = [2, 2, 2]
mbar = MBAR(u_kn, n_k)
print(u_kn, n_k, mbar)
```

**Comment by davidhewitt** [comment]
@Yoshanuikabundi thanks for reporting and apologies for the delayed response.

I've just had a quick try with your mvce myself and am not able to reproduce the issue. (I installed latest `pymbar` from pip, I'm on Python 3.8 and Ubuntu 20.04.) This suggests to me that there's potentially some undefined behaviour occurring which has corrupted a pointer.

Taking a look at https://github.com/choderalab/pymbar/blob/ca4c8b8fd25a210f7e9f0237de8ab6db825ee976/pymbar/_pymbar.c#L85 it doesn't seem to me that the `pymbar` C is actually checking the arguments are numpy arrays, so while that could be a red herring that is easily a place where invalid inputs could cause something strange to occur.

**Comment by davidhewitt** [comment]
There has been no response on this issue for three months now, so I will assume that there there's nothing we need to fix here in PyO3.

Please comment if that is not the case and we can reopen!
