### ISSUE TITLE
Importing SciPy causes segfault in PyFinalize()

### ISSUE THREAD

**Issue by jroesch** [PyO3/pyo3#1261]
### 🌍 Environment

 - Your operating system and version: macOS 10.15.5
 - Your python version: 3.8.3
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: homebrew and pyenv, no venv
 - Your Rust version (`rustc --version`): rustc 1.47.0 (18bf6b4f0 2020-10-07)
 - Your PyO3 version: v0.12.3
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: yes, same error

### 💥 Reproducing

The below code dropped in a fresh Cargo project with a pyo3 dependency is sufficient. 
```
fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();

    let _mod = PyModule::import(py, "scipy").unwrap();
}
```

```cargo run```

### Discussion
```
tentactl(1184,0x10f08cdc0) malloc: *** error for object 0x7ff13f5a5b70: pointer being freed was not allocated
tentactl(1184,0x10f08cdc0) malloc: *** set a breakpoint in malloc_error_break to debug
```
This is the error you observe when running, I am writing a chunk of code that is a Rust, C++ and Python hybrid and thought that was the issue, after doing some debugging I found it is crashing during PyFinalize and is free-ing memory that has likely already been freed. 

My hunch is this is a deinitilization ordering issue, if extensions are not careful they can leave memory around that is no longer owned by Python causing faults like this (have encountered same problem while developing Apache TVM).

Similar to https://github.com/PyO3/pyo3/issues/1073. I traced down what is happening GDB.

Removing all SciPy imports from the code temporarily fixed this for me, I do not have the expertise to dig into SciPy and figure out what is going on.

**Comment by davidhewitt** [comment]
@jroesch thanks for the report. Which `scipy` version are you using? On ubuntu 20.04, scipy 1.5.3, and pyo3 master I do not get the crash.

**Comment by jhseu** [comment]
I can confirm I see this issue on Ubuntu 20.10, python3.8/3.9, and pyo3 master testing many different packages (scipy, jax, several others). Some packages don't have this problem (like numpy). I also tested with several allocators, and it occurs with system malloc and tcmalloc but not with jemalloc.

Stack trace:
```
#0  0x00007fa4f6d7eeeb in tcmalloc::ThreadCache::ReleaseToCentralCache(tcmalloc::ThreadCache::FreeList*, unsigned int, int) ()
   from /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.3
#1  0x00007fa4f6d7f1fe in tcmalloc::ThreadCache::Scavenge() () from /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4.5.3
#2  0x00007fa4f68cd4f1 in ?? () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#3  0x00007fa4f68a12d5 in ?? () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#4  0x00007fa4f68a3206 in ?? () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#5  0x00007fa4f68bb545 in ?? () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#6  0x00007fa4f68ca260 in _PyModule_ClearDict () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#7  0x00007fa4f698492b in ?? () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#8  0x00007fa4f69a5648 in Py_FinalizeEx () from /lib/x86_64-linux-gnu/libpython3.9.so.1.0
#9  0x00005645d5354b45 in pyo3::gil::prepare_freethreaded_python::{{closure}}::finalize () at /home/jhseu/.cargo/git/checkouts/pyo3-a22e69bc62b9f0fd/8b61830/src/gil.rs:90
#10 0x00007fa4f65d0a57 in __run_exit_handlers (status=0, listp=0x7fa4f676f738 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:108
#11 0x00007fa4f65d0c00 in __GI_exit (status=<optimized out>) at exit.c:139
#12 0x00007fa4f65b4cb9 in __libc_start_main (main=0x5645d534cad0 <main>, argc=1, argv=0x7ffed056e7c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffed056e7b8) at ../csu/libc-start.c:348
#13 0x00005645d534c0be in _start ()
```

tcmalloc_debug says `Memory was written to after being freed.  MallocBlock: 0x56138f74e900, user ptr: 0x56138f74e920, size: 136.`

**Comment by davidhewitt** [comment]
#1355 has now merged - we decided to disable finalizing by default because as we see it can lead to weird crashes like this.
