### ISSUE TITLE
Building with maturin in manylinux fails because of missing PYO3_CROSS_LIB_DIR

### ISSUE THREAD

**Issue by marco-c** [PyO3/pyo3#1264]
The command which is failing is at https://github.com/mozilla/pyo3-parsepatch/blob/e531232ee6760a9fe7f2bca24905fae626c51495/Dockerfile#L41 (`maturin build --target x86_64-unknown-linux-musl --manylinux off`).

```
error: failed to run custom build command for `pyo3 v0.12.3`

Caused by:
  process didn't exit successfully: `/rs_pp/target/debug/build/pyo3-a884c8252d1eb1d1/build-script-build` (exit code: 1)
  --- stderr
  Error: "Must provide PYO3_CROSS_LIB_DIR environment variable when cross-compiling"
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --target x86_64-unknown-linux-musl --`
```

It used to work with pyo3 0.9.2.

**Comment by kngwyu** [comment]
Unfortunately, we actually need this variable and the previous behabior is a kind of bug.
See https://pyo3.rs/v0.12.3/building_and_distribution.html#cross-compiling for more.

**Comment by davidhewitt** [comment]
I'm not sure whether we do? This is probably a case like 32-bit windows where it's possible to be building for a target different than the host toolchain. We can potentially check and allow this in `build.rs`.

**Comment by marco-c** [comment]
> I'm not sure whether we do? This is probably a case like 32-bit windows where it's possible to be building for a target different than the host toolchain. We can potentially check and allow this in build.rs.

That's what I was thinking as well.

**Comment by marco-c** [comment]
@davidhewitt could you make a new release which contains this fix?

**Comment by davidhewitt** [comment]
We already have breaking changes on the pyo3 master so we can't do this without calling it `0.13` - @kngwyu what do you think? I'd ideally like to give us more time to test and clean up the ABI3 changes before we release, though TBH it seems to have been fine overall.

@marco-c are you willing to pin to a git commit for now? e.g.

```
[dependencies]
pyo3 = { git = "https://github.com/Pyo3/pyo3.git", rev = "470716e" }
```

**Comment by marco-c** [comment]
Yeah, I can do that for now. I just need to remember to update to stable again (I'm used to rely on Dependabot, IDK what it does when you pin to a specific commit).

**Comment by kngwyu** [comment]
At least we need to have some consensus on #1263. But I don't think we are far from the release.
