### ISSUE TITLE
python import error 

### ISSUE THREAD

**Issue by sademakn** [PyO3/pyo3#1265]
this is my lib.rs file:
```use pyo3::prelude::*;
use pyo3::wrap_pyfunction;

/// Formats the sum of two numbers as string.
#[pyfunction]
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

/// A Python module implemented in Rust.
#[pymodule]
fn string_sum(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(sum_as_string, m)?)?;

    Ok(())
}
```

and this is my Cargo.toml file:

```[package]
name = "string_sum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "string_sum"
crate-type = ["cdylib"]


[dependencies.pyo3]
version = "0.12.3"
features = ["extension-module"]

[dependencies]
```

and I am getting this error :
 ```ImportError: dynamic module does not define module export function (PyInit_libstring_sum)```

How  should I fix it ?

**Comment by davidhewitt** [comment]
This looks like two issues:

1. You're running `import libstring_sum` instead of `libstring_sum`.
2. You did not copy or rename the output library to `string_sum`, as per the README:

> While developing, you can symlink (or copy) and rename the shared library from the target folder: On MacOS, rename `libstring_sum.dylib` to `string_sum.so`, on Windows `libstring_sum.dll` to `string_sum.pyd`, and on Linux `libstring_sum.so` to `string_sum.so`. Then open a Python shell in the same folder and you'll be able to `import string_sum`.

I suggest using [maturin](https://github.com/PyO3/maturin) to handle build your project in a more user-friendly way. I plan to update the README soon to suggest this; the maturin README already has good instructions on how to use it.

**Comment by tal-zvon** [comment]
I also ran into this issue.
The thing to keep in mind is that the module name (function name) you declare here:

```rust
#[pymodule]
fn string_sum(py: Python, m: &PyModule) -> PyResult<()> {
...
}
```

and the filename of your module must match.
If my rust function name was called `my_mod` instead, my resulting filename must be `my_mod.so`.

Someone more familiar with the project - please confirm.
Is there a way to not have this dependency?
If not, it would be nice if the documentation made this clearer.
