### ISSUE TITLE
Add support for Rust char type

### ISSUE THREAD

**Issue by bderrett** [PyO3/pyo3#1281]
Currently it doesn't seem to be possible to wrap a function accepting a char as an argument using PyO3. A char is a (particular kind of) unicode code point, so it could be converted to a single-character Python string. I think this would be a useful feature for users wanting to wrap such functions.

**Comment by kngwyu** [comment]
Good catch, thanks. For now, I made an initial implementation on #1282.

**Comment by bderrett** [comment]
Many thanks!
