### ISSUE TITLE
DeprecationWarning: builtin type X has no __module__ attribute

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1298]
On Python 3.7 and up I see warnings of the following form when running the pyo3 test suite:

```
DeprecationWarning: builtin type X has no __module__ attribute
```

I _think_ this is probably related to using a `#[pyclass]` when not adding it to a module. I haven't investigated yet.

Example test which demonstrates this issue:

```
$ cargo test --test test_various return_custom_class
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running target/debug/deps/test_various-a73ba5b7affaefde

running 1 test
<string>:1: DeprecationWarning: builtin type PyUsize has no __module__ attribute
test return_custom_class ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 7 filtered out
```

I'm not sure what changes we need to make to resolve.

**Comment by ChillFish8** [comment]
> I think this is probably related to using a #[pyclass] when not adding it to a module. I haven't investigated yet.
This does seem to be the trend with the issue when re-producing, when exposed to the module this error goes away. Only when you dont expose it directly does this warning get raised from my findings

**Comment by bderrett** [comment]
This appears to cause an error when running doctests:
```
$ python -m doctest -v myfile.py
Traceback (most recent call last):
  File "/home/ben/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ben/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ben/miniconda3/lib/python3.8/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/home/ben/miniconda3/lib/python3.8/doctest.py", line 2783, in _test
    failures, _ = testmod(m, verbose=verbose, optionflags=options)
  File "/home/ben/miniconda3/lib/python3.8/doctest.py", line 1955, in testmod
    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):
  File "/home/ben/miniconda3/lib/python3.8/doctest.py", line 939, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/home/ben/miniconda3/lib/python3.8/doctest.py", line 1000, in _find
    self._from_module(module, val)):
  File "/home/ben/miniconda3/lib/python3.8/doctest.py", line 967, in _from_module
    return module.__name__ == object.__module__
AttributeError: __module__
```

**Comment by bderrett** [comment]
"\_\_module__ is the name of the module the function was defined in or None if unavailable" https://docs.python.org/3/reference/datamodel.html

So perhaps the \_\_module__ attribute should be set to None if the pyclass is not added to a module?

**Comment by davidhewitt** [comment]
That sounds like a valid solution, though it's not super clear how to do that correctly with `PyType_FromSpec`. I'll keep playing with it and see if I can get it right.

**Comment by davidhewitt** [comment]
@bderrett am I right in thinking this is a new regression for PyO3 0.13? It's quite possibly related to the abi3 work / switch to heap types.

**Comment by bderrett** [comment]
@davidhewitt Yes. A bisection shows that it was introduced when the "PyO3/abi3" branch was merged.
