### ISSUE TITLE
Interaction between gil and tokio causing a deadlock

### ISSUE THREAD

**Issue by jorgecarleitao** [PyO3/pyo3#1305]
## 🐛 Bug Reports

We have a multi-threaded Rust application that calls Python from time to time within (tokio) threads. However, I am observing a deadlock on the code.

I am not entirely sure that what I am doing is correct, but I was able to reduce it to a minimal example (see below).

### 🌍 Environment

 - Your operating system and version: MacOS
 - Your python version: 3.7.4
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: brew + venv
 - Your Rust version (`rustc --version`): `rustc 1.46.0-nightly (3503f565e 2020-07-02)`
 - Your PyO3 version: `0.12.3`
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: not yet

### 💥 Reproducing

```rust
#src/lib.rs
use pyo3::{prelude::*, wrap_pyfunction};
use tokio::runtime::Runtime;
use tokio;

#[pyfunction]
fn compute() -> i32 {
    let mut rt = Runtime::new().unwrap();
    rt.block_on(async {
        let a = tokio::spawn(async {
            let gil = pyo3::Python::acquire_gil();
            let py = gil.python();
            let builtins = PyModule::import(py, "builtins").unwrap();
            let total: i32 = builtins.call1("sum", (vec![1, 2, 3],)).unwrap().extract().unwrap();        
            total
        });
        let b = tokio::spawn(async {
            let gil = pyo3::Python::acquire_gil();
            let py = gil.python();
            let builtins = PyModule::import(py, "builtins").unwrap();
            let total: i32 = builtins.call1("sum", (vec![1, 2, 3],)).unwrap().extract().unwrap();        
            total
        });
        let r1 = a.await.unwrap();
        let r2 = b.await.unwrap();

        r1 + r2
    })
}

#[pymodule]
fn blabla(_: Python, module: &PyModule) -> PyResult<()> {
    module.add_function(wrap_pyfunction!(compute, module)?)?;
    Ok(())
}
```

```
#Cargo.toml
[package]
name = "rust-tokio-pyo3"
version = "0.1.0"
authors = ["Jorge C. Leitao <jorgecarleitao@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "^0.2", features = ["macros", "rt-core", "rt-threaded"] }
pyo3 = { version = "0.12.3", features = ["extension-module"] }

[lib]
name = "blabla"
crate-type = ["cdylib"]
```

```python
# test_bla.py
import blabla

print(blabla.compute())
```

To reproduce, run:

```bash
python -m venv venv
source venv/bin/activate

pip install maturin==0.8.2 toml==0.10.1

maturin develop
python -m test_bla
```

WARNING: this code will not exit via keyboard: `kill PID` is required.

**Comment by khionu** [comment]
I would suggest using [an async RwLock from Tokio](https://docs.rs/tokio/0.3.5/tokio/sync/struct.RwLock.html) at the beginning of each Tokio Task that contains PyO3 code. While I haven't used PyO3 myself, I've heard issues with it and threading. Using the RwLock, you can use [the read lock](https://docs.rs/tokio/0.3.5/tokio/sync/struct.RwLock.html#method.read) for the scopes of each Task, and [the write lock](https://docs.rs/tokio/0.3.5/tokio/sync/struct.RwLock.html#method.write) for the Task with the GIL call. This would ensure as many concurrent non-GIL Tasks as possible, while having a global lock when you're about to do a GIL call.

This is mostly a guess from my async knowledge and my very rudimentary Python knowledge. I hope it helps in some form.

**Comment by khionu** [comment]
Also, RwLocks are normally prone to unfairness due to how the CPU schedules the locks, but Tokio's fairness mechanisms should compensate.

**Comment by kivo360** [comment]
Are you forced to create a runtime when you activate the compute function? I have a lazy runtime that I'm building at the start of the program and I'm trying to create a connection to a grpc service when I call a command.

The problem is, the client says I have reactor core problems.

**Comment by davidhewitt** [comment]
When interacting with Python, you have to always be aware that the Python GIL is exactly that - a global lock. If one thread holding the GIL is blocked waiting on another thread, you'll get a deadlock if that other thread is waiting to acquire the GIL.

The general rule is that you should *always* release the Python GIL before performing any other operation that blocks a thread. That could be waiting to lock a mutex, for example.

In your case, you need to remember that the thread calling the `#[pyfunction]` already has the GIL. So your call to `rt.block_on` is incorrect, as you are not first releasing the GIL.

You can do this by using `Python::allow_threads` to temporarily release the GIL before issuing the blocking instruction, like this:

```
#[pyfunction]
fn compute(py: Python) -> i32 {
    let mut rt = Runtime::new().unwrap();
    py.allow_threads(|| {
        // Inside this closure, this thread has temporarily released the GIL, meaning that 
        // the tasks a and b are now actually able to acquire the GIL and progress.
        rt.block_on(async {
            let a = tokio::spawn(async {
                let gil = pyo3::Python::acquire_gil();
                let py = gil.python();
                let builtins = PyModule::import(py, "builtins").unwrap();
                let total: i32 = builtins.call1("sum", (vec![1, 2, 3],)).unwrap().extract().unwrap();
                total
            });
            let b = tokio::spawn(async {
                let gil = pyo3::Python::acquire_gil();
                let py = gil.python();
                let builtins = PyModule::import(py, "builtins").unwrap();
                let total: i32 = builtins.call1("sum", (vec![1, 2, 3],)).unwrap().extract().unwrap();
                total
            });
            let r1 = a.await.unwrap();
            let r2 = b.await.unwrap();

            r1 + r2
        })
    })
}
```

This modified version of your `compute` function completes successfully without deadlocking.

**Comment by jorgecarleitao** [comment]
@khionu and @davidhewitt , thank you for your help.

@davidhewitt thanks for the solution. It makes sense, I was not aware of `allow_threads` API to achieve this. It solved the problem.

FYI, the usage of pyo3 here is for data processing with Apache Arrow: https://github.com/jorgecarleitao/datafusion-python. We use threads for parallelism on the rust side, but allow Python to run in the middle, which is why we need to lock the GIL.

**Comment by dbsxdbsx** [comment]
@ davidhewitt,  just  a side question referring to your comment:`The general rule is that you should always release the Python GIL before performing any operation that blocks a thread.....`
If I just want a multi-thread function from rust-side, and hope to blocking it when using the funciton in python scripyt, is it still necessary to use `Python::allow_threads`?

**Comment by davidhewitt** [comment]
@dbsxdbsx I'm not entirely sure what you're asking, but here's my attempt to answer:

1. You can make as many Rust threads as you like. If they don't run Python code, they won't get blocked by the GIL.
2. If the threads are just running Rust code (without Python), then no need to call `Python::allow_threads`. But if _any_ of those threads try to call Python code, you'll need to have called `Python::allow_threads`.

**Comment by programmerjake** [comment]
Also, if you want other Python threads to run while the current Python thread is running Rust code, you need to call `allow_threads`

**Comment by dbsxdbsx** [comment]
@davidhewitt @programmerjake , thanks for your reply. It is quite clear now.
