### ISSUE TITLE
abi3 causes compile failures where u128s are involved

### ISSUE THREAD

**Issue by aspenluxxxy** [PyO3/pyo3#1309]
A `#[staticmethod]` that takes a `u128` as an argument will fail to compile with abi3, but compiles fine without abi3

### 🌍 Environment

 - Your operating system and version: Arch Linux running in WSL2
 - Your python version: Python 3.9.0
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: `pacman`
 - Your Rust version (`rustc --version`): `rustc 1.48.0 (7eac88abb 2020-11-16)`
 - Your PyO3 version: Latest master (commits `92b7a9736c9585883df5ec5bc01004caa7f65106` and `9aa70f7c89afdbafad47bce02e1cdbdb893406bb`)
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: I already was.

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the Rust code and the Python.

```rust
use pyo3::prelude::*;

#[pyclass]
struct Example {
    a: u128,
}

#[pymethods]
impl Example {
    #[staticmethod]
    pub fn new_seed(seed: u128) -> Self {
        Example { a: seed }
    }
}
```

```toml
[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
rev = "9aa70f7c89afdbafad47bce02e1cdbdb893406bb"
features = ["extension-module", "abi3"]
```

Result:
```
error[E0277]: the trait bound `u128: PyClass` is not satisfied
 --> src/lib.rs:8:1
  |
8 | #[pymethods]
  | ^^^^^^^^^^^^ the trait `PyClass` is not implemented for `u128`
  |
  = note: required because of the requirements on the impl of `pyo3::FromPyObject<'_>` for `u128`
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info
```

**Comment by birkenfeld** [comment]
The `impl FromPyObject` for 128-bit integers uses in `_PyLong_AsByteArray`.

An alternative impl under `abi3` could call the method `to_bytes` on the Python object instead - it will be a little slower of course.  Alternately, use math on the Python side...

**Comment by kngwyu** [comment]
I implemented the conversions using `eval`. Let me know if you have any alternatives.
