### ISSUE TITLE
please include LICENSE files in all published crates

### ISSUE THREAD

**Issue by decathorpe** [PyO3/pyo3#1313]
The `pyo3-derive-backend` and `py3cls` crates published to crates.io do not contain the LICENSE text file of the project. For Apache-2.0, it's necessary to distribute the license text alongside the source code it covers. This crates issues for (linux) distributions which redistribute the crate source code.

Adding a symlink from the `pyo3-derive-backend` and `pyo3cls` directories to the LICENSE file in the root of the repository should be enough to fix this, assuming you're running `cargo publish` on linux or mac OS (AFAIK, full copies of the files are necessary on windows, since symlinks do not work there).

**Comment by programmerjake** [comment]
windows has symlinks, idk if they work with git

**Comment by kngwyu** [comment]
Thanks, for now, I added symlinks.

**Comment by decathorpe** [comment]
Thank you!
