### ISSUE TITLE
Integration tests can't find crate

### ISSUE THREAD

**Issue by OrangeTux** [PyO3/pyo3#1321]
This is not a bug in PyO3, but it can hit Pyo3 users nonetheless. 

I'm using PyO3 for a project and wrote some integration tests. I put those tests inside a `tests/` directory at the crate root. However my tests fail to compile because my crate couldn't be found:
   
``` bash
 error[E0463]: can't find crate for `yolo`
   --> tests/tests.rs:4:1
    |
  4 | use yolo;
    | ^^^^^^^^^ can't find crate
```

It turns out that `cdylib` crate types can't use tests inside a `tests/` directory. See https://github.com/rust-lang/cargo/issues/6659 

I think this should be documented, as this is not very obvious. What would be the best place to do that? Inside the FAQ?

**Comment by kngwyu** [comment]
Thanks.

> Inside the FAQ?

Yeah, I think FAQ & Troubleshooting is good and am really appriciate your PR.

**Comment by OrangeTux** [comment]
Sure. I just created a PR. 

Happy holidays!
