### ISSUE TITLE
Heisenbug in `test_check_exception_nested` on Python 2.7

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [PyO3/pyo3#133]
Tests [`test_check_exception`](https://github.com/PyO3/pyo3/blob/master/src/objects/exc_impl.rs#L114) and [`test_check_exception_nested`](https://github.com/PyO3/pyo3/blob/2aedbffcd01e05a8b0d1572ab87561db6ec79835/src/objects/exc_impl.rs#L128) fail from time to time on Travis and AppVeyor, only on Python 2.7.

I was unable to reproduce it locally, so the investigation is going slowly.
I added debug prints to the tests (#132).

 * Example [Travis failure](https://travis-ci.org/PyO3/pyo3/jobs/354672719#L1234)
 * Example [AppVeyor failure](https://ci.appveyor.com/project/fafhrd91/pyo3/build/0.2.163/job/cg67my1mgpmhb7yu#L299) (this particular run had slightly different debug prints, so particular messages won't match, but it looks like the same problem to me)

To summarize, here is what it looks like:

```rust
let d = PyDict::new(py);
println!("d={:?}, type(d)={:?}", d, d.get_type());
// d={}, type(d)=<type 'dict'>
// as expected

let email_module = py.import("email").unwrap();
println!("email_module={:?}, type(email_module)={:?}", email_module, email_module.get_type());
// email_module=<module 'email' from '/opt/python/2.7.14/lib/python2.7/email/__init__.pyc'>, type(email_module)=<type 'module'>
// as expected

println!("d={:?}, type(d)={:?}", d, d.get_type());
// d=<module 'email' from '/opt/python/2.7.14/lib/python2.7/email/__init__.pyc'>, type(d)=<type 'module'>
// WHAT?!

d.set_item("email", email_module).unwrap_or_else(|e| {
    e.print(py);
    // SystemError: Objects/dictobject.c:833: bad argument to internal function
    // expected when we call PyDict_SetItem() on a module object instead of a dict,
    // but how did that happen?

    panic!()
    // panics
});
```

There could undefined behavior in `PyDict::new()` or in `py.import()`.

**Comment by fafhrd91** [comment]
Seems worn now
