### ISSUE TITLE
[Coordination Request] Should PyO3 or Eyre implement From<eyre::Report>?

### ISSUE THREAD

**Issue by TheButlah** [PyO3/pyo3#1349]
Hi, the maintainer of `eyre` is interested in supporting conversion from their `eyre::Report` type to `PyErr`. Does this implementation belong in `pyo3` or in `eyre`?

Reference: https://github.com/yaahc/eyre/issues/45

**Comment by davidhewitt** [comment]
I think pyO3 is unlikely to ever depend on eyre internally. So I'm happy for the implementation to be in `eyre`, as it sounds like three maintainer is willing to own it there.

Thanks for checking!

**Comment by TheButlah** [comment]
@davidhewitt Would you be willing to briefly review the PR I just submitted to `eyre`? https://github.com/yaahc/eyre/pull/47
