### ISSUE TITLE
word-count example doesn't compile on manylinux

### ISSUE THREAD

**Issue by gukoff** [PyO3/pyo3#135]
Repository with code: https://github.com/gukoff/PyO3-manylinux-bug
One can clone it and run a one-liner to reproduce the issue.

Error:
```
  error: failed to run custom build command for `pyo3 v0.2.5`
  process didn't exit successfully: `/tmp/pip-sHw2jX-build/build/temp.linux-x86_64-2.7/word-count/release/build/pyo3-aea46c0f50a8070f/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "python script failed with stderr:\n\nTraceback (most recent call last):\n  File \"<string>\", line 1, in ?\nImportError: No module named sysconfig\n"', libcore/result.rs:945:5
```

Full build log: https://pastebin.com/RRFAMTga

The error does reproduce on Mac/Ubuntu Docker, pyo3 v0.2.4 and older nightly versions of rustc. 
And it was working just fine a couple of weeks ago.

**Comment by gukoff** [comment]
@fafhrd91 aren't you by chance familiar with this issue?

**Comment by fafhrd91** [comment]
looks like a problem with python paths. are you able to build project outside of docker?

**Comment by gukoff** [comment]
Yes, it builds perfectly outside of docker.

**Comment by fafhrd91** [comment]
are you able to build any c-extension inside docker?

**Comment by gukoff** [comment]
Yep. I managed to compile https://github.com/closeio/ciso8601 using the same `build_wheels.sh` script. So, the problem is neither in manylinux1 nor in installing rustc via rustup.sh.

**Comment by fafhrd91** [comment]
I am busy with other projects at the moment, but I’ll try to check this problem

**Comment by zaabjuda** [comment]
Hi, @gukoff I had a similar problem. The problem was solved by adding a variable PYTHON_SYS_EXECUTABLE. See Look how I did it https://github.com/PushAMP/pamagent/blob/master/build-wheels.sh#L6

**Comment by gukoff** [comment]
Interesting. `PYTHON_SYS_EXECUTABLE` fixes the problem, but still doesn't make pyo3 compile.
New build log: https://pastebin.com/z4YHBbdq

**Comment by zaabjuda** [comment]
This problem is now relevant for the latest nightly assemblies. As a temporary solution, you can use the last working build from March 26

```
rustup toolchain install nightly-2018-03-26
rustup default nightly-2018-03-26
```

**Comment by fafhrd91** [comment]
New version is released
