### ISSUE TITLE
pyO3 compilation fails because 'cannot find function `type_name` in module `std::any`'

### ISSUE THREAD

**Issue by kociak** [PyO3/pyo3#1357]
## 🐛 Bug Reports

pyO3 compilation fails because 'cannot find function `type_name` in module `std::any`'.
This happens with `cargo build` as well as `maturin develop`

complete compiler message:

`--> /Users/mathieukociak/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.11.1/src/pyclass.rs:362:27
    |
362 |                 std::any::type_name::<T>()
    |                           ^^^^^^^^^ not found in `std::any`
help: possible candidates are found in other modules, you can import them into scope
    |
2   | use core::intrinsics::type_name;
    |
2   | use std::intrinsics::type_name;
    |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `pyo3`.
`

### 🌍 Environment

 - Mac OS v11.1 (Big Sur), MacBook Pro (13 inches, 2020, 4 ports Thunderbolt 3)
 - Python 3.9.1 (through conda-forge)
 - Python installed with conda 
 - rustc 1.37.0
 - pyo3 v0.11.1
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: no

### 💥 Reproducing

`// src/lib.rs
use pyo3::prelude::*;`

then going to terminal, and invoking `Cargo build` or `maturin develop`

**Comment by kngwyu** [comment]
It's added in Rust 1.39 and we only support more recent Rust (>= 1.45)

**Comment by kociak** [comment]
Works now with Rust 1.49.0, same environment
Thanks
