### ISSUE TITLE
Python subclassing doesn't inherit from pyclass on py3.6 or 3.7

### ISSUE THREAD

**Issue by mtreinish** [PyO3/pyo3#1363]
## 🐛 Bug Reports

In retworkx I'm trying to update to use the latest pyo3 version in https://github.com/Qiskit/retworkx/pull/224 ci jobs on python 3.6 and 3.7: https://github.com/Qiskit/retworkx/pull/224/checks?check_run_id=1650749331#step:6:16

Several of the tests use a python subclass of a rust class (it's just a backwards compat alias so there are no changes besides the name it's defined here: https://github.com/Qiskit/retworkx/blob/master/retworkx/__init__.py#L15-L83 ) and those tests are all failing on python 3.6 and 3.7 (both locally and in CI) with a `TypeError` on method calls (the python subclass type isn't valid for the rust method) or on the constructor (saying no constructor is defined for the subclas). The issue looks like the changes in subclassing for 0.13.0 don't work with python 3.6 or 3.7 as the 3.8 and 3.9 jobs work fine. 

### 🌍 Environment

 - Your operating system and version: linux x86_64
 - Your python version: 3.6.12 and 3.7.9
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: distro package with virtualenv
 - Your Rust version (`rustc --version`): 1.49.0
 - Your PyO3 version: 0.13.0
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: no

### 💥 Reproducing

I tried to make a minimum reproduce case with:

```rust
#[pyclass(module = "mymodule", subclass)]
pub struct MyClass {
    pub value: bool,
}

#[pymethods]
impl MyClass {
    #[new]
    fn new() -> Self {
        MyClass {
            value: false,
        }
    }
    
    fn get_value(&self) -> bool {
        self.value
    }
}
```

```python3
import mymodule
class MySubClass(mymodule.MyClass):
    pass
    
obj = MySubClass()
print(obj.get_value())
```

but this worked fine locally (both in lib.rs and importing the class definition from another rust module). So I'm not sure what I'm doing differently in retworkx that could be causing this. But the same exact code worked fine with 0.12.x and the upgrade notes only called out using the `subclass` argument on the pyclass macro which I already was using.

**Comment by davidhewitt** [comment]
Thanks for reporting. As far as I can tell this is a bug in PyO3 0.13 which is caused by the change in https://bugs.python.org/issue35810 being applied to _all_ Python versions, when it should only have been applied in Python 3.8 and up.

https://docs.python.org/3/whatsnew/3.8.html#changes-in-the-c-api

I'm preparing a PR now to fix this in PyO3. Worthy of a 0.13.1 patch release for sure! 😬

**Comment by kngwyu** [comment]
Good catch, thank you!
👍🏼  for releasing 0.13.1.
