### ISSUE TITLE
Implement PyClass for PathBuf and Path

### ISSUE THREAD

**Issue by kangalioo** [PyO3/pyo3#1377]
There exists an infallible conversion from String to PathBuf (and hence Path), so if I'm not missing something, there is no real reason not to implement PyClass for PathBuf/Path.

That would allow Rust functions exposed to Python to take paths as parameters with the actual appropriate Rust type, instead of having to use String as a workaround.

**Comment by kangalioo** [comment]
I'm trying to make a PR for this

**Comment by davidhewitt** [comment]
I think rather than `PyClass`, you should implement `IntoPy<PyObject>`, `ToPyObject`, and `FromPyObject` for `PathBuf` (and maybe `Path`, if you can make it work).

**Comment by kangalioo** [comment]
I think it will be better to implement those three traits on OsStr and OsString, because that's what the this work is really about: converting between Python's magic strings and Rust's opaque OS strings.

Path and PathBuf can just redirect to the implementations on OsStr and OsString.

**Comment by davidhewitt** [comment]
That sounds sensible to me! If you're looking at string types, it could be worth assessing if `CStr` and `CString` should also be supported. I think Python allows null bytes in the middle of its strings so definitely from-Python would be fallible for those.

**Comment by kangalioo** [comment]
Should the conversion functions from/to OsStr/Cstr go onto the PyString struct? It would get four new methods:
- `from_osstr`
- `to_osstr`
- `from_cstr`
- `to_cstr`

The alternative would be to create new modules `types/cstr.rs` and `types/osstr.rs`, and implement the conversions there

**Comment by davidhewitt** [comment]
I would suggest avoiding new methods on `PyString` if we can - as much as possible the methods on the python-native types are just wrappers around the underlying Python C API.

Is there a reason the traits above don't provide enough functionality for what you need? The traits are all we need for `#[pyfunction]` / `#[pymethods]` etc.

**Comment by kangalioo** [comment]
I was just asking what you preferred, I'm fine with both.


In any case, I wrote the trait implementations for OsStr/OsString: https://github.com/kangalioo/pyo3/blob/bbc578fda767134ff678c1ebc62eae5e0e756cb2/src/types/osstr.rs. I'd greatly appreciate if you could check it out to make sure I didn't do anything totally stupid. Commenst with `// HELP` mark places where I was unsure if I was doing the right thing.

**Comment by davidhewitt** [comment]
👍 totally makes sense - nice work and thanks for the PR; I'll do my best to make time to review it as soon as I can.

**Comment by davidhewitt** [comment]
Closed by #1379 . Thanks again for the PR.
