### ISSUE TITLE
PyO3 doesn't find pip installed modules

### ISSUE THREAD

**Issue by rowungiles** [PyO3/pyo3#1381]
Hello - I want to start by saying thank you for this project. I really appreciate the amount of time and effort being put into it. It's really brilliant.

I have a Docker container where I'm using pip to install a number of modules.

```
Want to access Python APIs? Then use PyModule::import.

Pymodule::import can be used to get handle to a Python module from Rust. You can use this to import and use any Python module available in your environment.
```

If I access these modules via an import in a `.py` script, then all is well.

When I try to `PyModule::import(py, "numpy")` that module is not found.

Here is the output of python_config + the ModuleNotFoundError.
```
interpreter version: CPython 3.9

interpreter path: /usr/local/bin/python

libdir: Some("/usr/local/lib")

shared: true

base prefix: /usr/local

ld_version: 3.9

pointer width: 8

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'ModuleNotFoundError'>, value: ModuleNotFoundError("No module named 'numpy'"), traceback: None }', src/main.rs:38:47

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The TOML is using pyo3 version "0.13.1".
Python 3.9 is in the Docker container.

### 💥 Reproducing
I have ~created an minimum reproducible project to demonstrate~.

My hunch is that there must be an issue with a PATH but I'm uncertain given the lack of issue when running the `.py` file.

**Comment by birkenfeld** [comment]
Is the interpreter found by `python_config` really relevant? I think you should rather find the relevant from inside the pyo3 interpreter (examining `sys.executable`, `sys.path` etc).

**Comment by birkenfeld** [comment]
To be concrete, put this in the `with_gil` block:
```
        let x = 0;
        py_run!(py, x, r#"
import sys
print(sys.executable, sys.path)
"#);
```
(The `x` is a dummy because `py_run` doesn't like having no variables passed into Python...)

**Comment by rowungiles** [comment]
hi @birkenfeld thanks for the snippet. 

The output was:
```
/usr/local/bin/python3 ['/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages']
```

That was _exactly_ the clue I needed. The `python3-dev` installs 3.7 which clashes with the 3.9 in the container.

I've aligned the 2 versions of Python and now everything works as expected.

Thank you so much for your fast reply.
