### ISSUE TITLE
Using rust keywords as parameter names

### ISSUE THREAD

**Issue by Lehona** [PyO3/pyo3#1382]
Rust allows you to use keywords as identifiers by prepending `r#`, e.g. a parameter may be named `r#type`. 

When used as parameter in e.g. a constructor, passing e.g. `type="foo"` on Python's side is not accepted by Rust. Example

```python
arch = report.macho.CPUArchitecture(type=type_, subtype=subtype)
TypeError: CPUArchitecture.__new__() missing required positional argument: r#type
```

In Rust:
```rust
#[pymethods]
impl CPUArchitecture {
    #[new]
    pub fn new(_py: Python, r#type: Py<CPUType>, subtype: Py<CPUSubType>) -> PyResult<Self> {
        Ok(Self { r#type, subtype })
    }
}
```

I believe `r#type` should be translated to `type` for Python.

**Comment by davidhewitt** [comment]
I suspect a missing call to `serde::IdentExt::unraw` somewhere - we already have similar fixes in place for struct names etc.

I'll try to find the fix tonight if nobody else takes it on before then.
