### ISSUE TITLE
PyObject.clone doesn't actually clone?

### ISSUE THREAD

**Issue by SyntaxRules** [PyO3/pyo3#1394]
I want to copy a python object in my Rust code so that it cannot be mutated by external python code. I tried looking into the `PyObject.clone()` method. But this only clones the reference to the object.

A minimum example is: **EDIT: A more complete (and working) example below:** https://github.com/PyO3/pyo3/issues/1394#issuecomment-763130042
```
#[pyclass]
struct PyObjSaver {
    value: PyObject
}

#[pymethods]
impl PyObjSaver {
    pub fn get(&self) -> PyObject {
        self.value.clone()
    }
    pub fn set(&mut self, value: PyObject) {
        self.value = value.clone();
    }
}
```

Unfortunately an object (like a python dict) that is passed into the set method can later be mutated. A value retireved from the get method can be mutated as well.

I can get around this using the python copy method like so:
```
pub fn set(&mut self, value: PyObject) -> PyResult<()> {
      Python::with_gil(|py| {
          let copy_module = PyModule::import(py, "copy")?;
          self.value = copy_module.call1("copy", (value,))?.extract()?
      })
  }
```
This doesn't seem ideal. How might I copy a PyObject without importing the python copy module?

**Comment by birkenfeld** [comment]
Why is that not acceptable? After all this functionality isn't a built-in in Python itself.

BTW, `clone` in Rust is the equivalent of Python's `copy.deepcopy`, not `copy.copy`.

**Comment by SyntaxRules** [comment]
@birkenfeld I think you may have hit on the issue at hand:
> BTW, clone in Rust is the equivalent of Python's copy.deepcopy, not copy.copy.
It does not appear to be so. A value `n` passed to `PyObjSaver.set(n)` can be changed after the call and both references will be changed. In other words:
```
t = PyObjSaver()
n = {"a": 1}
t.set(n)
n["a"] = 5
t.get()["a"] == 5
```

The docs say PyObject: "Can be cloned using Python reference counts with .clone()." [Link](https://pyo3.rs/v0.13.1/types.html#pyt-and-pyobject) I'm not sure if that means marked as new reference or if it really is suppose to be a deepcopy.

Thank for the hints with `&PyAny` and the method block.

**Comment by SyntaxRules** [comment]
A more complete example:

**Rust Module**
```rust
use pyo3::prelude::*;

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}

#[allow(unused_variables)]
#[pymodule]
pub fn muta(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<PyObjSaver>()?;
    Ok(())
}

#[pyclass]
struct PyObjSaver {
    value: Option<PyObject>
}

#[pymethods]
impl PyObjSaver {
    #[new]
    pub fn new() -> PyObjSaver {
        PyObjSaver {
            value: None
        }
    }

    pub fn get(&self) -> Option<PyObject> {
        match &self.value {
            Some(t) => Some(t.clone()),
            None => None
        }
    }

    pub fn set(&mut self, value: PyObject) {
        self.value = Some(value.clone());
    }
}
```

**Build**
```
maturin build --interpreter python --release
pip uninstall muta -y
pip install target\wheels\muta-0.1.0-cp37-none-win_amd64.whl
```

**Python console testing**
```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import muta
>>> z = muta.PyObjSaver()
>>> z
<PyObjSaver object at 0x0000027E6113D2F0>
>>> a = {"one": 10}
>>> z.set(a)
>>> z.get()
{'one': 10}
>>> a["one"] = 30
>>> z.get()
{'one': 30}
>>>
```

I expected the value in from `z.get()` to be `{'one': 10}`. Unfortunately I was able to modify `a` to change the internals of `z` the `PyObjSaver` object.

**Comment by birkenfeld** [comment]
Sorry, this was misleading.  I meant that the definition of `clone()` in Rust on "plain" data types (such as `Vec`, `HashMap`) corresponds to `deepcopy` in Python.

On special types like `Arc`, or here `PyObject` it takes a different meaning.  That it only creates new Python references in PyO3 is intended.

**Comment by davidhewitt** [comment]
> On special types like `Arc`, or here `PyObject` it takes a different meaning. That it only creates new Python references in PyO3 is intended.

This. As Python is reference-counted, it is a natural translation to Rust for all of PyO3's Python-native objects to behave like `Arc`.

Also note that `copy.deepcopy` is implemented purely in Python; there is no Python C-API to "clone" an entire object in the way you ask. IIRC `copy.deepcopy` works by pickling and unpickling the entire object.

It's not intended for PyO3's behaviour to change in this regard. Perhaps there's some documentation we can improve though.

**Comment by SyntaxRules** [comment]
Understood. I don't particularly like the the dual meaning of clone on special vs non-special types in rust- but PyObject is following convention here. Feel free to close this issue, or keep it open if you want to come back around to do some documentation.

**Comment by davidhewitt** [comment]
I wouldn't particularly class it as "special" vs "non-special" types. I think of it as connected to ownership.

Types like `&T`, `Arc<T>`, `Py<T>` and `PyObject` all represent shared ownership of the underlying data. To call `.clone()` on any of these types gives you another handle to that underlying shared data.

Types like `Vec<T>` or `struct Foo` represent exclusive ownership; to call `.clone()` on any of these implies that you'll create a full new copy as the result of the clone.
