### ISSUE TITLE
Calling `io.StringIO('hello').read()` from Rust returns empty string

### ISSUE THREAD

**Issue by mre** [PyO3/pyo3#143]
I try to call [read()](https://docs.python.org/3/library/io.html#io.RawIOBase.read) on a Python object that implements it, like so:

```python
from io import StringIO
obj = StringIO(u'hello')
myrustmodule.read(obj)
```

```rust
fn load(py: Python, fp: PyObject, kwargs: Option<&PyDict>) -> PyResult<PyObject> {
    let s_obj = fp.call_method0(py, "read")?;
    let s: String = s_obj.extract(py)?;
    println!("Result {:?}", s);
    // ...
}
```

This prints
```rust
Result ""
```

Tried wit both, a file handle and an instance of `StringIO`.  
In both cases, I get an empty string as a result.

Also tried two other ways to call the method, which also returned an empty string:

```rust
let s_obj = fp.call_method(py, "read", NoArgs, NoArgs)?;
```

```rust
let func = fp.getattr(py, "read")?;
func.call(py, NoArgs, NoArgs)
```

**Comment by mre** [comment]
After some more trial and error, I found a way to do it, by calling `seek(0)` before reading:

```rust
fp.call_method(py, "seek", (0,), NoArgs)?;

let s_obj = fp.call_method0(py, "read")?;
let s: String = s_obj.extract(py)?;
println!("Result {:?}", s);
```
This prints `hello`.

So, apparently the stream position is not set to 0 in the beginning:
```rust
let pos: i64 = fp.call_method0(py, "tell")?.extract(py)?;
println!("Pos before: {}", pos);

fp.call_method(py, "seek", (0,), NoArgs)?;

let pos: i64 = fp.call_method0(py, "tell")?.extract(py)?;
println!("Pos after: {}", pos);
```

Output:
```
Pos before: 17
Pos after: 0
```

Also see this [related ticket](https://github.com/dgrunwald/rust-cpython/issues/94)

**Comment by konstin** [comment]
Can you provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example)? And have you checked that you didn't read the StringIO before?

**Comment by mre** [comment]
So it *does* work when I execute Python code from within Rust:

```rust
extern crate pyo3;
use pyo3::{AsPyRef, ObjectProtocol, PyDict, PyResult, Python, ToPyObject};

fn main() {
    let gil = Python::acquire_gil();
    hello(gil.python()).unwrap_or_else(|e| e.print(gil.python()));
}

fn hello(py: Python) -> PyResult<()> {
    let locals = PyDict::new(py);
    locals.set_item("io", py.import("io")?)?;
    let sio_obj = py.eval(r#"io.StringIO("hi")"#, None, Some(locals))?;

    assert_eq!(
        sio_obj.call_method0("tell")?,
        0_i64.to_object(py).as_ref(py)
    );
    assert_eq!(sio_obj.call_method0("read")?, "hi".to_object(py).as_ref(py));
    Ok(())
}
```

For some reason I can't get the second assertion to work. The output is quite suspicious:

```rust
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `'hi'`,
 right: `'hi'`', src/main.rs:18:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Nevertheless, the first assertion checks if the position of the stream to be 0, which is what I expect.
Therefore, it could have something to do with calling Rust code from Python.
When I find the time, I'll try to come up with a way to test this.

**Comment by konstin** [comment]
The problem in the example is that it compares pointers (and not their content). Extracting the value and comparing then does work:

```rust
extern crate pyo3;
use pyo3::{AsPyRef, ObjectProtocol, PyDict, PyResult, Python, ToPyObject};

fn main() {
    let gil = Python::acquire_gil();
    hello(gil.python()).unwrap_or_else(|e| e.print(gil.python()));
}

fn hello(py: Python) -> PyResult<()> {
    let locals = PyDict::new(py);
    locals.set_item("io", py.import("io")?)?;
    let sio_obj = py.eval(r#"io.StringIO("hi")"#, None, Some(locals))?;

    assert_eq!(
        sio_obj.call_method0("tell")?,
        0_i64.to_object(py).as_ref(py)
    );
    let left: String = sio_obj.call_method0("read")?.extract()?;
    assert_eq!(&left, "hi");
    Ok(())
}
```

**Comment by konstin** [comment]
(I'm not sure if comparing pointers is really a good default, `__eq__` might be a better choice, but that needs an extra evaluation)

**Comment by mre** [comment]
I think we can close this. All good from my side.
