### ISSUE TITLE
Defining member methods without #[pymethods]

### ISSUE THREAD

**Issue by abbec** [PyO3/pyo3#1434]
We are working on an embedded runtime for Python in WASI for which we are using pyo3. So far, everything has been working great until we wanted to define a class in Rust. The `pymethods` derive macro uses `inventory`, which in turn uses `ctor`, that is not supported on WASI/WASM. The `pyclass` derive macro works fine.

So my question is, is there an alternative method (that isn't the full C ffi method) to adding methods to a Python class defined in rust? One ugly one I guess could be to have a factory method for the class and then add methods through `setattr` but it seems like there should be a manual but less ugly method?

**Comment by abbec** [comment]
Is There an opt-out of the functionality to have multiple `pymethods` and instead specifying it "statically"?

**Comment by davidhewitt** [comment]
> Is There an opt-out of the functionality to have multiple pymethods and instead specifying it "statically"?

Great question - I've been actively working towards this feature. Currently #1424 is the latest step in that direction. Waiting for review on that part and then one or two PRs should be enough to finish the feature off.

**Comment by abbec** [comment]
That sounds great! In the meantime, is there a way to use `pyfunction` functions that take "self" and add them to the description of the class?

**Comment by davidhewitt** [comment]
Ugh, we don't really have a way to do this manually I'm afraid. The best I can think of right now would be to resort to c ffi to do this. You might have to implement the whole class that way though; `#[pyclass]` basically assumes that you're using the whole suite of `pyo3` macros.

Once #1424 is in then it really won't take long for me to provide the opt-out. I have a pretty clear idea of how it'll work.

**Comment by abbec** [comment]
Ah ok, no problem :) We can close this then since there is an answer in progress. Thanks!
