### ISSUE TITLE
__bytes__() method does not get a 'text_signature' by default 

### ISSUE THREAD

**Issue by ravenexp** [PyO3/pyo3#1465]
## 🐛 Bug Reports

I'm using pydoc to check the doc strings and function signatures in the compiled extension module.
When implementing `PyObjectProtocol` trait for my class, all trait methods except for `__bytes__()` seem
to get their #[text_signature]'s set implicitly (no Rust code attributes required).
I expect the same to happen for `__bytes__()` method as well.

Example pydoc output:

```
    class Instruction(builtins.object)
     |  Python class wrapper for Rust `Instruction` enum.
     |  
     |  Methods defined here:
     |  
     |  __bytes__(...)
     |  
     |  __repr__(self, /)
     |      Return repr(self).
     |  
     |  __str__(self, /)
     |      Return str(self).
     |  
     |  size(self, /)
     |      Returns the encoded instruction length in bytes.
     |  
     |  ----------------------------------------------------------------------
```

### 🌍 Environment

 - Your operating system and version: Arch Linux
 - Your python version: 3.9.2
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: pacman
 - Your Rust version (`rustc --version`): 1.50
 - Your PyO3 version: 13.2
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: no

**Comment by kngwyu** [comment]
Thanks, I'll investigate this bug.

**Comment by davidhewitt** [comment]
I wonder if this is because `__bytes__` is a method rather than a slot? Afaik we don't generate signature for methods automatically.

**Comment by ravenexp** [comment]
I've tried adding

```
/// Return bytes(self).                     
#[text_signature = "($self, /)"]
```

to the trait method implementation, but it had no effect.

**Comment by ravenexp** [comment]
I confirm that https://github.com/PyO3/pyo3/pull/1483 fixed the problem and both `#[text_signature]` and doc comments now work with `__bytes__()`.

I think we can close this issue now.
