### ISSUE TITLE
Where will the Python "print" function print to?

### ISSUE THREAD

**Issue by vedantroy** [PyO3/pyo3#1466]
On my local machine, if I call Python from Rust & the Python code calls `print`, then the Rust executable will print out whatever the Python script is printing. But inside a Docker container, it seems like the Rust executable is not printing whenever the Python script calls print because `docker logs <container id>` doesn't show the output from the Python script.

If the Python code calls `print`, will it output to the Rust stdout?

I'm not sure if there's just some Docker shenanigans going on here, or if I'm misunderstanding how the Python stdout interacts with the Rust stdout.

If this is a bug, I can provide a small Dockerfile to reproduce what's going on.

**Comment by programmerjake** [comment]
I'm likely misremembering, but doesn't docker only log stderr?

**Comment by vedantroy** [comment]
Docker seems to be printing Rust `println` statements, which I assume print to stdout?

**Comment by programmerjake** [comment]
the other thing to try is flushing python's stdout. both python's stdout and rust's println go to the same place, but they have separate buffering, which, if not flushed, will just leave stuff to be written in a memory buffer and won't write all of it to the linux stdout file descriptor.

**Comment by davidhewitt** [comment]
> the other thing to try is flushing python's stdout.

Or to set the environment variable `PYTHONUNBUFFERED` to `1` inside the docker container. https://stackoverflow.com/questions/59812009/what-is-the-use-of-pythonunbuffered-in-docker-file/59812588
