### ISSUE TITLE
Failure if there are multiple sysconfigdata files during cross-compilation

### ISSUE THREAD

**Issue by wietsedv** [PyO3/pyo3#1484]
PyO3 searches for `_sysconfigdata*.py` and crashes if it finds any other number than 1 of them:

https://github.com/PyO3/pyo3/blob/4c80ce93c39110f1d65944c2ce4ea2149e241613/build.rs#L411

If you are cross compiling, you can set the target lib dir with `PYO3_CROSS_LIB_DIR` and specify the python version with `PYO3_CROSS_PYTHON_VERSION` if there are multiple versions.

Within these contraints, any matching `_sysconfigdata*.py` file will be found:

https://github.com/PyO3/pyo3/blob/4c80ce93c39110f1d65944c2ce4ea2149e241613/build.rs#L431

However, there is a problem with Anaconda Python versions, which is that all alternative `_sysconfigdata*.py` files are always bundled with Python, not only the target platform variant. So we have among others, the following files, where only one of them is relevant:

- `/lib/python3.8/_sysconfigdata_arm64_apple_darwin20_0_0.py`
- `/lib/python3.8/_sysconfigdata_powerpc64le_conda_linux_gnu.py`
- `/lib/python3.8/_sysconfigdata_x86_64_conda_cos6_linux_gnu.py`

If I understand correctly, CPython uses a `_PYTHON_SYSCONFIGDATA_NAME` environment variable as a workaround for this specific cross-compilation issue.

My proposed solution is to take the sysconfigdata that corresponds with `_PYTHON_SYSCONFIGDATA_NAME` if there are multiple sysconfigdata files, the environment variable is set, and if that particular file exists.

### 🌍 Environment

 - Your operating system and version: macOS 11.2
 - Your python version: conda-forge/python 3.8.8
 - Your PyO3 version: 0.12.4+

This problem affects everyone who tries to do PyO3 cross compilation with Anaconda Python.

**Comment by davidhewitt** [comment]
Hi @wiesedv thanks for the bug report. Your proposed fix sounds reasonable; a PR implementing it would be very welcome! I can help if you need any pointers.

**Comment by kngwyu** [comment]
Nice catch, thank you for reporting!
