### ISSUE TITLE
Run Python in parallel from Rust?

### ISSUE THREAD

**Issue by vedantroy** [PyO3/pyo3#1485]
Not sure if this is solved by [multiple interpreters](https://github.com/PyO3/pyo3/issues/879), but I was wondering if it is possible to run a Python function in parallel. I.e run 2 instances at once?

My use-case is that I have a slow Python function in a fast Rust program and I would like to make this function less of a bottleneck by executing multiple instances of it at once over multiple threads (using something like `std::thread::spawn` or `tokio::spawn`)

**Comment by davidhewitt** [comment]
To run two Python functions concurrently _in the same process_ you'd need to have "isolated subinterpreters" which have their own individual GILs. Last I saw this was experimental in Python 3.10, and we don't have support for it in PyO3 I'm afraid.

You'd have to do something a bit more compicated and consider forking the process and use inter-process communication to run Python functions in parallel at the moment (i.e. exactly like the Python `multiprocessing` module).

**Comment by vedantroy** [comment]
Got it! Thanks for letting me know.
