### ISSUE TITLE
Serde-like deserialization for Python to Rust?

### ISSUE THREAD

**Issue by vedantroy** [PyO3/pyo3#1488]
Is there serde-like deserialization to convert Python objects to Rust?

Something like:

```rust
struct Foo(String, String);

// x is of type `PyAny`
let rustTuple: &Foo = x.as_rust_obj().unwrap();
```

**Comment by messense** [comment]
See https://github.com/davidhewitt/pythonize

**Comment by messense** [comment]
Closing as a duplicate of https://github.com/PyO3/pyo3/issues/566
