### ISSUE TITLE
Including a native python class in a PyO3 library

### ISSUE THREAD

**Issue by jafioti** [PyO3/pyo3#1491]
I have written a library in rust with PyO3, but there is a final class that I want to include, currently written in python, that I cannot translate to rust, because it is too flexible and open. I would like to include this class in my package, but I'm not sure if this can be done, since the rest of the package is written in pyo3/rust. Is there a way to just include a python module in the package?

**Comment by messense** [comment]
Take a look at the word-count example: https://github.com/PyO3/pyo3/tree/master/examples/word-count

**Comment by davidhewitt** [comment]
👍 both `maturin` and `setuptools-rust` can support these "mixed Python/Rust" projects.

**Comment by jafioti** [comment]
Thanks for pointing me to the right project! +1
