### ISSUE TITLE
PyBytes::new_with_uninitialised proposal

### ISSUE THREAD

**Issue by dvolodin7** [PyO3/pyo3#1499]
`PyBytes` offers `new_with` method, which creates `bytes` object of given size and populates it via `init` closure.
Before calling `init` the bytes' contents are zero-initialised.

Sometimes, `init` closure fills every byte of created structure and zero-initialisation adds nothing but additional
overhead.

I.e, consider following implementation:
```
    #[pyfn(m, "build_icmp_echo_request")]
    fn build_icmp_echo_request<'a>(
        py: Python<'a>,
        request_id: u16,
        seq: u16,
        payload: &'a [u8],
    ) -> PyResult<&'a PyBytes> {
        PyBytes::new_with(py, 8 + payload.len(), |buf: &mut [u8]| {
            // Type = 8, Code = 0, Checksum filler = 9
            BigEndian::write_u32(buf, 0x08000000);
            // Request id, 2 octets
            BigEndian::write_u16(&mut buf[4..], request_id);
            // Sequence, 2 octets
            BigEndian::write_u16(&mut buf[6..], seq);
            // Clone payload
            buf[8..].copy_from_slice(payload);
            // Calculate checksum
            // RFC-1071
            let cs = checksum(buf);
            buf[2] = cs[0];
            buf[3] = cs[1];
            Ok(())
        })
    }
```
we're sure that the data is fully initialised. As a result, naive pyo3 function is slightly slower than much more complex
Cython implementation:

| Impl | Payload | Time |
| --- | --- | --- |
| Cython | 64 | 331 ns ± 3.52 ns |
| Cython | 1000 | 759 ns ± 1.43 |
| Rust | 64 | 374 ns ± 1.2 ns |
| Rust | 1000 | 849 ns ± 7.08 |

The proposed solution is to provide additional `PyBytes::new_with_uninitialised` method
with straightforward implementation like:
```
    pub fn new_with_uninitialised<F>(py: Python, len: usize, init: F) -> PyResult<&PyBytes>
    where
        F: FnOnce(&mut [u8]) -> PyResult<()>,
    {
        unsafe {
            let pyptr = ffi::PyBytes_FromStringAndSize(std::ptr::null(), len as ffi::Py_ssize_t);
            // Check for an allocation error and return it
            let pypybytes: Py<PyBytes> = Py::from_owned_ptr_or_err(py, pyptr)?;
            let buffer = ffi::PyBytes_AsString(pyptr) as *mut u8;
            debug_assert!(!buffer.is_null());
            // Initialise the bytestring in init
            // If init returns an Err, pypybytearray will automatically deallocate the buffer
            init(std::slice::from_raw_parts_mut(buffer, len)).map(|_| pypybytes.into_ref(py))
        }
    }
```

**Comment by davidhewitt** [comment]
Unfortunately the api would have to be slightly more complicated than this. As far as I'm aware, reading from uninitialized memory must be `unsafe`, so we have to do something to ensure that this is the case.

The simplest change might be this:

```
        F: FnOnce(&mut [MaybeUninit<u8>]) -> PyResult<()>,
```

However that `MaybeUninit` slice won't be much fun to work with.

This discussion might be helpful reading: https://internals.rust-lang.org/t/uninitialized-memory/1652/25

The `ioslice` trait also has an interesting example: https://docs.rs/ioslice/0.5.1/ioslice/#a-read-like-trait-implemented-to-better-support-uninitialized-memory. How it works is it provides a type which doesn't enable reading until it's initialized.

When we added `new_with` we considered whether to initialize or not and concluded that the convenience of having a safe API outweighted the tiny performance overhead. In addition, if the user has to write `unsafe` code, why not just let them write the `new_with_uninitialised` implementation you suggest in their own code?

**Comment by davidhewitt** [comment]
There's been no discussion on here in some time, so I'm going to close this for now.
