### ISSUE TITLE
Inheritance support

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#15]
Allow to use custom base class

**Comment by fafhrd91** [comment]
base inheritance support has been added. but it is not possible to call ctor of base class.

```rust

#[py::class(base=asyncio.AbstractEventLoop)]
struct EventLoop {
    ...
}
```

**Comment by fafhrd91** [comment]
I think we need `super` method, which should return reference to base object. so constructor could look like this:

```rust
#[py::method]
impl MyClass {
     #[new]
     fn __new__(cls: &PyType, ...) -> PyResult<Py<MyClass>> {
         let slf = cls.py().init(|token| {
             MyClass {
                 num: 10,
                 debug: False,
                 token: token
             }
         })
        slf.super().call_method("__init__", NoArgs)
     }
}
```

**Comment by messense** [comment]
What about subclass support?

**Comment by fafhrd91** [comment]
That's easy. It is just extra tp_flags. I am not sure about consequences.

Do you want to test?

**Comment by messense** [comment]
I remember last time I tried to add that tp_flags it causes segfaults.

**Comment by fafhrd91** [comment]
try to add Py_TPFLAGS_BASETYPE
Post trace from segfault. It could be parameter for "py::class"

**Comment by fafhrd91** [comment]
main question right now how to call parent "__new__" method

**Comment by fafhrd91** [comment]
@messense could review this ed8599cfd3959b8ed08d86cf6a0615565be73d62
opinion?

**Comment by fafhrd91** [comment]
implemented
