### ISSUE TITLE
Coordinating near future work

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#151]
My wishlist and plan for pyo3 would be the following, mostly in that order:

 - [x] Merge #139
 - [x] Merge #150
 - [x] Merge #154
 - [ ] Run rustfmt (Diffstat: 159 files changed, 8330 insertions(+), 5913 deletions(-))
 - [x] Fix the scoping in the proc macros properly (i.e. `::pyo3` and `::std` everywhere), remove the unnecessary underscores and fix the unused imports.
 - [ ] Write further documentation
   - [x] Move rust-cpython comparison into the readme
   - [x] Write missing parts for the guide 
   - [ ] Write an explicit list of all supported types 
   - [ ] Write a list of supported `__methods__` and other supported python features.
 - [ ] Fix clippy errors

@fafhrd91 @althonos Any thoughts?

**Comment by konstin** [comment]
> I added you both to admin group, you should be able to make new crate.io releases

Great, thanks!

> sorry, I can not help. I am busy with other project at the moment.

No problem! actix-web is a really cool project :)

**Comment by althonos** [comment]
@konstin: I'll try to see if I come up with something sensible concerning the documentation, but I can't really help with proc macros otherwise. I'll try to review as well whenever needed, don't hesitate to request my reviews on a PR.

**Comment by fafhrd91** [comment]
we have to upgrade syn to 0.13 version. this is big task, but it prerequisite for stable procmacro and it will help significantly with errors

**Comment by konstin** [comment]
To clarify my initial post, those bullet points are the things I'm going to implement.

> we have to upgrade syn to 0.13 version. this is big task, but it prerequisite for stable procmacro and it will help significantly with errors

Just bumping the versions of syn and quote results in over 300 compilation errors. Doing that upgrade properly would mean rewriting most of the code generation. I'd love to have all the syn 0.13 features, but I have neither the time nor the motivation to do this huge rewrite.

**Comment by fafhrd91** [comment]
syn 0.13 upgrade is enevitable. Most annoying part of pyo3 is compiler error reporting. With syn 0.11 it is not possible to show proper errors
