### ISSUE TITLE
The examples in repo is not clear for new-hand and error-prone

### ISSUE THREAD

**Issue by poohRui** [PyO3/pyo3#1515]
I found the example under repo is unclear for new users. Using word-count for example,
```
python setup.py install
```
Only using this build command can not make this example runs successfully. Since the internal `word_count.cpython-38-x86_64-linux-gnu.so` can not be found by python interpreter which will lead to load module error:
```
ModuleNotFoundError: No module named 'word_count.word_count'
```
I think the readme can be written more clearly, in my opinion both copy the *.so file from `site-packages` and `python setup.py develop` will solve this problem.

I can pull request if it is necessary.

**Comment by davidhewitt** [comment]
Thanks, this is a known pain point; usually change directories to some other one after running `python setup.py install`.

The problem is not that the package isn't successfully installed, but that the local package in the folder will override the installed ones. I'm open to hearing suggestions for best practice to make this easier.

**Comment by poohRui** [comment]
Thanks for your response, I was confused about this problem for half a day since I am not quite familiar with features of Python. I even doubt there is something wrong with my code.

I think this problem can be solved by moving the python scripts folder to some other path or just changes the name of this folder. 

By the way, I think it will confuse the new hands like me, a more friendly user-guide readme under `example` folder will save a lot time.

**Comment by kngwyu** [comment]
> By the way, I think it will confuse the new hands like me, a more friendly user-guide readme under example folder will save a lot time.

Yeah, it would be nice, thanks.
It may be also good to use `maturin` instead of `setuptools-rust` in the word-count example. `maturin develop` is really convenient.
In addition, I think we should add a nicer complex. `rustapi-module` is mostly for testing some APIs and not very good as an example.

**Comment by poohRui** [comment]
> It may be also good to use maturin instead of setuptools-rust in the word-count example. maturin develop is really convenient.

I agree `maturin` is more convenient than `setuptools-rust`, but one thing is that `maturin develop` can only be used inside virtualenv. Since my develop environment is docker, I should config a redundant virtualenv just used for `maturin`, it is strange in my opinion. I am wondering why can't maturin be used without a virtualenv?

**Comment by davidhewitt** [comment]
We've changed the examples a lot since this issue was reported; I'm going to close as obsolete.
