### ISSUE TITLE
Taking in a PyAny argument to a class method

### ISSUE THREAD

**Issue by jafioti** [PyO3/pyo3#1524]
I am trying to write a method for a class that takes in a PyAny and returns a PyObject, but I am getting an error about implementing the trait "FromPyObject" not being staisfied. I've implemented it on my class, but I don't think it's about my class after all. Here is a picture of the error message:
![Screenshot from 2021-03-27 23-34-20](https://user-images.githubusercontent.com/13525371/112741597-3d65b580-8f55-11eb-802c-d44ca5c04451.png)

As you can see, I believe it is referring to something in the pymethods macro, rather than my class. The error occurs on the line where I put `#[pymethods]` Is this supported behavior?

**Comment by birkenfeld** [comment]
Please always provide the full code or a minimal example that shows your problem.  My guess is that you're taking `PyAny` as an argument and not `&PyAny`.

**Comment by jafioti** [comment]
@birkenfeld Sorry for no code, you were correct about using `PyAny` instead of `&PyAny`. Now it works, thanks!
