### ISSUE TITLE
Retaining and accessing global values in module

### ISSUE THREAD

**Issue by xd009642** [PyO3/pyo3#1526]
I was hoping to make an application where the user specifies a python script and then for every event in my application it calls one of the functions in the script. So I was kind of thinking of roughly the following state:

```python
x = 0 # Some variable they want to persist across the run

fn handle_event(data=None):
    x += 1

fn finish():
    return x
```

So that way they can keep track of state that lasts through the run via globals in the script and then process and return some sort of report at the end. However, it seems when I call a function in the module the globals aren't initialised, so I guess they also won't persist?

I tried something like this:

```rust
use pyo3::prelude::*;
use std::fs::read_to_string;

fn main() {
    let script = read_to_string("test.py").unwrap();
    Python::with_gil(move |py| -> PyResult<()> {
         let module = PyModule::from_code(py, &script, "my_module", "my_module")?;
         module.getattr("handle_event")?.call0()?;
         module.getattr("handle_event")?.call0()?;
    }).expect("It failed");
}
```

And it failed as "local variable x referenced before assignment". I'm just wondering if there's a way to do it how I was planning or if I should just bite the bullet and make the user create some Context class in python that gets passed in each time and returned

**Comment by davidhewitt** [comment]
I think your script has invalid python syntax - try this?

```

**Comment by davidhewitt** [comment]
(accidentally sent previous message before typing the script - have edited it to add it.)

**Comment by xd009642** [comment]
That worked thanks, I'll close this :+1:
