### ISSUE TITLE
Distribute a submodule only

### ISSUE THREAD

**Issue by milesgranger** [PyO3/pyo3#1535]
Hi!

Question :question: 
---

I develop a Python lib using PyO3 (and loving it!). It's distributed under MIT, and there is a feature I'd like to add but the dependency is GPL; by default, I would control not including it in the distribution wheel using feature flags. But then wanted to make it available as a separate wheel that could be installed as an additional submodule to the parent package. Is that at all possible you think?

**Comment by davidhewitt** [comment]
Hi @milesgranger, thanks for the question.

You won't be able to "install" the submodule into the parent package using a separate wheel. However there's a couple of tricks I can think of that could help you do this:

- You could name the library in the submodule wheel something like `_parent_module_submodule_impl.so`, and then in the parent module you could try to import this and re-export it with a nicer name (e.g. `parent_module.submodule`).
- You could make `parent_module.submodules` a namespace package, and then you can have as many separate projects as you like provide modules for that namespace package (as `parent_module.submodules.foo`, `parent_module.submodules.bar` etc.)

**Comment by milesgranger** [comment]
Good tips, thanks!

I sort of assume this would require using a more traditional `setup.py` process with some python wrappings to re-export the potentially non-existent submodule(s) then? Presently, I use a pure maturin build without any python wrappings; is there a way to try re-exporting a _maybe_ installed submodule in Rust?

**Comment by davidhewitt** [comment]
You could do something of the first kind in Rust code:

```rust
if let Ok(submodule) = PyModule::import(py, "_parent_module_submodule_impl") {
   m.add("submodule", submodule)?;
   // You might want to do this as well to make importing the submodule directly feel nicer in Python:
   let sys = PyModule::import(py, "sys")?;
   sys.getattr("modules")?.set_item("submodule", submodule)?;
}
```

(code unchecked; there could be compile errors lurking there but hopefully you take my meaning!)

**Comment by milesgranger** [comment]
ah of course, smart! Thanks for the tips, very much appreciated. :raised_hands:
