### ISSUE TITLE
Safer trait for PyBufferProtocol

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1536]
At the moment `PyBufferProtocol` requires users to initialize the raw `ffi::Py_Buffer` structure in a pointer.

This forces the user to write `unsafe` code. It would be nice to rewrite this protocol to offer something better.

Prompted by the below discussion:

----

In the future I would like to remove `Py_buffer::new()`, but I think to do so right now would be inconvenient for users because [`PyBufferProtocol`](https://docs.rs/pyo3/0.13.2/pyo3/class/buffer/trait.PyBufferProtocol.html) basically forces you to handle the raw ffi pointer (which probably points to uninitialized memory which C created).

I chose `MaybeUninit` here because that's pretty much identical to what C would do: we create a slab of memory and pass its location to `PyObject_GetBuffer` to initialize the contents.

_Originally posted by @davidhewitt in https://github.com/PyO3/pyo3/pull/1534#discussion_r605900560_

**Comment by kngwyu** [comment]
Nice, I also want to implement safe buffer trait for rust-numpy.

**Comment by davidhewitt** [comment]
This is now tracked in #1884 as part of the move to `#[pymethods]`
