### ISSUE TITLE
making __pyo3_get_function_ pub?

### ISSUE THREAD

**Issue by dovahcrow** [PyO3/pyo3#1541]
Currently, it seems that `wrap_pyfunction` will use the private function `__pyo3_get_function_foo` that `#[pyfunction]` generated along with the wrapped function `foo` in a same sub module. This forbids putting `#[pyfunction]`  in some rust submodules because `wrap_pyfunction` will not be able to access the private functions.

**Comment by davidhewitt** [comment]
Since #1280 (i.e. release `0.13.0`) they're `pub(crate)`, will this be sufficient for you? This is deliberately undocumented in the hope that one day we'll have a better solution which is easier to use.

**Comment by dovahcrow** [comment]
Thanks for the help! The reason I could not make it work previously was that I was using `pub use submodule::__pyo3_get_function_foo` to reexport the companion function. It should be `pub(crate) submodule::__pyo3_get_function_foo`.
