### ISSUE TITLE
Cannot return PyBytes / PyList?

### ISSUE THREAD

**Issue by vedantroy** [PyO3/pyo3#1549]
I have the following:

```rust
    pub fn apply_local_change(&mut self, change: &PyAny) -> PyResult<(Py<PyAny>, PyBytes)> {
       // function implementation ...
        let bytes = *PyBytes::new(py, change.raw_bytes());
        Ok((pythonize(py, &patch)?, bytes))
    }
```
However, I get an error saying "the trait `IntoPyCallbackOutput<_>` is not implemented for `Result<(pyo3::Py<PyAny>, PyBytes), PyErr>`". Is there any reason this trait would not be implemented for `PyBytes`?

I can solve the problem by returning a `Vec<u8>`, but that seems less Pythonic.

**Update**: This seems to apply for all `Py...` types, i.e, I can't return a `Pylist` either.

**Comment by ravenexp** [comment]
I think this is because you are trying to return a Rust tuple. Maybe you could try returning a [`PyTuple`](https://docs.rs/pyo3/0.13.2/pyo3/types/struct.PyTuple.html) object instead.

**Comment by davidhewitt** [comment]
Sorry for my slow response! The return type needs to be `PyResult<(Py<PyAny>, &PyBytes)>` or `PyResult<(Py<PyAny>, Py<PyBytes>)>`.

(Plain `PyBytes` isn't meaningful with PyO3 - it needs to be wrapped as a pointer either as `&PyBytes` or `Py<PyBytes>`. This is likely going to improve eventually with #1308.)

**Comment by davidhewitt** [comment]
Will close this as it's been a stale discussion and we'll be marking a lot of documentation changes in #3382
