### ISSUE TITLE
Module name truncated  in exported symbols if not defined in double quote

### ISSUE THREAD

**Issue by rohitjoshi** [PyO3/pyo3#156]
In https://pyo3.github.io/pyo3/guide/module.html, 

When module name is defined as  `#[pymodinit(mcmc)]`, it exports symbols as below where first and last characters are truncated and exports only `cm`

```
 nm mcmc.cpython-36m-darwin.so | grep Init
                 U _PyEval_InitThreads
0000000000001ae0 T _PyInit_cm
00000000000533f8 d __ZN4mcmc9PyInit_cm10MODULE_DEF17h9f2670baf9727f57E
```
and due to this, getting error

`
ImportError: dynamic module does not define module export function (PyInit_mcmc)
`

When I define as ``#[pymodinit("mcmc")]`, it correctly exports symbols.

```
nm mcmc.so | grep Init
                 U _PyEval_InitThreads
0000000000002eb0 T _PyInit_mcmc
000000000002b868 d __ZN4mcmc11PyInit_mcmc10MODULE_DEF17hb68a6e48c8b777b2E
```

**Comment by konstin** [comment]
Oh, I just realised that this is actually about a change in nightly and I already fixed that in https://github.com/PyO3/pyo3/commit/d0c42dfcc1623e0279573511d9fdcb0601cf4a09#diff-93f14f429ed8ab10db22a29c55d99179R400. It will be part of the next release.

**Comment by rohitjoshi** [comment]
Thanks
