### ISSUE TITLE
Pyfunctions which use a non-static reference inside it

### ISSUE THREAD

**Issue by qt2** [PyO3/pyo3#1580]
I'm considering integrating PyO3 into Amethyst, which is the most popular Rust game engine.

However, I have a problem on its implementation, because the reference that needs to be called from a pyfunction is not static but I have no idea to achieve that.

Is there a good way to make a pyfunction which uses a non-static reference inside it?

Example code is as follows:

```rust
#[pyfunction]
fn create(world: &mut World) -> u32 {
    world.create_entity().build().id()
}

#[derive(Default)]
pub struct Game {
    pub gil: Option<GILGuard>,
}

impl Game {
    pub fn new() -> Game {
        let gil = Python::acquire_gil();
        Game { gil: Some(gil) }
    }
}

impl SimpleState for Game {
    // This method is called 60 times per a second.
    fn fixed_update(&mut self, data: StateData<'_, GameData<'_, '_>>) -> SimpleTrans {
        let world = data.world; // This reference does not have 'static lifetime.
        let py = self.gil.as_ref().unwrap().python();
        let create = wrap_pyfunction!(create)(py).unwrap();
        let locals = [("create", create)].into_py_dict(py);
        // I'd like to attach the reference like this: (But this code fails of course)
        py.run("print(create())", None, locals, world).unwrap();
    }
}
```

**Comment by davidhewitt** [comment]
Can you elaborate more on what the `World` type is in your example?

If you want to call the `create` pyfunction, you should do it like this:

```
let id = create.call1((world,))?;
```

The above would work if `world` was a `#[pyclass]`, wrapped up as `Py<World>`.

**Comment by qt2** [comment]
@davidhewitt Thank you for your reply.

Struct `World` is defined in amethyst as [amethyst::prelude::World][world], which is not a `#[pyclass]`.

Additionally, since I plan to run a code from a certain file, unfortunately I would not be able to call `.call1()` either.

What I'd like to achive is something like the following code, but I'm not sure this implmentation is possible:

```python
# script.py
entity = Enemy::new()
entity.operate()
```

```rust
use std::fs;
use amethyst::{
    prelude::World,
    ecs::Entity,
},

#[pyclass]
struct Enemy {
    entity: Entity
}

#[pymethods]
impl Enemy {
    #[new]
    fn new() -> Self {
        let entity = world.create_entity().build();
        Enemy { entity }
    }

    fn operate(&mut self)  {
        if let Some(entry) = world.entry(self.entity) {
            let mut component = entry.get_component_mut::<SomeComponent>().unwrap();
            component.do_something();
        }
    }
}

pub struct Game {
    pub gil: GILGuard,
    pub code: String,
}

impl Game {
    pub fn new() -> Game {
        let gil = Python::acquire_gil();
        let code = fs::read_to_string("script.py").unwrap();
        Game { gil, code }
    }
}

impl SimpleState for Game {
    fn fixed_update(&mut self, data: StateData<'_, GameData<'_, '_>>) -> SimpleTrans {
        let world = data.world; // This reference does not have 'static lifetime.
        let py = self.gil.as_ref().unwrap().python();
        // py.run(&self.code, None, locals).unwrap();
    }
}
```


[world]:https://book.amethyst.rs/api/stable/amethyst/prelude/struct.world

**Comment by davidhewitt** [comment]
Right, I understand what you're asking now.

Ok, so this can't be done "trivially" using Rust's compile-time lifetimes. Python isn't aware of lifetimes, so we can't just hand that `World` reference over to Python.

You could consider looking at solutions such as [`scoped_tls`](https://docs.rs/scoped-tls/) which could allow you to safely place the `World` reference into some static location so that you don't have to expose to to Python.

**Comment by qt2** [comment]
Thanks for giving me advice.
I've never heard about such a crate so your suggestion was really helpful.
I'll try to use `scoped_tls` along with PyO3 in my project.

Thank you so much!
