### ISSUE TITLE
How can I include pyfunctions/pyclasses in `__main__`? 

### ISSUE THREAD

**Issue by qt2** [PyO3/pyo3#1586]
How can I include pyfunctions/pyclasses in `__main__`? 

I read [a related issue](https://github.com/PyO3/pyo3/issues/567) and tried to call `import("__main__").dict().copy().unwrap()` and then `.set_item()`, but it was impossible since I need to call scripts multiple times in a different scope, while `&Pydict` does not have `'static` lifetime.
Reference codes are as follows:

I'm sorry to make quite a few questions in a short period.

```python
# script.py
c = 0

def a():
    print(one())
    c += 1
```

```rust
use std::fs;

#[pyfunction]
fn one() -> f32 {
    1.
}

pub struct Game {
    pub gil: GILGuard,
}

impl Game {
    pub fn new() -> Game {
        let gil = Python::acquire_gil();        
        Game { gil }
    }
}

impl SimpleState for Game {
    fn on_start(&mut self, data: StateData<'_, GameData<'_, '_>>) {
        let py = self.gil.python();
        let code = fs::read_to_string("script.py").unwrap();
        let locals = [("one", wrap_pyfunction!(one))].into_py_dict(py)
        py.run(&code, None, Some(locals)).unwrap();
    }

    fn fixed_update(&mut self, data: StateData<'_, GameData<'_, '_>>) -> SimpleTrans {
        let py = self.gil.python();
        let locals = [("one", wrap_pyfunction!(one))].into_py_dict(py)
        py.run("a()", None, Some(locals)).unwrap();
        // => NameError("name 'one' is not defined")
    }
}
```

**Comment by davidhewitt** [comment]
You can store `Py<PyDict>` as a static object. It's `&PyDict` but disconnected from the GIL, so you must prove you have the GIL to use it.

**Comment by qt2** [comment]
Oh, that's completely what I was looking for.
I greatly appreciate your help.
Thanks so much!
