### ISSUE TITLE
Proposal: use a `docsrs`  rustdocs flag

### ISSUE THREAD

**Issue by mejrs** [PyO3/pyo3#1587]
This is inspired by an user that had difficulty finding out about one of the optional features (num-bigint) the other day. Tokio, for example, [communicates these things very well](https://docs.rs/tokio/1.5.0/tokio/#modules), and I think we should too. This is how they do it:

Doc features like [doc_cfg](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html) and [doc_alias](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html#adding-search-aliases) can be gated behind this flag, so these only affect anything when rendering documentation. 

These features allow for some really useful things:

- Add redirects for search terms that don't appear in the documentation on their own:

![afbeelding](https://user-images.githubusercontent.com/59372212/116694466-9e9eff80-a9bf-11eb-9d04-1fe00ee7c5d8.png)

- Clearly show when things are not available on certain platforms:

![afbeelding](https://user-images.githubusercontent.com/59372212/116694799-03f2f080-a9c0-11eb-924d-db11735d7591.png)
![afbeelding](https://user-images.githubusercontent.com/59372212/116696381-1ff79180-a9c2-11eb-8f59-bf92a841eaeb.png)

- Clearly show when something is gated behind an optional feature:

![afbeelding](https://user-images.githubusercontent.com/59372212/116696111-c1caae80-a9c1-11eb-8887-5bb5dfa25267.png)

There are also some things that need to be done that I'm not 100% sure about how to do:

- Figure out the optimal set of features to compile the documentation with (`--all-features` won't work) .

- Add metadata for rustdoc to `cargo.toml`, probably something like this:
```
[package.metadata.docs.rs]
all-features = false
features = ["macros","num-bigint","num-complex","hashbrown","serde","nightly"]
rustdoc-args = ["--cfg", "docsrs"]
```

- Change the CI to do something like this:
```
$env:RUSTDOCFLAGS="--cfg docsrs"

cargo +nightly doc --no-deps --features=macros,num-bigint,num-complex,hashbrown,serde,nightly
```

Otherwise, the scope of the changes looks like this: https://github.com/mejrs/pyo3/commit/22958bdc5ae9cf22386fbdac2a5d73d11d18cc30 . It would also require putting these attributes everywhere relevant.

**Comment by davidhewitt** [comment]
Having seen this on other crates' documentation, I definitely support this. It's so useful to have this kind of information to hand, especially for new users. I've considered exploring this myself but never found time to take a look at it, so thank you for doing so!

> Figure out the optimal set of features to compile the documentation with (--all-features won't work) .

In our CI (`ci.yml`) we can have a notion of "all additive features" - we probably want to use the same set here.

> Change the CI to do something like this:

I would suggest adding a new job similar to `coverage` which uses nightly to build the docs on the latest ubuntu. (We already build the "stable" docs on each tested platform, so we'd just need a new CI job to test the new additions.)
