### ISSUE TITLE
Request: Getter/Setter support for struct/unit tuples

### ISSUE THREAD

**Issue by ruffson** [PyO3/pyo3#1593]
So after [this](https://github.com/PyO3/pyo3/pull/1504) PR implemented support for unit/tuple structs in `pyclass` it would be awesome if getter/setters could be supported as suggested [here](https://github.com/PyO3/pyo3/pull/1504#discussion_r597162765).

As far as I understand, the support for `name`s with getters/setters is already merged [here](https://github.com/PyO3/pyo3/pull/1507).

**Comment by davidhewitt** [comment]
Indeed it's on the plan👍. I plan to merge #1567 and then work on this.

Let's keep this issue open to track the work.

**Comment by ruffson** [comment]
Awesome, thank you!
