### ISSUE TITLE
ToPyObject and IntoPy<PyObject> boilerplates

### ISSUE THREAD

**Issue by pickfire** [PyO3/pyo3#1595]
While working on chrono pyo3 integration, I noticed I am typing out `IntoPy` referencing `ToPyObject` quite often.

```rust
    impl ToPyObject for NaiveDate {
        fn to_object(&self, py: pyo3::Python) -> pyo3::PyObject {
            let mdf = self.mdf();
            let date = PyDate::new(py, self.year(), mdf.month() as u8, mdf.day() as u8)
                .expect("Failed to construct date");
            date.into()
        }
    }

    impl IntoPy<pyo3::PyObject> for NaiveDate {
        fn into_py(self, py: pyo3::Python) -> pyo3::PyObject {
            ToPyObject::to_object(&self, py)
        }
    }
```

If we have implemented `IntoPy<pyo3::PyObject>` is there a reason why one still wants to implement `ToPyObject` when it could exactly be the same thing? So most of the time I just reference the same thing. I know in some cases where there could be like specialization mechanism when `self` in involved but at least from what I did, all of the are the same (since I couldn't think it could be better done when it is using `self`).

Is there any reason why we don't do something like trait default function (like `Iterator`) so without typing the `ToPyObject` it will automatically gets created unless user wants a specialized version? Or is there some cases where we can only have like `IntoPy<PyObject>` but not `ToPyObject` so we can't automatically create the function for it?

**Comment by davidhewitt** [comment]
Closing now we have #4495
