### ISSUE TITLE
Generate getter/setter for fields

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#16]
Add proc attr that automatically creates getter and setter for struct field

```rust

#[py::class]
struct cls {
    #[prop(setter, getter)]
    num: i32
}
```

**Comment by fafhrd91** [comment]
@messense want to do this too?

**Comment by messense** [comment]
I am not sure about this one. I don't know much about `syn`, might need to take some time learning the basics. Debugging isn't easy either.

**Comment by fafhrd91** [comment]
You can always use println! Also `cargo expand` shows expanded macros.

**Comment by messense** [comment]
I'll give it a try.

**Comment by messense** [comment]
https://github.com/messense/PyO3/commit/b10089d9abaf3fca905040fc2303f400267db1d9
ods
Progress so far. Not sure how to add impls, it's not like `#[methods]` that already have impl blocks.

**Comment by fafhrd91** [comment]
you can access attributes of struct, so just generate `wrap` method and directly access attributes.
also you can create multiple `impl` blocks

**Comment by messense** [comment]
I need `syn::Ty` of the struct but I only have `syn::Ident`, not sure how to get `syn::Ty` for the struct from `syn::DeriveInput`

https://dtolnay.github.io/syn/syn/struct.DeriveInput.html

**Comment by fafhrd91** [comment]
is this what you need?
https://github.com/PyO3/pyo3/blob/master/pyo3cls/src/py_class.rs#L17
https://github.com/PyO3/pyo3/blob/master/pyo3cls/src/py_class.rs#L222

**Comment by messense** [comment]
I don't think so, that gives me `syn::Ty` of the struct field while I need `syn::Ty` of the struct itself to pass to `impl_wrap_getter`/`impl_wrap_setter`

**Comment by fafhrd91** [comment]
but all you need is name of the struct, it is type.

**Comment by fafhrd91** [comment]
example https://github.com/PyO3/pyo3/blob/master/pyo3cls/src/py_method.rs#L60

**Comment by messense** [comment]
I tried but there are a lot of subtle details that I am not aware of. I doubt I can finish this recently so if you want to implement it yourself it's ok.

**Comment by fafhrd91** [comment]
It is fine, it is not priority
