### ISSUE TITLE
How to pass and use an async python function as an argument in Rust?

### ISSUE THREAD

**Issue by sansyrox** [PyO3/pyo3#1631]
##  Question

When we write vanilla rust and we have to pass in an async function as an argument to another function we do the following:

```
pub f<F,'a>(
    test: &dyn Fn(&'a mut String, String, String, TcpStream) -> F,
) where
    F: Future<Output = ()> + 'a,
```

But when I do the same on a `#![pyfunction]` expecting to get an async **python** function, I am getting an error.
```
e.g async def fn():
            ....
```

How can I implement this in my code. I would understand if this is not possible , if that is the case, I would request you to please recommend me an alternative.

Thanks in advance. 😄

**Comment by sansyrox** [comment]
This question has been answered here: https://stackoverflow.com/questions/67686409/how-to-pass-an-async-function-as-a-parameter-in-rust-pyo3

Hence, closing it.

**Comment by Eric-Arellano** [comment]
Perhaps it would make sense to add this to PyO3's book, if not yet there? More discoverable than StackOverflow.

**Comment by davidhewitt** [comment]
An addition to the async-await chapter would be very welcome. I suggest adding it as a new section - maybe called "Calling async Python functions from Rust" ?

**Comment by sansyrox** [comment]
@davidhewitt , that sounds great. I will try to open a PR by this weekend. 😄
