### ISSUE TITLE
Automated continuous benchmarking

### ISSUE THREAD

**Issue by messense** [PyO3/pyo3#1634]
https://github.com/marketplace/actions/continuous-benchmark

Tokio has an example workflow: https://github.com/tokio-rs/tokio/blob/master/.github/workflows/bench.yml and tracking benchmark result with GH Pages: https://tokio-rs.github.io/tokio/dev/bench/

I can send a PR if this is desirable.

**Comment by davidhewitt** [comment]
Personally I would love to see this! I was actually talking a look at that exact action the other day!
