### ISSUE TITLE
How to store PyAny in hashmap?

### ISSUE THREAD

**Issue by sansyrox** [PyO3/pyo3#1646]
## 🐛 Question

I am trying to create a router that has a route and PyAny as the KV pair in a hashmap.

(PyAny is an async function that is being passed from python to Rust and I want to push it to a threadpool, hence I am not using &PyAny or futures in the initial stage.)

I have two questions for the same: 
1. How to convert the PyAny object to Py<PyAny>
I read on one of the issues in this repo only that I need to store the PyAny object as Py<PyAny>

This is how the hashmap is looking like 

```
        let get_routes: HashMap<Route, Py<PyAny>> = HashMap::new();

```

and this is how I am appending to the hashmap

```
    pub fn add_route(&mut self, route: String, handler: PyAny) {
// how do I convert this to Py<PyAny>
        self.get_routes
            .insert(Route::new(RouteType::Route(route)), handler);
    }
```

2.  When I am implementing the `#[pymethods]` trait on my implementation, it is giving me this error:

```
[rustc E0277] [E] the trait bound `pyo3::PyAny: pyo3::FromPyObject<'_>` is not satisfied

expected an implementor of trait `pyo3::FromPyObject<'_>`

note: required because of the requirements on the impl of `pyo3::FromPyObject<'_>` for `pyo3::PyAny`
```

What does the above error mean and how can I fix it?

This is how the impl looks like at the moment:

```
#[pymethods]
impl Server {
    // pub fn new(port: usize, number_of_threads: usize) -> Self {
    #[new]
    pub fn new() -> Self {
        let url = format!("127.0.0.1:{}", 5000);
        let get_routes: HashMap<Route, Py<PyAny>> = HashMap::new();
        Self {
            port: 5000,
            number_of_threads: 1,
            router: Router::new(),
            threadpool: ThreadPool::new(1),
            listener: TcpListener::bind(url).unwrap(),
            get_routes, // not implemented in router as unable to match lifetimes
        }
    }
```

Thanks in advance 😄

**Comment by birkenfeld** [comment]
You need to take the argument as `Py<PyAny>` or `&PyAny`.  In the latter case you have to convert it into a new `Py` reference with `handler.into()`.

**Comment by birkenfeld** [comment]
> What does the above error mean and how can I fix it?

This error is an indication the the type (`pyo3::PyAny` as given in the first line of the error message) is not supported by PyO3 as a function/method argument.

In this case, it is because `PyAny` is not a useful type: it needs to be behind a GIL reference (`&'py PyAny`) or in a GIL-independent container (`Py<PyAny>`).

**Comment by sansyrox** [comment]
Hi @birkenfeld . Thank you for the answer.
> n the latter case you have to convert it into a new Py reference with handler.into()

How do I do that? Should I use the following syntax ` let f = handler.into(Py<PyAny>);`?

**Comment by birkenfeld** [comment]
`into()` does not take arguments; the type to convert to is a type parameter.

Normally just
```
let f = handler.into();
```
will suffice, if type inference can identify what you want to get out.  Otherwise you can use
```
let f: Py<PyAny> = handler.into();
```

But in the case of `add_route` above, you should write it like this:
```
    pub fn add_route(&mut self, route: String, handler: Py<PyAny>) {
        self.get_routes
            .insert(Route::new(RouteType::Route(route)), handler);
    }
```

**Comment by sansyrox** [comment]
Hi @birkenfeld ,

Thank you for the help! Can you please also tell me how can I convert `Py<PyAny>` back to `&PyAny`.

If possible can you point me to the documentation so that I don't nag you everytime 😅 

I found some documentation here: https://pyo3.rs/v0.13.2/types.html?highlight=Py#pyt-and-pyobject , but I am unable to figure it out from here.

Thank you again!

**Comment by birkenfeld** [comment]
`as_ref(py)` should do it.

**Comment by sansyrox** [comment]
@birkenfeld, how do I get the `py` object (which I need to pass as a param) ?

**Comment by birkenfeld** [comment]
I think we'd better continue this in https://gitter.im/PyO3/Lobby - issues are not the ideal way for this kind of help.
