### ISSUE TITLE
Split master and release guide

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#165]
The guide publlshed under https://pyo3.github.io/pyo3/guide/ is the guide for master, while the users need the docs for the version released on crates.io.

This can be solved by publishing a separate guide through an extra deploy block in the travis ci config. The block could either work on a yet-to-create stable branch or publish a guide for every tag.

**Comment by fafhrd91** [comment]
All crates docs are available through docs.rs

**Comment by fafhrd91** [comment]
https://docs.rs/crate/pyo3/0.2.7

**Comment by fafhrd91** [comment]
Oh, it is about guide

**Comment by konstin** [comment]
I actually meant the guide; Someone on gitter was confused about the guide containing features that were not available. I've changed the title to make that more clear

**Comment by fafhrd91** [comment]
In actix, we moved guide to separate repo. Then you create branches for specific version. And master always points to latest stable

**Comment by fafhrd91** [comment]
Btw I have pyo3.rs domain, I can point it to github

**Comment by fafhrd91** [comment]
I enabled pyo3 domain, https://pyo3.rs/guide/

**Comment by konstin** [comment]
I've implemented versioned guide now: https://pyo3.rs always points to the latest stable version (i.e. the latest git tag starting with v), while https://pyo3.rs/master has the guide for the master. I've updated the readme accordingly.
