### ISSUE TITLE
_PyFrameEvalFunction has different definitions in Python 3.8 and Python 3.9

### ISSUE THREAD

**Issue by itamarst** [PyO3/pyo3#1675]
### 🌍 Environment

This `pyo3` 0.13.2.

### 💥 Reproducing

Per [The docs](https://docs.rs/pyo3/0.13.2/pyo3/ffi/type._PyFrameEvalFunction.html), `_PyFrameEvalFunction` is `extern "C" fn(_: *mut PyFrameObject, _: c_int) -> *mut PyObject;` This is in fact the case in Python 3.8; however, it's worth noting that this is private in Python 3.8.

In Python 3.9 this was made public, alongside some related APIs for PEP 523 that aren't in PyO3's FFI (e.g. https://docs.python.org/3/c-api/init.html#c._PyInterpreterState_SetEvalFrameFunc).

However, the signature in Python 3.9 has changed, it's now `PyObject* (*_PyFrameEvalFunction)(PyThreadState *tstate, PyFrameObject *frame, int throwflag)`.

### Bigger picture

As someone currently munging the internals of Python 3 for profiling purposes, I want to use the private API on Python 3.8, and the public API on Python 3.9. The current way `pyo3::ffi` works in pyo3 makes this difficult insofar as it's exposing types that change over time across Python releases, so I'm going to have to make my own types... it would be handy if PyO3 had some way for me to detect at compile time which Python API version was available.

Alternatively, perhaps PyO3 should have different versions of the low-level `pyo3::ffi` module depending which version of Python you're building against? Which I imagine would be some work.

### Smaller picture

On Python 3.9 or later `pyo3::ffi::_PyFrameEvalFunction` definition is wrong, and given that it's private before that, probably the newer signature should be there if there's only going to be one `pyo3:ffi` module variant for all Python versions.

### Final thoughts

This is an obscure API for a rare use case. However, the bigger picture issue of `pyo3:ffi` not matching the Python API version that code is compiling against is perhaps more significant.

**Comment by itamarst** [comment]
Ah, I found the `cfg()` options for Python API versions: https://github.com/PyO3/pyo3/blob/97d6f15b32c3090498911b8bff2edcef496bf228/pyo3-build-config/src/impl_.rs#L72

**Comment by mejrs** [comment]
Thanks for the bug report :)

> Ah, I found the cfg() options for Python API versions: 

Glad you found it :) @davidhewitt made `pyo3-build-config` for (the upcoming) pyo3 0.14, so you probably a need git dependency for now to make it work (?).

> Alternatively, perhaps PyO3 should have different versions of the low-level pyo3::ffi module depending which version of Python you're building against?

We can do that quite easily with cfgs:

```rust
pub type _PyFrameEvalFunction = extern "C" fn(#[cfg(Py_3_9)] *mut PyThreadState, *mut PyFrameObject, c_int) -> *mut PyObject;
```
This would also force authors (such as yourself) to use the `pyo3-build-config` crate to correctly call it across different Python versions.

Would that fit your use case?

**Comment by itamarst** [comment]
(In my specific case, playing around with direct interaction with hooking `eval_frame` didn't seem to work in 3.8, so I haven't actually tried the cfg() options. Once I get 3.9 working I might try, or not, we'll see.)

There's two cases, I think: this particular issue is an API that changed between 3.8 and 3.9. However, in 3.8 it is a private API. In practice Python C API tries to be backwards compatible, so this should only happen for private APIs and probably PyO3 doesn't want to think about it.

So probably the thing to do is just omit (and any other private APIs that slipped through). People like me who maybe want access to private APIs can just define the FFI structs/fns manually, it's a rare use case.

The other case is much more common: Python 3.9 added a whole bunch of new public APIs. This can be handled two ways:

* If you just generate FFI from latest current release (which I expect is the current practice?) then someone who uses a Python 3.9 API and builds a Python extension 3.6 will only get an error when they actually run that code. If they have tests, and are therefore building an executable, they will probably get the error at link time?
* You can alternatively use `#cfg(Py_3_9)]` on APIs that are Python 3.9 only. Ideally the generated `pyo3:ffi` docs would also have comment saying "Added in 3.9". In this case attempting to use such an API from Python 3.6 build will result in compile-time error.

**Comment by mejrs** [comment]
Only defining it for Py_3_9 is probably the way to go, having a footgun for python 3.8 users probably isn't worth it.

> use #cfg(Py_3_9)] on APIs that are Python 3.9 only

That is pretty much the case already; there's also a ton of limited_api/pypy cfg'ing going on.

>  Ideally the generated pyo3:ffi docs would also have comment saying "Added in 3.9"

We do that already (on the main branch) - except for in the ffi module. I'll look into adding that there as well.

**Comment by itamarst** [comment]
Sounds good, thank you!

**Comment by itamarst** [comment]
@messense thank you!
