### ISSUE TITLE
allocation limit with 32 bit python (when I'm using threads)

### ISSUE THREAD

**Issue by 20iahazban** [PyO3/pyo3#1680]
When I try to allocate a big Vec for example 653206806 bytes my app terminates with the following error:
  memory allocation of 653206806 bytes failed

My minimal working example just simply crash.
This is only happening with the 32 bit version. As i know a default 32-bit process gets 2GB memory, and im only want to allocate 0.6 GB.
Maybe this is expected and not a bug but in this case i would appreciate some help because i need to support 32 bit python :(

### 🌍 Environment

 - Your operating system and version:
    OS Name:                   Microsoft Windows 10 Enterprise
    OS Version:                10.0.18363 N/A Build 18363
 - Your python version:
      Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:
    windows installer
 - Your Rust version (`rustc --version`):
    rustc 1.52.1 stable-i686-pc-windows-msvc
 - Your PyO3 version:
    [dependencies.pyo3]
     version = "0.13.2"
     features = ["extension-module"]
 - Have you tried using latest PyO3 main (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`:
    no

### 💥 Reproducing

minimal working example:

lib.rs:
          use pyo3::prelude::*;
          use pyo3::wrap_pyfunction;
          
          #[pyfunction]
          fn proba(size: usize) -> Vec<u8> {
              let mut result: Vec<u8> = Vec::with_capacity(size);
              for _ in 0..size {
                  result.push(0);
              }
              result
          }
          
          #[pymodule]
          fn py_wrapper(py: Python, m: &PyModule) -> PyResult<()> {
              m.add_wrapped(wrap_pyfunction!(proba))?;
              Ok(())
          }

python file:
      import py_wrapper

      size_to_alloc = 400000000 
      d = py_wrapper.proba(size_to_alloc)
      print(d[23])

**Comment by mejrs** [comment]
Be aware that when you hand out a Vec to Python code it is converted into a python list, which takes up a lot more memory than a Vec.. - in your example that is about 3 GB, around 10 times more than that Vec.

In your case you could convert it to a `&PyBytes`, [rust-numpy's `PyArray`](https://pyo3.github.io/rust-numpy/numpy/array/struct.PyArray.html) or just not hand it over to Python code and instead wrap it in a pyclass and implement container-like methods on that.

**Comment by 20iahazban** [comment]
Thank you for the reply.
yes that's true and i have to use a more efficient data structure  on python side.
But i get an error on rust side first:
memory allocation of 653206806 bytes failed

when i do this:
let mut result: Vec<u8> = Vec::with_capacity(653206806);

which is around 600 MB and at this time the app only use 3 MB.

**Comment by mejrs** [comment]
Can you post the full error message/backtrace?

**Comment by 20iahazban** [comment]
could you tell me please how can i get a full backtrace?
im using the debug build with environment variable :
![image](https://user-images.githubusercontent.com/30409619/122194319-9f1f2700-ce95-11eb-9fda-19081fe86755.png)
but im only getting the : "memory allocation of 653206806 bytes failed" error

**Comment by mejrs** [comment]
Uhh

> in a simple 32 bit rust program i do not get this error.

Can you post this program? I'm thinking your rust only program might not actually allocate this memory.

**Comment by davidhewitt** [comment]
(If the same allocation failure can be reproduced in a Rust-only program without PyO3, this might be worth putting on https://users.rust-lang.org/ where there's a lot of people with wide knowledge on Rust-specific stuff like this.)

**Comment by 20iahazban** [comment]
currently I'm trying to create an example (as clean as possible) which reproduce this...maybe you are right and its not pyo3 related.

**Comment by 20iahazban** [comment]
The rust only version is working fine.
this is the minimal pyo3 example where i can reproduce the failure: https://github.com/20iahazban/pyo3_bigvec
thank you guys very much if anybody can help or give feedback what I'm doing wrong.

**Comment by mejrs** [comment]
I'm not sure this is something I can figure out - I don't have a 32bit system. It works fine with a 32 bit Python version, up to the point where it attempts to convert the Vec.

Here are some things you could try:

1) Do you still crash if you stall the program before converting the Vec? like:
```rust
#[pyfunction]
fn proba(py: Python, size: usize) -> Vec<Vec<u8>> {
    let (results_tx, results_rx) = unbounded();
    let results = py.allow_threads(move || {
        let children = runworkers(size, results_tx);
        for child in children {
            let _ = child.join();
        }

        let results: Vec<Vec<u8>> = results_rx.iter().collect();

        results
    });

    loop {
        py.check_signals().unwrap();
    }
}
```

2) Turn on nightly and use `try_reserve` (with `#![feature(try_reserve)]` ) instead of using `with_capacity`: this should at least print a stack trace:

```rust
let mut v: Vec<u8> = Vec::new();
v.try_reserve(size).unwrap();
```
3. Post this on users.rust-lang.org,  this might just be a win32 oddity.

**Comment by davidhewitt** [comment]
This hasn't had any discussion in a year and a half, so I'm going to close this thread. Please ping if there's further questions to discuss here.
