### ISSUE TITLE
PyFunction::call does not give error when not called correctly

### ISSUE THREAD

**Issue by NOBLES5E** [PyO3/pyo3#1681]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Linux 5.12.10-arch1-1
 - Your python version: 3.9.5
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: pacman, no
 - Your Rust version (`rustc --version`): rustc 1.54.0-nightly
 - Your PyO3 version: 0.13.2
 - Have you tried using latest PyO3 main (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: yes

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the Rust code and the Python.

Please also write what exact flags are required to reproduce your results.

Rust

```rust
#[pyfunction]
fn test(test_func: &PyFunction) -> PyResult<&PyAny> {
    test_func.call((), None)
}

#[pymodule]
fn pyo3_closure_exp(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(test, m)?)?;
    Ok(())
}
```

Python
```py
import pyo3_closure_exp
pyo3_closure_exp.test(lambda: should_throw_error_since_i_am_not_defined)
```

The python code does not give any error and I do not know how to discover the function does not run correctly.

**Comment by birkenfeld** [comment]
I cannot reproduce this. I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
NameError: name 'should_throw_error_since_i_am_not_defined' is not defined
```
Please make sure that what you're not swallowing the traceback printout somehow.

**Comment by birkenfeld** [comment]
BTW, you should not take `PyFunction` as an argument; it will needlessly exclude other callable objects.

**Comment by NOBLES5E** [comment]
> I cannot reproduce this. I get
> 
> ```
> >>> import pyo3_closure_exp
> >>> pyo3_closure_exp.test(lambda: should_throw_error_since_i_am_not_defined)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<stdin>", line 1, in <lambda>
> NameError: name 'should_throw_error_since_i_am_not_defined' is not defined
> ```
> 
> Please make sure that you're not swallowing the traceback printout somehow.

Thanks！ I do not see anything in my current code that could swallow the traceback. Could you share your Python version so that I can also check my Python environment?

**Comment by NOBLES5E** [comment]
Just tried to reproduce in a fresh installed miniconda environment and I cannot reproduce either.. Maybe there are some misconfigurations previously on my side. Sorry for bothering. Thanks!
