### ISSUE TITLE
Move `wrap_pyfunction` into prelude?

### ISSUE THREAD

**Issue by Eric-Arellano** [PyO3/pyo3#1691]
Hello! We're using `wrap_pyfunction` a lot in pantsbuild/pants, and found we prefer `#[pyfunction]` over `#[pyfn]` to keep our `#[pymodule]` block clean. (I'm submitting a docs PR on other things we've found to help.)

I'm wondering if it makes sense to move the macro into the prelude, given how common this type seems to be, for fewer imports? Maybe the `create_exception` macro too?

I'm happy to implement if you think so!

**Comment by davidhewitt** [comment]
I would definitely support `wrap_pyfunction` being in the prelude. It's very commonly used.

I would prefer not to add `create_exception` for now, only because we plan to eventually replace it (#295).
