### ISSUE TITLE
Link to pyo3.rs/main from pyo3.rs/master?

### ISSUE THREAD

**Issue by nw0** [PyO3/pyo3#1704]
We've renamed in #1130, but today I was reading the guide and accidentally used an old link to https://pyo3.rs/master rather than the up-to-date https://pyo3.rs/main. Perhaps we could add a prominent banner on the old `master` docs linking to the new ones, or even remove the old docs altogether?

**Comment by davidhewitt** [comment]
Thanks for reporting. I think I can use a symlink to make the link transparent...

**Comment by davidhewitt** [comment]
The docs on https://pyo3.rs/master now show the same content as https://pyo3.rs/main. Thanks again for the heads up.
