### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by cjrzs** [PyO3/pyo3#1705]
## 🐛 Bug Reports

Error: ImportError: DLL load failed: %1 is not a valid Win32 application

### 🌍 Environment

 - Your operating system and version: win10
 - Your python version: 3.8
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: miniconda 4.9.2
 - Your Rust version (`rustc --version`): rustc 1.52.1 (9bc8c42bb 2021-05-09)
 - Your PyO3 version: 0.13.2
 - Have you tried using latest PyO3 main (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`:

### 💥 Reproducing

I packaged it as a my_rust.pyd file used `maturin develop`。I had this problem when I introduced my_rust

**lib.rs**
```
use pyo3::prelude::*;
use pyo3::wrap_pyfunction;

#[pyfunction]
fn add(x: f64, y: f64) -> f64 {
    return x+y
}

#[pyfunction]
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

#[pymodule]
fn my_rust(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(add, m)?)?;
    m.add_function(wrap_pyfunction!(sum_as_string, m)?)?;
    Ok(())
}
```

**Cargo.toml**
```
[package]
name = "myrust"
version = "0.1.0"
authors = ["cjrzs <wawy826442063@163.com>"]
edition = "2018"

[dependencies]

[lib]
name = "my_rust"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
```

**test.py**

```
from my_rust import add, sum_as_string

print("add value :", add(1, 2))
print("sum_as_string: ", sum_as_string(5, 6))
print("hello world")
```

**Comment by davidhewitt** [comment]
This sounds like environment setup error. You've probably built a 64-bit DLL with a 32-bit Python (or vice-versa)?

**Comment by davidhewitt** [comment]
It's been nearly 3 months with no further response, so I'm going to close this. Please open a new issue if this is still a problem.
