### ISSUE TITLE
macOS not working without setuptools_rust

### ISSUE THREAD

**Issue by jalexvig** [PyO3/pyo3#172]
### 🌍 Environment

 - Your operating system and version: macOS 10.13.4
 - Your python version: 3.6.5
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: venv and sys installation
 - Your rust version: rustc 1.28.0-nightly

### 💥 Reproducing

As referenced in [this issue](https://github.com/PyO3/pyo3/issues/88) I cannot get pyo3 working for the example in the README without resorting to `setuptools_rust`.

The docs say

> For MacOS, "-C link-arg=-undefined -C link-arg=dynamic_lookup" is required to build the library

I could not get this to work and [@fafhrd91 hinted](https://github.com/PyO3/pyo3/issues/88#issuecomment-393968233) that looking at the setuptools_rust output might be useful. Here is the error I get when I try the command I got from setuptools_rust:

```
cargo rustc --lib --manifest-path Cargo.toml --features pyo3/python3 pyo3/extension-module --release -- --crate-type cdylib -C link-arg=-undefined -C link-arg=dynamic_lookup
   Compiling pyo3 v0.2.5 (file:///Users/alex/learn/rust/pyo3)
   Compiling word-count v0.1.0 (file:///Users/alex/learn/rust/pyo3/examples/word-count)
error: Unrecognized option: 'release'

error: Could not compile `word-count`.

To learn more, run the command again with --verbose.
```

What is the best way to get this to run on a mac without needing `setuptools_rust`?

**Comment by konstin** [comment]
I don't have a mac, so I can't test this myself. There are two things that should work though: One is running `cargo rustc --release -- -C link-arg=-undefined -C link-arg=dynamic_lookup`, the other is creating a [.cargo/config](https://doc.rust-lang.org/cargo/reference/config.html) with the links args and then using `cargo build --release` normally:

```toml
[target.macos]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

**Comment by jalexvig** [comment]
@konstin thanks! Just submitted a PR that makes the README more explicit.

**Comment by mre** [comment]
Tiny addition for everybody trying to get `.cargo/config` to work. I had to adjust the target like so:
```toml
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```
See also: https://github.com/inferiorhumanorgans/r2-c166/blob/752b61d36acd1ddbbcd0844505f94093773e4cc5/README.md
