### ISSUE TITLE
Regression: lost support PYO3_NO_PYTHON

### ISSUE THREAD

**Issue by adam-azarchs** [PyO3/pyo3#1723]
With pyo3 version 0.13.2, setting `PYO3_NO_PYTHON` to something in your environment and setting the python abi level via feature flags would allow you to successfully build in an environment where python was not available at the time the rust build executed.  This functionality was critical for our build system (which runs in a sandbox and produces a static lib which is then linked into an extension module by a separate system), but was removed with https://github.com/PyO3/pyo3/commit/79c7149d524f86dc2503597759fb2f19d4de21de#diff-d0d98998092552a1d3259338c2c71e118a5b8343dd4703c0c7f552ada7f9cb42.

Since there was no mention of this in the changelog, I'm hoping this was accidental.  If it was not, then the changelog should at least be updated to note this breaking change.

**Comment by davidhewitt** [comment]
The code was refactored but `PYO3_NO_PYTHON` is still present and expected to work. Can you please describe the build failure you are experiencing in more detail? 

https://github.com/PyO3/pyo3/blob/584fc6fe42a8ec6fe7fa55ff98aec8bf8471e134/pyo3-build-config/src/impl_.rs#L891

**Comment by adam-azarchs** [comment]
Sorry about this.  Got a late night notification that dependabot tried updating pyo3 and the build failed, but the actual root cause doesn't seem to be a problem in pyo3 per se.  Rather, dependabot updated pyo3 to 0.14.1, but the `numpy` crate still depended on 0.13.2, with the result that the indirectly-depended-upon version 0.13.2 no longer had the `abi3-py38` feature enabled during the build.  So, not a pyo3 bug, just an idiosyncrasy of cargo's feature resolution.

**Comment by adam-azarchs** [comment]
(That said, please publish an updated version of `rust-numpy`.  I somewhat doubt this will be the only problem people run into if they're using a `numpy` version that depends on a different version of `pyo3` from what the rest of their project is using)

**Comment by birkenfeld** [comment]
In any case I think pyo3 should be a crate that can't be in the dep graph in more than one Version.

**Comment by davidhewitt** [comment]
> In any case I think pyo3 should be a crate that can't be in the dep graph in more than one Version.

Wholly agree, though I'm not sure there's a way we can enforce this from the `pyo3` crate itself. I think `maturin` has such a check though.

**Comment by birkenfeld** [comment]
Well, there is https://doc.rust-lang.org/cargo/reference/resolver.html#links which we could set to "python" or "libpython" or such.

**Comment by adam-azarchs** [comment]
our team uses [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) to generally keep the number of multi-version crates down, for the sake of build times.  The problem with introducing it now is that it wouldn't prevent one from linking multiple old versions alongside the new one.  Still, would help in the future perhaps.

**Comment by davidhewitt** [comment]
Mmm I looked at `links` in the past, because it also gives us a way to transport metadata for `pyo3-build-config`, but I figured out a different way now.

`links` felt like a white-lie because we don't actually do any linking in `extension-module` case. But I could be persuaded we should add it.
