### ISSUE TITLE
PyBuffer::get leads to memory corruption under PyPy

### ISSUE THREAD

**Issue by oconnor663** [PyO3/pyo3#1736]
I've put up a repository containing a minimal repro of this bug: https://github.com/oconnor663/pyo3_pybuffer_repro. You can run the `repro.sh` script there to execute all the repro steps below.

I'm on x86-64 Arch Linux, with CPython 3.9.6, PyPy 7.3.5, and Rust 1.53.0. Here is a minimal Rust extension demonstrating this bug:

Cargo.toml:
```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2018"

[lib]
name = "repro"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.14.1"
features = ["extension-module"]
```

src/lib.rs:
```rust
use pyo3::buffer::PyBuffer;
use pyo3::prelude::*;

#[pyfunction]
fn buffer_len(obj: &PyAny) -> PyResult<usize> {
    let buffer = PyBuffer::<u8>::get(obj)?;              // <-- THIS IS THE INTERESTING LINE
    Ok(buffer.item_size() * buffer.item_count())
}

#[pymodule]
fn repro(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(buffer_len, m)?)?;
    Ok(())
}
```

test.py:
```python
from repro import buffer_len

assert buffer_len(b"foo") == 3
```

I create a `virtualenv -p pypy3`, and inside that virtualenv I build and install with extension module with `maturin develop`. (Note that this relies on the fix at https://github.com/PyO3/maturin/pull/596, which only just shipped in v0.11.2.) Finally I execute `test.py` over and over in a loop something like this in Bash (where `python` refers to the virtualenv Python interpreter):

```bash
i=1
while python ./test.py ; do
    echo "run number $i"
    i=$(($i + 1))
done
```

Here's an example run of `repro.sh` (which executes all the steps above) on my box:

```
❯ ./repro.sh
created virtual environment PyPy3.7.10.final.0-64 in 144ms
  creator PyPy3Posix(dest=/tmp/tmp.n8Evydf1LW, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jacko/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
🔗 Found pyo3 bindings
🐍 Found PyPy 3.7 at python
   Compiling pyo3 v0.14.1
   Compiling repro v0.1.0 (/home/jacko/tmp/repro)
    Finished dev [unoptimized + debuginfo] target(s) in 3.63s
run number 1
run number 2
run number 3
malloc_consolidate(): invalid chunk size
./repro.sh: line 14: 125301 Aborted                 (core dumped) python ./test.py
```

Note that the assert in `test.py` did pass a few times before the crash in this case. On some runs it crashes immediately for me, and on others it gets through a handful of executions before crashing like it did here.

If I replace `virtualenv -p pypy3` with `virtualenv -p /usr/bin/python` (CPython 3.9.6), `test.py` always succeeds and that while loop runs forever.

**Comment by messense** [comment]
I can reproduce this on x86_64 macOS with pypy3.7

```bash
❯ ./repro.sh
run number 1
python(98724,0x11530fe00) malloc: Incorrect checksum for freed object 0x7ff6e6604138: probably modified after being freed.
Corrupt value: 0x1
python(98724,0x11530fe00) malloc: *** set a breakpoint in malloc_error_break to debug
./repro.sh: line 9: 98724 Abort trap: 6           python ./test.py
```

**Comment by davidhewitt** [comment]
Nice repro, that's really useful. I think I've found the issue, see #1737
