### ISSUE TITLE
Can't compile on Windows 10

### ISSUE THREAD

**Issue by fasihrana** [PyO3/pyo3#175]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Windows 10 Pro (v1803)
 - Your python version: 3.6.5
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Through Windows installer and No.
 - Your rust version: 1.27 (nightly)

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the rust code and the python.

Compiling the example on PyO3 main doc page using `cargo +nightly build` I get a lengthy list of errors complaining about "unresolved external symbols". I'm not sure what environment variable is rquired on windows for PyO3 to finid python36.lib. I've tried adding the path to "PATH" variable.

**Comment by konstin** [comment]
We'll need some more information to track this down:

* Which example did you use? The one with the main function or the one creating an extension module?
* Which is the exact rust version your using (The one you get from `rustc --version`)?
* Could you post the errors you got?
* What is the content of `$PATH`?

**Comment by oconnor663** [comment]
I'm running into this issue now. I cloned this repo, changed directory to `examples\word-count` and ran `cargo +nightly install --release`. Here's a gist with the [full output](https://gist.github.com/oconnor663/5c5a87db3c35dd2d49e054b1aa123150).

`cargo +nightly --version`: cargo 1.42.0-nightly (9d32b7b01 2020-01-26)

`echo %PATH%`: `C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Jack\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Jack\AppData\Local\Programs\Python\Python37-32\;C:\Users\Jack\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Jack\AppData\Local\Programs\Python\Python36-32\;C:\Users\Jack\.cargo\bin;C:\Users\Jack\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Minimal ADB and Fastboot;C:\Users\Jack\AppData\Local\Keybase\`

**Comment by davidhewitt** [comment]
@oconnor663 you're running into a different issue - #712 . Follow that thread for instructions how to resolve it.

I plan to add a more friendly error message soon as #752

**Comment by oconnor663** [comment]
Woops thank you.
