### ISSUE TITLE
Help: Convert rust error enums to python errors

### ISSUE THREAD

**Issue by Shadow53** [PyO3/pyo3#1757]
I've been through the docs and guide a few times and I'm stuck figuring out how to go about this.

I have a library that should be usable in both Rust and Python, where Python support is feature-gated. The Rust library defines a bunch of error types as enums using `thiserror`, e.g.

```rust
#[derive(Debug, Error)]
pub enum SomeError {
    #[error("display impl: {0}")]
    VariantOne(#[source] AnotherError),
    #[error(...)]
    VariantTwo(usize),
    #[error(...)]
    VariantThree(#[source] AnotherError),
    #[error(...)]
    VariantFour(#[from] YetAnotherError),
}
```

What I'm struggling to wrap my head around is the best way to transform this error type into a Python exception.

1. `pyclass` fails because it is an enum and not a struct.
2. `create_exception!` creates a new type and does not modify an existing one.
3. `impl_exception_boilerplate!` seems closest, but conflicts with the implementation of `std::error::Error` from `thiserror`. If I modify the code to remove the use of `thiserror` (i.e. impl things myself), I get a new error that `SomeError` does not `impl PyTypeInfo`, which I am not comfortable trying to implement on my own.

Is there something I'm missing, or is this something that just isn't every doable in the current state of PyO3?

**Comment by davidhewitt** [comment]
If you want to use builtin Python exception types and be able to return `Result<_, SomeError>` from `#[pymethods]`, `impl From<SomeError> for PyErr` might suit what you need?

If you want a custom exception type I would probably recommend `#[pyclass(extends=PyException)]` to make a separate error classe which the `From` impl would target.

**Comment by Shadow53** [comment]
I'm going with the second option for now.

After further searching, it looks like this is a (partial?) duplicate of #417, so I'll close this in favor of that.
