### ISSUE TITLE
Py_DecodeLocale() incorrect signature

### ISSUE THREAD

**Issue by indygreg** [PyO3/pyo3#1766]
Currently `Py_DecodeLocale()` is defined as the following:

```
pub fn Py_DecodeLocale(arg1: *const c_char, arg2: Py_ssize_t) -> *mut wchar_t;
```

But in CPython `Include/fileutils.h`, it is defined as the following:

```
PyAPI_FUNC(wchar_t *) Py_DecodeLocale(
    const char *arg,
    size_t *size);
```

I believe the Rust signature should be:

```
pub fn Py_DecodeLocale(arg1: *const c_char, arg2: *mut Py_ssize_t) -> *mut wchar_t;
```

Given this is an API change, I'm unsure how you want to handle this. Hence why I filed an issue instead of going straight to a PR.

**Comment by davidhewitt** [comment]
Yep looks like our ffi definition is wrong; the C declaration you quote has been the same since Python 3.6 (and maybe earlier, didn't check).

Given our declaration is wrong I class this as a bug fix that's fine to be merged whenever. It seems unlikely anyone is using this correctly at the moment.
