### ISSUE TITLE
How to impl __anext__ using pyo3-asyncio

### ISSUE THREAD

**Issue by Earthson** [PyO3/pyo3#1770]
I can not find a way to convert a future-like PyObject to PyIterANextOutput

```
type Result: IntoPyCallbackOutput<PyIterANextOutput>
```

**Comment by davidhewitt** [comment]
If you use `Option<PyObject>` as the return type of your `__anext__` function, I think it should work? What error do you get?

**Comment by Earthson** [comment]
It works:)

convert from `PyResult<PyObject>` to `PyResult<Option<PyResult>>`

thanks:)
