### ISSUE TITLE
Support `del` on `#[setter]` defined attributes

### ISSUE THREAD

**Issue by indygreg** [PyO3/pyo3#1778]
This is a follow-up to the discussion in #1775 to track implementing support for `del` on `[setter]` defined attributes.

**Comment by davidhewitt** [comment]
To clarify, implementing `__delattr__` for dynamic attributes is supported and does work.

What we don't currently support is using `del myclass.x` when `x` is defined by a `#[setter]` or `#[pyo3(set)]`. 

TBH I'm tempted to go with "we don't need this" (after #1779 trying to delete such an attribute will raise `AttributeError`), however if a user does indeed have a valid use-case for this please do comment on this issue and we can discuss designs.

**Comment by davidhewitt** [comment]
As there's been no demand for a year, I'm going to close this. The comment above remains true that if a use-case emerges I'd be happy to discuss designs.
