### ISSUE TITLE
Getters can not be added to non-Copy types

### ISSUE THREAD

**Issue by yanganto** [PyO3/pyo3#178]
`#[prop(get, set)]` cannot apply to a String member

### 🌍 Environment

- Arch Linux
- Python3.6.5 (installed not pyenv )
- rustup 1.11.0
- rustc 1.27.0-nightly (8ff4b4206 2018-05-08)`):

### 💥 Reproducing
```
#[pyclass]
struct MyClass{
    #[prop(get, set)]
    title: String,
    token: PyToken
}

#[pymethods]
impl MyClass{
    #[new]
    fn __new__(obj: &PyRawObject) -> PyResult<()>
    {
        obj.init(|t| MyClass{
            title: String::new(),
            token: t
        })
    }
}
```
```
error[E0507]: cannot move out of borrowed content
  --> src/lib.rs:26:1
   |
26 | #[pyclass]
   | ^^^^^^^^^^ cannot move out of borrowed content

error: aborting due to previous error
```

**Comment by konstin** [comment]
I've narrowed it down a bit:

```rust
#![feature(proc_macro, specialization)]
#[macro_use]
extern crate pyo3;

use pyo3::prelude::*;

use pyo3::py::class;

#[class]
struct MyClass{
    #[prop(get)]
    title: String,
}
```

The culprit is this piece of code:

https://github.com/PyO3/pyo3/blob/4fc52cf966ab0a3df6434ee372589fce18e04e7d/pyo3-derive-backend/src/py_class.rs#L301-L309

With the current implementation, only Copy-types can be used for getters.
