### ISSUE TITLE
Python 3.6 end-of-life, MSRV to 1.48?

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#1782]
Python 3.6 end-of-life is scheduled for 23rd December this year. (https://endoflife.date/python)

This means our first breaking release in 2022 can drop support for Python 3.6 and also bump MSRV. It looks like Debian bullseye will release with Rust 1.48, so I expect that to be the next MSRV as per https://github.com/PyO3/pyo3/blob/main/Contributing.md#python-and-rust-version-support-policy

This ticket is just a placeholder which we can use to mark TODOs in code related to Python 3.6 or MSRV which we can clean up once reaching Python 3.7 and Rust 1.48 as minimum versions.

**Comment by birkenfeld** [comment]
+1 for making these bumps together.
