### ISSUE TITLE
How to get digits of PyLong/PyInt instance?

### ISSUE THREAD

**Issue by lycantropos** [PyO3/pyo3#1797]
In `Python C API` we can simply access digits of `int` with `ob_digit` slot like
```c
PyLongObject* value = ...;
Py_ssize_t digits_count = Py_ABS(Py_SIZE(value));
if (digits_count != 0) {
  digit highest_digit = value->ob_digit[digits_count - 1];
  ...
}
```
is there a way to do the same thing using given library?
I need this to add conversion between custom big int class and `int` one.

There is a workaround by converting to string and parsing it again, but copying digits should be easier & faster than roundtrip to string and back.

**Comment by mejrs** [comment]
Can you use `_PyLong_AsByteArray` for this?


That is what our conversions for num_bigint use (if that is what you (can) use, you can simply use that conversion instead)

See https://github.com/PyO3/pyo3/blob/main/src/num_bigint.rs

**Comment by lycantropos** [comment]
It worked, thanks @mejrs!
