### ISSUE TITLE
Complex Number Support

### ISSUE THREAD

**Issue by adamisntdead** [PyO3/pyo3#184]
So python has built in complex number support, so I want to ask is it possible to implement the `IntoPyObject` trait for the complex number struct in the `num_complex` crate?

I can't do it in my code becuase:

```rust
impl IntoPyObject for num_complex::Complex<f32> {
  //  ...
}
```

gives the error

```
impl doesn't use types inside crate
```

**Comment by konstin** [comment]
But the problem isn't one specific to pyo3 or num_complex, but rather a rule in rust that forbids implementing foreign traits one foreign type. See [this stackoverflow answer](https://stackoverflow.com/questions/25413201/how-do-i-implement-a-trait-i-dont-own-for-a-type-i-dont-own) for details and solutions. The following is the minimal solution, without any deref magic:

```rust
extern crate pyo3;
extern crate num_complex;

use pyo3::prelude::*;

struct MyComplexType(num_complex::Complex<f32>);

impl IntoPyObject for MyComplexType {
    fn into_object(self, py: Python) -> PyObject {
        unimplemented!()
    }
}
```

**Comment by adamisntdead** [comment]
Sorry my bad - I missremembered that you do it with a struct tried to do that with  a type alias `type MyComplexType = num_complex::Complex<f32>` which didn't work - sorry!
