### ISSUE TITLE
Complete sequence API for list/tuple?

### ISSUE THREAD

**Issue by birkenfeld** [PyO3/pyo3#1845]
I propose to add all methods present in `PySequence` (such as `del_item`) to `PyList` and `PyTuple`.  It is quite convenient not to have to cast to `PySequence` for some operations but not for others.

**Comment by davidhewitt** [comment]
Specifically on `del_item` - it should already be available thanks to deref to `PyAny`?

Though in general I'm in favour of making it easier for users, so happy to find improvements here.

We could also have `.as_sequence()` method on `PyList` and `PyTuple` to make the cast less awkward?

**Comment by birkenfeld** [comment]
Well, there's a few inconsistencies: for example, since the `del_item` is the generic version it will take negative indices :)

**Comment by davidhewitt** [comment]
Ah, that's a good point! In which case a specialized `del_item` on `PyList` would be a good idea!
