### ISSUE TITLE
Allow taking slices when implementing PySequenceProtocol __getitem__

### ISSUE THREAD

**Issue by staticintlucas** [PyO3/pyo3#1855]
In Python `__getitem__` can accept both an `int` and a `slice` object. Currently when implementing `PySequenceProtocol` in Rust the `__getitem__` method only accepts an `isize` index, so there is no way to implement slicing.

I guess the best way to add this would be to add a separate method (called `__getslice__` or similar) which accepts a `PySlice` or `PySliceIndices` object (to avoid breaking backwards compatibility).

Alternatively, PyO3 could just take care of slices internally and call `__getitem__` for every index; negative indices are already handled by PyO3. But this approach is probably going to have some overhead for large slices or complex `__getitem__` implementations.

I'm not super familiar with the PyO3 codebase but I'm happy to help with a PR if I can get a few pointers on this :smile:

**Comment by birkenfeld** [comment]
Breaking compatibility is not a concern (yet), there will be a big break soon anyway when we move protocol methods to `#[pymethods]`.

**Comment by staticintlucas** [comment]
In that case it should just accept a `PyAny` object and let the implementation handle different types right? Let me see if I can implement that and get a PR ready

**Comment by birkenfeld** [comment]
> In that case it should just accept any `impl FromPyObject` object and let the implementation handle different types right

We could also try to be helpful for the usual use cases and provide an enum with three variants: `isize`, `PySlice` and `PyAny`...

**Comment by davidhewitt** [comment]
Note that the `PySequence_GetSlice` actually uses the `tp_as_mapping.mp_subscript` member.

https://github.com/python/cpython/blob/ce5e1a6809b714eb0383219190a076d9f883e008/Objects/abstract.c#L1910-L1930

This means that adding `__getslice__` to `PySequenceProtocol` would become incompatible with `PyMappingProtocol`.

I would discourage you from spending too long wrestling with this, as I'm hoping I can give a first stab at a `#[pymethods]` rewrite of these things next week while I'm on holiday.

**Comment by staticintlucas** [comment]
> I would discourage you from spending too long wrestling with this, as I'm hoping I can give a first stab at a `#[pymethods]` rewrite of these things next week while I'm on holiday.

I'll leave it for now in that case. Maybe I'll have another look at it in future when the `#[pymethods]` rewrite is complete

**Comment by davidhewitt** [comment]
Ok we have a first implementation of the `#[pymethods]` rewrite just merged in #1864. The remaining items (including the sequence protocol) is in #1884. Any ideas on design are very welcome!

**Comment by davidhewitt** [comment]
Sorry for the slow reply on this one.

> So coming back to the question of design, my specific "dream" for this is as follows:

I understand the ergonomic desire for overloading methods in this way however it's not idiomatic Rust so it's not something I would personally support for PyO3. In particular one feature I like of `#[pymethods]` is that they remain regular Rust methods which can be called from the Rust side too.

It would be possible to write your own proc-macro which you could apply before `#[pymethods]` which collected all overloads and did the syntactic transformation you suggest; that would be a nice opt-in crate which could be published for those who want to do this.

> Potentially also this: for the #[pymethods] proc-macro to be able to expand macro invocations (is it even possible in Rust?

You should look at the `cargo-expand` tool which enables exactly this kind of thing. I think `rust-analyzer` can do it too.

**Comment by davidhewitt** [comment]
Regarding the original discussion, the correct solution for this with `#[pymethods]` is to have something like the following:

```rust
#[derive(FromPyObject)]
enum SliceOrInt<'a> {
    Slice(&'a PySlice),
    Int(isize),
}

#[pyclass]
struct GetItem {}

#[pymethods]
impl GetItem {
    #[new]
    fn new() -> Self {
        Self { }    
    }

    fn __getitem__(&self, idx: SliceOrInt) -> &'static str {
        match idx {
            SliceOrInt::Slice(_) => "slice",
            SliceOrInt::Int(_) => "int",
        }
    }
}
```

This already compiles and works on PyO3 0.15:

```
>>> g = GetItem()
>>> g[1]
'int'
>>> g[1:5]
'slice'
```

So I'll mark this as wontfix - the `#[pymethods]` solution works and `PySequenceProtocol` (`#[pyproto]`) will most likely be deprecated in PyO3 0.16.
