### ISSUE TITLE
Document more macros

### ISSUE THREAD

**Issue by mejrs** [PyO3/pyo3#1869]
Currently the following macros appear in the crate root:

- `create_exception_type_object`
- `impl_exception_boilerplate`
- `pyobject_native_type`
- `pyobject_native_type_base`
- `pyobject_native_type_core`
- `pyobject_native_type_extract`
- `pyobject_native_type_info`
- `pyobject_native_type_named`
- `pyobject_native_type_sized`

I'd love to add some documentation/examples for these, but:
- I don't really know what they do
- Which of these are actually meant for users to use? Can the `*_native_*` macros even be implemented by users? If not should they be private?
- Which ones are implementation details of other macros? Should they be `#[doc(hidden)]`?

**Comment by davidhewitt** [comment]
Good idea. TBH I would prefer that we documented none of them for users for now. All of these are implementation-detail in my opinion.

Maybe the `pyobject_native_*` macros will eventually be useful downstream (e.g. `rust-numpy` does use a couple of them), however I think that #1308 will require changes to a lot of them so would prefer we didn't encourage people to use them for now.
