### ISSUE TITLE
Interpreter path location is not correct for conda on windows

### ISSUE THREAD

**Issue by Japanuspus** [PyO3/pyo3#1871]
Virtual environments created with anaconda on windows have their `python` executable located in the root of the environment folder (conda v4.10.3), but implementation in `pyo3-build-config` assumes executable to reside in `Scripts`-subdirectory.

Relevant line of code: 
https://github.com/PyO3/pyo3/blob/6e83516e9445a2aa0a3a1c3117a6a38300142d9b/pyo3-build-config/src/impl_.rs#L1112

I have not submitted a PR, as I do not know if virtualenv on windows uses `Script` or `bin` (i.e. if more branches in `if`-statement will be needed). A more robust approach might be to rely on the OS to resolve the python executable if a virtual environment is active?

This issue appears to be root cause of #1554.

**Comment by davidhewitt** [comment]
Thanks, I've opened a PR to tweak the path as suggested, however I still encounter #1554 when testing anaconda locally with that fix...

**Comment by davidcian** [comment]
PyO3 correctly interprets the information that Conda leaves out about a virtual environment via `conda activate`, which in turn generates and runs a (usually dynamically generated) shell script. The shell script itself can be seen (for Powershell) with `conda shell.powershell activate <env_name>`, and we can see it sets the `CONDA_PREFIX` env var which is used by PyO3. PyO3 uses this to emit a link signal to `rustc`, and the Python gets linked correctly. However, I don't think that's enough for it to also be initialized correctly by `Py_InitializeEx`. Instead, what might be required is respecifying the config via `Py_InitializeFromConfig`. I might be wrong, maybe it should work by default and something else is messing up how `Py_InitializeEx` works.

**Comment by davidhewitt** [comment]
I agree with the thinking that `Py_InitializeFromConfig` is worth investiating. I haven't tried, though. I'd like to eventually, but other pieces keep claiming higher prioritisation.
