### ISSUE TITLE
Question: How to capture the stdout of the python interpreter

### ISSUE THREAD

**Issue by sebschmi** [PyO3/pyo3#1872]
Please see the following question I asked on stackoverflow: https://stackoverflow.com/questions/69203700/how-to-capture-the-stdout-of-the-python-interpreter-inside-the-rust-program-when

How can I achieve this with pyo3?

The use case is to envelope the output with the logger used by the Rust application.

**Comment by birkenfeld** [comment]
Same as in Python, you replace sys.stdout (and maybe sys.stderr too) with a custom object whose write() method does what you want.

**Comment by birkenfeld** [comment]
Ok, now that I can actually run and test something, here's an example:

```
use pyo3::prelude::*;

#[pyclass]
struct LoggingStdout;

#[pymethods]
impl LoggingStdout {
    fn write(&self, data: &str) -> PyResult<()> {
        println!("stdout from python: {:?}", data);
        Ok(())
    }
}

fn main() -> PyResult<()> {
    Python::with_gil(|py| {
        let sys = py.import("sys")?;
        sys.setattr("stdout", LoggingStdout.into_py(py))?;
        py.run("print('some', 'output')", None, None)?;
        Ok(())
    })
}
```

The output will be:
```
stdout from python: "some"
stdout from python: " "
stdout from python: "output"
stdout from python: "\n"
```

As you can see, depending on how the output is written to `sys.stdout` by the Python side, you may not get full lines in one go - you can accept that, add a line buffer in the Rust implementation, or make sure that the Python side uses `write` with full lines.

**Comment by sebschmi** [comment]
Thank you very much, this looks simple!
