### ISSUE TITLE
call rust fuction from python which is called by rust

### ISSUE THREAD

**Issue by iamnhphu** [PyO3/pyo3#1878]
Hello,
I have a rust application use python to do some Machine Learning. I need to call rust fuction from python which is called by rust.

My code:
```rust

fn rust_fn(x: String) {
    println!("{}", x)
}

fn main() {
    Python::with_gil(|py| {
        let module = PyModule::from_code(py, r"
def test():
    rust_fn('hello world')
        ", "test.py", "test").unwrap();
        let _result = module.getattr("test").unwrap().call0().unwrap();


    });
}
```
After run the application, rust_fn is called and print `hello world` . How I can do that?

**Comment by davidhewitt** [comment]
How about this:

```
use pyo3::prelude::*;

#[pyfunction]
fn rust_fn(x: String) {
    println!("{}", x)
}

fn main() -> PyResult<()> {
    Python::with_gil(|py| {
        // Get a Python object representing rust_fn
        let rust_fn_py = wrap_pyfunction!(rust_fn, py)?;
        // Create the module
        let module = PyModule::from_code(py, r"
def test():
    rust_fn('hello world')
        ", "test.py", "test")?;
        // add rust_fn to the module
        module.setattr("rust_fn", rust_fn_py)?;
        // execute the module
        module.getattr("test")?.call0()?;
        Ok(())
    })
}
```

Because `rust_fn` doesn't need to be defined until running `test`, we can set it in the module scope using `setattr`. You could also pass `rust_fn` as an argument to test.

**Comment by iamnhphu** [comment]
> How about this:
> 
> ```
> use pyo3::prelude::*;
> 
> #[pyfunction]
> fn rust_fn(x: String) {
>     println!("{}", x)
> }
> 
> fn main() -> PyResult<()> {
>     Python::with_gil(|py| {
>         // Get a Python object representing rust_fn
>         let rust_fn_py = wrap_pyfunction!(rust_fn, py)?;
>         // Create the module
>         let module = PyModule::from_code(py, r"
> def test():
>     rust_fn('hello world')
>         ", "test.py", "test")?;
>         // add rust_fn to the module
>         module.setattr("rust_fn", rust_fn_py)?;
>         // execute the module
>         module.getattr("test")?.call0()?;
>         Ok(())
>     })
> }
> ```
> 
> Because `rust_fn` doesn't need to be defined until running `test`, we can set it in the module scope using `setattr`. You could also pass `rust_fn` as an argument to test.

Thank you very much

**Comment by iamnhphu** [comment]
> How about this:
> 
> ```
> use pyo3::prelude::*;
> 
> #[pyfunction]
> fn rust_fn(x: String) {
>     println!("{}", x)
> }
> 
> fn main() -> PyResult<()> {
>     Python::with_gil(|py| {
>         // Get a Python object representing rust_fn
>         let rust_fn_py = wrap_pyfunction!(rust_fn, py)?;
>         // Create the module
>         let module = PyModule::from_code(py, r"
> def test():
>     rust_fn('hello world')
>         ", "test.py", "test")?;
>         // add rust_fn to the module
>         module.setattr("rust_fn", rust_fn_py)?;
>         // execute the module
>         module.getattr("test")?.call0()?;
>         Ok(())
>     })
> }
> ```
> 
> Because `rust_fn` doesn't need to be defined until running `test`, we can set it in the module scope using `setattr`. You could also pass `rust_fn` as an argument to test.

what if `rust_fn` need to define before running `test`?

``` rust
 #[pyfunction]
 fn rust_fn(x: String) {
     println!("{}", x)
 }
 
 fn main() -> PyResult<()> {
     Python::with_gil(|py| {
         // Get a Python object representing rust_fn
         let rust_fn_py = wrap_pyfunction!(rust_fn, py)?;
         // Create the module
         let module = PyModule::from_code(py, r"
     rust_fn('hello world')
         ", "test.py", "test")?;
         // add rust_fn to the module
         module.setattr("rust_fn", rust_fn_py)?;
         // execute the module
         module.getattr("test")?.call0()?;
         Ok(())
     })
 }
 ```

**Comment by davidhewitt** [comment]
I would change your Python code so it takes the Rust function as an argument, and then use `.call1((rust_fn_py,))` instead of .call0()`.
