### ISSUE TITLE
what's the best way to detect a python type in rust?

### ISSUE THREAD

**Issue by shi-yan** [PyO3/pyo3#1910]
I'm trying to serialize a python dict into a json in rust.

what's the best way to detect python types?

currently I'm doing python_var.get_type().name().unwrap(), with a string comparison. it seems  to be inefficient?

is there a better way doing this? Thanks!

Another question, how to initialize python's NoneType? there is no document covering that?

And how can I convert from PyDict to PyAny? 

Thanks.

**Comment by birkenfeld** [comment]
You should be able to directly compare the result of `get_type()?` (better not use unwrap unless forced) for equality.  However, `obj.is_instance` is also available which might be a better fit.

What do you mean by "initialize NoneType"?

`&PyDict` should automatically deref to `&PyAny`, so for specific problems please post a bit of code.
