### ISSUE TITLE
Python 3.6: SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported! (pyo3 v0.14.5)

### ISSUE THREAD

**Issue by Congyuwang** [PyO3/pyo3#1911]
## 🐛 Bug Reports

Building on python 3.6.15 fails to run on python 3.6.13. Below is the error message:
```
❯ python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import string_sum
>>> string_sum.sum_as_string(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!
```

If I build the same project using python 3.6.13 on my laptop, it runs successfully.

### 🌍 Build Environment (Github Workflow)

 - OS: `runs-on: macos-latest`, `Mac OS X 10.15.7 19H1417`
 - python version: `3.6.15`
 - python installation: `actions/setup-python@v2`, with: `python-version: 3.6`, `architecture: x64`
 - rust: `stable-x86_64-apple-darwin unchanged - rustc 1.55.0 (c8dfcfe04 2021-09-06)`
 - Your PyO3 version: `pyo3 v0.14.5`

#### Run Environment (My Laptop)

 - OS: `Mac OS X 11.6`
 - python version: `3.6.13`
 - python installation: `conda install python=3.6`

### 💥 Reproducing

lib.rs
```rust
use pyo3::prelude::*;

/// Formats the sum of two numbers as string.
#[pyfunction]
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

/// A Python module implemented in Rust. The name of this function must match
/// the `lib.name` setting in the `Cargo.toml`, else Python will not be able to
/// import the module.
#[pymodule]
fn string_sum(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(sum_as_string, m)?)?;

    Ok(())
}

```

Cargo.toml
```toml
[package]
name = "string_sum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.14.5", features = ["extension-module"] }

```

pyproject.toml
```toml
[project]
name = "congyu_pyo3_bug"
version = "0.0.1"

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

```

Installing package:
```sh
pip install congyu_pyo3_bug==0.0.1 -i https://test.pypi.org/simple
```

Reproduce bug:
```
❯ python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import string_sum
>>> string_sum.sum_as_string(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!
```

The repository where I built this: https://github.com/Congyuwang/congyu_pyo3_debug

Built using GitHub workflow: https://github.com/Congyuwang/congyu_pyo3_debug/blob/master/.github/workflows/blank.yml

**Comment by messense** [comment]
@Congyuwang See https://github.com/messense/maturin-action/commit/3c864831d650744ae7b5d3bd65d005fea448bae1

Please give it try with `uses: messense/maturin-action@main`
