### ISSUE TITLE
`PyType.is_subclass` does not work with two dynamic `PyType`s

### ISSUE THREAD

**Issue by Eric-Arellano** [PyO3/pyo3#1984]
Hello! During Pants's [migration to PyO3](https://github.com/pantsbuild/pants/pull/13526), I'm stuck on how to get `&PyType.is_subclass()` working.

This is what I would like to do:

```rust
#[pyfunction]
fn check_subclass(typ1: &PyType, typ2: &PyType) -> PyResult<bool> {
  typ1.is_subclass(typ2)
}
```

If I understand correctly, this is not possible because the API is `is_subclass<T>(&self)`, and it doesn't seem possible to say this due to how Generics work in Rust:

```rust
typ1.is_subclass::<typ2>()
```

For now, I'm thinking I can work around this by writing our own `unsafe` implementation, but I'd love to be able to contribute a more flexible API to PyO3. I'm thinking `is_subclass(&self, T: ToPyObject) -> bool`.

What do you think? How would we handle deprecations? (Note that rust-cpython calls it `is_subtype_of`, maybe that's an option)

Also I'm curious what you think about it returning `bool` instead of `PyResult<bool>`?

**Comment by birkenfeld** [comment]
Interesting! The current API is fine for some cases, but for cases such as yours we should also offer one that takes the type as parameter. Same for `is_instance` on `PyAny`.

For the moment, the best you can do is to call `typ1.__subclasscheck__(typ2)` using `call`.

**Comment by Eric-Arellano** [comment]
Thank you for that workaround! Much better than unsafe code.

**Comment by birkenfeld** [comment]
Ok, I've started a PR at #1985 to fix this for the next version.

**Comment by birkenfeld** [comment]
> Also I'm curious what you think about it returning `bool` instead of `PyResult<bool>`?

Since the subclass/instance checks can run arbitrary Python code (by overriding `__subclasscheck__`/`__instancecheck__` in the metaclass), we kind of have to keep the possibility for exceptions open.
