### ISSUE TITLE
Documentation fails to build on docs.rs

### ISSUE THREAD

**Issue by joar** [PyO3/pyo3#199]
See the following logs for details:

- 0.3.2: https://docs.rs/crate/pyo3/0.3.2/builds
- 0.4.0: https://docs.rs/crate/pyo3/0.4.0/builds

**Comment by konstin** [comment]
Yeah, that's known and I've already forwarded it to the relevant issue: https://github.com/onur/docs.rs/issues/23#issuecomment-406792865.

Fortunately, you can get all the rust docs offline: To e.g. open pyo3's docs, use `cargo doc -p pyo3 --open`.
