### ISSUE TITLE
Guide page for "Installation" / "Getting Started"

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2017]
As discussed in https://github.com/PyO3/pyo3/pull/763#issuecomment-972763362

I think it would be helpful to have a page in the guide for first-time users on documenting the ways we recommend to install Python, Rust, set up a virtualenv (maybe?) and install `maturin`.

This might need to be split out by OS. For example in #763 / #1800 we have quite a lot of experience of users who've had trouble on macOS because they've done things in ways that don't quite line up.

**Comment by mejrs** [comment]
I like how https://rustwasm.github.io/docs/book/ approaches this. Very friendly to people new to Rust.

**Comment by savente93** [comment]
I don't have access to a lot of different OSes so I can't necessarily test all the steps, but I'm willing to take a first crack at it so at least there is something people can add to over time, if you like

**Comment by davidhewitt** [comment]
@savente93 if you're willing to spend some time to get this started, that would be brilliant. Anything is better than nothing! I still think this would be a very valuable resource for beginners that I just never quite manage to get around to myself...
