### ISSUE TITLE
Can we have OSX travis builds please?

### ISSUE THREAD

**Issue by gilescope** [PyO3/pyo3#202]
I'm getting a linker error building the example on OSX at the moment, but seems fine when I build the example under Linux. Would it be possible to add in an OSX build to travis so that I can see it does work on someone else machine?

This is the kind of thing I'm getting:

 = note: Undefined symbols for architecture x86_64:
            "_PyUnicode_FromStringAndSize", referenced from:
                pyo3::objects::string::PyString::new::h9fb8a4b84a834ac6 in libpyo3-49b4944a87639b83.rlib(pyo3-49b4944a87639b83.3c5roxachxe1z4t.rcgu.o)
            "_PyDict_Items", referenced from:
                pyo3::objects::dict::PyDict::items::h8bd206fbf2672629 in libpyo3-49b4944a87639b83.rlib(pyo3-49b4944a87639b83.9vksi06m8ba06d9.rcgu.o)
To me it seems like these should be left as dynamic external calls to the std python library.

I tried setting:
DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.6/lib
but to no avail.

Versions:
OSX High Serra, Python 3.6.1, pyo3: Master

**Comment by konstin** [comment]
>  Would it be possible to add in an OSX build to travis so that I can see it does work on someone else machine?

We have people successfully using pyo3 on a mac following the readme. Getting travis build to work is incredibly time consuming and I don't even have a os x machine to reproduce failures locally. You're free to make a pull request and figure out the os x build though as all pull requests are run on travis.

**Comment by gilescope** [comment]
Ah - that's what it was. Sorry didn't spot there was a separate readme in the examples.
