### ISSUE TITLE
`Py_DECREF()` uses a private `_Py_Dealloc()` function even when `abi3` feature is enabled

### ISSUE THREAD

**Issue by ravenexp** [PyO3/pyo3#2020]
### Bug Description

Python3 API provides a function `PyDecRef()` and a macro `Py_DECREF()`. The former is a part of the stable C API, while the latter is not. [(source)][1]

[1]: https://docs.python.org/3/c-api/stable.html#contents-of-limited-api

### Steps to Reproduce

1. Link an extension module with `abi3` feature enabled.
2. Observe that it imports a private function `_Py_Dealloc`, which is not a part of the stable ABI.

### Your operating system and version

Arch Linux

### Your Python version (`python --version`)

Python 3.9.7

### Your Rust version (`rustc --version`)

rustc 1.56.0 (09c42c458 2021-10-18)

### Your PyO3 version

0.15.1

### How did you install python? Did you use a virtualenv?

pacman

**Comment by birkenfeld** [comment]
Yeah we need to check for `abi3` in our `Py_DECREF`.

**Comment by ravenexp** [comment]
I've been studying PEP 652 some more, and now I don't think this is actually a bug. Sorry.

While `_Py_Dealloc()` is not a part of the Limited API, it's included in the Stable ABI contract as can be seen in [`stable_abi.txt`][1].
Same goes for for example `_Py_NoneStruct`, which is used by PyO3 in its `Py_IsNone()` implementation.

[1]: https://github.com/python/cpython/blob/main/Misc/stable_abi.txt#L1622-L1624
[2]: https://github.com/PyO3/pyo3/blob/a0d3ab0de1d4aeb19c74af97c55495f02dceeea7/src/ffi/object.rs#L465-L473

**Comment by davidhewitt** [comment]
Yes, I think this is safe to depend on too. Thanks for looking into this carefully for us.

I'm going to close this issue for now, however if new information comes to light which suggests we need to change things please shout!
