### ISSUE TITLE
wrap_pyfunction! makro cannot be imported in versions  >= 0.15.0

### ISSUE THREAD

**Issue by Darkskald** [PyO3/pyo3#2030]
### Bug Description

Since version 0.15.0, the compiler has trouble to find the `wrap_pyfunction!` macro. Downgradingt to 0.14.5 solves the problem.

### Steps to Reproduce

```rust
use pyo3::prelude::*;

#[pyfunction]
fn noop() -> PyResult<()> {
    Ok(())
}

#[pymodule]
fn rust(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(noop, m)?)?;
    Ok(())
}

```

### Backtrace

```shell
error: cannot find macro `wrap_pyfunction` in this scope
  --> src/lib.rs:10:20
   |
10 |     m.add_function(wrap_pyfunction!(noop, m)?)?;
   |                    ^^^^^^^^^^^^^^^ help: a macro with a similar name exists: `wrap_functions`
   |
  ::: /home/flo/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.15.1/src/macros.rs:7:1
   |
7  | macro_rules! wrap_functions {
   | --------------------------- similarly named macro `wrap_functions` defined here

error: could not compile `multiply` due to previous error
```

### Your operating system and version

Arch Linux (Kernel  5.15.4)

### Your Python version (`python --version`)

Python 3.9.7

### Your Rust version (`rustc --version`)

1.56.1

### Your PyO3 version

0.15.0

### How did you install python? Did you use a virtualenv?

pacman, venv was used

### Additional Info

0.15.1 leads to the same result

**Comment by davidhewitt** [comment]
Can you please upload an MVP reproduction which demonstrates the issue?

We have extensive tests on 0.15.1 which use `wrap_pyfunction` just fine. You can also see on docs.rs that is is documented and exposed correctly inside the prelude: https://docs.rs/pyo3/0.15.1/pyo3/prelude/index.html

**Comment by davidhewitt** [comment]
(Looking at your snippet above again, I see that `macros.rs` incorrectly has `wrap_pyfunction` renamed to `wrap_functions`. How did you install PyO3? Is it possible the PyO3 source code has accidentally been modified on your local machine?)

**Comment by Darkskald** [comment]
Sorry, you are right- somehow I managed to mess up my local version of the PyO3 source...
