### ISSUE TITLE
cannot use PyO3 and tensorflow at the same time.

### ISSUE THREAD

**Issue by tsubakisakura** [PyO3/pyo3#2032]
### Bug Description

When importing a module when using PyO3 and tensorflow at the same time, it hangs.
(I couldn't figure out whether the problem was with tensorflow or PyO3)

### Steps to Reproduce

```
use pyo3::prelude::*;
use tensorflow::Tensor;

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();

    let sys = py.import("sys").unwrap();
    let _ = py.import("google.cloud.storage").unwrap();
    let version :String = sys.getattr("version").unwrap().extract().unwrap();
    println!("Hello python {}", version );

    let tensor = Tensor::new(&[1,2]).with_values(&[1.0,2.0]).unwrap();
    println!("{:?}", tensor );
}
```

Running this code causes a segmentation fault when importing google.cloud.storage.
However, if I comment out the last two lines, this code ends normally, even though it is not related to the processing order.

### Backtrace

```shell
(gdb) bt
#0  0x00007f9f2fde0614 in google::protobuf::python::AddEnumValues(_typeobject*, google::protobuf::EnumDescriptor const*) [clone .isra.0] [clone .constprop.0] ()
   from /opt/conda/lib/python3.7/site-packages/google/protobuf/pyext/_message.cpython-37m-x86_64-linux-gnu.so
#1  0x00007f9f2fde0f02 in google::protobuf::python::InitDescriptor() () from /opt/conda/lib/python3.7/site-packages/google/protobuf/pyext/_message.cpython-37m-x86_64-linux-gnu.so
#2  0x00007f9f2fdd995e in google::protobuf::python::InitProto2MessageModule(_object*) () from /opt/conda/lib/python3.7/site-packages/google/protobuf/pyext/_message.cpython-37m-x86_64-linux-gnu.so
#3  0x00007f9f2fdeb975 in PyInit__message () from /opt/conda/lib/python3.7/site-packages/google/protobuf/pyext/_message.cpython-37m-x86_64-linux-gnu.so
#4  0x00007f9f31d34a93 in _PyImport_LoadDynamicModuleWithSpec () from /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
#5  0x00007f9f31d3500b in ?? () from /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
#6  0x00007f9f31e23f37 in _PyMethodDef_RawFastCallDict () from /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
#7  0x00007f9f31e24a45 in _PyCFunction_FastCallDict () from /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
#8  0x00007f9f31c25700 in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
#9  0x00007f9f31d4d1e6 in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
```

### Your operating system and version

debian 10.11

### Your Python version (`python --version`)

Python 3.7.12

### Your Rust version (`rustc --version`)

rustc 1.56.1 (59eed8a2a 2021-11-01)

### Your PyO3 version

0.15.1

### How did you install python? Did you use a virtualenv?

use preinstalled image

### Additional Info

I created instance on GCP by this command

```
gcloud compute instances create dl-test-cpu-preemptible
  --image-project="deeplearning-platform-release"
  --image-family="tf2-ent-latest-cpu"
  --maintenance-policy="TERMINATE"
  --preemptible
  --scopes storage-rw
```

It happens in docker as well.
Source code is here:
https://github.com/tsubakisakura/pyo3tensorflow

**Comment by aviramha** [comment]
What's the google cloud library version? 
My wild guess would be that both "google cloud storage" library links to a protobuf library and Tensor with different versions. 
Can you try to install protobuf without binaries? i.e, let pypi compile it from source?

**Comment by davidhewitt** [comment]
As this has not received a follow-up response from OP for three months, I'm going to close this one. @aviramha's theory sounds likely correct.
