### ISSUE TITLE
maturin dev produces unsupported wheel on M1/arm64

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [PyO3/pyo3#2052]
### Bug Description

I can run `cargo build` on my Apple M1 to build the `maturin-starter` example after having added this `config.toml`: 
```[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```
However, when I run `maturin develop` it exits with: `ERROR: maturin_starter-0.1.0-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.`

I 

### Steps to Reproduce

1. go into the maturin_starter example on an Apple M1
2. Follow the readme instructions:
3. pip install maturin
4. pip install -r requirements-dev.txt
5. maturin develop && pytest

### Backtrace

```shell
Finished dev [unoptimized + debuginfo] target(s) in 8.32s
📦 Built wheel for CPython 3.9 to /Users/mariuskriegerowski/src/rust/pyo3/examples/maturin-starter/target/wheels/maturin_starter-0.1.0-cp39-cp39-macosx_11_0_arm64.whl
💥 maturin failed
  Caused by: pip install in /Users/mariuskriegerowski/src/rust/pyo3/examples/maturin-starter/.venv failed running ["-m", "pip", "--disable-pip-version-check", "install", "--force-reinstall", "/Users/mariuskriegerowski/src/rust/pyo3/examples/maturin-starter/target/wheels/maturin_starter-0.1.0-cp39-cp39-macosx_11_0_arm64.whl"]: exit status: 1
--- Stdout:

--- Stderr:
ERROR: maturin_starter-0.1.0-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.
---
```
```


### Your operating system and version

MacOS Monterey 12.1

### Your Python version (`python --version`)

Python 3.9.4

### Your Rust version (`rustc --version`)

rustc 1.59.0-nightly (efec54529 2021-12-04)

### Your PyO3 version

0.15.1

### How did you install python? Did you use a virtualenv?

based off of standard system python
```
python3 -m venv  .venv
source .venv/bin/activate
```

### Additional Info

```
❯ pip3 --version
pip 21.3.1 from /Users/mariuskriegerowski/src/rust/pyo3/examples/maturin-starter/.venv/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by messense** [comment]
Usually it's caused by misused Python interpreters, see https://github.com/sansyrox/robyn/issues/120

**Comment by HerrMuellerluedenscheid** [comment]
In fact my venv seems to spawn an x86 python from arm64. Also the osx version tag is odd. Very strange... 

```
❯ which python
/opt/homebrew/opt/python@3.9/libexec/bin/python
❯ python -c 'import sysconfig; print(sysconfig.get_platform())'
macosx-12-arm64
❯ python -m venv  .venv
❯ source .venv/bin/activate
❯ python -c 'import sysconfig; print(sysconfig.get_platform())'
macosx-10.9-x86_64
```

**Comment by HerrMuellerluedenscheid** [comment]
Closing as this is not related to `pyo3` but some misconfiguration of different python interpreter versions.

**Comment by messense** [comment]
> 

My homebrew Python works fine

```bash
❯ /opt/homebrew/opt/python@3.9/libexec/bin/python -c 'import sysconfig; print(sysconfig.get_platform())'
macosx-12-arm64
❯ /opt/homebrew/opt/python@3.9/libexec/bin/python -m venv venv
❯ . venv/bin/activate
❯ python -c 'import sysconfig; print(sysconfig.get_platform())'
macosx-12-arm64
```

**Comment by HerrMuellerluedenscheid** [comment]
In case others stumble accross this thread: I uninstalled my `brew` installed version and re-installed. It worked fine afterwards.
