### ISSUE TITLE
No API docs for pyo3-build-config and others on main

### ISSUE THREAD

**Issue by messense** [PyO3/pyo3#2053]
https://pyo3.rs/main/doc/pyo3/index.html

![image](https://user-images.githubusercontent.com/1556054/146294316-15909db9-55f1-4b2a-8c2b-8ce7c3084bf7.png)

**Comment by mejrs** [comment]
Do you think they should be?

We can have `pyo3-build-config` on the sidebar. I don't think we should have pyo3-macros and pyo3-macros-backend there.

**Comment by messense** [comment]
> We can have pyo3-build-config on the sidebar. I don't think we should have pyo3-macros and pyo3-macros-backend there, because they're really not public api.

I agree.

**Comment by mejrs** [comment]
It might be nice to have a `pyo3.rs/internal`, that shows all the hidden and internal api, similar to https://stdrs.dev/ Probably much more convenient than searching through a repo.
