### ISSUE TITLE
'dict' attribute generates an empty Dict

### ISSUE THREAD

**Issue by Genarito** [PyO3/pyo3#2063]
### Bug Description

I am trying to support my Rust Struct to have the `__dict__` method. I am reading in [the documentation](https://pyo3.rs/v0.15.1/class.html?highlight=__dict__#customizing-the-class) that there is a `dict` parameter that adds support, but when I print the dictionary returned by the auto-generated method, it returns an empty dictionary.

### Steps to Reproduce

Rust code:

```rust
use pyo3::prelude::*;
use pyo3::types:PyTuple;

#[pyclass(module = "pickleme", dict)]
struct PickleMe {
    #[pyo3(get, set)]
    foo: Option<usize>,
}

#[pymethods]
impl PickleMe {
    #[new]
    #[args(args = "*")]
    fn new(args: &PyTuple) -> Self {
        match args.len() {
            0 => PickleMe { foo: None },
            1 => {
                if let Ok(f) = args.get_item(0).unwrap().extract::<usize>() {
                    PickleMe { foo: Some(f) }
                } else {
                    PickleMe { foo: None }
                }
            }
            _ => unreachable!(),
        }
    }
}

#[pymodule]
fn pickleme(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<PickleMe>()?;
    Ok(())
}

```

Python:

```python
import pickleme

obj = pickleme.PickleMe(33)
print(obj.__dict__)  # Prints "{}"
```

### Your operating system and version

Kubuntu 21.04

### Your Python version (`python --version`)

Python 3.9.5

### Your Rust version (`rustc --version`)

rustc 1.57.0 (f1edd0429 2021-11-29)

### Your PyO3 version

0.15.1

### How did you install python? Did you use a virtualenv?

python.org source code

**Comment by davidhewitt** [comment]
Hi @Genarito, thanks for reporting.

As far as I know, this is expected behaviour. The `dict` generated is initialised empty, with the idea that you can then fill it with arbitrary data. The native contents of the `#[pyclass]` implemented in Rust won't be in this dict - else they'd exist twice: once in the struct data and a second time inside the dict. I see the documentation is not very clear on this.

Can you elaborate what you're trying to use `__dict__` for? Maybe I can help you come up with a solution to your original problem which doesn't need it.

**Comment by birkenfeld** [comment]
This is also how types from C extensions behave. I they want to support pickling they need to define `__get/setstate__`.

**Comment by Genarito** [comment]
HI! Thank you both for your answers. In the actual project, I have already implemented `__setstate__` and `__getstate__` methods to be able to do struct pickle in parallel environments. Now I would like to add support for `__dict__` as that allows Python users to use some serialization methods. I would simply like all struct attributes to be part of the dictionary. Is there any way to achieve that?

Thanks in advance!

**Comment by Genarito** [comment]
Thanks @birkenfeld. Sorry for the ignorance, but I don't understand what would be the utility of the `dict` parameter if it generates an empty dictionary. According to the [Python documentation](https://docs.python.org/3/library/stdtypes.html#object.__dict__), `__dict__` returns the object representation, so it is intuitive to think that the Struct attributes would be added inside the dictionary. 

Regardless of that, how could I add fields inside? If I define `__dict__` method explicitly it's not automatically bound like `__str__` or `__repr__` and when I do `print(obj.__dict__)` in Python it prints `module __dict__...` instead of the dictionary representation. Maybe It could be added to [Magic Methods](https://pyo3.rs/master/class/protocols.html#magic-methods-in-pymethods)?

**Comment by birkenfeld** [comment]
The `__dict__` can be added to allow adding arbitrary attributes to the object, like you can do with all objects derived from Python classes. The Python documentation you linked is quite terse and could use some clarification: `__dict__` cannot reflect all attributes an object supports: in the case of C (and Rust) defined types, types with `__slots__`, objects with dynamic attributes with `__getattr__` or objects with descriptor class attributes (such as properties), these present additional ways to have attributes.

As for the second question, `__dict__` is not a method, it is an attribute. The method I was proposing is not predefined by Python, but it would do something like:

```
def update_dict(self):
    self.__dict__['attr_a'] = <Rust self>.attr_a
    self.__dict__['attr_b'] = <Rust self>.attr_b
```

and just be a workaround if you absolutely *need* to have `__dict__` reflect all attributes. But the better way is not to rely on `__dict__` in the first place if possible.

**Comment by Genarito** [comment]
I understand. Thank you very much for your time! 👍

**Comment by mstarodub** [comment]
(copy pasting from #123, commented there by mistake)

Hello, I'm currently in the situation of needing this. I'd like to be able to serialize classes from rust into json while maintaining control over that process, necessitating a dict representation for #[pyclass]es.

Is there any convenient way of achieving this right now?

**Comment by davidhewitt** [comment]
The best I have seen is a `to_dict()` method which creates a Python dict from the Rust state. You might be able to automate a lot of that with a helper struct which uses `#[derive(IntoPyObject)]`.
