### ISSUE TITLE
Bounds checking in Python <=3.5

### ISSUE THREAD

**Issue by pganssle** [PyO3/pyo3#208]
There are a slew of `xfail` tests in both the [`rustapi_module`](https://github.com/PyO3/pyo3/blob/master/examples/rustapi_module/tests/test_datetime.py#L73) and [`test_datetime.rs`](https://github.com/PyO3/pyo3/blob/master/tests/test_datetime.rs#L142) because the Python C API only started doing bounds checking on inputs in Python 3.6.

It *may* be that an exception is set in Python <=3.5 and it's just never actually *raised*, but I think more likely you get a malformed date/time object.

If no exception is set, I believe we should fix this by doing bounds checking ourselves on the Rust side (`objects/datetime.rs`), probably with a macro under a conditional compilation flag.

**Comment by davidhewitt** [comment]
As we're set to drop Python 3.5 support soon (either `0.12` or `0.13`) I'm marking this as `wontfix` and closing.
