### ISSUE TITLE
multiple impl blocks & generics

### ISSUE THREAD

**Issue by hiaselhans** [PyO3/pyo3#2094]
From looking through some older issues i found that generics and custom traits are not supported by pyo3.

Is that something that is on the roadmap?
or is it an "impossible" issue?
I am used to using pybind11's interface which allows for py::class_ being defined in (templated) functions, making it easy to bind existing libraries. I think there is no counterpart in pyo3 and probably this is impossible too?

EDIT: I got multiple impl blocks working by enabling the "multiple-pymethods" feature in cargo.toml
``` rust
#[pyclass]
pub struct TestPyVector {
    v: TestVector<2>
}

#[pymethods]
impl TestPyVector {
    #[new]
    pub fn __new__(v: [f64; 2]) -> PyResult<Self> { 
        Ok(Self {v: TestVector::new(v)})
    }

    pub fn dot(&self, other: &Self) -> f64 {
        let result = self.v.dot(&other.v);
        result
    }
}

#[pymethods]
impl TestPyVector {
    pub fn length(&self) -> f64 {
        self.v.length()
    }
}
```

I'm leaving the error message for other users of this library to find it in case.
```
error[E0119]: conflicting implementations of trait `pyo3::class::impl_::PyMethods<vector::TestPyVector>` for type `pyo3::class::impl_::PyClassImplCollector<vector::TestPyVector>`                 
  --> src/vector.rs:60:1
   |
47 | #[pymethods]
   | ------------ first implementation here
...
60 | #[pymethods(parent=TestPyVector)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `pyo3::class::impl_::PyClassImplCollector<vector::TestPyVector>`
```

**Comment by aviramha** [comment]
See https://pyo3.rs/v0.15.1/migration.html?highlight=inventory#new-multiple-pymethods-feature

**Comment by hiaselhans** [comment]
thanks @aviramha, actually i did open an issue for two things and found the multiple-pymethods mysefl.
I will open a new issue for the generics.
