### ISSUE TITLE
Add `in` operator method to `PyAny`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2107]
We don't have a method for `x in foo` on `PyAny`.

We have `PySequence::contains` - probably this just wants to be copied as `PyAny::contains`, with some tests to check this does behave like Python's `in` operator.

As per https://github.com/PyO3/pyo3/pull/1844#issuecomment-1002551273

**Comment by aganders3** [comment]
I'm interested to take this on!

For design purposes, the `in` keyword means two things in Python. This was kind of covered in the linked PR where there was discussion of `contains_key` but I think it was kept out. The idea here then is to use `PySequence_Contains` for `PyAny::contains`, right? Is there any need to do a check first?

**Comment by davidhewitt** [comment]
Great, thank you!

> The idea here then is to use PySequence_Contains for PyAny::contains, right? Is there any need to do a check first?

Yes, I think probably calling `PySequence_Contains` is all the implementation needs. A few tests should be able to confirm that it behaves as expected.
