### ISSUE TITLE
Add support for mappingproxy? (standard library read-only dict)

### ISSUE THREAD

**Issue by aldanor** [PyO3/pyo3#2108]
Quoting Python docs for [`vars`](https://docs.python.org/3.8/library/functions.html#vars):

> Objects such as modules and instances have an updateable `__dict__` attribute; however, other objects may have write restrictions on their `__dict__` attributes (for example, classes use a [`types.MappingProxyType`](https://docs.python.org/3.8/library/types.html#types.MappingProxyType) to prevent direct dictionary updates).

There's `pyo3::ffi::PyDictProxy_Type` and ` pyo3::ffi::PyDictProxy_New` but they are currently unused.

It's almost a copy of `PyDict`, with only these methods present: `copy`, `get`, `items`, `keys`, `values`.

This has come up while implementing structured dtypes in `rust-numpy`, where `dtype.fields` is a read-only mappingproxy dict. It could be worked around via `PyAny`, but I figured maybe I should raise it here in case there's any interest.

**Comment by davidhewitt** [comment]
Yep I think having this is very reasonable. Anyone is welcome to pick this up - should be a case of copying the relevant parts of the `PyDict` implementation to create a new type. Perhaps the hardest bit is what to call it - the C API is `PyDictProxy`, but I wonder if `PyMappingProxy` is better to reflect it's name from Python?

**Comment by aviramha** [comment]
I'll try to take it.
