### ISSUE TITLE
Usage of `ExactSizeIterator` is incorrect

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2118]
The other day, I noticed the following in the [docs for `ExactSizeIterator`](https://doc.rust-lang.org/stable/std/iter/trait.ExactSizeIterator.html):

> Note that this trait is a safe trait and as such does not and cannot guarantee that the returned length is correct. This means that unsafe code must not rely on the correctness of Iterator::size_hint. The unstable and unsafe `TrustedLen` trait gives this additional guarantee.

Unfortunately, we currently rely on the correctness of the length of `ExactSizeIterator` in `PyTuple::new` and `PyList::new` to assume that we are filling all the elements of the newly-created list (or tuple).

Instead, I guess we should track the number of elements we've inserted and the current container of the list / tuple, and then ensure that when we hit the capacity of the container we do a few things:
- For tuples, we can use `_PyTuple_Resize` to grow the allocation manually
- For lists, we probably just fall back to using `PyList_Append`

Similarly, when the iterator is exhausted we may need to shrink the allocation down so there's no uninitialized elements in the tail of the container. For tuples, this again works with `_PyTuple_Resize`. For lists, I'm not sure - we might need to fill the tail of the list with `None` for safety reasons and then slice the list to create a new list of the correct size. That seems a bit painful so maybe there's a better idea.

Unfortunately this will be a de-optimization of our tuple / list creation code, but I think it's necessary. On the upside, we can switch from `ExactSizeIterator` to just `Iterator` bound on `PyTuple::new` and `PyList::new`, allowing them to construct from more types!

If someone wants to take this on, might be a nice fun algorithmic one :)

**Comment by mejrs** [comment]
It looks like we're also leaking memory if a `ToPyObject` implementation panics. And we're not checking whether `PyList/Tuple_New` returns null.

> Unfortunately this will be a de-optimization of our tuple / list creation code

I imagine the majority of implementations start from vectors or slices, which have correct `ExactSizeIterator` implementations, and don't need this. Therefore I am inclined to just check whether `ExactSizeIterator` was truthful, and panic if it isn't.

**Comment by adamreichold** [comment]
> Therefore I am inclined to just check whether ExactSizeIterator was truthful, and panic if it isn't.

Indeed. While unsafe code cannot rely on that length being correct, I would still call it a logic bug if it is hence a panic seems more appropriate than trying to fix things up at runtime.

**Comment by davidhewitt** [comment]
I think you folks are correct, let's just add assertions and also guard against memory leaks on panics 👍

**Comment by davidhewitt** [comment]
(if anyone wants to claim this please feel welcome, otherwise I'll do it in a couple weeks time as one of the last bits before releasing 0.16)

**Comment by mejrs** [comment]
I wrote a bunch of tests we'll want :) I don't have time  to fix the implementation though, I'm really busy this weekend. 

```rust
use pyo3::prelude::*;
use pyo3::types::PyList;

use std::ops::Range;

struct FaultyIter(Range<usize>, usize);

impl Iterator for FaultyIter {
    type Item = usize;

    fn next(&mut self) -> Option<Self::Item> {
        self.0.next()
    }
}

impl ExactSizeIterator for FaultyIter {
    fn len(&self) -> usize {
        self.1
    }
}

#[test]
#[should_panic(
    expected = "Attempted to create PyList but `elements` was larger than reported by its `ExactSizeIterator` implementation."
)]
fn buffer_overrun() {
    Python::with_gil(|py| {
        let iter = FaultyIter(0..usize::MAX, 73);
        let _list = PyList::new(py, iter);
    })
}

#[test]
#[should_panic(
    expected = "Attempted to create PyList but `elements` was smaller than reported by its `ExactSizeIterator` implementation."
)]
fn get_null() {
    Python::with_gil(|py| {
        let iter = FaultyIter(0..35, 73);
        let _list = PyList::new(py, iter);
    })
}

#[test]
#[should_panic(expected = "todo")]
fn overflowing_size() {
    Python::with_gil(|py| {
        let iter = FaultyIter(0..0, usize::MAX);

        // Should cause `PyList_New` to return NULL
        let _list = PyList::new(py, iter);
    })
}

#[test]
fn bad_clone() {
    use std::sync::atomic::{AtomicUsize, Ordering::SeqCst};

    static NEEDS_DESTRUCTING_COUNT: AtomicUsize = AtomicUsize::new(0);

    #[pyclass]
    struct Bad(usize);

    impl Clone for Bad {
        fn clone(&self) -> Self {
            if self.0 == 42 {
                panic!()
            };
            NEEDS_DESTRUCTING_COUNT.fetch_add(1, SeqCst);

            Bad(self.0)
        }
    }

    impl Drop for Bad {
        fn drop(&mut self) {
            NEEDS_DESTRUCTING_COUNT.fetch_sub(1, SeqCst);
        }
    }

    impl ToPyObject for Bad {
        fn to_object(&self, py: Python) -> Py<PyAny> {
            self.to_owned().into_py(py)
        }
    }

    struct FaultyIter(Range<usize>, usize);

    impl Iterator for FaultyIter {
        type Item = Bad;

        fn next(&mut self) -> Option<Self::Item> {
            self.0.next().map(|i| {
                NEEDS_DESTRUCTING_COUNT.fetch_add(1, SeqCst);
                Bad(i)
            })
        }
    }

    impl ExactSizeIterator for FaultyIter {
        fn len(&self) -> usize {
            self.1
        }
    }

    Python::with_gil(|py| {
        let _ = std::panic::catch_unwind(|| {
            let iter = FaultyIter(0..50, 50);
            let _list = PyList::new(py, iter);
        });
    });

    assert_eq!(
        NEEDS_DESTRUCTING_COUNT.load(SeqCst),
        0,
        "Some destructors did not run"
    );
}
```

**Comment by mejrs** [comment]
> you folks are correct, let's just add assertions and also guard against memory leaks on panics 👍

We can do a "clever" implementation that doesn't need `ExactSizeIterator` and also have an optimized impl using `TrustedLen`, if (ever) that hits stable.
