### ISSUE TITLE
Unify GILGuard and Python

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#213]
Currently, there a two types: `GILGuard` and `Python`, where `GILGuard` carries data and has a Drop implementation, while `Python` is a zero sized marked type. This leads to the following boilerplate all over the code:

```rust
let gil = Python::acquire_gil();
let py = gil.python();
```

We should unify those two types, so that we can just write

```rust
let gil = GIL::acquire();
```

and then use the `gil` just like the `py` now.

**Comment by fafhrd91** [comment]
I don’t think this is possible. Also acquire is rare for extensions

**Comment by joar** [comment]
Just to add a datapoint, I use acquire quite a lot in https://github.com/joar/rust-csv-py

**Comment by kngwyu** [comment]
@joar 
Since acquiring gil can be overhead(though it's not so large), I recommend to use `self.token.py()` when it's possible(e.g. [here](https://github.com/joar/rust-csv-py/blob/c4e010aa900bbb9c432d2b6c778e4dc46a643564/src/writer.rs#L58)).

**Comment by kngwyu** [comment]
If we remove `Python<'p>(PhantomData<&'p GILGuard>)`, then we have to pass `&'py GILGuard`  to functions, instead of `Python<'p>`.
So... I don't feel ↑this model much more useful and convenient than current API.  It's same as what we do now.

**Comment by konstin** [comment]
I'd rather like to remove PyToken completely (see #94).

For the GILGuard vs. Python story I thought about using things like Deref or a Python type that hides the GILGuard internally, but I haven't found a good design yet.

**Comment by kngwyu** [comment]
I see.
Yeah I feel like `PyToken` is not 'the best' approach, but have no better ides now :thinking:

**Comment by davidhewitt** [comment]
I think that most users will use the new `Python::with_gil` API, so I'm not sure that any changes here are really necessary.

As a result I'm going to close this issue, but please shout if anyone thinks this still needs to happen and we can reopen.
