### ISSUE TITLE
PyBuffer support with limited ABI in py3.11+

### ISSUE THREAD

**Issue by alex** [PyO3/pyo3#2139]
Starting with https://github.com/python/cpython/commit/f66c857572a308822c70fd25e0197b6e0dec6e34 (landed about 5 minutes ago) PyBuffer is supported in the limited ABI. Once py3.11 ships, it'd be great if pyo3 took advantage of this!

**Comment by davidhewitt** [comment]
I think definitely once the next alpha gets released and it's running on Github actions, we can then start testing with it 👍
