### ISSUE TITLE
How to return a python object from a rust function?

### ISSUE THREAD

**Issue by astrojhgu** [PyO3/pyo3#214]
According to the document, I know:
1. A struct can be returned by a rust function in python if it implements ```IntoPyObject```
2. A struct that has a ```PyToken``` member and attached with a #[pyclass] property can auto impl ```IntoPyObject```
3. PyToken cannot be created in rust for its ```new``` is private.

So If I want to return a struct from a rust function in python, I have to implement ```IntoPyObject``` myself.

But I didn't find any example about how to impl a ```IntoPyObject``` by hand or is there any more easy way to do this? All examples about returning something from a rust function are about primitive types: e.g., PyResult<()>, PyResult<i32>. How could I write a function in rust like:
```
#[pyclass]
struct MyOjb{
...
}

#[pyfunction]
pub fn get_obj()->PyResult<MyObj>{
...
}
```
Thanks.

**Comment by konstin** [comment]
On master `IntoPyObject` is implemented for all `#[pyclass]` structs. It uses the following code:

```rust
impl ::pyo3::IntoPyObject for #cls {
    fn into_object(self, py: ::pyo3::Python) -> ::pyo3::PyObject {
        ::pyo3::Py::new(py, |_| self).unwrap().into_object(py)
    }
}
```

On 0.4.1, you could e.g. just use the `pyo3::Py::new(py, |_| self).unwrap().into_object(py)` part and return a `PyObject` instead of `MyObj`.
