### ISSUE TITLE
associated function `new` is private

### ISSUE THREAD

**Issue by elbaro** [PyO3/pyo3#2168]
### Bug Description

When `multiple-pymethods` is enabled, it does not compile because
Pyo3MethodsInventoryFor[MyClassName]::new is private

### Steps to Reproduce

```
#[pyo3::pyclass]
#[derive(Clone, Debug)]
pub struct Client {
..
}
```
features = [
    "extension-module",
    "multiple-pymethods",
]

expands to

```py
...
#[doc(hidden)]
    pub struct Pyo3MethodsInventoryForClient {
        items: _pyo3::impl_::pyclass::PyClassItems,
    }
    impl Pyo3MethodsInventoryForClient {
        const fn new(items: _pyo3::impl_::pyclass::PyClassItems) -> Self {
            Self { items }
        }
    }
    impl _pyo3::impl_::pyclass::PyClassInventory for Pyo3MethodsInventoryForClient {
        fn items(&self) -> &_pyo3::impl_::pyclass::PyClassItems {
            &self.items
        }
    }
    _pyo3::inventory::collect!(Pyo3MethodsInventoryForClient);
...
```

I had to manually paste the expanded code and change `const fn new` to `pub const fn new`

### Your operating system and version

.

### Your Python version (`python --version`)

.

### Your Rust version (`rustc --version`)

.

### Your PyO3 version

rev = "3ed0df1169f43d28c493fdbd485d24feb4e00782"

### How did you install python? Did you use a virtualenv?

.

**Comment by mejrs** [comment]
Can you show more code please? That is not enough to reproduce it.

**Comment by elbaro** [comment]
Here is a reproduce:
https://github.com/elbaro/pyo3-2168

**Comment by mejrs** [comment]
Thanks, that reproduces it for me :)

**Comment by mejrs** [comment]
https://github.com/PyO3/pyo3/pull/2169 should fix this
