### ISSUE TITLE
Maturin creates empty module

### ISSUE THREAD

**Issue by swizzard** [PyO3/pyo3#2179]
### Bug Description

When using maturin to create a python module, the module compiles but is empty.

### Steps to Reproduce

1. Create a new folder
2. Create a virtualenv in the folder
3. Create a new crate in the folder, following the setup instructions
4. Activate the virtual environment
5. Call `maturin develop -m $crate/Cargo.toml`
6. Start a python shell
7. Import $crate, see that the functions you added to the module aren't there

### Your operating system and version

Ubuntu 20.04.3 LTS

### Your Python version (`python --version`)

Python 3.8.10

### Your Rust version (`rustc --version`)

rustc 1.58.0 (02072b482 2022-01-11)

### Your PyO3 version

0.15.1

### How did you install python? Did you use a virtualenv?

`virtualenv venv`

**Comment by swizzard** [comment]
See https://github.com/swizzard/pyo for a minimal reproduction.

**Comment by adamreichold** [comment]
I tried to reproduce the issue using Python 3.8.12 and Rust 1.61.0-nightly on OpenSUSE Tumbleweed and could not. (I tried both creating a new crate using `maturin init --bindings pyo3 p` and closing your minimal example.) Could you maybe post some more information on how the imported module looks?

**Comment by swizzard** [comment]
@adamreichold 
```
samraker@system76-pc ~/rust-stuff/pyo 🦇» python
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import p
>>> dir(p)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by davidhewitt** [comment]
Is this just because the cwd you're running Python from is the folder containing the `p` directory, and so Python's just importing that directory as an implicit package?

**Comment by swizzard** [comment]
@davidhewitt if i start python within the `p` directory, I get an error importing `p`. `p` doesn't have an `__init__.py` in it, though, so I'm not sure how "importing [it] as an implicit package" would work.

**Comment by davidhewitt** [comment]
Since [PEP 420](https://www.python.org/dev/peps/pep-0420/#specification) implicit namespace packages don't need an `__init__.py`.

Can you share the error when you try to import `p` from within the `p` directory? (The virtualenv was definitely activated?)

**Comment by adamreichold** [comment]
> Is this potentially because the cwd you're running Python from is the folder containing the p directory, 

This I can  reproduce, if `maturin develop -m p/Cargo.toml` has not completed or the virtualenv is not activated, I can `import p` from the repository root, i.e. the `pyo` folder, and are presented with an empty module.

@swizzard Could you run `which python` before starting the Python shell to see whether the interpreter is taken from the virtualenv? (The prompt does not have the usual adornment with the virtualenv name.)

**Comment by swizzard** [comment]
oh _weird_, even though i had activated the virtualenv, `which python` was still pointing to `/usr/bin/python`, so @davidhewitt was 100% correct about the implicit package thing. thanks for the help!
