### ISSUE TITLE
Throw exception on item and attribute annotations on tuple struct

### ISSUE THREAD

**Issue by ricohageman** [PyO3/pyo3#2185]
Quick question on this: should we be allowing `#[pyo3(item)]` here? Is there any reasonable interpretation beside the elements always being item 0, item 1, item 2 etc? 

I wonder if we want to consider throwing an error if `#[pyo3(item)]` or `#[pyo3(attribute)]` are used on tuple struct elements.

_Originally posted by @davidhewitt in https://github.com/PyO3/pyo3/pull/2181#discussion_r814210259_

**Comment by davidhewitt** [comment]
Thanks, looks like that is indeed the case. The error message I introduced is perhaps not the greatest (could say something about `item` or `attribute` rather than getter?), however it's good enough to say this is done.
