### ISSUE TITLE
Incorrect #[cfg] before PyEval_InitThreads breaks Python::acquire_gil() in standalone scripts on <= 3.6

### ISSUE THREAD

**Issue by joar** [PyO3/pyo3#219]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Ubuntu 18.04
 - Your python version: Python 3.6 in this case
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:
   - Python is installed via apt.
   - I use python's `venv`.
 - Your rust version (`rustc --version`): `rustc 1.30.0-nightly (2d4e34ca8 2018-09-09)`

### 💥 Reproducing

Check out the code in the fork at https://github.com/joar/pyo3/tree/bug/pyeval-threadsnotinitialized/examples/verify_gil.

`cd examples/verify_gil`

if you haven't already

```console
$ python -VV
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

$ python setup.py develop
[...]

$ cat ../../target/debug/build/pyo3-4833970e0e0d17d0/output
cargo:rustc-cfg=Py_3_5
cargo:rustc-cfg=Py_3_6
cargo:rustc-cfg=Py_3
cargo:rustc-cfg=py_sys_config="WITH_THREAD"
cargo:python_flags=FLAG_WITH_THREAD=1,CFG_Py_3_5,CFG_Py_3_6
cargo:rerun-if-env-changed=LD_LIBRARY_PATH
cargo:rerun-if-env-changed=PATH
cargo:rerun-if-env-changed=PYTHON_SYS_EXECUTABLE
cargo:rerun-if-env-changed=LIB

$ python naked-script.py
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', src/pythonrun.rs:42:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
fish: “python naked-script.py” terminated by signal SIGABRT (Abort)
```

*Note:* Importing the script via ipython still works. I supect that is because some other extension that ipython uses calls `PyEval_InitThreads`.

### :tada: Solution?

It think that [`#[cfg(py_sys_config = "WITH_THREAD")]`](https://github.com/PyO3/pyo3/blob/9405ffa3b9f14284697e2a7339fcd97c31e35d33/pyo3-derive-backend/src/module.rs#L30-L31) always is false even if `build.rs` sets `cargo:rustc-cfg=py_sys_config="WITH_THREAD"`. I think the solution might be to just change to `#[cfg(not(Py_3_7))]`.

**Comment by joar** [comment]
Actually, the issue is probably that the `--cfg` from `pyo3` aren't set for the `pyo3-derive-backend` crate.

Although it seems like Python 3.7 survives a call to `PyEval_InitThreads` in my case.

**Comment by konstin** [comment]
Thank you for this great bug report! The problem is indeed that the cfg isn't set. (The code that is called is part of the generated code for the `#[pymodule]`, so it's in the verify-gil crate rather than in the backend, but the point stands either way).

Python 3.7 works because of
