### ISSUE TITLE
Python modules fails to load on Python < 3.8 since pyo3 0.16.0

### ISSUE THREAD

**Issue by brmmm3** [PyO3/pyo3#2214]
### Bug Description

Since pyo3 0.16.0 I get the following error message on Python version older than 3.9 (I've tried 3.8 and 3.7) when I try to import the created Python module:
E   ImportError: scandir_rs.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyCMethod_New

I've also tried pyo3 0.16.1. Same error.

Python version 3.9 and 3.10 work as expected.

### Steps to Reproduce

Build Python module with maturin.
Try to import Python module.

### Your operating system and version

Kubuntu 21.10

### Your Python version (`python --version`)

3.7, 3.8, 3.9, 3.10

### Your Rust version (`rustc --version`)

rustc 1.61.0-nightly (68369a041 2022-02-22)

### Your PyO3 version

0.16.1

### How did you install python? Did you use a virtualenv?

I'm using pyenv

**Comment by davidhewitt** [comment]
Hmm can you try building with your problematic Python 3.8 and `PYO3_PRINT_CONFIG=1` environment variable set?

**Comment by brmmm3** [comment]
Interesting. When I run it with PYO3_PRINT_CONFIG=1 then pyo3-ffi fails. Without this it succeeds to build.

user@machine:~/Rust/scandir-rs$ PYO3_PRINT_CONFIG=1 ./build_wheel_3.8.sh 
Requirement already satisfied: pip in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (22.0.3)
Requirement already satisfied: pytest in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (7.0.1)
Requirement already satisfied: iniconfig in /home/user/.local/lib/python3.8/site-packages (from pytest) (1.0.0)
Requirement already satisfied: attrs>=19.2.0 in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from pytest) (21.4.0)
Requirement already satisfied: py>=1.8.2 in /home/user/.local/lib/python3.8/site-packages (from pytest) (1.9.0)
Requirement already satisfied: tomli>=1.0.0 in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from pytest) (2.0.1)
Requirement already satisfied: packaging in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from pytest) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/user/.local/lib/python3.8/site-packages (from pytest) (0.13.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from packaging->pytest) (3.0.7)
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python3.8
📦 Built source distribution to /home/user/Rust/scandir-rs/build/wheels/scandir_rs-0.9.7.tar.gz
   Compiling pyo3-ffi v0.16.1
error: failed to run custom build command for `pyo3-ffi v0.16.1`

Caused by:
  process didn't exit successfully: `/home/user/Rust/scandir-rs/build/release/build/pyo3-ffi-3758c6086265fb66/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_PRINT_CONFIG

  -- PYO3_PRINT_CONFIG=1 is set, printing configuration and halting compile --
  implementation=CPython
  version=3.9
  shared=true
  abi3=false
  lib_name=python3.9
  lib_dir=/usr/lib/x86_64-linux-gnu
  executable=/usr/bin/python3
  pointer_width=64
  build_flags=
  suppress_build_script_link_lines=false
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release -- -C link-arg=-s`
Processing ./build/wheels/scandir_rs-0.9.7-cp38-cp38-manylinux1_x86_64.whl
Installing collected packages: scandir-rs
  Attempting uninstall: scandir-rs
    Found existing installation: scandir-rs 0.9.7
    Uninstalling scandir-rs-0.9.7:
      Successfully uninstalled scandir-rs-0.9.7
Successfully installed scandir-rs-0.9.7
================================================================================= test session starts ==================================================================================
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-0.13.1
rootdir: /home/user/Rust/scandir-rs
collected 0 items / 1 error                                                                                                                                                            

======================================================================================== ERRORS ========================================================================================
________________________________________________________________________ ERROR collecting tests/test_scandir.py ________________________________________________________________________
ImportError while importing test module '/home/user/Rust/scandir-rs/tests/test_scandir.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_scandir.py:8: in <module>
    import scandir_rs as scandir
E   ImportError: /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scandir_rs.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyCMethod_New
=============================================================================== short test summary info ================================================================================
ERROR tests/test_scandir.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================== 1 error in 0.11s ===================================================================================
user@machine:~/Rust/scandir-rs$ ./build_wheel_3.8.sh 
Requirement already satisfied: pip in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (22.0.3)
Requirement already satisfied: pytest in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (7.0.1)
Requirement already satisfied: tomli>=1.0.0 in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from pytest) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from pytest) (21.4.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/user/.local/lib/python3.8/site-packages (from pytest) (0.13.1)
Requirement already satisfied: py>=1.8.2 in /home/user/.local/lib/python3.8/site-packages (from pytest) (1.9.0)
Requirement already satisfied: iniconfig in /home/user/.local/lib/python3.8/site-packages (from pytest) (1.0.0)
Requirement already satisfied: packaging in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from pytest) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages (from packaging->pytest) (3.0.7)
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python3.8
📦 Built source distribution to /home/user/Rust/scandir-rs/build/wheels/scandir_rs-0.9.7.tar.gz
   Compiling pyo3-ffi v0.16.1
   Compiling pyo3 v0.16.1
   Compiling scandir-rs v0.9.7 (/home/user/Rust/scandir-rs)
    Finished release [optimized] target(s) in 18.78s
📦 Built wheel for CPython 3.8 to /home/user/Rust/scandir-rs/build/wheels/scandir_rs-0.9.7-cp38-cp38-manylinux1_x86_64.whl
Processing ./build/wheels/scandir_rs-0.9.7-cp38-cp38-manylinux1_x86_64.whl
Installing collected packages: scandir-rs
  Attempting uninstall: scandir-rs
    Found existing installation: scandir-rs 0.9.7
    Uninstalling scandir-rs-0.9.7:
      Successfully uninstalled scandir-rs-0.9.7
Successfully installed scandir-rs-0.9.7
================================================================================= test session starts ==================================================================================
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-0.13.1
rootdir: /home/user/Rust/scandir-rs
collected 0 items / 1 error                                                                                                                                                            

======================================================================================== ERRORS ========================================================================================
________________________________________________________________________ ERROR collecting tests/test_scandir.py ________________________________________________________________________
ImportError while importing test module '/home/user/Rust/scandir-rs/tests/test_scandir.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_scandir.py:8: in <module>
    import scandir_rs as scandir
E   ImportError: /home/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scandir_rs.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyCMethod_New
=============================================================================== short test summary info ================================================================================
ERROR tests/test_scandir.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================================================================== 1 error in 0.12s ===================================================================================
user@machine:~/Rust/scandir-rs$

**Comment by adamreichold** [comment]
> When I run it with PYO3_PRINT_CONFIG=1 then pyo3-ffi fails.

This is intentional, so that the result will actually be printed (instead of captured and hidden if the build continues without errors as in this case), c.f. https://github.com/PyO3/pyo3/blob/main/pyo3-ffi/build.rs#L109-115

I think the main question is why pyo3-build-config does not seem to pick up the Python interpreter set up by pyenv:

```
-- PYO3_PRINT_CONFIG=1 is set, printing configuration and halting compile --
implementation=CPython
version=3.9
shared=true
abi3=false
lib_name=python3.9
lib_dir=/usr/lib/x86_64-linux-gnu
executable=/usr/bin/python3
pointer_width=64
build_flags=
suppress_build_script_link_lines=false
```

**Comment by davidhewitt** [comment]
> I think the main question is why pyo3-build-config does not seem to pick up the Python interpreter set up by pyenv:

This. @brmmm3 can you start by showing us the output of `which python3` and `which python`?

You could also try using the `PYO3_PYTHON` environment variable to force usage of a particular interpreter.

**Comment by walksanatora** [comment]
can you give a example build command please as idk where i should point it to
(my project fails with the error `libpython3.8.so.1.0: cannot open shared object file: No such file or directory`)

**Comment by walksanatora** [comment]
(and note `which python` points to `/usr/bin/python3` which in turn points to `/usr/bin/python3.9`)

**Comment by davidhewitt** [comment]
@walksanatora how about `PYO3_PYTHON=/usr/bin/python3` ?

If you're trying deliberately to link against some custom installed `libpython3.8` you may need to use `LD_LIBRARY_PATH` to set the interpreter location.

**Comment by brmmm3** [comment]
@davidhewitt `which python3`and `which python` return:
/home/user/.pyenv/shims/python3
/home/user/.pyenv/shims/python

When I set `PYO3_PYTHON=/home/user/.pyenv/shims/python3` I get:
error: failed to run custom build command for `pyo3-ffi v0.16.1`

Caused by:
  process didn't exit successfully: `/home/user/Rust/pgrep/target/release/build/pyo3-ffi-3758c6086265fb66/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_PRINT_CONFIG

  -- PYO3_PRINT_CONFIG=1 is set, printing configuration and halting compile --
  implementation=CPython
  version=3.8
  shared=false
  abi3=false
  lib_name=python3.8
  lib_dir=/home/user/.pyenv/versions/3.8.12/lib
  executable=/home/user/.pyenv/versions/3.8.12/bin/python3
  pointer_width=64
  build_flags=
  suppress_build_script_link_lines=false
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release -- -C link-arg=-s`
WARNING: Requirement 'build/pgreplib/wheels/pgreplib-0.1.0-cp38-cp38-manylinux1_x86_64.whl' looks like a filename, but the file does not exist

**Comment by davidhewitt** [comment]
@brmmm3 can you try with `PYO3_PYTHON` set and `PYO3_PRINT_CONFIG` unset?

**Comment by walksanatora** [comment]
@davidhewitt mine still does not build with the command `PYO3_PYTHON=/usr/bin/python3 cargo build --release` and when i run it  I get the `libpython3.8.so.1.0: cannot open shared object file: No such file or directory` error again

**Comment by davidhewitt** [comment]
@walksanatora did you follow this step of the README (or similar if you're running a different distro to Ubuntu):

> To install the Python shared library on Ubuntu:
> 
> ```
> sudo apt install python3-dev
> ```

**Comment by walksanatora** [comment]
@davidhewitt it is most definetly installed
![image](https://user-images.githubusercontent.com/47339836/157681728-e047dc09-35de-4f73-b86b-1d27f2daf98c.png)

**Comment by walksanatora** [comment]
and yes even the normal python3-dev 
![image](https://user-images.githubusercontent.com/47339836/157681945-12fec4b1-d480-44ea-8db0-019eafe4e906.png)

**Comment by davidhewitt** [comment]
@walksanatora can you list full set of commands you're running including all the output?

**Comment by walksanatora** [comment]
never mind, i just figured out that it was because i forgot to sym-link the .so to the same folder as the python script so it was trying to use a old version.

**Comment by davidhewitt** [comment]
👍 would fully recommend using `maturin` to avoid pain like that!

**Comment by davidhewitt** [comment]
As I believe the problem has been resolved and this issue has been quiet for a couple months, will close this now.
