### ISSUE TITLE
Documentation on building muslinux wheels with cibuildwheel

### ISSUE THREAD

**Issue by adriangb** [PyO3/pyo3#2215]
Continuing the discussion from https://github.com/pypa/cibuildwheel/issues/1038

<details>
<summary>A dump of Gitter conversations</summary>

Adrian Garcia Badaracco @adriangb 10:30
Hi folks, I am having trouble building some wheels with the 0.16.0 release. This release dropped support for Rust < 1.48, but cibuildwheel / pypa manylinux images are Alpine 3.12 which ships with Rust 1.44. This means that it is a mess to build those wheels now. Does anyone have any solutions to this? Some relevant discussions: pypa/cibuildwheel#1038, pypa/manylinux#1225

mejrs @mejrs 12:25
You can use pyo3 0.15

Adrian Garcia Badaracco @adriangb 12:28
Yes but I don't think that's a long term solution right?
(a good long terms solution)
And this isn't specific to my project / my situation (I've already worked around it by skipping those wheels), it seems like it'll be a problem for the ecosystem given that providing pre-built wheels is recommended and that cibuildwheel is the recommended way to do that and that the latest pyo3 release is partially incompatible with cibuildwheel.

mejrs @mejrs 12:56
I mean, the proper solution would be for people to stop using/upgrade tools that are years out of date
Our policy is that we support (at least) the Rust that is shipped with current alpine distributions

Adrian Garcia Badaracco @adriangb 12:59
I don't disagree with that policy. But it seems like it conflicts with the pypa's policy, which makes it problematic for the ecosystem even if it is the right policy to have.

mejrs @mejrs 13:02
What is pypa's policy on this?
I figured this was just a case of "nobody has bothered updating the rust version" but I don't actually know

Adrian Garcia Badaracco @adriangb 13:03
Well from the links it seems that they don't want to update to Alpine 3.14 because that ships with musllinux_1_2 which would cause fragmentation and more binaries on PyPi. I guess. To be honest the whole muslinux wheels thing is quite confusing to me so I may be interpreting it wrong.
This conversation to be specific: pypa/manylinux#1225
That conversation is not related to Rust versions but rather other reasons to upgrade to Alpine 3.14, and the conclusion was "we don't want to do that". Again, I may be misinterpreting so please read it for yourself.

mejrs @mejrs 13:20
I don't understand how this isn't cibuildwheel's problem for running old images

Adrian Garcia Badaracco @adriangb 13:58
I don't think this is anyone's "problem" per se. If you believe the solution is for them to update the images, then we should propose that to them (to pypa not cibuildwheel) with a clear use case (PyO3 needs to be able to build wheels).
I already proposed that here: pypa/cibuildwheel#1038
And my understanding of the answer was "that's a PyO3 problem".
I am not a maintainer of PyPa, PyO3 neither am I knowledgable about the internals of either, so I don't think I am in a place to further this request.
I am simply presenting what I believe to be an ecosystem problem catalyzed by the PyO3 0.16.0 release (again, I'm not saying anything is right or wrong here, just that as a user of PyO3 and of cibuildwheel/pypa images the current status quo is problematic as of the 0.16.0 release).

David Hewitt @davidhewitt 16:08
Hmm @adriangb that is a bit unfortunate. I'm not sure exactly what the right answer is. In theory it's likely possible to use a newer Rust compiler on Alpine 3.12 using e.g. rustup for the installation. I'll have to investigate how feasible this is vs. downgrading PyO3.

Adrian Garcia Badaracco @adriangb 16:18
Yeah, in theory. But throw the cross arch wheel building in there (rustup doesn't work) and I, personally, am lost as to how to get it working
But if you can figure out how to install a newer rust compiler, all you'd need to do is build a docker image and publish it since cibuildwheel lets you specify an image to use

David Hewitt @davidhewitt 17:26
why doesn't rustup work for the cross-arch wheel building?
Also maybe @messense has some insight on this problem? They have a huge amount of knowledge about all the packaging options out there.

Adrian Garcia Badaracco @adriangb 17:29
I tried just running rustup in the image and got:
rustup: installer for platform 'i686-unknown-linux-musl' not found, this may be unsupported
Again my solution was to just skip building wheels for that arch since I have 0 users for that arch, but that's not ideal, if nothing else because it requires extra configuration of cibuildwheel which sort defeats the purpose of having an easily pre-packaged solution to build all of the wheels.

David Hewitt @davidhewitt 17:31
Hmm, I see. Are you using maturin or setuptools-rust? You might want to look at maturin_action in the short term, however I think we should also aim to support cibuildwheel for sure.
Oh, maybe that doesn't support musllinux...

Adrian Garcia Badaracco @adriangb 17:32
I am using maturin. I haven't looked into either of those two workflows, and tbh I probably wont unless someone comes asking for those wheels, just want to be honest 

</details>

**Comment by messense** [comment]
Building musllinux wheels using maturin-action is quite easy if your Rust crate doesn't link to external shared libraries. Here is a GitHub Actions workflow example: https://github.com/messense/rjieba-py/blob/f2e89d282ddfacfc76e4ab7f81aaa97c0c38db76/.github/workflows/CI.yml#L145-L217

**Comment by messense** [comment]
Right now the musllinux policies are very conservative, only `libc` and `libz` can be dynamically link without bundling, other dynamic libraries, for example even `libgcc_s` requires bundling within the wheel.

Thus for pyo3 based abi3 wheels, as long as you don't link to external shared libraries that are not part of the gcc sysroot, cross compiling is easy since building abi3 wheels doesn't require Python interpreters. But for non-abi3 wheels, you'd need to compile or download some target Python interpreters which is inconvenient. 

In the future, https://github.com/PyO3/maturin/issues/796#issuecomment-1030739971 should help with this situation.

**Comment by adriangb** [comment]
@messense  helped me out in #6 and I was able to move my CI over to their GitHub Action, which works A LOT better than cibuildwheel, at least for my project which has no external libs and is building abi3 wheels.

Browsing through the maturing docs again, I see that the action is listed. I guess I missed it the first time around. I'm going to comment on the original cibuildwheel ticket and see if they'd be willing to put a note on their docs that for PyO3 rust packages this is an alternative. But I don't think there's anything else left to do on the PyO3 / maturin side 😄
