### ISSUE TITLE
Cannot run tests with the abi3 feature.

### ISSUE THREAD

**Issue by mejrs** [PyO3/pyo3#2219]
### Bug Description

When I run pyo3's tests, I can't run tests with the abi3 feature

### Steps to Reproduce

cargo test --features=abi3

### Backtrace

```shell
Finished test [unoptimized + debuginfo] target(s) in 2m 38s
     Running unittests (target\debug\deps\pyo3-47fd354bc7aaab3c.exe)
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `C:\Users\bruno\rust\pyo3\target\debug\deps\pyo3-47fd354bc7aaab3c.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```

### Your operating system and version

Windows 10

### Your Python version (`python --version`)

Python 3.10.2

### Your Rust version (`rustc --version`)

rustc 1.58.1 (db9d1b20b 2022-01-20)

### Your PyO3 version

0.16

### How did you install python? Did you use a virtualenv?

downloaded from python.org

### Additional Info

I'm always getting incremental compilation failures, e.g. "warning: Error finalizing incremental compilation session directory `\\?\C:\Users\bruno\Rust\pyo3\target\debug\incremental\test_wrap_pyfunction_deduction-30s32wv9zkd0t\s-g7rdsrec4r-1f5oeza-working`: Access is denied. (os error 5)"

**Comment by davidhewitt** [comment]
Weird.
- Does a `cargo clean` fix it?
- For the incremental errors, do you have antivirus software scanning the target dir?

**Comment by mejrs** [comment]
> Does a cargo clean fix it?

No

> For the incremental errors, do you have antivirus software scanning the target dir?

I ignore my target dirs, so i don't think so.

**Comment by davidhewitt** [comment]
Hmmm strange. I just retested on my Windows box and I can't reproduce this. Try updating to Rust 1.59? I'd be suprised if that fixed it though.

Otherwise, I'm not really sure what else to suggest...

**Comment by mejrs** [comment]
I ran it in Dependency Walker and it turned out it was linking to a `python3.dll` and `python38.dll` in `C:\Program Files\Amazon\AWSCLIV2`. I deleted those and now it works 🥲
