### ISSUE TITLE
"assertion failed: `(left != right)`" when initializing module

### ISSUE THREAD

**Issue by msanders** [PyO3/pyo3#223]
### 🌍 Environment

 - macOS High Sierra
 - Your python version: 3.6 & 3.5
 - Python installation method: pyenv
 - Rust version: rustc 1.30.0-nightly (28bcffead 2018-09-01)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`Yes, 0.4.1 

### 💥 Reproducing

Hi, I'm running into the following assertion when compiling a module built via [cibuildwheel](https://github.com/joerick/cibuildwheel) using pyo3:

```
~ $ env RUST_BACKTRACE=1 pip uninstall -y autopy; and pip install --index-url https://test.pypi.org/simple/ autopy==1.0.1.dev48; and python -c 'import autopy'
Uninstalling autopy-1.0.1.dev48:
  Successfully uninstalled autopy-1.0.1.dev48
Looking in indexes: https://test.pypi.org/simple/
Collecting autopy==1.0.1.dev48
  Using cached https://test-files.pythonhosted.org/packages/90/63/2df192feed68c4c923f130f317fe94c0a5be79301b9a913e7659481f60e9/autopy-1.0.1.dev48-cp35-cp35m-macosx_10_6_intel.whl
Installing collected packages: autopy
Successfully installed autopy-1.0.1.dev48
thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.4.1/src/pythonrun.rs:42:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
fish: 'and python -c 'import autopy'' terminated by signal SIGABRT (Abort)
```

This only happens on 3.5 and 3.6, but not 3.7 or 2.7. Any ideas on what the cause might be?

**Comment by konstin** [comment]
This looks another instance of #219. Could you try latest master?

**Comment by msanders** [comment]
Thanks for the help @konstin, looks like that fixed it. When do you think the next release will be published?

**Comment by konstin** [comment]
Not to soon. There are bunch of breaking changes already, so release has to be a new minor version (0.5.0) and I'd like to get fixed #94 and #210 before publishing that. I could publish a prerelease though; That would still allow publishing on crates.io.

**Comment by msanders** [comment]
A prerelease would be great, actually. Hoping to get a new version of my library out that depends on PyO3.

**Comment by konstin** [comment]
Done: https://crates.io/crates/pyo3/0.5.0-alpha.1 (Got the releasing procedure right on the first try :tada: )
