### ISSUE TITLE
`from_py_with` doesn't seem to play nicely with optional arguments

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#2280]
### Bug Description

When trying to build optional arguments, using `from_py_with` I'm getting 

```
expected struct `InnerType`, found enum `Option`
```

### Steps to Reproduce

```rs

fn build_regex(obj: &PyAny) -> PyResult<Option<Regex>> {
    if obj.is_none() {
        Ok(None)
    } else {
        let regex_str: &str = obj.extract()?;
        let regex = Regex::new(regex_str).map_err(|e| PyValueError::new_err(e.to_string()))?;
        Ok(Some(regex))
    }
}

#[pyfunction]
pub fn regex_match(
    str: String,
    #[pyo3(from_py_with = "build_regex")] pattern: Option<Regex>,
) -> PyResult<bool> {
    if let Some(pattern) = pattern {
        if !pattern.is_match(&str) {
            return Ok(false);
        }
    }
    Ok(true)
}
```

(I know in this case I could build the regex inside `regex_match` but in practice I want to be able to call `regex_match` from other code with a pre-compiled regex.

### Backtrace

```shell
error[E0308]: mismatched types
  --> src/validators.rs:36:52
   |
36 |     #[pyo3(from_py_with = "build_regex")] pattern: Option<Regex>,
   |                                                    ^^^^^^ expected struct `regex::Regex`, found enum `Option`
   |
   = note: expected struct `regex::Regex`
                found enum `Option<_>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `pydantic-core` due to previous error
```
```


### Your operating system and version

MacOS 12.2.1

### Your Python version (`python --version`)

3.10.4

### Your Rust version (`rustc --version`)

rustc 1.59.0 (9d1b2106e 2022-02-23)

### Your PyO3 version

`{version = "0.16.3", features = ["extension-module"]}`

### How did you install python? Did you use a virtualenv?

pyenv, yes

### Additional Info

_No response_

**Comment by adamreichold** [comment]
Did you try just removing the `obj.is_none()` check from `build_regex` and changing its return type to `PyResult<Regex>` and letting the '#[pyfunction]` macro handle the `Option<_>` layer?

**Comment by adamreichold** [comment]
> in practice I want to be able to call regex_match from other code with a pre-compiled regex.

I am not sure if this works like you intend it to as `FromPyObject` or `from_py_with` will always compile a `Regex` from a string passed by Python. If you want Python code to be able to pass in a pre-compiled regular expression, you probably need to wrap it using  `#[pyclass]`.

**Comment by davidhewitt** [comment]
Just as a thought here, I suspect there's some undocumented interaction occurring between `from_py_with` and how the macros transform `Option<T>` function arguments. Probably the `from_py_with` function needs to take `Option<&PyAny>`.

I've commented before in #2193 how I would be keen to rethink the implicit `None` defaults and optionality with `Option<T>` arguments. This is an edge case we should keep in mind.
