### ISSUE TITLE
Panic in build script when building with `cibuildwheel` on windows 32-bit

### ISSUE THREAD

**Issue by Askaholic** [PyO3/pyo3#2303]
### Bug Description

I encountered the following error when trying to build my project with cibuildwheel 2.4.0 on windows 32 bit, after upgrading from pyo3 0.14 to 0.16.3. Wheels for 32-bit linux and macos seem to be building just fine.

```
thread 'main' panicked at 'failed to parse PyO3 config: Error { value: "expected key=value pair on line 7", source: None }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\pyo3-build-config-0.16.3\src\lib.rs:94:10
```

I could be wrong, but it looks to me as if the build script is failing to read a config file that was automatically produced by pyo3, so whatever code is generating that config script may have a bug.

The github actions run is here: https://github.com/Askaholic/faf-replay-parser-python/runs/5964311969?check_suite_focus=true

### Steps to Reproduce

See GitHub actions workflow log: https://github.com/Askaholic/faf-replay-parser-python/runs/5964311969?check_suite_focus=true

### Backtrace

```shell
Running `D:\a\faf-replay-parser-python\faf-replay-parser-python\target\release\build\pyo3-95bac919b5a4dff3\build-script-build`
    error: failed to run custom build command for `pyo3 v0.16.3`
    
    Caused by:
      process didn't exit successfully: `D:\a\faf-replay-parser-python\faf-replay-parser-python\target\release\build\pyo3-95bac919b5a4dff3\build-script-build` (exit code: 101)
      --- stderr
      thread 'main' panicked at 'failed to parse PyO3 config: Error { value: "expected key=value pair on line 7", source: None }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\pyo3-build-config-0.16.3\src\lib.rs:94:10
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    cargo rustc --lib --manifest-path Cargo.toml --target i686-pc-windows-msvc --release -v --features pyo3/extension-module -- --crate-type cdylib
    error: cargo failed with code: 101
    
    [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for faf-replay-parser
```

### Your operating system and version

Microsoft Windows Server 2019 10.0.17763

### Your Python version (`python --version`)

pythonx86 3.7.9

### Your Rust version (`rustc --version`)

rustc 1.59.0 (9d1b2106e 2022-02-23)

### Your PyO3 version

0.16.3

### How did you install python? Did you use a virtualenv?

cibuildwheel
virtualenv

**Comment by adamreichold** [comment]
Most likely a duplicate of #2298. Could you check that the current main branch still exhibits the problematic behaviour? Otherwise we are in the process of releasing version 0.16.4 which should fix this.

**Comment by Askaholic** [comment]
Ok awesome! I tried to search for related issues but didn’t find anything. I’ll check with the main branch this evening.

**Comment by Askaholic** [comment]
Using the main branch of pyo3 fixed it. Closing this issue.
