### ISSUE TITLE
PyDate(Time)::from_timestamp should take an integer type

### ISSUE THREAD

**Issue by pganssle** [PyO3/pyo3#231]
When working on the documentation for the `datetime` bindings, I realize that probably [`PyDate::from_timestamp`](https://github.com/PyO3/pyo3/blob/master/src/types/datetime.rs#L69) and `PyDateTime::from_timestamp` should not take `*args, **kwargs` but rather `timestamp: i64, tz=Option<&PyObject>` or something to that effect.

I believe I wrote these trying to be a bit stricter to the C API than is really idiomatic for this project.

**Comment by pganssle** [comment]
@konstin This only fixes half of it. There's also `PyDateTime::from_timestamp`.

**Comment by konstin** [comment]
Oh sorry, I should have read that more closely
