### ISSUE TITLE
Python 3.11 prints `Could not find platform dependent libraries <exec_prefix>`

### ISSUE THREAD

**Issue by mejrs** [PyO3/pyo3#2320]
See https://github.com/PyO3/pyo3/pull/2314#issuecomment-1101761842 

Ever since 3.11 was added to the workflow, it has been printing `Could not find platform dependent libraries <exec_prefix>`. I also get this warning locally (on Window) as the python interpreter is initialized.

**Comment by davidhewitt** [comment]
@mejrs do you still see this issue with latest Python 3.11 betas? I haven't noticed this in our CI for a while, I wonder if we can close this?

**Comment by mejrs** [comment]
I still see it in the CI logs. (for example, [here](https://github.com/PyO3/pyo3/runs/7761038831?check_suite_focus=true#step:15:122))

**Comment by davidhewitt** [comment]
Ah thanks, I was looking in the wrong spot 👍

**Comment by davidhewitt** [comment]
Well I asked upstream in https://github.com/python/cpython/issues/98790, no response yet. It looks like this warning is mostly benign, the [documentation for `Py_GetExecPrefix`](https://docs.python.org/3/c-api/init.html?highlight=py_getexecprefix#c.Py_GetExecPrefix) even implies that `exec_prefix` is meaningless on Windows.

I think given that the PyO3 test suite completes without issue on 3.11 I'm thinking we can go ahead and release announcing 3.11 support, and this can get resolved here or upstream later on.

**Comment by davidhewitt** [comment]
This has been resolved upstream.
