### ISSUE TITLE
Don't accept `str` in `FromPyObject` for `Vec<&str>` and `Vec<String>`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2342]
As per the title, it would be nice if we didn't accept Python `str` in `FromPyObject` for `Vec<&str>` and `Vec<String>`. Some background below.

I'm not sure how hard this will be (without specialization).

### Discussed in https://github.com/PyO3/pyo3/discussions/2341

<div type='discussions-op-text'>

<sup>Originally posted by **atoav** April 27, 2022</sup>
In python one can iterate over a `str` as if it was a `List[str]`. And while this is occasionaly useful it can also be a major footgun if users pass in a `"string"` instead of a `["string"]` and suddenly have a function operate on single characters instead of the whole string, as they might (admittedly, errouniously) assumed one that one string.

In python I'd prevent this user error  by ensuring incoming str are never treated as a list of characters by wrapping a lone `str` in a list as follows:

```python
if isinstance(strings, str):
    strings = [strings]
```

In pyo3 this is an issue as well. Let's say i have a simple function that should take a `Vec<String>` and print out each string in the vec:

```Rust
/// Print out each string in a list of strings
#[pyfunction]
fn print_strings(strings: Vec<String>) {
    for s in strings {
        println!("{}", s);
    }
}
```

If I now run this in the python interpreter with a string that is not a list each character is printed out seperately:  

```python
>>> from my_module import print_strings
>>> print_strings("string")
s
t
r
i
n
g
```

Is there any simple way to ensure single `str` are treated as `[str]` using pyo3? Even an Error would be acceptable, as long as users don't pass a string and have it iterate over characters without them noticing.</div>

**Comment by jeertmans** [comment]
Hi! Shouldn’t this be closed as #2500 was merged?
