### ISSUE TITLE
Debugging docs for rust-gdb

### ISSUE THREAD

**Issue by cjermain** [PyO3/pyo3#2345]
Since PyO3 uses `cdylib` for Python shared objects, it does not receive the pretty-print debug hooks in `rust-gdb` ([rust-lang/rust#96365](https://github.com/rust-lang/rust/issues/96365)). I think adding information about this to the debugging documentation for PyO3 would help avoid confusion as to why pretty printers are not loaded. I'm happy to update the docs when I get a chance.
 ​https://github.com/PyO3/pyo3/blob/main/guide/src/debugging.md#L38

**Comment by davidhewitt** [comment]
Thanks for sharing! It sounds like this is potentially something that upstream `rustc` might fix one day?

**Comment by cjermain** [comment]
That is my hope. I'm not sure the right way to get visibility on the upstream issue.
