### ISSUE TITLE
PyDateTime::new_with_fold says the fold parameter signifies leap seconds

### ISSUE THREAD

**Issue by RazerM** [PyO3/pyo3#2381]
The doc comment for `PyDateTime::new_with_fold` says:

> Alternate constructor that takes a `fold` parameter. A `true` value for this parameter signifies a leap second

This is **not** what the fold attribute represents. See [PEP 495](https://peps.python.org/pep-0495/). It's about clocks showing the same time twice when the clocks go back with DST.

**Comment by davidhewitt** [comment]
Thanks, opened #2386.

**Comment by davidhewitt** [comment]
Thanks, opened #2386.
