### ISSUE TITLE
`#[classattr]` functions should be able to take `Python` arguments

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2383]
Try to compile the following:

```rust
#[pyclass]
struct Singleton { }

#[pymethods]
impl Singleton {
    #[classattr]
    fn VALUE(py: Python<'_>) -> Py<Self> {
        Py::new(py, Singleton { }).unwrap()
    }
}
```

I expected this to compile, but instead the compiler emits:

```
error: class attribute methods cannot take arguments
  --> src/lib.rs:10:14
   |
10 |     fn VALUE(py: Python<'_>) -> Py<Self> {
   |              ^^
```

I think it'd be nice to change `#[classattr]` to allow `Python` argument (like `#[getter]`, for example).

**Comment by mdaj06** [comment]
@davidhewitt i'd really like to implement this

**Comment by davidhewitt** [comment]
@mdaj06 please do! Do you need any tips to get started?

**Comment by mdaj06** [comment]
@davidhewitt i'll look into it and if I get blocked I'll reach out,if that's okay?

**Comment by birkenfeld** [comment]
Don't worry, we will try to help if you get stuck.

**Comment by mdaj06** [comment]
thanks!! @birkenfeld

**Comment by mdaj06** [comment]
i ran a few circles, trying to find out where to start. Could you point out the file i can start from?

**Comment by davidhewitt** [comment]
Sure thing.

The call to the `#[classattr]` function is generated in macro code at https://github.com/PyO3/pyo3/blob/9dfeaa38d4a3b7e0b7cf77b61ab3f58e489a0277/pyo3-macros-backend/src/pymethod.rs#L366

You will want to conditionally add `py` in there according to whether the `#[classattr]` function takes an argument. See the equivalent code for `#[getter]`: https://github.com/PyO3/pyo3/blob/9dfeaa38d4a3b7e0b7cf77b61ab3f58e489a0277/pyo3-macros-backend/src/pymethod.rs#L489-L500

Let me know if you need more detail than that :)
