### ISSUE TITLE
class method support with async

### ISSUE THREAD

**Issue by b23r0** [PyO3/pyo3#2388]
I think it's very necessary to support asynchrony for class methods, in the form of something like this.

```rs
#[pymethods]
impl Test{

    #[new]
    pub fn new() -> PyResult<Test> {
        Ok(Test{})
    }

    // now report `async fn` is not yet supported for Python functions.
    async pub fn async_test(&mut self) -> PyResult<()> {
        Ok(())
    }
}
```

**Comment by mejrs** [comment]
You can use the `pyo3-asyncio` crate for this. You have to make a normal method that returns a future object, similar to the examples at https://docs.rs/pyo3-asyncio/latest/pyo3_asyncio/index.html

**Comment by b23r0** [comment]
> You can use the `pyo3-asyncio` crate for this. You have to make a normal method that returns a future object, similar to the examples at https://docs.rs/pyo3-asyncio/latest/pyo3_asyncio/index.html

I know that normal functions can implement async, but I hope class methods can too.

**Comment by davidhewitt** [comment]
My understanding was that you can use `pyo3-asyncio` to implement `#[pymethods]` too.

**Comment by davidhewitt** [comment]
I'm also going to close this, as a duplicate of #1632.
