### ISSUE TITLE
LinkedList<T> to PyList conversion

### ISSUE THREAD

**Issue by InnovativeInventor** [PyO3/pyo3#2405]
For some functions, I'd like to return a `LinkedList`. However, `IntoPy` is only implemented for `Vec<T>`, so I currently first convert to a `Vec`, then allow pyo3 to convert the `Vec` to a `PyList`. This seems a bit inefficient, if I'm properly understanding how the conversions happen under the hood. It seems like going directly from `LinkedList` to `PyList` would be more efficient. I am willing to implement this, if such a PR would be welcome here.

This project's awesome!

**Comment by davidhewitt** [comment]
I think `PyList::new(py, my_linked_list)` should work for a manual conversion?

A PR to implement `IntoPy` and `ToPyObject` for `LinkedList<T>` would be very welcome - see the implementations for `Vec<T>` as a starting point.

**Comment by OliverFM** [comment]
I may give this a try!

**Comment by davidhewitt** [comment]
@OliverFM see https://github.com/PyO3/pyo3/pull/2446 - we almost merged this previously but stalled as we weren't convinced that it's definitely helpful.

Before putting effort into rebooting the implementation we should justify whether this conversion should exist.

**Comment by OliverFM** [comment]
Thanks for the heads up – it looks like that issue is surmountable, and was only because of the way the test was constructed.
Very happy to skip this on the basis of it not being useful though.

I don't make very extensive use of pyo3 at the moment, and very rarely use linked lists, so I wouldn't know if this would be a useful addition.

**Comment by davidhewitt** [comment]
> I mean, they're very different data structures. I'm not convinced that linkedlist -> pylist is the obvious thing to do.

This is the comment I am referring to as being the concern from @mejrs which we never resolved.

**Comment by mejrs** [comment]
> very rarely use linked lists

As does everyone else 😆 So this wouldn't be very useful.

My main concern is that it doesn't do what people expect. If you naively write some Rust code returning a String, Vec or HashMap to Python you can reasonably expect what you'll get on the Python side. What do you get when you return a LinkedList to Python?

**Comment by OliverFM** [comment]
Maybe worth closing this issue in that case?

**Comment by davidhewitt** [comment]
I think that's probably a good idea 👍
