### ISSUE TITLE
Add support for PyObject_CallMethodNoArgs

### ISSUE THREAD

**Issue by dignissimus** [PyO3/pyo3#2426]
The FFI bindings expose [`pyo3::ffi::PyObject_CallMethod`](https://docs.rs/pyo3/latest/pyo3/ffi/fn.PyObject_CallMethod.html), [`pyo3::ffi::PyObject_CallNoArgs`](https://docs.rs/pyo3/latest/pyo3/ffi/fn.PyObject_CallNoArgs.html), [`pyo3::ffi::PyObject_CallObject`](https://docs.rs/pyo3/latest/pyo3/ffi/fn.PyObject_CallObject.html) but `pyo3::ffi::PyObject_CallMethod` seems to have been left out. The C API reference for `PyObject_CallMethod` is here: https://docs.python.org/3/c-api/call.html#c.PyObject_CallMethodNoArgs

**Comment by davidhewitt** [comment]
It is actually supported ([see definition here](https://github.com/PyO3/pyo3/blob/3cd9e3b4116018a54dbf3ab5d7f33c2955d8df8b/pyo3-ffi/src/cpython/abstract_.rs#L196)), but it looks like it's not present on docs.rs.

@mejrs - it looks like docs.rs builds with Python 3.8, so it doesn't show symbols available on Python 3.9 or 3.10. E.g. compare the fields of [PyConfig](https://docs.rs/pyo3/latest/pyo3/ffi/struct.PyConfig.html) with its [source](https://docs.rs/pyo3-ffi/0.16.5/src/pyo3_ffi/cpython/initconfig.rs.html#82-172). I wonder if we can change PyO3's docs.rs build to add `Py_3_9` and `Py_3_10` (and maybe even `Py_3_11`)? Depends whether we can get away without linking when building docs, I guess.

**Comment by mejrs** [comment]
I think that should work, yes.

**Comment by mejrs** [comment]
Filed https://github.com/rust-lang/crates-build-env/pull/104

**Comment by davidhewitt** [comment]
Thanks! I think let's call this issue closed. There's potentially a follow-up to change PyO3's docs to always include all symbols, regardless of the Python version installed in the docs.rs build environment, however for now that's a good step forward 👍
