### ISSUE TITLE
dyld[85569]: Library not loaded: @rpath/Python3.framework

### ISSUE THREAD

**Issue by chatwyn** [PyO3/pyo3#2437]
when I use VSCode to debug programs， It will show 
dyld[85569]: Library not loaded: @rpath/Python3.framework/Versions/3.8/Python3

**Comment by davidhewitt** [comment]
Reminds me of https://github.com/PyO3/setuptools-rust/issues/106#issuecomment-781195463 - I suspect you need to specify RPATH at some point.

**Comment by davidhewitt** [comment]
This was documented in #2534
