### ISSUE TITLE
Counting loop faster than default count method on PyIterator

### ISSUE THREAD

**Issue by Numerlor** [PyO3/pyo3#2444]
When implementing a simple function to count the amount of elements in an iterable, I've noticed that counting the elements myself was faster than using the `count` method provided by `Iterator` when compiled using the `stable-x86_64-pc-windows-msvc` toolchain.
<details>
 <summary>With the following code</summary>

 ```rust
use pyo3::prelude::*;
use pyo3::types::PyIterator;

#[pyfunction]
pub fn ilen_for(py: Python, iterable: PyObject) -> PyResult<usize> {
    let iterator = PyIterator::from_object(py, &iterable)?;

    let mut sum: usize = 0;
    for val in iterator {
        val?;
        sum += 1;
    }
    Ok(sum)
}

#[pyfunction]
pub fn ilen_count(py: Python, iterable: PyObject) -> PyResult<usize> {
    let iterator = PyIterator::from_object(py, &iterable)?;

    Ok(iterator.count())
}

#[pymodule]
fn iterable_test(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(ilen_for, m)?)?;
    m.add_function(wrap_pyfunction!(ilen_count, m)?)?;
    Ok(())
}
```
</details>

Timing it from ipython yields these results on my computer
```py
In [1]: r = range(1000000)

In [2]: timeit ilen_for(r)
25.9 ms ± 502 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]: timeit ilen_count(r)
30.1 ms ± 578 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

The default `count` uses the `fold` method to count the elements; trying out others like `last` that use it I see similar behaviour.
While doing this kind of iteration on the rust side is not ideal with the ffi calls, this does seem like it could be a nice optimization if it is being done

**Comment by birkenfeld** [comment]
If I'm not mistaken, It is 25 ns per iteration vs 30 ns per iteration, probably due to a subtle difference in optimization of the iterator adapter code. In all normal cases you'd be doing work within the loop body which should dwarf that cost.

In any case, `.count()` is a Rust stdlib iterator method, so nothing that pyo3 can try to optimize.

**Comment by Numerlor** [comment]
> If I'm not mistaken, It is 25 ns per iteration vs 30 ns per iteration, probably due to a subtle difference in optimization of the iterator adapter code. In all normal cases you'd be doing work within the loop body which should dwarf that cost.
> 
> In any case, `.count()` is a Rust stdlib iterator method, so nothing that pyo3 can try to optimize.

Can't the count method be override on the trait implementation? Or the fold if that could be somehow optimized while keeping its behaviour

**Comment by birkenfeld** [comment]
As I said, there is no obvious way to optimize it. Case in point, with your code on my machine, the result is:
```
In [3]: %timeit iterable_test.ilen_for(r)
46 ms ± 232 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]: %timeit iterable_test.ilen_count(r)
45.5 ms ± 449 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
