### ISSUE TITLE
PyCodeObject has different layout in Python 3.11

### ISSUE THREAD

**Issue by itamarst** [PyO3/pyo3#2445]
### Bug Description

The layout of PyCodeObject is different in 3.11.

### Steps to Reproduce

3.10: https://github.com/python/cpython/blob/3.10/Include/cpython/code.h#L18

3.11: https://github.com/python/cpython/blob/3.11/Include/cpython/code.h#L36

### Your operating system and version

Linux (Ubuntu 22.04)

### Your Python version (`python --version`)

3.11b3 via deadsnakes PPA

### Your Rust version (`rustc --version`)

1.61

### Your PyO3 version

0.16.4

### How did you install python? Did you use a virtualenv?

venv

### Additional Info

Quite likely other FFI objects changed as well...

I realize 3.11 isn't out yet, but I'm trying to update some code so I can file bugs in beta period, before it's released. So having beta support in PyO3 would be useful

**Comment by davidhewitt** [comment]
We already test 3.11 in CI (currently 3.11.0b3), and we have the new definition of `PyCodeObject`: https://github.com/PyO3/pyo3/blob/9dfeaa38d4a3b7e0b7cf77b61ab3f58e489a0277/pyo3-ffi/src/cpython/code.rs#L51-L54

When 0.17 releases (maybe a month or two) we should be compatible with whichever beta version is live at that point, however we won't declare "official" support for 3.11 until it's released.

If you want to test 3.11 already, is it acceptable for you to use PyO3 as a git dependency?

**Comment by itamarst** [comment]
Ah, should've checked `main` branch, my apologies. I can use the git version for my code's 3.11 branch at least, the goal is testing not releasing, so that should be fine.

**Comment by itamarst** [comment]
(It works!)
