### ISSUE TITLE
Could `PyDict.set_item` performance be improved with `_PyDict_SetItem_KnownHash`?

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#2463]
I was looking at ways to improve performance of adding items to a dict, and I noticed that orjson is using `_PyDict_SetItem_KnownHash`, see [here](https://github.com/ijl/orjson/blob/master/src/deserialize/json.rs#L156).

Would it be possible to hash specific types (e.g. `String` with length <63 as orjson do) using a custom implementation, then using `_PyDict_SetItem_KnownHash`?

Would it make a significant difference to performance?

**Comment by mejrs** [comment]
It looks like that implementation just calls the hash implementation and then that function. So I'm not sure how more effective that is 🤔

**Comment by davidhewitt** [comment]
Agree with @mejrs. Specifically I think it would have to be the Python hash that is called for this to be sound, right? I think maybe it would be possible to improve performance by using a cache and looking up if you expect lots of duplicates, thus avoiding the hash on each call. Presumably that is what `orjson` is doing.

TBH caching on that kind of level sounds like something for application code rather than directly in PyO3.

**Comment by samuelcolvin** [comment]
I think i was somewhat confused when I first looked at the orjson code.

It seems they hash the input in rust (if the string is short), to look up the cache of python hashes. Presumably they've profiled it and found that's faster than just generating the python hash, though I guess it matters a lot how often values are repeated.

> Specifically I think it would have to be the Python hash that is called for this to be sound, right?

Is this so that future use of the dict in python code works as expected?

It occurs to me (and I fully expect you to tell me this is a terrible idea), that if you don't care about later mutation of the dict, and you're just building a dict in one place, then iterating over it in another place (as we do in a couple of places in pydantic-core), that you could use an incrementing int as the "hash"?

I've tried that in a benchmark [here](https://github.com/samuelcolvin/rust-bench/blob/b05299ed59f209f1fa30cb1c4a04800dbd490711/benches/main.rs#L109-L121) and it seems to work and be ~16% faster, not sure that's really worth it.

---

The massive saving comes from reusing the `PyString` which is around 70% faster. I guess the question for me (and I totally agree this shouldn't be part of pyo3) is whether to cache `PyString` for short strings.

Using a pre-computed hash with  a `PyString` doesn't seem to save any more time, presumably because `PyString` somehow stores it's own hash for reuse.

But overall i don't see a reason to add a new method to expose `_PyDict_SetItem_KnownHash` in pyo3.

**Comment by adamreichold** [comment]
> I guess the question for me (and I totally agree this shouldn't be part of pyo3) is whether to cache PyString for short strings.

Maybe the [`PyString::intern`](https://docs.rs/pyo3/latest/pyo3/types/struct.PyString.html#method.intern) method could be helpful here?

**Comment by samuelcolvin** [comment]
I'm already using it where I know the dict keys, e.g. to build a model, the question is whether to have a general purpose cache when validating `Dict[str, int]` or anything with a string in it from JSON.

**Comment by samuelcolvin** [comment]
For anyone coming to this in future, I worked on an implementation https://github.com/samuelcolvin/pydantic-core/pull/213. It's around 10-15% faster with 100% cache hits (e.g. lots of use of the same strings), but up to 2x slower with 0 cache hints.

Overall (for now) I decided it's not worth it.
