### ISSUE TITLE
Reduce `gh-pages` branch size?

### ISSUE THREAD

**Issue by messense** [PyO3/pyo3#2472]
It gets annoying `git pull` receives several hundred megabytes due to `gh-pages` branch updates. 

```bash
❯ git pull
remote: Enumerating objects: 23466, done.
remote: Counting objects: 100% (23466/23466), done.
remote: Compressing objects: 100% (2336/2336), done.
remote: Total 23466 (delta 21105), reused 23257 (delta 20905), pack-reused 0
Receiving objects: 100% (23466/23466), 214.82 MiB | 5.80 MiB/s, done.
Resolving deltas: 100% (21105/21105), completed with 2622 local objects.
From github.com:PyO3/pyo3
   53b83cccbf..ef308ffaad  main       -> upstream/main
   74f4ccd485..2d9e575e3d  gh-pages   -> upstream/gh-pages
Updating 53b83cccbf..ef308ffaad
```

How about only keep the latest commit in `gh-pages` branch?

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan

**Comment by birkenfeld** [comment]
Yes please! I was already wondering why the repo is so big.

Alternately, the `gh-pages` can be put into a separate repo.

**Comment by davidhewitt** [comment]
Yeah this had been bothering me too but I didn't have time to look into it 🙂

`force_orphan` seems like a good quick fix, yes please! I also wonder if we should consider moving to netlify or something similar?

**Comment by messense** [comment]
> With the v3, this option does not support working with the force_orphan option. The next major release (version 4) will support this

Oops, `keep_files` does not work with `force_orphan`.

**Comment by messense** [comment]
Moving to Netlify will require a DNS change, but we can try it out first with Netlify subdomain.

**Comment by birkenfeld** [comment]
> Oops, `keep_files` does not work with `force_orphan`.

The `redirect` step might not need `force_orphan` though?

**Comment by davidhewitt** [comment]
Just force-pushed to trim the branch

**Comment by messense** [comment]
Looks like https://pyo3.rs/main/ somehow does not include #2499 , not sure what's going on, build the guide locally does include it.

If we going to use netlify, we can apply for a open source plan first and create a team on netlify.

* [Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/)
* [Apply for an Open Source Account](https://opensource-form.netlify.com/)

**Comment by davidhewitt** [comment]
Looks like we have to first create the netlify pages and then apply, to demonstrate we meet their open source plan requirements. I'm happy to give configuring netlify a shot later.

**Comment by davidhewitt** [comment]
I've squashed the `gh-pages` branch one last time, removing all the stuff other than the versioned guide builds.

The branch pre-squash can be found in my fork at https://github.com/davidhewitt/pyo3/tree/gh-pages-20220828, should we ever need it.
