### ISSUE TITLE
Python code packaging in rust library

### ISSUE THREAD

**Issue by elaye** [PyO3/pyo3#249]
First of all thank you for this crate, it's really useful !

I have a question regarding the build process. Maybe the answer hides somewhere on the internet but I'm not sure what to search for.

I'm writing a library in rust that calls python code that depends on external packages. So I set up a virtualenv with the required dependencies installed. Now I want to use this library in another rust project, but to do so I need to activate the virtualenv of my library.

Is there a way to package the python code and its dependencies so that the usage of python is transparent for the user using the rust library ?

**Comment by konstin** [comment]
There is no existing solution for this, mostly because most people don't like their rust code to depend on python package. You'll most likely need to build something custom like vendoring the python packages, installing them in a build script or simply telling user to install the packages.

**Comment by elaye** [comment]
Thank you for your answer, that makes sense.
