### ISSUE TITLE
`maturin publish` always "Username and/or password are wrong"

### ISSUE THREAD

**Issue by RiotGamesU** [PyO3/pyo3#2498]
### Bug Description

```shell
(.env) root@instance:~/a# maturin publish -u aaaa -p aaaaaaaa
🔗 Found bin bindings
    Finished release [optimized] target(s) in 0.12s
📦 Built wheel to /root/a/target/wheels/a-0.1.8-py3-none-manylinux_2_28_aarch64.whl
🚀 Uploading 1 packages
⛔ Username and/or password are wrong
💥 maturin failed
  Caused by: Username and/or password are wrong
(.env) root@instance:~/a# 
```

always

pypi.org "Security history":

```
Login failed - Basic Auth (Upload endpoint)
Reason: Incorrect Password
```

### Steps to Reproduce

```shell
maturin publish -u aaaa -p aaaaaaaa
```

tried use "Api Token":

```shell
maturin publish -u __token__ -p pypi-xxxx
```

### Your operating system and version

Linux version 5.13.0-1021-oracle (buildd@bos02-arm64-014) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #26~20.04.1-Ubuntu SMP Mon Mar 7 14:30:17 UTC 2022

### Your Python version (`python --version`)

Python 3.8.10

### Your Rust version (`rustc --version`)

rustc 1.62.0 (a8314ef7d 2022-06-27)

### Your PyO3 version

maturin       0.12.20

### How did you install python? Did you use a virtualenv?

apt

use virtualenv

**Comment by davidhewitt** [comment]
I see you also opened https://github.com/PyO3/maturin/issues/999, so will close here.
