### ISSUE TITLE
Pyo3 dose not work with rust 1.29.2 stable ? 

### ISSUE THREAD

**Issue by toplinuxsir** [PyO3/pyo3#250]
## 🐛 Bug Reports

When build with stable 1.29.2:
The error:
```
rror[E0554]: #![feature] may not be used on the stable release channel
Error: pyo3 requires a nightly or dev version of Rust.
Installed version is: 1.29.2 (2018-10-05). Minimum required: 1.30.0-nightly (2018-08-18).

```

### 🌍 Environment

 - Your operating system and version:
 - Your python version:
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:
 - Your rust version (`rustc --version`):
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` 

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the rust code and the python.

Please also write what exact flags are required to reproduce your results.

**Comment by kngwyu** [comment]
Pyo3 requires nightly.
See https://github.com/PyO3/pyo3/blob/master/README.md#usage
