### ISSUE TITLE
`error: #[ctor] is not supported on the current target` when compiling for `wasm32-unknown-emscripten`

### ISSUE THREAD

**Issue by kylebarron** [PyO3/pyo3#2517]
👋 I'm trying to compile [polars](https://github.com/pola-rs/polars) to wasm to work with pyodide (ref https://github.com/PyO3/pyo3/issues/2412 and https://github.com/pola-rs/polars/issues/3672#issuecomment-1188613095).

After removing some dependencies, I got all of `polars`'s dependencies to build for `wasm32-unknown-emscripten` using `RUSTUP_TOOLCHAIN=nightly maturin build --release -o dist --target wasm32-unknown-emscripten -i python3.10`, but compilation failed on polars itself with a couple hundred `#[ctor] is not supported on the current target` errors:
```
2310   │ error: #[ctor] is not supported on the current target
2311   │   --> src/lazy/dataframe.rs:95:1
2312   │    |
2313   │ 95 | #[pymethods]
2314   │    | ^^^^^^^^^^^^
2315   │    |
2316   │    = note: this error originates in the attribute macro `$crate::ctor` (in Nightly builds, run with -Z macro-backtrac
       │ e for more info)
```

I've seen https://github.com/mmastrac/rust-ctor/issues/14 and https://github.com/PyO3/pyo3/issues/1434. Does this mean there's no way to use a pyo3 class in `wasm32-unknown-emscripten`? Did the opt-out functionality mentioned [here](https://github.com/PyO3/pyo3/issues/1434#issuecomment-780866997) ever get implemented?

**Comment by messense** [comment]
I wonder if it's possible to get rid of multiple `pymethods` usage in polars?

**Comment by kylebarron** [comment]
When compiling from [this commit](https://github.com/kylebarron/polars/commit/3e52839c89367e8fb676c483f6c618a83f0460f9), this ([log1.txt](https://github.com/PyO3/pyo3/files/9137848/log1.txt)) is the output log from 
```
RUSTUP_TOOLCHAIN=nightly maturin build --release -o dist --target wasm32-unknown-emscripten -i python3.10
```
So for example several of the errors come from here: https://github.com/kylebarron/polars/blob/3e52839c89367e8fb676c483f6c618a83f0460f9/py-polars/src/series.rs#L31-L61

> I wonder if it's possible to get rid of multiple `pymethods` usage in polars?

I'm not sure I understand pyo3 well enough to answer this question 😅 (I also didn't write the polars python bindings; I'm just exploring compiling them to pyodide). It seems like there's a compile error every time `#[pymethods]` is used...?

**Comment by messense** [comment]
Only `multiple-pymethods` feature in pyo3 requires `#[ctor]`, see https://pyo3.rs/v0.16.4/class.html#implementation-details

**Comment by kylebarron** [comment]
Oh I see! That makes sense now!

It looks like polars uses multiple pymethods to simplify their macros (they use `#[pymethods]` dozens of times on just the `PySeries` struct). I'll talk to the polars project and see what they say.

Thanks for your help!

**Comment by davidhewitt** [comment]
As this is documented and not anything PyO3 can realistically change, I will close this issue.
