### ISSUE TITLE
Alternative recommendation for workspaces with an extension-module and linker issues

### ISSUE THREAD

**Issue by acshi** [PyO3/pyo3#2521]
Right now on the FAQ, there is an entry for `cargo test` problems when using an extension-module, recommending to use `cargo test --no-default-features`.

However, this is not the only way that these problems might surface. For me, I couldn't run `cargo check` from my workspace route, because of the additiveness of cargo features and using pyo3 both in an extension module and another use in different crates.

My solution was a combination and reversion of existing suggestions:
In my extension-module `Cargo.toml`
```
[lib]
name = "name"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.15.2"

[features]
# NOT a default feature
extension-module = ["pyo3/extension-module"]
```

Then I build with `maturin develop --features extension-module --release`

This way, the feature is _only_ enabled when it is needed. I think this is a more composable and general solution than the current recommendation.

Ideally, this recommendation, or at least a link to it on the FAQ, could be linked from the main page (https://pyo3.rs/v0.14.2/index.html), since using PyO3 in a workspace seems a fairly common use-case to me and I see any drawbacks to this solution right now, besides a slightly longer maturin build command.

**Comment by davidhewitt** [comment]
Thanks for sharing, that's an interesting approach, I agree it's probably better.

I think you could even go further and add the following to your `pyproject.toml`:

```
[tool.maturin]
cargo-extra-args = ["--features", "extension-module"]
```

That way I think `maturin` will pass the feature automatically. (Similar could also be done with `setuptools-rust`.)

Would you be willing to push a PR to add this recommendation to the FAQ?

**Comment by acshi** [comment]
Great! Yeah, I'll see if I can send a PR for this later this week
