### ISSUE TITLE
It's not obvious how to call `ObjectProtocol::call_method` with kwargs

### ISSUE THREAD

**Issue by koute** [PyO3/pyo3#254]
I'm using `0.5.0-alpha.2`.

The `ObjectProtocol::call_method`'s prototype looks like this:

```rust
fn call_method<A>(
    &self, 
    name: &str, 
    args: A, 
    kwargs: Option<PyDict>
) -> PyResult<&PyObjectRef>
```

It takes `Option<PyDict>` as `kwargs`. And here's how `PyDict::new`'s prototype looks like:

```rust
pub fn new(py: Python) -> &PyDict
```

It returns `&PyDict`, not `PyDict`! And I don't see an obvious way to convert that reference to an owned object so that I can pass it as `kwargs`.

So, a few questions:

1) How are you actually supposed to call it? So far only this works:

   ```rust
   let kwargs: &PyDict = PyDict::new();
   // ...modify kwargs here...
   let kwargs: PyDict = unsafe { mem::transmute(kwargs.to_object(py)) };
   obj.call( ..., kwargs )
   ```
   ...but surely this isn't the way to go?

2) Related - what is the official way to grab an owned instance of a Python object from a reference? (e.g. `PyDict` from a `&PyDict`?) Is it supposed to be impossible? If so then why can I get an owned `PyObject` from a `&PyDict` with `ToPyObject::to_object`, but I can't get a `PyDict` which is just internally a `struct PyDict(PyObject)` newtype?
2) Shouldn't the `kwargs` actually be `Option<&PyDict>` in `ObjectProtocol::call_method`?
4) I'm confused as to how the lifetime of e.g. an object created with `PyDict::new()` is managed if it returns `&PyDict`. If I call `PyDict::new()` I'd assume that I'm the owner of it, but I get only a reference, so when exactly will that object be freed? Is it leaked? Is it automatically freed when I drop the GIL?

The [`ObjectProtocol::call_method`'s docs](https://pyo3.rs/master/doc/pyo3/trait.ObjectProtocol.html#tymethod.call_method) have an example, however it's unfortunately not tested, and as far as I can see it is broken anyway.

[The conversion docs](https://github.com/PyO3/pyo3/blob/master/guide/src/conversions.md) also look outdated.

**Comment by kngwyu** [comment]
Thanks.

> 1. How are you actually supposed to call it? So far only this works:

I think it **should** take `&Option<PyDict>` (cc: @konstin what do you think?)

> 4. I'm confused as to how the lifetime  is managed

Please read https://pyo3.rs/master/doc/pyo3/index.html#ownership-and-lifetimes.

> If I call PyDict::new() I'd assume that I'm the owner of it, but I get only a reference, so when exactly will that object be freed? Is it leaked? Is it automatically freed when I drop the GIL?

It's managed by Python GC and drops when its reference counter become 0.

**Comment by kngwyu** [comment]
> 2. Related - what is the official way to grab an owned instance of a Python object from a reference? 

It should be restricted, but about `ToPyObject`, I think it's confusing, too :thinking:

**Comment by konstin** [comment]
It should indeed be `Option<&PyDict>`; I chose the wrong type when refactoring. Thank you @kngwyu for fixing this! 

>  Related - what is the official way to grab an owned instance of a Python object from a reference? (e.g. PyDict from a &PyDict?) Is it supposed to be impossible? If so then why can I get an owned PyObject from a &PyDict with ToPyObject::to_object, but I can't get a PyDict which is just internally a struct PyDict(PyObject) newtype?

Unfortunately the whole types story is currently chaotic.

> The ObjectProtocol::call_method's docs have an example, however it's unfortunately not tested, and as far as I can see it is broken anyway.

I've used @kngwyu's test to replace it by a tested one.

**Comment by koute** [comment]
Thanks for the quick fix!

> > 1. I'm confused as to how the lifetime  is managed
> 
> Please read https://pyo3.rs/master/doc/pyo3/index.html#ownership-and-lifetimes.
> 
> > If I call PyDict::new() I'd assume that I'm the owner of it, but I get only a reference, so when exactly will that object be freed? Is it leaked? Is it automatically freed when I drop the GIL?
> 
> It's managed by Python GC and drops when its reference counter become 0.

That's how I assumed it works, but, again, this:

```rust
impl PyDict {
    pub fn new(py: Python) -> &PyDict
}
```

will return a *reference* to a `PyDict`, which means that there is no `Drop` implementation which will decrement the reference counter once I stop using that `PyDict`. So what *exactly* will make its reference count become zero?

**Comment by konstin** [comment]
The function signature is deceiving. With the lifetimes written out explicitly it gets clearer:

```rust
impl PyDict {
    /// Creates a new empty dictionary.
    pub fn new<'p>(py: Python<'p>) -> &'p PyDict {
        unsafe { py.from_owned_ptr::<PyDict>(ffi::PyDict_New()) }
    }
}
```

This means that &PyDict is bound to the lifetime of the GIL and e.g. the following doesn't compile:

```rust
use pyo3::types::PyDict;

let x: &PyDict;
{
    let gil = GILGuard::acquire();
    let py = gil.python();
    x = PyDict::new(py);
}
```

The actual reference counter decrementation is done by `Python`'s drop implementation through a static ReleasePool where the PyDict was registered upon creation. For storing objects over the lifetime of GIL there's `PyObject` and `Py<T>`.

**Comment by koute** [comment]
@konstin This makes sense now! Thanks for the explanation!
