### ISSUE TITLE
pyo3.rs/ redirects to https://pyo3.rs/v0.16.4/ instead of https://pyo3.rs/v0.16.5/

### ISSUE THREAD

**Issue by jmhodges** [PyO3/pyo3#2551]
### Bug Description

Currently, the pyo3.rs site's `/` redirect is redirecting to the 0.16.4 version of the docs instead of the currently published 0.16.5

### Steps to Reproduce

1. Go to https://pyo3.rs/
2. See it redirects to pyo3.rs/0.16.4 (there's a meta tag with `http-equiv=refresh` in it)

### Your operating system and version

any

### Your Python version (`python --version`)

any

### Your Rust version (`rustc --version`)

any

### Your PyO3 version

any

### How did you install python? Did you use a virtualenv?

N/A

**Comment by davidhewitt** [comment]
Thanks for reporting, yes I noticed that too. Our github-pages push seems to be having trouble recently (see #2472), I think we'd better move to a service like Netlify...

**Comment by davidhewitt** [comment]
The landing page now links to the latest version again.
