### ISSUE TITLE
publish current master?

### ISSUE THREAD

**Issue by inv2004** [PyO3/pyo3#256]
Hello,

0.5.0-alpha.2 has something strange that PyDict::new creates a ref, but call/eval requires deref value. I found that the problem is fixed in master. Would you like to publish it?

I would use git-link, but its also necessary to fork and fix rust-numpy also.

Thank you,

**Comment by kngwyu** [comment]
cc: @konstin

**Comment by konstin** [comment]
Sure

**Comment by kngwyu** [comment]
Looks it's not published https://crates.io/crates/pyo3
