### ISSUE TITLE
Example of the generator with yield #question

### ISSUE THREAD

**Issue by inv2004** [PyO3/pyo3#257]
Hello,

Is it possible to call some python function which uses generator (would like to create it in rust part).
What is correct way to do yield(val) from pyo3 side?

Im afraid that calling from python could affect performance significantly.
Do you have any examples (with PyIterator?)?

Thank you,

**Comment by konstin** [comment]
I don't think calling `yield` in rust is what you want; yield is just a syntactic sugar that will build an object with `__iter__` and `__next__` methods from that function. What you can do in rust is to create an object that has `__iter__` and `__next__` which you can pass to your python code.

**Comment by inv2004** [comment]
Unfortunately, stuck a bit:

I found one example, but it uses yield:

https://pyo3.rs/master/doc/src/pyo3/types/iterator.rs.html#157

**Comment by inv2004** [comment]
Works perfect. Thank you.

**Comment by jymchng** [comment]
Hi

Just curious if the object I wish to 'yield' is not a struct but a `#[pyfunction]`, how should I be writing this?
