### ISSUE TITLE
Doesn't build on recommended branches/toolchains

### ISSUE THREAD

**Issue by JellyWX** [PyO3/pyo3#258]
PyO3 won't build on my Ubuntu 18.04 (Python 3.6 through APT)

Rustup 1.14.0

Attempted to build on 4 different Rustc versions, listed below:

Rustc STABLE 1.29.0 (What I had installed before I read- failed because of the features macro)
Rustc NIGHTLY 1.32.0 (Lastest nightly- failed with a Rust compiler error)
Rustc NIGHTLY 1.29 2018-07-16 (Version said to be lowest compatible on docs.rs)
Rustc NIGHTLY 1.30 2018-08-18 (Version said to be lowest compatible on the Readme- failed saying the version was too low. Rustup actually didn't have a version dating 2018-08-18 and installed the closest I presume which was 2018-08-17)

About to try some more versions I guess

**Comment by JellyWX** [comment]
Working on Rustc NIGHTLY 1.31 2018-10-09

**Comment by konstin** [comment]
The requirement was involuntarily bumped by https://github.com/rust-lang/rust/issues/55380
