### ISSUE TITLE
"migration guide" link in release notes is broken.

### ISSUE THREAD

**Issue by ericseppanen** [PyO3/pyo3#2594]
In the [release notes for 0.17](https://github.com/PyO3/pyo3/releases/tag/v0.17.0), there is a link for the [migration guide](https://pyo3.rs/v0.17.0/migration.html), and that link returns a 404 error page.

**Comment by davidhewitt** [comment]
Thanks for reporting; we were having trouble with DNS, I think this is now resolved.
