### ISSUE TITLE
Support for exceptions with custom data

### ISSUE THREAD

**Issue by bluenote10** [PyO3/pyo3#2597]
I'd like to create a custom exception that contains additional properties, i.e., not just a message-based exception. I assume I'm supposed to use [`create_exception!`](https://docs.rs/pyo3/latest/pyo3/macro.create_exception.html), but I couldn't figure out how to use a custom class with it.

If it is already supported it would be great to document it, otherwise this would be a feature request to support custom data classes for exceptions.

**Comment by davidhewitt** [comment]
We have #295 which talks about this and what remaining work to call this feature "complete". Please join the discussion there, it would be great to have some opinions to help finish this off!

Closing this issue as a duplicate.
