### ISSUE TITLE
Run demo error on MacOS M1

### ISSUE THREAD

**Issue by xunfeng1980** [PyO3/pyo3#2605]
### Bug Description

Run demo error on MacOS M1

### Steps to Reproduce

/Users/lux/.cargo/bin/cargo build --color=always --message-format=json-diagnostic-rendered-ansi --bin pyo3-demo --manifest-path /Users/lux/src/github.com/xunfeng1980/rust-study/crates/pyo3-demo/Cargo.toml
   Compiling pyo3-demo v0.1.0 (/Users/lux/src/github.com/xunfeng1980/rust-study/crates/pyo3-demo)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/var/folders/f0/gy549lln5dvg6hgqm13fjj7m0000gn/T/rustcjwACRV/symbols.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.16bni2wbes2ce9km.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.2nw3zer2nsxabc6d.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.35wfhqdjzks2dzw3.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.38qygprujr5f7fw8.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.3a1zadpd29cpdir0.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.3h4c884py4uzy7me.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.3h7qgz5oytl5npp3.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.3hjo2mh75vd7avp0.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.3uito4yvy9vcx3mj.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.42b2lj73oz90yjg0.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.47zhinwz3ns525vo.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.4eycmq61varf59k2.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.4ijxsg1yyhkkecn6.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.4mkmmjeltfdr1xke.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.4t3yrq8osdqqsl0x.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.4zhsrptxk9azuc8m.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.51y5vzqv5yecd4vl.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.53mv1560o8n4kmgl.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.56mxjvz450drxdvm.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.fr819zhun9jjuno.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.ot06ig45dgve61k.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.s9ld7nipn99p3xb.rcgu.o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a.2w2sq7u640nv5pb9.rcgu.o" "-L" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps" "-L" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libpyo3-fc517cc7da2a3fc7.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libmemoffset-d9adb3cfcd75f234.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libparking_lot-76b1757e52b1757e.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libparking_lot_core-6f03426115b4dc1d.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libcfg_if-e6509c5f025d8702.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libsmallvec-189ef8f70668ca0f.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/liblock_api-7fbb72b6cfc1b0c6.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libscopeguard-eb1e61010332a1cf.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libpyo3_ffi-e36f72483a255b7f.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/liblibc-5666b5f002ccdb48.rlib" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/libunindent-d1f558f03edeee6e.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-3019167bb774d6f7.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-5d6c50a5511d5b38.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-44703751ec754c6f.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-d6f3bfbb73711004.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-44af0db03be329d2.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-9dc78b50bf1c45c0.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-8697aceef2377a94.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-2af5cab8ea27cc2f.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-a80be289d3b85f20.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-85181678fc783242.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-4e642e6b12910c5b.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-b67175a3e890da31.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-1ba63ac4e9539424.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-58428a237963e73e.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-7512abb04e6cb940.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-880986a981365e05.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-a8a859a864856684.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-908209eee60fb642.rlib" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-cb46d4fa30adb098.rlib" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/lux/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/deps/pyo3_demo-7e16cb16b31d629a" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture arm64:
            "_PyBytes_AsString", referenced from:
                pyo3::types::bytes::PyBytes::as_bytes::h1d60f1c62994301e in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_PyBytes_Size", referenced from:
                pyo3::types::bytes::PyBytes::as_bytes::h1d60f1c62994301e in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_PyErr_Fetch", referenced from:
                pyo3::err::PyErr::take::h0b304e8cce90a5c6 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyErr_NewExceptionWithDoc", referenced from:
                pyo3::err::PyErr::new_type::hb4e4f048ead8c810 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyErr_NormalizeException", referenced from:
                pyo3::err::PyErr::make_normalized::h493e8dd84824d8d5 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyErr_Print", referenced from:
                pyo3::err::panic_after_error::h88c98b870344240f in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyErr_PrintEx", referenced from:
                pyo3::err::PyErr::take::h0b304e8cce90a5c6 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyErr_Restore", referenced from:
                pyo3::err::PyErr::take::h0b304e8cce90a5c6 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyEval_SaveThread", referenced from:
                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::hc209b934268d1072 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "_PyExc_BaseException", referenced from:
                _$LT$pyo3..exceptions..PyBaseException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::h546ba5e8bd8107b4 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.1.rcgu.o)
            "_PyExc_TypeError", referenced from:
                _$LT$pyo3..exceptions..PyTypeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::hcdc060a4eb088ab2 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.1.rcgu.o)
            "_PyExc_ValueError", referenced from:
                _$LT$pyo3..exceptions..PyValueError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::haa8d35abcdf35d7d in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.1.rcgu.o)
            "_PyGILState_Ensure", referenced from:
                pyo3::gil::GILGuard::acquire_unchecked::hdff1d3b704633dd5 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "_PyGILState_Release", referenced from:
                _$LT$pyo3..gil..GILGuard$u20$as$u20$core..ops..drop..Drop$GT$::drop::hd5afd861d463ce9a in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "_PyImport_ExecCodeModuleEx", referenced from:
                pyo3::types::module::PyModule::from_code::h01825747271d5ded in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.9.rcgu.o)
            "_PyModule_Type", referenced from:
                pyo3_ffi::moduleobject::PyModule_Check::h2bffb470904d63cb in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.10.rcgu.o)
            "_PyObject_Call", referenced from:
                pyo3::instance::Py$LT$T$GT$::call::h0be31e809135bf6b in pyo3_demo-7e16cb16b31d629a.s9ld7nipn99p3xb.rcgu.o
                pyo3::instance::Py$LT$T$GT$::call::h87b48caa7f7a0495 in pyo3_demo-7e16cb16b31d629a.s9ld7nipn99p3xb.rcgu.o
            "_PyObject_CallNoArgs", referenced from:
                pyo3::instance::Py$LT$T$GT$::call0::hd204632c4041b767 in pyo3_demo-7e16cb16b31d629a.s9ld7nipn99p3xb.rcgu.o
            "_PyObject_GetAttr", referenced from:
                pyo3::types::any::PyAny::getattr::h0401a0db1ad47b53 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
                pyo3::types::any::PyAny::getattr::h84eb164fe6f91496 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "_PyObject_Repr", referenced from:
                pyo3::types::any::PyAny::repr::h83941ab98b9ecdae in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "_PyTuple_New", referenced from:
                pyo3::types::tuple::new_from_iter::h1abc2f00b5ec8687 in pyo3_demo-7e16cb16b31d629a.38qygprujr5f7fw8.rcgu.o
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$C$T2$RP$$GT$::into_py::h2f37b4e0f9678781 in pyo3_demo-7e16cb16b31d629a.4eycmq61varf59k2.rcgu.o
            "_PyTuple_SetItem", referenced from:
                pyo3::types::tuple::_$LT$impl$u20$pyo3..conversion..IntoPy$LT$pyo3..instance..Py$LT$pyo3..types..tuple..PyTuple$GT$$GT$$u20$for$u20$$LP$T0$C$T1$C$T2$RP$$GT$::into_py::h2f37b4e0f9678781 in pyo3_demo-7e16cb16b31d629a.4eycmq61varf59k2.rcgu.o
            "_PyType_IsSubtype", referenced from:
                pyo3_ffi::object::PyObject_TypeCheck::h243088d102540099 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.11.rcgu.o)
            "_PyUnicode_AsEncodedString", referenced from:
                pyo3::types::string::PyString::to_string_lossy::h5d640b43468df22d in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_PyUnicode_AsUTF8AndSize", referenced from:
                pyo3::types::string::PyString::to_str::h9ed455683d40bade in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_PyUnicode_FromStringAndSize", referenced from:
                pyo3::types::string::PyString::new::hee34f62daacf0262 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
                pyo3::types::string::PyString::intern::h7e1ae79b7b67bdc1 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_PyUnicode_InternInPlace", referenced from:
                pyo3::types::string::PyString::intern::h7e1ae79b7b67bdc1 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_Py_CompileStringExFlags", referenced from:
                pyo3_ffi::cpython::pythonrun::Py_CompileString::hb7eee2ffb17c8061 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.5.rcgu.o)
            "_Py_InitializeEx", referenced from:
                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::hc209b934268d1072 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "_Py_IsInitialized", referenced from:
                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::hc209b934268d1072 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
                pyo3::gil::GILGuard::acquire::_$u7b$$u7b$closure$u7d$$u7d$::h17dea90a330625d2 in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.13.rcgu.o)
            "__Py_Dealloc", referenced from:
                pyo3_ffi::object::Py_DECREF::h7252db0acf248f50 in pyo3_demo-7e16cb16b31d629a.35wfhqdjzks2dzw3.rcgu.o
                pyo3_ffi::object::Py_DECREF::h1668feaedf34ab9d in libpyo3-fc517cc7da2a3fc7.rlib(pyo3-fc517cc7da2a3fc7.pyo3.54bd611a-cgu.11.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `pyo3-demo` due to 2 previous errors
Process finished with exit code 101

### Your operating system and version

Darwin luxdeMacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Mon Aug 15 20:06:40 PDT 2022; root:xnu-8792.40.29.161.2~1/RELEASE_ARM64_T8103 arm64

### Your Python version (`python --version`)

Python 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ] :: Anaconda, Inc. on darwin

### Your Rust version (`rustc --version`)

 rustc --version rustc 1.65.0-nightly (0b79f758c 2022-08-18)

### Your PyO3 version

0.17.1

### How did you install python? Did you use a virtualenv?

conda

### Additional Info

 1

**Comment by davidhewitt** [comment]
Hi, can you share your `Cargo.toml` file? Do you use `setuptools-rust` or `maturin`?

Can you please run `PYO3_PRINT_CONFIG=1 cargo build` and share the output?

**Comment by xunfeng1980** [comment]
Cargo.toml
```
https://github.com/xunfeng1980/rust-study/tree/main/crates/pyo3-demo
```

no setuptools-rust or maturin.

build with PYO3_PRINT_CONFIG=1
```
/Users/lux/.cargo/bin/cargo build --color=always --message-format=json-diagnostic-rendered-ansi --bin pyo3-demo --manifest-path /Users/lux/src/github.com/xunfeng1980/rust-study/crates/pyo3-demo/Cargo.toml
   Compiling target-lexicon v0.12.4
   Compiling proc-macro2 v1.0.43
   Compiling syn v1.0.99
   Compiling unindent v0.1.10
   Compiling indoc v1.0.7
   Compiling memoffset v0.6.5
   Compiling quote v1.0.21
   Compiling pyo3-build-config v0.17.1
   Compiling pyo3-macros-backend v0.17.1
   Compiling pyo3-ffi v0.17.1
   Compiling pyo3 v0.17.1
error: failed to run custom build command for `pyo3-ffi v0.17.1`
Caused by:
  process didn't exit successfully: `/Users/lux/src/github.com/xunfeng1980/rust-study/target/debug/build/pyo3-ffi-aaaec387dcd4a431/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_CROSS
  cargo:rerun-if-env-changed=PYO3_CROSS_LIB_DIR
  cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_VERSION
  cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_IMPLEMENTATION
  cargo:rerun-if-env-changed=PYO3_PRINT_CONFIG
  -- PYO3_PRINT_CONFIG=1 is set, printing configuration and halting compile --
  implementation=CPython
  version=3.9
  shared=true
  abi3=false
  lib_name=python3.9
  lib_dir=/Users/lux/opt/miniconda3/lib
  executable=/Users/lux/opt/miniconda3/bin/python
  pointer_width=64
  build_flags=
  suppress_build_script_link_lines=false
  note: unset the PYO3_PRINT_CONFIG environment variable and retry to compile with the above config
warning: build failed, waiting for other jobs to finish...
Process finished with exit code 101
```

**Comment by davidhewitt** [comment]
Try changing `features = ["extension_module"]` with `features = ["auto-initialize"]`. You're building a binary, not an extension module, so you've got the wrong feature set activated.

**Comment by xunfeng1980** [comment]
it work,thx.

**Comment by chishui** [comment]
I found many posts about this issue, and this post acturally works, this should be put into FAQ. Thanks
