### ISSUE TITLE
`val` ndarray object cannot be converted to `Sequence`

### ISSUE THREAD

**Issue by ritchie46** [PyO3/pyo3#2615]
In updating to pyo3/numpy 0.17 upstream in polars we've hit the case where we have a function that accepts a `Vec<T>` where `T:  FromPyObject` to do the conversion from any sequence passed from python.

This function is opaque to use, in that anything that can be converted to a `Vec<>` is fine. Such as lists, tuples, but also numpy arrays.

Now with updating it seems that this design is not possible anymore. Is this intentional? 

What would be the recommended function signature for such generic sequence?

**Comment by ritchie46** [comment]
We have a few conversion from python to our types. So I assume it is `T: FromPyObject`. Further encountered types were `String` types. 

Here are a few examples of types that failed. I think the common denominator is the `FromPyObject` trait conversion.

# ObjectValue (an opaque python object)

```rust
#[derive(Clone, Debug)]
#[repr(transparent)]
pub struct ObjectValue {
    pub inner: PyObject,
}

impl From<PyObject> for ObjectValue {
    fn from(p: PyObject) -> Self {
        Self { inner: p }
    }
}

impl<'a> FromPyObject<'a> for ObjectValue {
    fn extract(ob: &'a PyAny) -> PyResult<Self> {
        Python::with_gil(|py| {
            Ok(ObjectValue {
                inner: ob.to_object(py),
            })
        })
    }
}

```

# AnyValue (An enum over our allowed values )

```rust
impl<'s> FromPyObject<'s> for Wrap<AnyValue<'s>> {
    fn extract(ob: &'s PyAny) -> PyResult<Self> {
        if ob.is_instance_of::<PyBool>().unwrap() {
            Ok(AnyValue::Boolean(ob.extract::<bool>().unwrap()).into())
        } else if let Ok(v) = ob.extract::<i64>() {
            Ok(AnyValue::Int64(v).into())
        } else if let Ok(v) = ob.extract::<f64>() {
            Ok(AnyValue::Float64(v).into())
        } else if let Ok(v) = ob.extract::<&'s str>() {
            Ok(AnyValue::Utf8(v).into())
        } else if ob.get_type().name()?.contains("datetime") {
            Python::with_gil(|py| {
                // windows
                #[cfg(target_arch = "windows")]
                {
                    let kwargs = PyDict::new(py);
                    kwargs.set_item("tzinfo", py.None())?;
                    let dt = ob.call_method("replace", (), Some(kwargs))?;

                    let pypolars = PyModule::import(py, "polars").unwrap();
                    let localize = pypolars
                        .getattr("utils")
                        .unwrap()
                        .getattr("_localize")
                        .unwrap();
                    let loc_tz = localize.call1((dt, "UTC"));

                    loc_tz.call_method0("timestamp")?;
                    // s to us
                    let v = (ts.extract::<f64>()? * 1000_000.0) as i64;
                    Ok(AnyValue::Datetime(v, TimeUnit::Microseconds, &None).into())
                }
                // unix
                #[cfg(not(target_arch = "windows"))]
                {
                    let datetime = PyModule::import(py, "datetime")?;
                    let timezone = datetime.getattr("timezone")?;
                    let kwargs = PyDict::new(py);
                    kwargs.set_item("tzinfo", timezone.getattr("utc")?)?;
                    let dt = ob.call_method("replace", (), Some(kwargs))?;
                    let ts = dt.call_method0("timestamp")?;
                    // s to us
                    let v = (ts.extract::<f64>()? * 1_000_000.0) as i64;
                    // we choose us as that is pythons default unit
                    Ok(AnyValue::Datetime(v, TimeUnit::Microseconds, &None).into())
                }
            })
        } else if ob.is_none() {
            Ok(AnyValue::Null.into())
        } else if ob.is_instance_of::<PyDict>()? {
            let dict = ob.downcast::<PyDict>().unwrap();
            let len = dict.len();
            let mut keys = Vec::with_capacity(len);
            let mut vals = Vec::with_capacity(len);
            for (k, v) in dict.into_iter() {
                let key = k.extract::<&str>()?;
                let val = v.extract::<Wrap<AnyValue>>()?.0;
                let dtype = DataType::from(&val);
                keys.push(Field::new(key, dtype));
                vals.push(val)
            }
            Ok(Wrap(AnyValue::StructOwned(Box::new((vals, keys)))))
        } else if ob.is_instance_of::<PyList>()? {
            if ob.is_empty()? {
                Ok(Wrap(AnyValue::List(Series::new_empty("", &DataType::Null))))
            } else {
                let avs = ob.extract::<Wrap<Row>>()?.0;
                let s = Series::new("", &avs.0);
                Ok(Wrap(AnyValue::List(s)))
            }
        } else if ob.hasattr("_s")? {
            let py_pyseries = ob.getattr("_s").unwrap();
            let series = py_pyseries.extract::<PySeries>().unwrap().series;
            Ok(Wrap(AnyValue::List(series)))
        } else if ob.get_type().name()?.contains("date") {
            Python::with_gil(|py| {
                let date = py_modules::UTILS
                    .getattr(py, "_date_to_pl_date")
                    .unwrap()
                    .call1(py, (ob,))
                    .unwrap();
                let v = date.extract::<i32>(py).unwrap();
                Ok(Wrap(AnyValue::Date(v)))
            })
        } else if ob.get_type().name()?.contains("timedelta") {
            Python::with_gil(|py| {
                let td = py_modules::UTILS
                    .getattr(py, "_timedelta_to_pl_timedelta")
                    .unwrap()
                    .call1(py, (ob, "us"))
                    .unwrap();
                let v = td.extract::<i64>(py).unwrap();
                Ok(Wrap(AnyValue::Duration(v, TimeUnit::Microseconds)))
            })
        } else {
            Err(PyErr::from(PyPolarsErr::Other(format!(
                "row type not supported {:?}",
                ob
            ))))
        }
    }
}
```

**Comment by aganders3** [comment]
It sounds like it's the outer (sequence) type that's causing the issue, not the inner (item) type. If so I think it is indeed a victim of the breaking change introduced by #2477. 😕

Unfortunately `np.ndarray` is a case where it would pass the old check that used [`PySequence_Check`](https://docs.python.org/3/c-api/sequence.html#c.PySequence_Check) but not the new check that requires `isinstance(np.ndarray, collections.abc.Sequence) == True`.

If the `PySequence_Check` is sufficient for this use perhaps we can replace the downcast in rust-numpy or polars to provide the old behavior with `try_from_unchecked` (unsafe, of course).

Sorry if I'm off the mark here but as a fan of both rust-numpy and polars I'm motivated to find a good fix for this and will do my best to help.

**Comment by adamreichold** [comment]
> If the PySequence_Check is sufficient for this use perhaps we can replace the downcast in rust-numpy or polars to provide the old behavior with try_from_unchecked (unsafe, of course).

I think the code that needs to be relaxed is

> EDIT: More specifically, the extract_sequence helper function defined [here](https://github.com/PyO3/pyo3/blob/8797a6f7990a911e36c1bbf7b5859d5c9a5b1542/src/types/sequence.rs#L302).

as this - passing `np.ndarray` from Python where a Rust extension expected `Vec` - used to work with plain PyO3 without involving code in rust-numpy or polars.

I guess we could implement `extract_sequence` without the help of `PySequence`. Or we could manually call `PySequence_Check` and then `PySequence::try_from_unchecked`.

**Comment by aganders3** [comment]
I don't want to over-focus on `np.ndarray` because I think this bug report was more general, but taking that specific example I think downcasting it to a `PySequence` is actually wrong. For example `np.ndarray` has no `index()` method. That's not a problem specifically for `extract_sequence` but it would be for other uses.

To your point though I suppose there could be a more relaxed version of `extract_sequence` that would work for this and other use cases - maybe via `PyIterator` instead? It looks like that's what `sequence::extract_sequence` ultimately requires right now.

**Comment by adamreichold** [comment]
@davidhewitt I think it would personally prefer to manually call `PySequence_Check` and then use `PySequence::try_from_unchecked` as I think missing methods would only yield errors, not unsafety.

Switching the implementation to `PyIterator` would cost us the ability to call `with_capacity` to preallocate the `Vec` which seems an unnecessary loss considering the relevant types here do implement enough of the sequence protocol.

**Comment by Billyangnz** [comment]
This issue seems to not have been fixed yet. I am getting _TypeError: argument 'oned': 'ndarray' object cannot be converted to 'Sequence'_  running test.py with the following files:

src/lib.rs
```
use pyo3::prelude::*;

#[pyclass(module = "rust_module")]
#[derive(Default, Debug, serde::Serialize, serde::Deserialize, Clone)]
pub struct DummyClass{
    name: String,
    oned: [f64;3],
    twod: [[f64;3];3],
}

#[pymethods]
impl DummyClass {
    #[new]
    pub fn pynew(
        name: String,
        oned: [f64;3],
        twod: [[f64;3];3],
    ) -> PyResult<Self>{
        Ok(Self { name, oned, twod})
    }

    fn __call__(&self) -> PyResult<String>{
        Ok("Success".into())
    }
}

#[pymodule]
fn pyo3_pure(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<DummyClass>()?;
    Ok(())
}

```

Cargo.toml

```
[package]
name = "reproduce-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.17.2", features = ["serde", "abi3-py37", "extension-module"] }
numpy = { version = "^0.17.2" }
serde = { version = "^1.0", features = ["derive"]}

[lib]
name = "pyo3_pure"
crate-type = ["cdylib"]

```

pyproject.toml
```
[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"

[project]
# The name pyo3_pure instead of pyo3-pure is intentional,
# it's used as a crate name resolution regression test
name = "pyo3_pure"
version = "0.1.0"

dependencies = [
    "numpy"
]
```

test.py
```
from pyo3_pure import DummyClass
import numpy as np

# test = DummyClass("hello",[0,0,0],[[0,0,0],[0,0,0],[0,0,0]])
test = DummyClass("hello",np.array([0,0,0]),np.array([[0,0,0],[0,0,0],[0,0,0]]))

print(test())
```

**Comment by adamreichold** [comment]
> This issue seems to not have been fixed yet. I am getting _TypeError: argument 'oned': 'ndarray' object cannot be converted to 'Sequence'_ running test.py with the following files:

This is a slightly different code path affected by the same underlying issue. The OP reported failures to extract `Vec<T>` whereas this is a failure to extract `[T; N]` which we failed to consider we authoring the initial fix. Could you open a separate issue here so we can track that properly? Thanks!

**Comment by jjerphan** [comment]
Hi all,

First, thank you for working on PyO3 ! 🙌

Currently we are facing a similar problem in https://github.com/pola-rs/polars/pull/6531 when trying to upgrade Py03 to 0.18.0.

We are planning in the mean time to introduce a constructor for this case.

Do you think this is a good approach? Do you have any recommendations?

Thanks!

**Comment by adamreichold** [comment]
@jjerphan Py03 0.18 does contain the fix and we do test for this, c.f. https://github.com/PyO3/pyo3/blob/v0.18.0/pytests/tests/test_sequence.py#L28

Can you add more details of what is failing and how?
