### ISSUE TITLE
NonZero Int type support

### ISSUE THREAD

**Issue by MiguelX413** [PyO3/pyo3#2650]
Implementing FromPyObject for NonZero int types.
I think it'd be a great minor feature, but far from necessary.

**Comment by davidhewitt** [comment]
Agreed, I'd be very happy if someone was interested in adding this.

I've also wanted support for the `ordered-float` crate in the past for `NotNan` types, so would happily accept that as an optional feature like our other thirdparty conversion features.

**Comment by MiguelX413** [comment]
> Agreed, I'd be very happy if someone was interested in adding this.
> 
> I've also wanted support for the `ordered-float` crate in the past for `NotNan` types, so would happily accept that as an optional feature like our other thirdparty conversion features.

That sounds like a great idea! I'll see if I'm at a level good enough to add them myself.

**Comment by davidhewitt** [comment]
Thanks for the interest! Have a look at the contents in https://github.com/PyO3/pyo3/tree/main/src/conversions. 

I'd suggest putting these in `conversions/std/num.rs` and `conversions/ordered_float.rs`. I'd do them as separate PRs to keep reviews simpler and easier to track history.

Please ask if there are any parts which seem unclear which you'd like clarification.
