### ISSUE TITLE
Interface to `deque` type

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#2655]
I'm a bit unclear on how [`deque`](https://docs.python.org/3/library/collections.html#collections.deque) works, it seems implemented in c but isn't (as far as I can tell) exposed via the c-api.

Is there any possibility that pyo3 could expose a `PyDeque` type? Or should I use

```rust
let deque = py.import("collections")?.getattr("deque")?;
...
```
?

**Comment by birkenfeld** [comment]
You are right, it is not exposed in the C API, the type object is private and all its methods are `static`.

PyO3 couldn't give you more than going via the generic Python API (using `getattr`, `call_method`, `get_item` etc.), so I don't think we should pretend otherwise.

**Comment by samuelcolvin** [comment]
Agreed, thanks for confirming.
