### ISSUE TITLE
`#[pyo3(get, set)]` for wrapper types 

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2659]
As an offhand thought, I wonder if we should be trying to make `Cell<T>` automatically work with `#[pyo3(get)]`? (And similar for other wrapper types such as `Box<T>` or `Mutex<T>`?)

Out of scope of this PR of course.

_Originally posted by @davidhewitt in https://github.com/PyO3/pyo3/pull/2657#discussion_r987222272_

----

Presumably there could be a trait which becomes part of the public PyO3 API to control this for people who wanted to implement it.

@mejrs suggested in the original thread that it might be too far to support `Mutex`, and I'm inclined to agree, we can see what makes sense if someone comes forward with a design.

**Comment by adamreichold** [comment]
> @mejrs suggested in the original thread that it might be too far to support `Mutex`, and I'm inclined to agree, we can see what makes sense if someone comes forward with a design.

I would like to suggest to use the `Deref` trait as the blue print for this behaviour, i.e. it should never fail and be free of side effects, so basically just unwrapping plain memory, e.g. removing pure type-level layers or following a pointer.

**Comment by mejrs** [comment]
> I would like to suggest to use the `Deref` trait as the blue print for this behaviour, i.e. it should never fail and be free of side effects, so basically just unwrapping plain memory, e.g. removing pure type-level layers or following a pointer.

I'm worried about running into conflicting impls if we do that:

```rust
use core::cell::Cell;
use core::ops::Deref;

pub trait IntoPy {
    // ...
}

impl<T: Copy> IntoPy for Cell<T> {}
impl<T: Deref<Target = P>, P: IntoPy> IntoPy for T {}
```

```
error[[E0119]](https://doc.rust-lang.org/stable/error-index.html#E0119): conflicting implementations of trait `IntoPy` for type `std::cell::Cell<_>`
 --> src/lib.rs:9:1
  |
8 | impl<T: Copy> IntoPy for Cell<T> {}
  | -------------------------------- first implementation here
9 | impl<T: Deref<Target = P>, P: IntoPy> IntoPy for T {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `std::cell::Cell<_>`
  |
  = note: upstream crates may add a new impl of trait `std::ops::Deref` for type `std::cell::Cell<_>` in future versions

For more information about this error, try `rustc --explain E0119`.
```

**Comment by adamreichold** [comment]
> I'm worried about running into conflicting impls if we do that:

I meant this only conceptually, not literally. As a guideline on which impls make sense and which do not, e.g. `Cell` is alright (even though it cannot implement `Deref` itself) because it is just memory. But `RefCell` is not (can fail) and `Mutex` is not (can block).

**Comment by AntoineRR** [comment]
Hi, I would like to try working on this as a first contribution to pyo3. From what I understand, the goal is to be able to set a default getter/setter for wrapper struct themselves (and not the field they contain as it is currently already doable), something like

```
#[pyclass]
#[pyo3(get, set)]
struct Wrapper(PyString);  // Or wrap any type implementing `IntoPy`
```
And from Python
```
wrapped = Wrapper("")
wrapper += "test"  # This works because Wrapper is derefed into a `str`
```

Am I understanding this correctly?

**Comment by adamreichold** [comment]
@AntoineRR I think this is basically correct, but the main issue discussed above is which trait bound is appropriate for the wrapped/inner type, i.e. `IntoPy` without further specific is most likely not sufficient. My personal guess is that you man to introduce a new trait for all types which can be wrapped transparent in a sensible manner and then provide useful blanket impls where appropriate.

**Comment by AntoineRR** [comment]
Ok thanks for pointing this. I will start working on this and try to come up with a relevant design.

**Comment by AntoineRR** [comment]
Hey, I took a deeper look at the code of pyo3 and tested some things, and I came to the conclusion I may have misunderstood the initial goal for this issue. I'm not sure what I described in my previous comment really is doable, except maybe if `#[pyo3(get, set)]` on a struct would implement all the `__add__`, `__mul__` and other dunder methods to expose the inner field.

After reading the description again, I thought the goal for this issue may be to do something like this instead and be able to use the inner `String` and `u32` types from Python ?
```rust
#[pyclass]
struct ComplexStruct {
    #[pyo3(get, set)]
    field: Wrapper<String>,
    #[pyo3(get, set)]
    cell_field: Cell<u32>
}
```

If that is correct, here is a breakdown of how I think it could be implemented using a trait:
- Define a trait with a `get` and `set` method.
- This trait can be implemented automatically via the `#[pyo3(get, set)]` macro for any wrapper struct or struct with a single field (just return the first field)
- This trait can be implemented manually for struct `A` to define a more complex behavior and be able to use `#[pyo3(get, set)]` on a field of a struct `B` with type `A`.
- the `#[pyo3(get, set)]` macro will call the method of this trait to set everything that is required for getting and setting the field from Python

However this trait would kind of conflict with the `#[getter]` and `#[setter]` macros? Or maybe it is doable to not use a trait and provide a default getter/setter method directly? So what is your opinion on all this and could I get more details on what really is expected for this issue?
Sorry for all those questions, I would like to make sure I have a good understanding of the feature before implementing something.

**Comment by mejrs** [comment]
My understanding is that there'd just be a bunch of new impls, e.g.
```rust
impl<T: Copy> IntoPy for Cell<T> { ... }
```

**Comment by mejrs** [comment]
> My personal guess is that you'll want to introduce a new trait for all types which can be wrapped transparent in a sensible manner

This does not seem the right approach to me.

**Comment by AntoineRR** [comment]
I didn't figure `#[pyo3(get)]` used `IntoPy` under the hood. I tested it by implementing `IntoPy` for `Cell<T>` as you suggested and it does seem to work! I should be set to really get started now, thanks!
