### ISSUE TITLE
Support specifying __name__ and __doc__ in PyCFunction::new_closure

### ISSUE THREAD

**Issue by dalcde** [PyO3/pyo3#2665]
This seems fairly easy to support if we only accept `&'static str` as the
arguments. These arguments are mostly useful only when the function lives
forever, so users who have an owned string can simply leak it to get a
`&'static str`.

I'm not sure what the correct API change would be. Having e.g.
`PyCFunction::new_closure_with_name_and_doc` would be backwards compatible but
the duplication of APIs could be annoying in the long run.

**Comment by davidhewitt** [comment]
Sure thing, we already did similar to `PyErr::new_type` in [#2027](https://github.com/PyO3/pyo3/pull/2027/files#diff-1ee6ab4e82cb9604cb3d8c518ebddb5ebeed323959201c9a93e5c498375019e8R355).

A PR to change `PyCFunction::new_closure` to have additional extra arguments as a breaking change in 0.18 would be ok in my opinion.
