### ISSUE TITLE
ContextManager types, Python `with` syntax

### ISSUE THREAD

**Issue by mladedav** [PyO3/pyo3#2679]
I would like to create an object that can be used with `with` such as:
```
with create_foo() as f:
    f.work()
```

On Python level, this object needs two methods, `__enter__` and `__exit__`. Both can be created with `#[pyo3(name = "__enter__")]` but the `__exit__` methods has four arguments including self. The types of the positional arguments are `type`, `Exception` and `traceback`. I am unable to either find objects that can represent these in Rust, or use `PyAny` or anything else since I do not care for the values themselves. If I put arbitrary types there, an exception is thrown because of bad types.

I think this would be possible if types are added for `type` and `traceback`. Or rather `PyType` could implement `PyClass` so that it can be  used as a function argument.

**Comment by birkenfeld** [comment]
I didn't understand why PyAny does not work for your?

**Comment by mladedav** [comment]
I'm sorry, you're right that `PyAny` works. I just tried to use an owned version instead of a reference so I got an error. So this was mostly an issue on my part in understanding the usage of `PyAny`.

It works with the following method:
```
    #[pyo3(name = "__exit__")]
    fn exit(&mut self, py: Python<'_>, _exception_type: Option<&PyType>, _exception_value: Option<&PyException>, _traceback: &PyAny)
```

So this issue is solved except for the traceback object which I personally don't need. I will create a pull request [here](https://pyo3.rs/latest/class/protocols.html) unless you think there is another place where this can be mentioned.

Thanks for your help.

**Comment by davidhewitt** [comment]
@mladedav, extra documentation there would be very welcome!

There is also [`PyTraceback`](https://docs.rs/pyo3/latest/pyo3/types/struct.PyTraceback.html) as a type, so I think you should be able to do `_traceback: Option<&PyTraceback>` for the last argument?

**Comment by birkenfeld** [comment]
Yes, since the pyproto removal we kind of lack documentation for special methods that *aren't* specially handled by PyO3...
