### ISSUE TITLE
Check 2018 ergonomics for macros

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#269]
Macros need some adaptions to be properly importable with the 2018 edition. See the [edition guide](https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html?highlight=macro#macros-with-crate-prefix) for details. If you've confirmed that you can use a macro with the new path imports please update or comment:

 - [ ] import_exception
 - [ ] int_convert_bignum
 - [ ] int_fits_larger_int
 - [ ] py_exception
 - [ ] pyobject_downcast
 - [ ] pyobject_native_type
 - [ ] pyobject_native_type_convert
 - [ ] pyobject_native_type_named
 - [x] wrap_function

**Comment by discosultan** [comment]
Considering `wrap_function!` is used in the getting started guide, it would be nice if it was included in prelude for easy import in 2018 edition.

Currently the sample requires:
```rust
use pyo3::prelude::*;
use pyo3::wrap_function;
```

**Comment by Alexander-N** [comment]
How about we add examples which use 2018 edition imports? This way the doctests would ensure that it works.

**Comment by konstin** [comment]
@discosultan I'd like to keep the prelude as small as possible, and especially since the macro namespace still behaves a bit weird I'd like to keep that explicit.

**Comment by konstin** [comment]
@Alexander-N That's a good idea!

This issue in general is meant for small contributions to the projects that also beginners can do: Pick a macro, add an example as (doc-)test, maybe fix a line here until the compiler is happy and make a pull request.

**Comment by davidhewitt** [comment]
It's been quite some time since the 2018 edition, so I'm closing this issue. I think if these macros didn't work with 2018 ergonomics it would have been fixed by now.
