### ISSUE TITLE
Allow any object as "type" in `is_instance`

### ISSUE THREAD

**Issue by birkenfeld** [PyO3/pyo3#2694]
### Discussed in https://github.com/PyO3/pyo3/discussions/2693

<div type='discussions-op-text'>

<sup>Originally posted by **samuelcolvin** October 18, 2022</sup>
I'd like to do an `is_instance` check with `typing.Sequence`, however

```rs
let sequence_type: &PyType = sequence_obj.extract();
```

Is failing with `TypeError: '_SpecialGenericAlias' object cannot be converted to 'PyType'`.

Is this a fundamental limitation of the python C API, or something that pyo3 could support?

Mostly for my record, here's the failing test from [pydantic-core](https://github.com/pydantic/pydantic-core):

```py
def test_is_instance_sequence():
    v = SchemaValidator({'type': 'is-instance', 'cls': typing.Sequence})
    assert v.isinstance_python(1) is False
    assert v.isinstance_python([1]) is True
```

Fails when creating the `SchemaValidator` with:

```
    def test_is_instance_sequence():
>       v = SchemaValidator({'type': 'is-instance', 'cls': typing.Sequence})
E       pydantic_core._pydantic_core.SchemaError: Error building "is-instance" validator:
E         TypeError: '_SpecialGenericAlias' object cannot be converted to 'PyType'

tests/validators/test_is_instance.py:204: SchemaError
```

**Comment by birkenfeld** [comment]
So to fix this, we could either change `is_instance` to take any `&PyAny` as the type argument, or add another API for this case.

Since the current `is_instance` does nothing that would require `&PyType`, I'd vote for this, although it is of course a breaking change.

**Comment by birkenfeld** [comment]
Same for `is_subclass` on `PyType` I guess. `PyType::is_instance` is already deprecated.

**Comment by samuelcolvin** [comment]
Also worth noting that tuples and unions are valid arguments to `is_instance`, as well as types.
