### ISSUE TITLE
failed inheritance in python after adding `subclass` attribute to `pyclass` 

### ISSUE THREAD

**Issue by calbaker** [PyO3/pyo3#2701]
### Bug Description

I have an example of a pyo3 subclass failing to be inherited from in Python.  I tried using subclass in a pyclass in https://github.com/NREL/fastsim (can grant access to this private repo if needed), and when I tried:

``` python
import fastsimrust as fsr
import fastsim as fsim
class ChildVehicle(fsr.RustVehicle):
    def get_veh_kg(self) -> float:
        return self.veh_kg

veh = ChildVehicle.from_file(str(fsim.package_root() / 'resources/vehdb/2012_Ford_Fusion.yaml'))

veh.get_veh_kg()
```

this happened:

``` python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [12], line 7
      3         return self.veh_kg
      5 veh = ChildVehicle.from_file(str(fsim.package_root() / 'resources/vehdb/2012_Ford_Fusion.yaml'))
----> 7 veh.get_veh_kg()

AttributeError: 'fastsimrust.RustVehicle' object has no attribute 'get_veh_kg'

Note that on the Rust side, we use a proc macro to add the pyo3 attributes so it'll look a little wonky to anyone who looks into the Rust code.
@birkenfeld 
```

### Steps to Reproduce

1. Give me your github user name so I can give you access to https://github.com/NREL/fastsim.
2. Clone and install by following the instructions in `fastsim/fastsim/docs/README.md`
3. run this code
``` python
import fastsimrust as fsr
import fastsim as fsim
class ChildVehicle(fsr.RustVehicle):
    def get_veh_kg(self) -> float:
        return self.veh_kg

veh = ChildVehicle.from_file(str(fsim.package_root() / 'resources/vehdb/2012_Ford_Fusion.yaml'))

veh.get_veh_kg()
```

### Backtrace

```shell
python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [12], line 7
      3         return self.veh_kg
      5 veh = ChildVehicle.from_file(str(fsim.package_root() / 'resources/vehdb/2012_Ford_Fusion.yaml'))
----> 7 veh.get_veh_kg()

AttributeError: 'fastsimrust.RustVehicle' object has no attribute 'get_veh_kg'
```
```


### Your operating system and version

Windows 10

### Your Python version (`python --version`)

3.10.6

### Your Rust version (`rustc --version`)

1.64.0

### Your PyO3 version

0.17.2

### How did you install python? Did you use a virtualenv?

python.org installer

yes, using the command `python -m venv fastsim-venv` in the project folder, and `fastsim-venv` is in `.gitignore`.  

### Additional Info

_No response_

**Comment by birkenfeld** [comment]
Thanks for making a new issue.

Can you share the code of `RustVehicle::from_file`? It is probably a static/class method that returns an instance of `RustVehicle`, so it has no idea about `ChildVehicle`.

It would instead have to be a class method that creates an instance of the class passed to it (which might be a bit involved due to the Rust/Python interface).

**Comment by calbaker** [comment]
@birkenfeld ,

``` rust
pub fn from_file(filename: &str) -> Result<Self, anyhow::Error> {
    let extension = Path::new(filename)
        .extension()
        .and_then(OsStr::to_str)
        .unwrap_or("");

    let file = File::open(filename)?;
    let mut veh_res: Result<RustVehicle, anyhow::Error> = match extension {
        "yaml" => Ok(serde_yaml::from_reader(file)?),
        "json" => Ok(serde_json::from_reader(file)?),
        _ => Err(anyhow!("Unsupported file extension {}", extension)),
    };
    veh_res.as_mut().unwrap().set_derived();
    veh_res
}
```

I can understand how this didn't magically do what I expected.  It's not clear to me that what I had planned to do is worth doing.  I feel like there should be something in the documentation, which I'm happy to write up, making it clear that this _inheritance_ won't work like it would in pure python.

**Comment by calbaker** [comment]
What I could probably do to get the behavior I want is have a subclass `from_file` method that calls the parent class `from_file` method, iterates through the attributes (python equivalent of fields) of the instantiated parent class and assigns the values to identical fields in the instantiated child class, and then returns the child class instance which can have (still have not tested this out) attributes/fields and/or methods that are only in the child class.  

@birkenfeld , does this sound like it'd work?  If yes, I'll test it out, and if it works, I'll close this issue.  I'll also write up a simple example that demonstrates the concepts mentioned above that can go in the docs.

**Comment by davidhewitt** [comment]
You're looking for a `#[classmethod]` - something along the lines of

```rust
#[classmethod]
pub fn from_file(cls: &PyType, filename: &str) -> PyResult<Py<Self>> {
    let instance = cls.call(( /* your args tuple */, /* your kwargs dict */)?
    instance.extract() // cast the &PyAny to Py<Self> to ensure this is a subclass as expected - can make a better error message
}
```

**Comment by calbaker** [comment]
@davidhewitt , interesting!  Let me try to wrap my mind around that, test it out, and then I'll report back.  It may be a few days.

**Comment by birkenfeld** [comment]
>  I feel like there should be something in the documentation, which I'm happy to write up, making it clear that this inheritance won't work like it would in pure python.

@davidhewitt has already given the proper solution using `@classmethod`. I just want to stress that what you were showing would *not* work in pure Python either. It is equivalent to:

```
class RustVehicle:
    def __init__(self, some_param):
        ...

    def from_file(filename):
        return RustVehicle(...)

class PythonVehicle(RustVehicle):
    def get_veh_kg(self):
        return ...

veh = PythonVehicle.from_file("file")
print(veh.get_veh_kg())
```

gives the same exception:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(veh.get_veh_kg())
AttributeError: 'RustVehicle' object has no attribute 'get_veh_kg'
```

**Comment by calbaker** [comment]
@birkenfeld , I'm pretty sure it would work with:  
``` python
from typing_extensions import Self

class RustVehicle:
    def __init__(self, some_param):
        ...

    def from_file(filename):
        return Self(...)

class PythonVehicle(RustVehicle):
    def get_veh_kg(self):
        return ...

veh = PythonVehicle.from_file("file")
print(veh.get_veh_kg())
```

**Comment by birkenfeld** [comment]
Is there anything left to keep this open?

**Comment by davidhewitt** [comment]
I think this can be closed, thanks for handling 👍
