### ISSUE TITLE
add bors to CI

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2710]
Sounds like we are generally in favour of doing this.

@messense - are you planning to do this? Otherwise I might try to have a play next in the next week or so.

**Comment by adamreichold** [comment]
So which jobs are we running on each PR before running all of them on the main, staging and trying branch.

I'd suggest fmt, clippy, build (stable Rust on all OS, MSRV and nightly on Linux only, latest stable Python only or at most all Python versions on stable Rust and Linux only), and coverage (one OS).

@davidhewitt I just noticed that our 32-bit Windows build still targets CPython 3.10 instead of .11. Is that intentional?

**Comment by adamreichold** [comment]
> build (stable Rust on all OS, MSRV and nightly on Linux only, latest stable Python only or at most all Python versions on stable Rust and Linux only), and coverage (one OS).

Theoretically going even more minimal, e.g. running the tests for coverage once might also be useful since we will still test the full matrix before merging into main.

**Comment by messense** [comment]
> are you planning to do this? Otherwise I might try to have a play next in the next week or so.

I'm currently working on https://github.com/PyO3/maturin/issues/1221 and https://github.com/PyO3/maturin/pull/1214, please go ahead if you have time.

**Comment by davidhewitt** [comment]
> Theoretically going even more minimal, e.g. running the tests for coverage once might also be useful since we will still test the full matrix before merging into main.

Yes, I'd be tempted to keep the on-push checks as light as possible, something like run check (not test) for each OS / Python version, and then one run of the test suite on each OS w. latest Python? Should catch most issues and then full regression test run can make sure everything is tip-top shape.

**Comment by adamreichold** [comment]
> one run of the test suite on each OS w. latest Python?

Sounds reasonable. I would argue to do this with coverage though as this is information we need before approving.

**Comment by davidhewitt** [comment]
Agreed

**Comment by messense** [comment]
Build cache will be a problem for pull requests, GitHub Actions cache has [restrictions for accessing a cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), PR can only access caches from default `main` branch, but if we don't run workflows on `main` there will be no cache available.
