### ISSUE TITLE
add memory view wrapper

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2711]
I noticed that we don't have a `PyMemoryView` wrapper, however we have C-API symbols for it. Someone interested would be welcome to add one. I think the implementation for `PyBytes` and `PyByteArray` would be good starting points to draw from.

**Comment by ikrivosheev** [comment]
@davidhewitt hello! I will work on this PR.

**Comment by davidhewitt** [comment]
Thanks! Please let me know if you need any pointers. It looks like `pyo3-ffi/src/memoryobject.rs` contains enough symbols for us to have a `PyMemoryView` type, which might be all that's possible with abi3.

**Comment by ikrivosheev** [comment]
@davidhewitt hello! I created draft PR (https://github.com/PyO3/pyo3/pull/2792)  but I have some questions:

1. Can I edit `pyo3-ffi/src/memoryobject.rs`? Or it's auto generated code.
2. Which methods do we want to add to PyMemoryView?

**Comment by davidhewitt** [comment]
> Can I edit pyo3-ffi/src/memoryobject.rs

Yes - it's handwritten based off current CPython headers.

> Which methods do we want to add to PyMemoryView?

 I think what you've written in #2792 is great, we possibly don't need more? _Maybe_ `PyMemoryView::get_base` ?

**Comment by davidhewitt** [comment]
Done in #3514
