### ISSUE TITLE
Registering a pointer when dropping PyObject?

### ISSUE THREAD

**Issue by dsorokin** [PyO3/pyo3#273]
Hi!

I'm actually trying to support the Python GC. The problem is that I receive a segfault on macOS. So, I began investigating the cause and found something strange in the implementation of Drop for PyObject. The `register_pointer` function is called in the `drop` method. I'm just curios to know is it ok?

```
/// Dropping a `PyObject` instance decrements the reference count on the object by 1.
impl Drop for PyObject {
    fn drop(&mut self) {
        unsafe {
            pythonrun::register_pointer(self.0);
        }
    }
}
```

**Comment by kngwyu** [comment]
It's stored in a [global variable](https://github.com/PyO3/pyo3/blob/0890f24391caf6c04812a8471cf5559e7666038a/src/pythonrun.rs#L173) and released when `GILGuard` drops.

> The problem is that I receive a segfault on macOS

I recommend to check #271

**Comment by dsorokin** [comment]
Thank you! Then I will close the issue. You actually replied to all my questions. Only I would like to add that this week-end I observed the permanent segfault on macOS when exiting from the Python interpreter session, but my tests worked fine on Windows and Linux. Also when I commented the code related to support of GC, I didn't see the segfault. Probably, it will help.

Best regards,
David Sorokin
