### ISSUE TITLE
Check for "method has no arguments" considers `py` an argument

### ISSUE THREAD

**Issue by birkenfeld** [PyO3/pyo3#2750]
When deciding whether to use `METH_NOARGS` for a pymethod, the [check](https://github.com/PyO3/pyo3/blob/main/pyo3-macros-backend/src/method.rs#L203) only considers `signature.arguments.is_empty()` which includes the `py` argument.

I.e., argument-less methods with `py` get a different calling convention, which should not be necessary.

Before I endeavour to fix something: was it intended that `py` is in the `arguments` list?

**Comment by davidhewitt** [comment]
I think this is indeed a bug, but at least one which only causes a de-optimization.
