### ISSUE TITLE
Rewrite build.rs

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#276]
The current is a bit of a mess and should be rewritten.

 - [x] Currently, setting `PYTHON_SYS_EXECUTABLE` to python 2 requires the python2 feature to be additionally set, while this should be required.
 - [x] Currently, flags and options/values are parsed separately, there are special cases for different operating systems which we don't need and the manual string building and parsing is bad. We can do this much more simple and resilient using a single python script dumping json which is then read by serde. See [pyo3-pack](https://github.com/PyO3/pyo3-pack/blob/master/src/python_interpreter.rs) for an example. It also contains [multiple sysconfigs](https://github.com/PyO3/pyo3-pack/tree/master/sysconfig) showing the os specifics.
 - [ ] `PYTHON_SYS_EXECUTABLE` should be renamed into something more explicit like `PYO3_INTERPRETER`.
- [ ] Support static linking, at least on linux. `cargo:rustc-link-search=native` must be set to the value of  `LIBPL` in the python sysconfig and `cargo:rustc-link-lib=static=` must be used instead of `cargo:rustc-link-lib`. It should be possible to enable this with a feature flag.

The first point should be doable without prior knowledge by some basic `println`-style debugging. The second should be doable if you already know serde and what compile settings are by using the same structure as pyo3-pack. Having a second os installed is helpful for testing. The third should be done last and is a simple `s/PYTHON_SYS_EXECUTABLE/PYO3_INTERPRETER/g` with some extra notes in the documentation. The fourth point is optional and can still be finished later.

If you want to work on this issue and have questions, feel free to post them here.

**Comment by kngwyu** [comment]
> We can do this much more simple and resilient using a single python script dumping json which is then read by serde. See pyo3-pack for an example. 

Should we extract related codes as library from pyo3-pack?

**Comment by konstin** [comment]
No, I don't think there's enough shared code to build a library from it.

**Comment by kngwyu** [comment]
> In the first point do we want to print some debugging line during build?

You mean the lines like
```rust
            println!(
                "cargo:warning={}",
                "Build may fail due to incompatible rustc version."
            );
```
?
They're just messages to cargo, not debug print.
Please see [this page](https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-building-some-native-code).

Or, you're talking about actually printing some messages to stdout or else, while executing the build script? 
If so, I don't know how to do it.

**Comment by eriol** [comment]
@kngwyu @konstin many thanks for the hints and the links, I will study them.
Sorry for the silly question but I'm not a native speaker and I must confess that, after your explanations, I'm more confused about the requirements then a was before.

I wrote about adding debugging information during build because of my understanding of:
>   Currently, setting PYTHON_SYS_EXECUTABLE to python 2 requires the python2 feature to be additionally set, while this should be required.

and

> The first point should be doable without prior knowledge by some basic println-style debugging.
but, for sure, I'm missing something here! 
Or the list of points is only for indication (to keep them in mind) and `build.rs` should be rewritten from scratch following best practices from, I suppose, the cargo book you suggested me?

I will read the cargo book, and I plan to play with PyO3 during the weekend. Thanks for the mentoring!

**Comment by konstin** [comment]
Sorry for the confusion, I should have explained that better:

When run `PYTHON_SYS_EXECUTABLE=python2`, you currently get an error. To find out which methods were called leading to the error and which variables had which value, you can simply `println!("Method x was called")` or `println!("y: {}", y)` and run `PYTHON_SYS_EXECUTABLE=python2 cargo build -vvv`. Once you've identified and fixed the error, you can remove those debugging lines. Normally, the final pull requests doesn't contain any `println`.

**Comment by Alexander-N** [comment]
I don't see how the python2/python3 features are used. Maybe we could remove them completely?

**Comment by konstin** [comment]
When you're in a python 2 virtualenv and have python 3 installed system wide, pyo3 will pick up python 3 instead of the venv unless you use the python2 feature. So unless we start detecting virtualenvs (or remove python 2 support  - see #138) we still need those flags.
