### ISSUE TITLE
Change `PySet::new` to accept a `ExactSizeIterator`

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#2789]
Somewhat related to #2673.

`PyList::new` has signature:

```rust
    pub fn new<T, U>(py: Python<'_>, elements: impl IntoIterator<Item = T, IntoIter = U>) -> &PyList
    where
        T: ToPyObject,
        U: ExactSizeIterator<Item = T>,
    {
```

But `PySet::new` is defined as

```rs
    pub fn new<'p, T: ToPyObject>(py: Python<'p>, elements: &[T]) -> PyResult<&'p PySet> {
        let list = elements.to_object(py);
        unsafe { py.from_owned_ptr_or_err(ffi::PySet_New(list.as_ptr())) }
    }
```

`PySet::new` `elements` parameter type should be relaxed to `ExactSizeIterator<Item = T>`, not a slice.

**Comment by mejrs** [comment]
`PyList` requires `ExactSizeIterator` because it creates an empty list with a capacity (like vec::with_capacity). But `PySet` has no such api.

We can update  `PySet::new` to just take an iterator and call `PySet_Add` in a loop.

**Comment by samuelcolvin** [comment]
> Shouldn't it actually take `IntoIterator<IntoIter=U> where U: ExactSizeIterator`, i.e. exactly the same signature as `PyList::new`?

agreed.

> `PyList` requires `ExactSizeIterator` because it creates an empty list with a capacity (like vec::with_capacity). But `PySet` has no such api.
> 
> We can update `PySet::new` to just take an iterator and call `PySet_Add` in a loop.

Not sure what would be fastest, but currently `PySet::new` is creating an intermediate `PyList`, hence the matching signature would make sense.

**Comment by davidhewitt** [comment]
My gut feeling is that using `PySet_Add` will be faster, because `PySet_New` is doing the iteration via Python dynamic protocol and also then we avoid the intermediate Python allocation.

**Comment by samuelcolvin** [comment]
Then I guess there should be a `from_list` for the specific case where you already have a `list`?

**Comment by mejrs** [comment]
> Then I guess there should be a `from_list` for the specific case where you already have a `list`?

If we let it take an `IntoIterator`, then users can just do PyList -> PyIterator -> PySet

**Comment by samuelcolvin** [comment]
Awesome, thank you.
