### ISSUE TITLE
chrono feature not compatible with abi3 feature

### ISSUE THREAD

**Issue by tafia** [PyO3/pyo3#2793]
### Bug Description

It seems that we can't build extension-modules with both `chrono` and `abi3` features.

```
   |
88 |     pub fn contains(&self, s: NaiveDate) -> bool {
   |                               ^^^^^^^^^ the trait `PyClass` is not implemented for `NaiveDate`
```

It is working fine is I disable abi3 or of course if I manually get a `NaiveDate` from a `&PyAny`.

### Steps to Reproduce

```toml
[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module", "chrono", "abi3"] }
```

```rs
use chrono::{NaiveDate, Duration};
use pyo3::prelude::*;

#[pyfunction]
#[pyo3(text_signature = "(strike, freq, condition, size, update, keep_trade_date)")]
pub fn test_date(from: NaiveDate, to: NaiveDate) -> Duration {
    to - from
}

#[pymodule]
fn ext_test(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(test_date, m)?)
}
```

Removing `abi3` makes it compile fine.

### Your operating system and version

WSL Ubuntu 22.04

### Your Python version (`python --version`)

3.8, 3.9

### Your Rust version (`rustc --version`)

rustc 1.65.0 (897e37553 2022-11-02)

### Your PyO3 version

0.17.3

### How did you install python? Did you use a virtualenv?

virtualenv

**Comment by tafia** [comment]
[Reading](https://github.com/PyO3/pyo3/blob/main/src/conversions/chrono.rs#L6) the source code, it seems that this was intentional.

Couldn't we have some fallback conversion when the "abi3" feature is on? Like trying to extract it from a `PyAny` and returning a `PyErr` if it doesn't work?

**Comment by davidhewitt** [comment]
@tafia this is intended, though documentation could be better.

PyO3 currently only implements special interoperability with Python types exposed through the C API. The datetime apis aren't available with abi3.

Here is a similar comment explaining why we don't support `deque` at all: https://github.com/PyO3/pyo3/issues/2655#issuecomment-1265242473

**Comment by tafia** [comment]
Thanks
