### ISSUE TITLE
Positional-only parameters do not follow PEP 570

### ISSUE THREAD

**Issue by RazerM** [PyO3/pyo3#2799]
### Bug Description

Amongst several benefits to positional-only arguments, [PEP 570](https://peps.python.org/pep-0570) demonstrates two which are not currently possible in PyO3:

- the author may rename a positional-only parameter without it being a breaking change
- it allows functions to accept any keyword argument but also accept a positional one

### Steps to Reproduce

Let us first look at a pure Python function:

```pycon
>>> def makedict(other=(), /, **kwargs):
...     return dict(other, **kwargs)
...
>>> makedict(other=1)
{'other': 1}
```

This is how the `dict` constructor works, for example. There is no possible naming of the positional-only argument that is visible (as an effect) to the caller.

When we try to implement this in Rust, like so:

```rust
#[pyfunction(other = "None", "/", kwargs = "**")]
fn makedict(py: Python<'_>, other: Option<&PyAny>, kwargs: Option<&PyDict>) -> PyResult<PyObject> {
    let dict = py.import("builtins")?.getattr("dict")?;
    Ok(dict.call((other.unwrap_or_else(|| PyTuple::empty(py)),), kwargs)?.into())
}
```

then we get an error

```pycon
>>> makedict(other=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: makedict() got some positional-only arguments passed as keyword arguments: 'other'
```

### Your operating system and version

macOS Monterey

### Your Python version (`python --version`)

3.10.7

### Your Rust version (`rustc --version`)

rustc 1.64.0 (a55dd71d5 2022-09-19)

### Your PyO3 version

0.17.2

### How did you install python? Did you use a virtualenv?

pyenv

**Comment by davidhewitt** [comment]
Thanks for the report. I verified expected behaviour with a Python-only function. #2800 should fix

**Comment by RazerM** [comment]
Thanks for the quick response!
