### ISSUE TITLE
Ensure fast linker is used by CI jobs

### ISSUE THREAD

**Issue by adamreichold** [PyO3/pyo3#2834]
Our CI jobs, especially the ones getting coverage, spent a lot of time building and running doc tests. Since each test is compiled separately, a lot of time is often spent linking those executables and we should make sure our CI jobs use a faster linker, e.g. LLD is often significantly faster and easily enabled by adding `-Clink-arg=-fuse-ld=lld` to `RUSTFLAGS`.

Potentially, [mold](https://github.com/rui314/mold) could provide further improvements but I have no personal experience using it.

**Comment by birkenfeld** [comment]
From my recent try, mold worked fine and brought a nice speedup.

**Comment by davidhewitt** [comment]
Closing in favour of #4017
