### ISSUE TITLE
Making a CLI REPL

### ISSUE THREAD

**Issue by OriDevTeam** [PyO3/pyo3#2857]
### Discussed in https://github.com/PyO3/pyo3/discussions/2856

<div type='discussions-op-text'>

<sup>Originally posted by **OriDevTeam** January  4, 2023</sup>
Most of the explanation about this issue situation is well explained in the [Discussion](https://github.com/PyO3/pyo3/discussions/2856) and also accompanied by a "temporary" solution and also some observations on the matter

___
I'll leave some key-words here in case that people that are trying  to find something similar to this can possibly do:
Py_Main, import code, code.interact, REPL, Py_Initialize, Py_InitializeEx, InteractiveConsole
___
Best regards

**Comment by davidhewitt** [comment]
Closing, as I'm not sure what the ask is here.
