### ISSUE TITLE
#[pyfunction] makes built-in function

### ISSUE THREAD

**Issue by JonathanPlasse** [PyO3/pyo3#2861]
Hi,
Love `pyo3`.
When defining a function like this:
```rust
#[pyfunction]
fn check() -> usize {
    0
}

#[pymodule]
fn mqttbytes(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(check, m)?)?;
    Ok(())
}
```
Is it normal to have `<built-in function check>` instead of something like this `<function check at 0x7fb3317f45e0>`?

**Comment by davidhewitt** [comment]
Hi, yes that's expected with the CPython APIs which PyO3 uses to create native functions (`PyCMethod_New`, IIRC). It would be lots of work for us to change this.

**Comment by JonathanPlasse** [comment]
Thanks for your reply.
