### ISSUE TITLE
Provide redirects to link a specific page in the latest version of the user guide

### ISSUE THREAD

**Issue by not-my-profile** [PyO3/pyo3#2867]
https://pyo3.rs/ currently redirects to https://pyo3.rs/v0.17.3/.

However there doesn't appear to be a way to link specific pages in a version-agnostic way, I tried:

https://pyo3.rs/class
https://pyo3.rs/latest/class
https://pyo3.rs/stable/class

but none of these redirect to https://pyo3.rs/v0.17.3/class.

**Comment by davidhewitt** [comment]
Actually https://pyo3.rs/latest should work, but is currently affected by #2850. Should be up again shortly after I push a fix.

**Comment by not-my-profile** [comment]
Thanks for the quick fix!
