### ISSUE TITLE
Cannot `except PanicException` in python

### ISSUE THREAD

**Issue by fzyzcjy** [PyO3/pyo3#2880]
### Bug Description

Hi thanks for the helpful crate! I need to catch rust panics in python. Example code:

```
def test_catch_rust_panic():
    caught = False
    try:
        deliberate_panic()
    except Exception as e:
        assert 'deliberate panic' in str(e)
        caught = True
    assert caught
```

```
pub fn deliberate_panic() -> () { panic!("this is deliberate panic") }
```

However it does not work, error log:

```
    def deliberate_panic(self) -> None:
>       self.inner.deliberate_panic()
E       pyo3_runtime.PanicException: this is deliberate panic

../../rust_wrapper/ineq.py:75: PanicException
```

Yes I can change it to BaseException but that will capture a lot of other exceptions which I should not catch.

I have tried to `import pyo3_runtime` but seems that package does not exist at all.

### Steps to Reproduce

see above

### Your operating system and version

macos

### Your Python version (`python --version`)

3.9

### Your Rust version (`rustc --version`)

1.66.1

### Your PyO3 version

0.17.3

### How did you install python? Did you use a virtualenv?

pip

**Comment by adamreichold** [comment]
Due to ABI issues/static linkage, every PyO3-based extension has its own `PanicException`. Meaning that to explicitly catch it, you need to explicitly make it part of your Python API, e.g. by calling

```rust
module.add("PanicException", <pyo3::panic::PanicException as pyo3::PyTypeInfo>::type_object(py))?;
```

on a suitable `module: &pyo3::types::PyModule` and import from there on the Python side.

**Comment by mejrs** [comment]
> Yes I can change it to BaseException but that will capture a lot of other exceptions which I should not catch.

This is also true for PanicException - you shouldn't catch it, you should fix the bugs in your code.

**Comment by adamreichold** [comment]
> latest

As an aside, please try to be specific here. At the moment, we all know what we are talking about. But the issue might be read by other people in the future where "latest" does not apply any more.

**Comment by fzyzcjy** [comment]
@adamreichold Thank you! So it is possible to catch *all* such PanicExceptions in different modules?

> @mejrs This is also true for PanicException - you shouldn't catch it, you should fix the bugs in your code.

I see. Indeed I am using it for some machine learning data generation, and bugs are acceptable as long as it is not frequent - I just throw away that part of data and restart randomly.

> latest

changed :)

**Comment by adamreichold** [comment]
> @adamreichold Thank you! So it is possible to catch all such PanicExceptions in different modules?

I don't think so. As each Python extension built using PyO3 has a different `PanicException` (meaning different type objects), you need to import and catch all of them. (And I think you are out of luck for extensions which do not export their exception type at all.)

One workaround that might work is to catch `BaseException` and doing something questionable like

```python
case BaseException as e:
  if not "PanicException" in str(type(e)):
    raise
```

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by davidhewitt** [comment]
As this is now resolved and there's no intention to change PyO3's design here, I'm going to close this issue. Thanks both!
