### ISSUE TITLE
Expose PyErr_WriteUnraisable

### ISSUE THREAD

**Issue by mitsuhiko** [PyO3/pyo3#2884]
Since you sometimes might have some situations where Rust code that is infallible really likes to call into a Python callback, you end up with a horrible situation where all you can do is log the error.

However with Python 3.8 and later you can report such errors so they can be trapped. It would be nice to have a way to do this without unsafe code:

```rust
pub fn report_unraisable(py: Python<'_>, err: PyErr) {
    err.restore(py);
    unsafe {
        PyErr_WriteUnraisable(std::ptr::null_mut());
    }
}
```

I propose to add a `write_unraisable()` method directly onto `PyErr` for this purpose.

**Comment by davidhewitt** [comment]
I fully support this! I've nearly added this in the past for various reasons (as a `pub(crate) fn`) while shuffling pieces of PyO3 around. The fix in #2886 actually ended up using `PyErr_WriteUnraisable` also.

Where do you see the limitation of 3.8 and later? My impression is that this is also available on 3.7 (i.e. oldest version of Python which we currently support).

**Comment by davidhewitt** [comment]
Please feel free to send as PR if you wish, otherwise I'll get around to this within a couple weeks (before the next release at a minimum).

**Comment by mitsuhiko** [comment]
Maybe it works on 3.7, I'm not sure. I took that information from [`sys.unraisablehook`](https://docs.python.org/3/library/sys.html#sys.unraisablehook) and I thought that not just the hook was new.

> `sys.unraisablehook(unraisable, /)`  
>    Handle an unraisable exception. […]
>
>   *New in version 3.8.*

I can try to make a PR when I find some time for it. I'm assuming it generally is probably relatively non controversial, particularly if it turns out it works with 3.7.
