### ISSUE TITLE
Can't convert python-created rust types to rust

### ISSUE THREAD

**Issue by c-a-m-o** [PyO3/pyo3#2898]
I am trying to write a rust app that would be able to dynamically run python plugins. Such plugins should be able to access some of the types of the rust app and return instances of these types.

The question is, is it possible to get the rust and the python types to match such that I can write python functions that I could call from rust and that will return objects that I can convert to rust ?

What I tried was to create a rust lib containing a public type :

```rust
#[pyclass]
pub struct RustStruct {
    #[pyo3(get, set)]
    value: usize,
}

#[pymethods]
impl RustStruct {
    #[new]
    pub fn new(value: usize) -> Self {
        Self { value }
    }
}
```

I was able to build a wheel with maturin and install it on a local install of python.
The problem is when I try to call python from rust : I don't seem to be able to get back a rust object from a python-created one.

In a test module inside the rust library, I wrote this code :

```rust
fn test_struct() {
    prepare_freethreaded_python();
    Python::with_gil(|py| {
        const CODE: &str = r#"
from rustlib import RustStruct
def test_fn(value):
    return isinstance(value, RustStruct)
"#;
        let module = PyModule::from_code(py, CODE, "test_mod.py", "test_mod").unwrap();
        let test_fn = module.getattr("test_fn").unwrap();
        let py_res = test_fn.call1((RustStruct::new(12),)).unwrap();
        let res: bool = py_res.extract().unwrap();
        assert!(res);
    })
}
```

The test fails because the types are not the same. However, when I give to python an instance of the right type, I am able to get the class and then create an instance that I can export to rust

```rust
fn test_struct() {
    prepare_freethreaded_python();
    Python::with_gil(|py| {
        const CODE: &str = r#"
from rustlib import RustStruct
def test_fn(value):
    return type(value)(13)
"#;

        let module = PyModule::from_code(py, CODE, "test_mod.py", "test_mod").unwrap();
        let test_fn = module.getattr("test_fn").unwrap();
        let py_res = test_fn.call1((RustStruct::new(12),)).unwrap();
        let res: RustStruct = py_res.extract().unwrap();
        assert_eq!(res.value, 13)
    })
}
```

The main point of this is to create the instance in the python script to use it afterwards in Rust, with something like this

```rust
fn test_struct() {
    prepare_freethreaded_python();
    Python::with_gil(|py| {
        const CODE: &str = r#"
from rustlib import RustStruct
def test_fn():
    return RustStruct(12)
"#;

        let module = PyModule::from_code(py, CODE, "test_mod.py", "test_mod").unwrap();
        let test_fn = module.getattr("test_fn").unwrap();
        let py_res = test_fn.call1(()).unwrap();
        // Error below :
        // called `Result::unwrap()` on an `Err` value: PyErr {
        //     type: <class 'TypeError'>,
        //     value: TypeError("'RustStruct' object cannot be converted to 'RustStruct'"),
        //     traceback: None
        // }
        let _: RustStruct = py_res.extract().unwrap();
    })
}
```

Is there a way to have the `RustStruct` from python and the `RustStruct` from  rust to match ?

**Comment by adamreichold** [comment]
> In a test module inside the rust library, I wrote this code :

I think the issue here is that you are running Rust unit tests which contain Python code. The unit test binary and the actual extension binary (which I guess is loaded by your `import` statements) are two distinct dynamically shared objects (DSO) and hence have distinct `RustStruct` type objects. (While this is not the case for you, they could have been built using different Rust compilers/flags and hence have incompatible ABI.)

One straight forward solution would be to run those tests as Python test using e.g. pytest if that is possible at all. This way, only one build of your extension and hence one `RustStruct` type object is involved. Of course, this depends on what you actually want to test and whether this involves the "innards" of your Rust library.

Or you could remove the other build of your extension by avoiding the `import` statements and rather pass `rustlib` into your scripts as an explicitly constructed `&PyModule` filled by your `#[pymodule]` initialization function, e.g. if you have

```rust
#[pymodule]
fn rustlib(py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<RustStruct>()?;

    Ok(())
}
```

call something like (I have not tested this):

```rust
let m = PyModule::new(py, "rustlib")?;
rustlib(py, m)?;

let globals = [("rustlib", m)].into_py_dict(py);

let res = py.eval("rustlib.RustStruct(42)", Some(globals), None)?;
let val: RustStruct = res.extract()?;
```

**Comment by c-a-m-o** [comment]
Thanks a lot, the code you posted worked. By using `py.run` instead of `py.eval` I should be able to have a workflow that is similar to what I first tried.

Is there a way to have the same DSO for the extension binary used by python and the one used by rust (for unit testing or for using the crate as a library) ? I tried to change the crate type in Cargo.toml but it had no effect on the result

**Comment by adamreichold** [comment]
> Is there a way to have the same DSO for the extension binary used by python and the one used by rust (for unit testing or for using the crate as a library) ? I tried to change the crate type in Cargo.toml but it had no effect on the result

In theory, you could use a separate crate for unit tests and link it against the shared library which is your extension. However, this would also preclude you from accessing its private implementation details and so I would not recommend that option over just writing the tests in Python.

**Comment by davidhewitt** [comment]
It looks like the problem here is solved, closing.
