### ISSUE TITLE
`PyEllipsis` type

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#2906]
Would be great to have an Ellipsis type, aka `...` in python.

The ffi type seems to exist

https://github.com/PyO3/pyo3/blob/18081ba14e8dfe4cf989ae68c308ea585dbfc734/pyo3-ffi/src/sliceobject.rs#L11-L13

But I'm not sure how I would use it in safe rust code.

**Comment by mejrs** [comment]
We can make a method for that just like `None` and `NotImplemented` : https://docs.rs/pyo3/latest/pyo3/marker/struct.Python.html#method.None

If you want it in safe rust right now, I think you'd need to get the `builtins` module, and then getattr the ellipsis object.

**Comment by samuelcolvin** [comment]
Thanks that would be great, that's what I was using, but your comment lead me to what I really needed which was simply

```rs
fn is_ellipsis(v: &PyAny) -> bool {
    unsafe { v.as_ptr() == Py_Ellipsis() }
}
```

Might be worth adding `is_ellipsis` as well like `is_none`?
