### ISSUE TITLE
`py_any.downcast::<PyIterator>()` behaviour is different on windows vs macos and linux

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#2913]
### Bug Description

This is an extension of https://github.com/PyO3/pyo3/discussions/2902

On Linux and MacOS, `py_any.downcast::<PyIterator>()` is only `Ok` for generators.

On windows it appears to be `Ok` for strings and anything which is a sequence.

### Steps to Reproduce

Should be as simple as

```rs
let s = "foobar".to_object().into_ref(py);
let iter: PyIterator = s.downcast()?;
```

Should fail on linux and macos, but pass on windows. 

### Your operating system and version

Ubuntu

### Your Python version (`python --version`)

3.10

### Your Rust version (`rustc --version`)

cargo 1.68.0-nightly (2381cbdb4 2022-12-23)

### Your PyO3 version

v0.18

### How did you install python? Did you use a virtualenv?

pyenv

**Comment by davidhewitt** [comment]
So I've just run the following test locally on PyO3 `main`, both Windows and Unix, Python 3.10 and 3.11:

```rust
#[test]
fn test_iterator_downcast() {
    Python::with_gil(|py| {
        let s = "foobar".to_object(py).into_ref(py);
        let iter: &pyo3::types::PyIterator = s.downcast().unwrap();
    })
}
```

In all cases, I get the expected failure:
```
---- test_iterator_downcast stdout ----
thread 'test_iterator_downcast' panicked at 'called `Result::unwrap()` on an `Err` value: PyDowncastError { from: 'foobar', to: "Iterator" }', tests/test_downcast.rs:7:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I don't think this is a bug in PyO3. Instead let's go back to the discussion and get some more information about how you're setting up your test environment, so we can understand what's different about your Windows setup.

**Comment by davidhewitt** [comment]
Actually, with your example Python class in #2902 I _can_ repro this, and will push a fix shortly.

**Comment by samuelcolvin** [comment]
My mistake, it was a subclass of `str`, sorry created this in a hurry.
