### ISSUE TITLE
Simulate `__exit__` using `Drop` trait

### ISSUE THREAD

**Issue by AsafFisher** [PyO3/pyo3#2949]
If one want to use a `with` statment with a `pyclass` then `__exit__` can be automatically implemented by calling drop on the `pyclass`.
This elimnates the need to implement a `__exit__` function.

```rust
#[pyclass]
struct DebugController {
    conn: TcpStream,
}
impl Drop for DebugController{
    fn drop(&mut self){
        // Do RAII stuff idk send bye bye message using the socket
    }
}
```
```python
with DebugController as d:
        d.do_stuff()
```

I am thinking about it and not sure if it's a good idea... because implementing `__exit__` might seem easier.

**Comment by birkenfeld** [comment]
Hey Asaf, can you elaborate a bit? I'm not sure what you're proposing here.

**Comment by AsafFisher** [comment]
Ultimately if a struct impl `Drop` then `__exit__` can be automatically implemented to call the `drop` function

**Comment by birkenfeld** [comment]
AFAICS that wouldn't be possible, since there's no guarantee in Python that the context manager object is destroyed at that point.

And if the Python object is still alive, the underlying Rust object must stay alive as well, so it can't be dropped.

**Comment by davidhewitt** [comment]
Agree with @birkenfeld 

To give some additional detail here, in general we don't automatically implement _any_ Python methods based on the existence of a Rust trait. I think to do that would probably require specialization.

Also, some other discussion about `Drop` and `__exit__` can be found at https://github.com/PyO3/pyo3/issues/1205#issuecomment-1397029973
