### ISSUE TITLE
Simplify detection of re-entrant initialization of pyclass types

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2950]
The detection of re-entrant initialization seem surprisingly heavy weight. What do you think about turning this around in the future, meaning to use e.g. a thread-local list of type object addresses which the current thread is currently initializing instead of a list of threads for each type object?

_Originally posted by @adamreichold in https://github.com/PyO3/pyo3/pull/2947#discussion_r1104796552_

**Comment by adamreichold** [comment]
This does not work as reentrancy can happen both from the current thread which could be detected using a thread-local list and from other threads at the same time, so we still need global synchronization. I guess, this could be done using hazard pointers but that seems a bit too much to reduce start-up time.
