### ISSUE TITLE
Little docs mistake

### ISSUE THREAD

**Issue by Enyium** [PyO3/pyo3#2958]
### Bug Description

[Docs for `Py::borrow_mut()`](https://docs.rs/pyo3/latest/pyo3/prelude/struct.Py.html#method.borrow_mut) say:

> Panics if the value is **currently mutably borrowed.** For a non-panicking variant, use [`try_borrow_mut`](https://docs.rs/pyo3/latest/pyo3/prelude/struct.Py.html#method.try_borrow_mut).

But the docs for the similar linked method say:

> returning an error if the value is **currently borrowed.**

(Emphasis mine.)

Seems "mutably" should be removed from the first quote.

**Comment by adamreichold** [comment]
@Enyium Thank you for reporting this. Could you open up a PR fixing the issue?

**Comment by Enyium** [comment]
I was searching for it with GitHub's search function, but couldn't find it. If you could point me to the respective file, please.

**Comment by kngwyu** [comment]
@Enyium 
Hi thank you for the issue. Here is the point: https://github.com/PyO3/pyo3/blob/c858ced8d4014c6601d04ca8bff4a09559205a22/src/instance.rs#L396
