### ISSUE TITLE
Is it possible to extend from python (not custom) class?

### ISSUE THREAD

**Issue by inv2004** [PyO3/pyo3#296]
Hello,

Is it possible to inherit my custom class from python owned class ?

Something like
```
#[pyclass(extends=keras.utils.Sequence)]
```
but now sure how to write it correct.

Thank you,

**Comment by konstin** [comment]
Unfortunately there's currently no prebuilt solution for that

**Comment by inv2004** [comment]
Thank you,

**Comment by kngwyu** [comment]
I think you need rust binding like rust-numpy to do it.
But personally I think it's very difficult to make a binding for DL libraries like PyTorch or TF or Keras and so on.
They're C or C++ APIs are not so rust friendly, unlike numpy's one :sob: (I think it's still worth tackling, though).

**Comment by kngwyu** [comment]
> TF bindings work good, I did not try TF to train, but predict works fine from keras model.

Wow it's great :slightly_smiling_face: 

> I use keras to train model from Rust by using pyo3

You mean using `Python::run_code` to call keras?

**Comment by inv2004** [comment]
@kngwyu 
Y, I just use:
```rust
    let keras_models = py.import("keras.models")?;
    let keras_layers = py.import("keras.layers")?;

    let model = keras_models.call0("Sequential")?;
    let dict = PyDict::new(py);

    let wide = 64;
    dict.set_item("input_dim", wide)?;
    dict.set_item("activation", "relu")?;

    model.call_method1("add", (keras_layers.call("Dense", (wide, ), Some(dict))?, ))?;
    model.call_method1("add", (keras_layers.call1("Dense", (1, ))?, ))?;

    let dict = PyDict::new(py);
    dict.set_item("optimizer", params.optimizer.to_string().to_lowercase())?;
    dict.set_item("loss", "mse")?;
    dict.set_item("metrics", vec!["mae"])?;

    model.call_method("compile", (), Some(dict))?;
    model.call_method("fit", (x,y), Some(dict))?; // x,y - numpy::PyArray2

``` 

I was thinking about to put it into separate crate, but decided that python is temporary solution,, because TF bindings are ok.

**Comment by leoleoasd** [comment]
Maybe we should state this in the API documentation or users guide?
