### ISSUE TITLE
RFC: Replace "extension module" with "native module" 

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#2962]
The original purpose of the cpython c api was to allow "Extending Python with C or C++" to "add new built-in modules to Python" (https://docs.python.org/3/extending/extending.html). This however isn't how the c api is used nowadays, and it's especially not how pyo3 is used. On the contrary, pyo3 users generally want something that is as close to a module written in pure python as possible! The rust code becomes the main thing, not an extension to something. I would reserve "extension" for things that extend pyo3, such as logging or serde adaptors.

i therefore propose to replace "extension module" with "native module", or alternatively "rust module" in pyo3, setuptools-rust and maturin.

**Comment by birkenfeld** [comment]
As far as I know, "extension module" is still the technical term for modules compiled to native DLLs and loaded from an interpreter.

I don't understand what you mean by the remark that an "extension module" is somehow an opposite to "as close to a module written in pure Python".

Why change this (including the feature name, which is a gratuitous breakage)?

**Comment by konstin** [comment]
> As far as I know, "extension module" is still the technical term for modules compiled to native DLLs and loaded from the interpreter.

Yes, but i believe it's a misleading term; people don't want to extend cpython, the want to write a python module in a language that isn't python. i think we can do better than the official docs by naming it something that actually tells the users what is going on (i think e.g. cpython describing pyo3 methods as `<built-in method foo of type object at 0x1234567>` is a ui bug since these methods aren't built-in, they come from an external module). I know there's a disadvantage in diverging from the official cpython docs, but given that pyo3 users ideally never should have to look at the [Extending and Embedding the Python Interpreter](https://docs.python.org/3/extending/index.html) docs anyway i think it's worth it. If we're lucky we might even be able to convince the cpython devs to improve some of the messaging around native code :)

Consider you are a user who has previously only written modules in python, and you're now coming across the term "extension module" vs. coming across the term "native module" or "rust module": Would it immediately allow you to guess what's going on or would you have to google what it does?

> including the feature name, which is a gratuitous breakage?

We can keep the old name around as an alias for as long as we want. i would want to do that though before we published a 1.0 release and are effectively locked with the terms we have in the api (we could still alias and deprecate, but it becomes significantly harder then when you can just remove things in a next release). i also don't think it's a gratuitous change, but it's important to use clear terminology.

**Comment by adamreichold** [comment]
I also the one-time cost of the breakage and the ongoing cost of diverging from the upstream Python nomenclature is not worth it. But I am admittedly not convinced of the need for changing this in first place.

I do agree about the "UI bug" though, I just we should focus on fixing this, e.g. by improving the how CPython represents native modules and functions. Meaning that a naming change does not help with this.

**Comment by konstin** [comment]
To give you a sense for the amount of change, modulo changelog and deprecation warnings this is the entire change, it's really mostly search&replace: https://github.com/PyO3/pyo3/compare/rename-extension-modules-to-native-modules. Technically it's not even a breaking change because the old features still exists and continues working.

**Comment by davidhewitt** [comment]
I agree with the sentiment here though feel similarly reluctant to make this change. I'd also prefer that we started an initiative upstream to improve nomenclature, and then if "native module" or some other term was settled upon we could then migrate to that here.

**Comment by davidhewitt** [comment]
I'm going to close this, as while this would be nice end state for the ecosystem, it's not clear that us actioning this without upstream CPython is worthwhile, and upstream is unlikely to change.
