### ISSUE TITLE
0.18.2 release

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#2970]
I think the optimisations and fixes landed since 0.18.1 are worth putting out as a patch release before long.

Tentatively suggest we aim to push this next week, Tuesday 28th Feb.

I think there's a couple of final things could probably be implemented / merged as part of the release:
- #2946 - I'm happy to push the patch proposed there.
- #2899 - @adamreichold I think it would be nice to include this, just waiting for your opinion on what the final API could look like.

**Comment by adamreichold** [comment]
> @adamreichold I think it would be nice to include this, just waiting for your opinion on what the final API could look like.

Oops, I was just waiting on your opinion on whether we should keep the conditional buffer protocol integration. (I did not get a notification for your comment in https://github.com/PyO3/pyo3/pull/2899#issuecomment-1426647157. This has happened repeatedly to me. Not sure whether GitHub does not like my ISP our something...)

**Comment by davidhewitt** [comment]
Heh, no worries! I assumed the notification got lost in a wave of them from me one day :)
