### ISSUE TITLE
Symbol renaming in IDE doesn't work within `#[pymethods]`

### ISSUE THREAD

**Issue by Enyium** [PyO3/pyo3#2983]
I'm using VS Code with rust-analyzer. And so far it only occured to me in `fn`s annotated with `#[pymodule]` or `impl` blocks annotated with `#[pymethods]` that there are the following deficiencies regarding parameters and local variables:

- When I place the cursor on either the declaration or a usage of the variable, only the declaration is highlighted.
- When I rename the variable with F2 - no matter whether the cursor is on declaration or usage - only the declaration is renamed.
- A variable's context menu action "Find All References" only finds the declaration.

This makes refactoring very cumbersome.

**Comment by davidhewitt** [comment]
This is probably to do with `rust-analyzer`'s macro engine? I'm not sure if there's much we can do here, would you be willing to open an issue upstream?
