### ISSUE TITLE
Making a rust-implemented python class compatible with the python's `pydantic` library.

### ISSUE THREAD

**Issue by jymchng** [PyO3/pyo3#2989]
Hi

I am attempting to create a python class using rust that is compatible with python's pydantic library and to set the context, the public API of pydantic requires the implementation of a custom `__get_validators__` method and within which, it should yield one or more classmethods of the same class.

An example from the pydantic's [docs](https://docs.pydantic.dev/usage/types/#classes-with-__get_validators__)
```
class PostCode(str):

    @classmethod
    def __get_validators__(cls):
        # one or more validators may be yielded which will be called in the
        # order to validate the input, each validator will receive as an input
        # the value returned from the previous validator
        yield cls.validate


    @classmethod
    def validate(cls, v):
        # NOT IMPORTANT
        return cls(f'{m.group(1)} {m.group(2)}')
```

My implementation in rust is as follows:
```
#[pymethods]
impl PyNRIC {
    #[new]
    pub fn new(string: String) -> PyResult<PyNRIC> {
        // not important
    }

    #[classmethod]
    pub fn __get_validators__(cls: &PyType) -> PyResult<&PyIterator> {
        let func = cls.getattr(intern!(cls.py(), "validate"));
        match func {
            Ok(func) => {
                if let Ok(funciter) = func.iter() {
                    return Ok(funciter)
                } else {
                    return Err(PyErr::new_err("`validate` method cannot be iterated!"))
                }
            },
            Err(err) => Err(err),
        }
    }

    #[classmethod]
    pub fn validate(cls: &PyType, value: &PyString) -> PyResult<PyNRIC> {
        let v: String = value.extract()?;
        PyNRIC::new(v)
    }
}
```

The classmethod `__get_validators__` defined for `PyNRIC` attempted to get the attribute of `cls`, via the `.getattr` method. This should translate to python to be `getattr(cls, "validate")` and ideally, returns the classmethod `validate`.

However, when I run the python script, I get an error that is due to `func.iter()` returning an error.

What should I do to yield a classmethod from another classmethod?

**Comment by adamreichold** [comment]
> However, when I run the python script, I get an error that is due to func.iter() returning an error.

The result of your call to `getattr` is a single classmethod, not an iterable which is why this fails. I am not sure from reading the pydantic docs, but maybe you could try just returning a `Vec<&PyAny>` instead? For example

```rust
#[classmethod]
pub fn __get_validators__(cls: &PyType) -> PyResult<Vec<&PyAny>> {
    let func = cls.getattr(cls.py(), intern!("validate"))?;
    Ok(vec![func])
}
```

**Comment by jymchng** [comment]
Thanks for your idea, I managed to make it work via:
```
#[classmethod]
    pub fn __get_validators__(cls: &PyType) -> PyResult<&PyTuple> {
       let py = cls.py();
       let func = cls.getattr(intern!(py, "validate"))?;
       Ok(PyTuple::new(py, vec![func]))
    }
#[classmethod]
    #[pyo3(text_signature="(value)")]
    pub fn validate(cls: &PyType, value: &PyAny) -> PyResult<PyNRIC> {
        let v: String = value.extract::<String>()?;
        PyNRIC::new(v)
    }
```

**Comment by jymchng** [comment]
Which is actually very python instead of rust lol. I guess I can make it better if there's a way to call classmethods within the same implementation block and so on, i.e. need to do what these `#[classmethod]` does to the codes.

**Comment by adamreichold** [comment]
Just out of curiosity, do you know why you had to manually convert the `Vec` into a `PyTuple`? Returning a `Vec` should convert it into `PyList` [behind the scenes](https://docs.rs/pyo3/latest/src/pyo3/conversions/std/vec.rs.html), so what it is the difference between tuples and lists? Mutability?

**Comment by adamreichold** [comment]
> Which is actually very python instead of rust lol. I guess I can make it better if there's a way to call classmethods within the same implementation block and so on, i.e. need to do what these `#[classmethod]` does to the codes.

While I understand the aim, I suspect that we would have to break out quite a bit of functionality to make the slots which `#[classmethod]` fills available as separately manageable objects to Rust code. And I also suspect that there would be very little difference w.r.t. performance or ergonomics compared to calling `getattr`.

**Comment by jymchng** [comment]
> > Which is actually very python instead of rust lol. I guess I can make it better if there's a way to call classmethods within the same implementation block and so on, i.e. need to do what these `#[classmethod]` does to the codes.
> 
> While I understand the aim, I suspect that we would have to break out quite a bit of functionality to make the slots which `#[classmethod]` fills available as separately manageable objects to Rust code. And I also suspect that there would be very little difference w.r.t. performance or ergonomics compared to calling `getattr`.

Yeah, I agree with you on this point, since initialization the `PyClass` would have already filled those slots, we might as well use them and like you said, a couple of lookups to those slots won't hurt. 😉

**Comment by davidhewitt** [comment]
cc @samuelcolvin this may interest you to see Pydantic Custom Data Types being implemented in Rust :)

**Comment by samuelcolvin** [comment]
@jymchng just so you're aware, pydantic V2 which should be released soon is implemented in rust, see [pydantic-core](https://github.com/pydantic/pydantic-core). The way custom validators work has changed completely, in future you'll just need to implement `__pydantic_core_schema__` or `__get_pydantic_core_schema__`.

Feel free to ask on pydantic-core if you have any more questions.

**Comment by jymchng** [comment]
> @jymchng just so you're aware, pydantic V2 which should be released soon is implemented in rust, see [pydantic-core](https://github.com/pydantic/pydantic-core). The way custom validators work has changed completely, in future you'll just need to implement `__pydantic_core_schema__` or `__get_pydantic_core_schema__`.
> 
> Feel free to ask on pydantic-core if you have any more questions.

Hi @samuelcolvin, thanks for your reply. I am aware of pydantic V2.0, and pydantic-core which is implemented in Rust. Definitely looking forward to using it once V2.0 is released! 😄
