### ISSUE TITLE
Folder structure for both python and rusts tests

### ISSUE THREAD

**Issue by prokie** [PyO3/pyo3#2994]
Hello!

I am new to rust. I am trying to put my tests in a separate folder.

```
├── Cargo.lock
├── Cargo.toml
├── pyproject.toml
├── src
│   └── lib.rs
└── tests
    └── add.rs
```

When I add in `cargo.toml`
```
[lib]
crate-type = ["cdylib"]
name = "my_proj"
```
I can no longer import my function from lib.rs
```
unresolved import `crate::add`
no `add` in the root
```
But when I remove from `cargo.toml`
```
[lib]
crate-type = ["cdylib"]
name = "my_proj"
```
The import works?

I guess this is not `pyo3` related, but it would be nice to have some documentation on how to structure your project with python and rust tests.

Preferably, I would like to have something like this. Where I have a common tests folder to place both my rust and python tests.

```
├── Cargo.lock
├── Cargo.toml
├── pyproject.toml
├── src
│   └── lib.rs
├── tests
    ├── python 
    │   ├── __init__.py 
    │   └── common.py
    └── rs
        └── common.rs
```

**Comment by davidhewitt** [comment]
For the import issue, the answer is already in the README:

```toml
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]
```

So add `"rlib"` to your `crate-type` selection.

The folder structure... This is currently not something PyO3 itself covers, you might want to look at https://www.maturin.rs/project_layout.html

(If you are not using `maturin`, I highly recommend it if you are a Rust beginner.)
