### ISSUE TITLE
How is the descriptor dunder/interface method `__set_name__` supported?

### ISSUE THREAD

**Issue by jymchng** [PyO3/pyo3#2996]
I am trying to implement a `cached_property` descriptor in Rust and porting it over to Python.

Just wondering how is `__set_name__` supported in pyo3.

I cannot find any docs on it:

https://pyo3.rs/v0.18.1/class/protocols - No mention of it in the docs.
https://github.com/PyO3/pyo3/blob/d118ee3a7306fe7123e000188a230fbc3bfc58cc/src/test_hygiene/pymethods.rs - One-liner which shows the signature of `__set_name__`.

**Comment by davidhewitt** [comment]
Just implement it like you would any other `#[pymethod]; `__set_name__` does not have a special C-API slot, so PyO3 doesn't do anything special with it.
