### ISSUE TITLE
Unable to use `Py<PyAny>` as keys for `hashbrown::HashMap`.

### ISSUE THREAD

**Issue by jymchng** [PyO3/pyo3#2999]
Using Rust and pyo3 to implement `cached_property` with a `setter` method has really some nice properties because the reference of the cached value can be stored in Rust and not in Python, i.e. retrieval of the cached value need not be solely though the `getter` as it is how it is done in pure python.

Codes:

```
use hashbrown::HashMap;

use pyo3::{
    prelude::{PyObject as PreludePyObject, *},
    types::{PyAny, PyTuple, PyType},
    exceptions::PyValueError,
};

#[pyclass(name = "cached_property")]
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct PropertyGetter {
    pv: HashMap<Py<PyAny>, Py<PyAny>>,
    fget: PreludePyObject,
}

use crate::withsetter::PropertySetterNoDeleter;


#[pymethods]
impl PropertyGetter {
    #[new]
    fn __new__(fget: &PyAny) -> PyResult<PropertyGetter> {
        Ok(PropertyGetter {
            pv: HashMap::default(),
            fget: fget.into(),
        })
    }

    fn __get__(
        &mut self,
        instance: &PyAny,
        _owner: Option<&PyType>,
    ) -> PyResult<&PreludePyObject> {
        let this_py = instance.py();
        // self.pv.contains_key()
    }
}
```

However, using `Py<PyAny>` as keys in a `hashbrown::HashMap` is not permitted because the traits `Hash` and `Eq` are not implemented.

Since I cannot implement foreign trait on foreign structs, is there anyway to circumvent this?

Thank you.

**Comment by adamreichold** [comment]
Do you want to hash this based on the identity of the object or based on the value?

If based on the identity, you should be able to just use the pointer value via `.as_ptr()` converted into a `usize` as the key, also c.f. https://github.com/PyO3/pyo3/discussions/2878

If based on the value, then you probably need to write a wrapper type of `Py<PyAny>` which calls `PyAny::hash` etc. But this will most likely be brittle as these methods can fail, so you need to `.unwrap()` inside the implementation of e.g. `Hash` and you will also need to ensure having the GIL inside these methods via `Python::with_gil` which might imply performance issues.

**Comment by jymchng** [comment]
I want to hash based on identity. Lol your first method actually makes more sense; I didn't see your reply and went on to implement `Eq`, `PartialEq` and `Hash` using `.as_ptr()` on a wrapper struct and without casting `as_ptr()` to usize. I shall change it then. Thank you for your help!
