### ISSUE TITLE
Support for slice indexing

### ISSUE THREAD

**Issue by JohnScience** [PyO3/pyo3#3000]
I was converting a piece of software from Python to Rust. There I encountered the following notation: `s[:,:,:,t]`. Shortly after I realized that it was [slice notation](https://stackoverflow.com/questions/509211/understanding-slicing) but I did not find a convenient and efficient PyO3 alternative. Could this convenience feature become a part of PyO3?

P.S. I fell back to constructing instances of `PySlice` from dimensions extracted separately.

Prior art:

* [`s!` macro in `ndarray`](https://docs.rs/ndarray/latest/ndarray/macro.s.html)

**Comment by adamreichold** [comment]
> Prior art:

There is not enough context to know what kind of object you are slicing, but if it is an `ndarray`, please have a look at using the [`rust-numpy` crate](https://github.com/pyO3/rust-numpy) which should give you an `ArrayView` of that data so that you can directly use `ndarray`'s `s!` macro.

**Comment by davidhewitt** [comment]
Closing as it's not clear what the feature request is, and the issue has been idle for several months now.
