### ISSUE TITLE
Garbage collection does not work on PyPy

### ISSUE THREAD

**Issue by adriangb** [PyO3/pyo3#3005]
### Bug Description

Garbage collection as described in [in the docs](https://pyo3.rs/v0.18.1/class/protocols.html?highlight=garba#garbage-collector-integration) works on CPython but no PyPy.

I know that PyPy does GC differently than CPython, but I thought API / behavior wise it would work the same. So I'm not sure if this is a PyO3 issue or a PyPy issue, but I'm starting here and we can always transfer the issue to PyPy if we determine that is the problem.

Discovered from https://github.com/pydantic/pydantic-core/pull/416

### Steps to Reproduce

https://github.com/adriangb/misc/actions/runs/4332105542/jobs/7564368491
https://github.com/adriangb/misc/tree/pyo3-pypy

### Your operating system and version

Linux / PyPy 3.9

### Your Python version (`python --version`)

3.9

### Your Rust version (`rustc --version`)

1.67

### Your PyO3 version

0.18.0

### How did you install python? Did you use a virtualenv?

github actions

**Comment by adriangb** [comment]
Posted on the PyPy issue tracker to see if they have any insight: https://foss.heptapod.net/pypy/pypy/-/issues/3899

**Comment by samuelcolvin** [comment]
Wow, good work @adriangb, in short it sounds like we're going to need a "limitations" section regarding usage with pypy.

**Comment by adriangb** [comment]
I think this should be documented, yes. I can PR that. But I'm not convinced yet it results in unbounded memory growth, I need to test that.

**Comment by adriangb** [comment]
I unfortunately think I've confirmed that PyPy experiences unbounded memory growth:

https://github.com/adriangb/misc/blob/pyo3-pypy/pypy.pdf

cpython control:

https://github.com/adriangb/misc/blob/pyo3-pypy/cpython.pdf
