### ISSUE TITLE
Error When Downloading Example Projects

### ISSUE THREAD

**Issue by mert-kurttutan** [PyO3/pyo3#3008]
### Bug Description

When I try `cargo generate --git https://github.com/PyO3/pyo3 examples/word-count`, I receive the following error
```
Error: ⛔   Failed executing script: .template/pre-script.rhai
```
My observation is that `tox.ini` file is missing from template file. Is this file supposed to be in the project template? I dont think it is needed since `tox` is not included in any of the steps or `requirements-dev.txt` file.

The content of the file `.template/pre-script.rhai`:
```
variable::set("PYO3_VERSION", "0.18.1");
file::rename(".template/Cargo.toml", "Cargo.toml");
file::rename(".template/setup.cfg", "setup.cfg");
file::rename(".template/tox.ini", "tox.ini");
file::delete(".template");
```
where you can see `tox.ini` file.

### Steps to Reproduce

1. cargo install cargo-generate
2. cargo generate --git https://github.com/PyO3/pyo3 examples/word-count

### Backtrace

```shell
🤷   Project Name: myproject
🔧   Destination: /home/mert-kurttutan/projects/learning/rust/myproject ...
🔧   project-name: myproject ...
🔧   Generating template ...
Error: ⛔   Failed executing script: .template/pre-script.rhai
```

### Your operating system and version

Ubuntu 22.04

### Your Python version (`python --version`)

3.10

### Your Rust version (`rustc --version`)

Latest 

### Your PyO3 version

Latest

### How did you install python? Did you use a virtualenv?

conda virtual env

**Comment by mert-kurttutan** [comment]
I was able to run it successfully after deleting line for tox.ini. I guess the reason is that you migrated to `nox` from `tox`

**Comment by adamreichold** [comment]
Thank you for reporting this! We switched from tox to nox in January of 2022 and apparently forgot to this fix since then. Sorry for that.

**Comment by mert-kurttutan** [comment]
Out of curiosity, why did you prefer nox?

**Comment by adamreichold** [comment]
This was done in #2106 and I think the main argument was the increased flexibility of nox scripts versus tox manifests. Since then, we do make extensive use of nox scripts not so much for the examples, but for the main project to automate various build and maintenance tasks.
