### ISSUE TITLE
Allow multiple #[pymethods] impl blocks

### ISSUE THREAD

**Issue by athre0z** [PyO3/pyo3#302]
Currently, having more than one impl block annotated with `#[pymethods]` results in a compiler error (`conflicting implementation for 'A'`). This appears to be the case due to

```rust
impl ::pyo3::class::methods::PyMethodsProtocolImpl for A {
    fn py_methods() -> &'static [::pyo3::class::PyMethodDefType] {
        static METHODS: &'static [::pyo3::class::PyMethodDefType] = &[];
        METHODS
    }
}
```

being emit on every invocation. While most certainly not a high priority issue, it'd be nice to be able to have multiple such impl blocks in order to allow macros to implement methods by opening up their own impl block instead of having to do so manually (e.g. for cases where you invoke them on types that otherwise wouldn't have any non-macro impl blocks).

Attached you'll find a minimal example of the issue.
[pyo3-muliple-impl.tar.gz](https://github.com/PyO3/pyo3/files/2656464/pyo3-muliple-impl.tar.gz)

**Comment by athre0z** [comment]
Turns out that methods expanded from macros inside of `#[pymethods]` are not recognized by PyO3 and registered to Python. I never wrote any proc macros, but I presume this is might be due to the proc macro being invoked before the macro rules macro and thus be a rust limitation rather than a PyO3 one. Nevertheless, it increases the priority of this issue for me since I'm now down to C&Ping code.

**Comment by konstin** [comment]
Are you sure you need multiple impl blocks? I ask because it's really hard to solve that through proc macros and it will definitely require at least extra attributes.

**Comment by kngwyu** [comment]
I think it's impossible, rather than hard.

**Comment by konstin** [comment]
You can theoretically do it by naming/numbering the impl block and then referencing those in the `#[pyclass]` expansion, but I'd prefer not to.

**Comment by athre0z** [comment]
I do realize this is a hard task and all of my personal use cases will be covered by the generic support that I'm currently working on. Nevertheless, I believe that implementing methods using macros will still have it's use cases from time to time. 

Right now, the two only ways apparent to me are using macros that expand to functions inside a pymethods block (which doesn't work due to [the current absence of support for macro input expansion in the compiler](https://internals.rust-lang.org/t/pre-rfc-macro-expansion-of-input-for-proc-macros-derives-primarily/7210/7)) or having the macro emit its own pymethods impl block (which doesn't work either). Perhaps there's a third way that I didn't think of, rendering this issue irrelevant. In case there isn't, one would be down to duplicating code by hand.

With the most obvious reason for using macros for me personally covered by generics, we might just want to [wait for this RFC to land](https://github.com/pierzchalski/rfcs/blob/macro-expansion-api/text/0000-macro-expansion-for-macro-input.md) (which, AFAIK, should solve the problem).

**Comment by konstin** [comment]
> having the macro emit its own pymethods impl block (which doesn't work either). 

Why wouldn't that work?

**Comment by athre0z** [comment]
Well, it works if you just want one macro to impl everything, but once you want to add some methods or compose by using multiple macros emitting methods, you're screwed.

**Comment by konstin** [comment]
Could you create macros that are composable, e.g. through manual tt-munchers or through [tt-call](https://github.com/dtolnay/tt-call)? Imo that's still better than creating really ugly workarounds to support multiple impl blocks.

**Comment by athre0z** [comment]
Hmm, my experience with this stuff is rather limited. I tried lots of variations, but cannot get it to work. The problem appears to be that if you do `a!{ b!{} }`, `b!{}` is passed to `a!` as tokens rather than being evaluated first, so if your idea was to be doing something like

```rust
compose_pymethods! {
    some_macro!{},
    some_other_macro!{},
    fn my_method(&self) { ... },
}
```

that doesn't seem to be working because we're hitting the same issue as with directly using macros inside of pymethods (eval order). This might very well be possible to do for someone with more experience in the arcane arts of macro magic -- I have no idea.

Either way, I'm not really into having dirty hacks to support this, either. Perhaps it's just a limitation that we'll have to live with until someone comes up with a better idea.

**Comment by chrisjuchem** [comment]
For anyone (like me) still running into this, the fix is behind the `multiple-pymethods` feature.
