### ISSUE TITLE
Type annotations for functions are absent

### ISSUE THREAD

**Issue by arihant2math** [PyO3/pyo3#3048]
### Bug Description

There aren't type annotation when using `inspect.signature` for everything _but_ Options, which produce a Ellipsis as default argument.

### Steps to Reproduce

```python
# main.py
import inspect
import test
print(inspect.signature(test.foo))
```
```rust
// lib/src.rs
...
#[pyfunction]
fn foo(a: i64, b: Option<i64>) -> String {
}
...
```
running the python code would produce: 
(a, b=Ellipsis)

### Your operating system and version

Windows

### Your Python version (`python --version`)

3.11.2

### Your Rust version (`rustc --version`)

rustc 1.68.0 (2c8cc3432 2023-03-06)

### Your PyO3 version

0.18.1

### How did you install python? Did you use a virtualenv?

python.org, a virtualenv with maturin was used

**Comment by messense** [comment]
I think it's intentional at the moment

> All default values are currently set to .... I think this is ok because .pyi files often do the same. Maybe for numbers, strings, None and True/False we could render these in a future PR.

See https://github.com/PyO3/pyo3/pull/2784

**Comment by messense** [comment]
I think we should close this in favor of #2863?

**Comment by arihant2math** [comment]
Yeah I think that's a good idea
