### ISSUE TITLE
Add scoped interpreter

### ISSUE THREAD

**Issue by singersbalm** [PyO3/pyo3#3070]
A scoped interpreter like the pybind11 c++ would be nice.
```
PyRun_SimpleString("import sys, os.path; "
                           "sys.path.insert(0, "
                           "os.path.abspath(os.path.dirname(sys.argv[0])) "
                           "if sys.argv and os.path.exists(sys.argv[0]) else '')");
```
that’s the code in c++. I would personally add the option to select the path manually, but use the project as default. So instead of sys.argv0.
Something like this could be used

```
fn path(v: Option<PathBuf>) -> std::io::Result<PathBuf> {
  fs::canonicalize(match v {
    Some(v) => v,
    None => PathBuf::from(".")
  })
}
```

**Comment by davidhewitt** [comment]
@singersbalm we have [with_embedded_interpreter](https://docs.rs/pyo3/latest/pyo3/fn.with_embedded_python_interpreter.html), is that suitable for your needs? (Maybe if we extend that functionality somewhat?)

**Comment by davidhewitt** [comment]
I am assuming that `with_embedded_python_interpreter` is fine, closing.
