### ISSUE TITLE
`#[new]` which is also a `#[classmethod]`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#3077]
### Discussed in https://github.com/PyO3/pyo3/discussions/3075

<div type='discussions-op-text'>

<sup>Originally posted by **adriangb** March 29, 2023</sup>
As far as I can tell, `#[new]` has to be a static method. It's a classmethod in Python, could it be made the same in PyO3? Context: I'd like to get the class name as seen by Python for the failure case of calling new.</div>

**Comment by stuhood** [comment]
Have you already started this? I can look at it today if not.

**Comment by davidhewitt** [comment]
I have not, please go ahead, thanks! I think the challenge is that we currently special case new in the backend (see `FnType` enum iirc). Any refactoring you fancy is welcome, and feel free to post questions here or in a PR; I'll answer when I can...

**Comment by stuhood** [comment]
Posted over here: https://github.com/PyO3/pyo3/pull/3157 ... thanks!
