### ISSUE TITLE
Add note about `PyObjectProtocol`

### ISSUE THREAD

**Issue by nickdrozd** [PyO3/pyo3#3082]
I've been porting some Python code to Rust module-by-module using PyO3. I'm not really a Rust person, so I've been using ChatGPT to write the new code. I give it the Python, it gives me back Rust. This has been unnervingly successful. It has even been giving back working PyO3!

One problem though is that it keeps suggesting a trait called `PyObjectProtocol`. And I cannot find a trace of this in the docs. Is it a so-called "hallucination"? No, it turns out that the "knowledge cutoff" was September 2021, and the trait was eliminated since then.

Given this strange situation, it might be helpful to add a comment somewhere about `PyObjectProtocol` and whatever replaced it.

**Comment by adamreichold** [comment]
We do have a migration guide which details that quite a few `Py*Protocol` traits have been first deprecated, then disabled by default and then removed, c.f. https://pyo3.rs/v0.18.2/migration#pyproto-has-been-deprecated
