### ISSUE TITLE
"maturin init" should be "maturin new"

### ISSUE THREAD

**Issue by BruceEckel** [PyO3/pyo3#3093]
### Bug Description

In:
https://pyo3.rs/v0.18.2/#using-rust-from-python

It says "Still inside this string_sum directory, now run maturin init. "

According to
https://github.com/PyO3/maturin#usage
This should be "maturin new" instead.

### Steps to Reproduce

Check docs

### Your operating system and version

Windows 11

### Your Python version (`python --version`)

3.11

### Your Rust version (`rustc --version`)

rustc 1.68.2 (9eb3afe9e 2023-03-27)

### Your PyO3 version

latest

### How did you install python? Did you use a virtualenv?

python.org

**Comment by davidhewitt** [comment]
`maturin init` does exist and is the intended command for that particular sequence; it's like `maturin new` but doesn't create the directory (just like `cargo`).

https://github.com/PyO3/maturin/blob/684b6c93c2914459087ac1f3a075037ee1e6519a/src/main.rs#L123
