### ISSUE TITLE
Mypyc compatibility

### ISSUE THREAD

**Issue by nickdrozd** [PyO3/pyo3#3094]
I have some Python code I'm porting to Rust with PyO3, module by module. It's working so that I can call the Rust modules from Python. I also have it set up so that I can compile the Python with Mypyc (a compiler based on Mypy).

The problem is, I can't do both. Ideally I would be able to compile the Rust code into Python extensions, and then compile the remaining Python with Mypyc and have it all work together. But currently they don't work together -- attempting to run them together variously leads to segfaults or attribute errors.

PyO3 and Mypyc ultimately both produce `.so` files. Beyond that I don't know any of the details. It seems like it should be possible though.

(Should this issue be cross-posted to the Mypy repo?)

**Comment by davidhewitt** [comment]
Looks like this is a `mypyc` issue - what's happening is that your compile command `mypyc tm generate` is also creating a mypyc compiled library from `tm/rust_stuff.pyi`, which is the source of the code that's segfaulting.

Things seem to work if I change the compile command to `mypyc tm generate --exclude tm.rust_stuff` (and remove all the generated `.so` files from the `tm` directory to get rid of existing `mypyc` outputs).

It could be worth submitting an issue against mypyc to flag that compiling a `.pyi` file seems both unexpected and apparently dangerous :)

**Comment by nickdrozd** [comment]
When you say things seem to work, do you mean you got the tests to pass? I tried that change and I still get segfaults.

**Comment by davidhewitt** [comment]
Yes, I get test failures but no segfaults. I ran your branch on Github code-spaces with Python 3.11 dev container with Rust added.

If you look at the core dumps (or run your tests under gdb or lldb), which native library is the segfault occurring in?

**Comment by nickdrozd** [comment]
Well I wasn't able to investigate the segfaults, but nevertheless I think I've isolated the problem to one particular function. First, it's definitely possible to get Mypyc and PyO3 working together correctly. Possibly there are minor problems, but not big ones. So this ticket can be downgraded from bug report to user support :)

Here are two branches that port a small amout of Python to Rust:
  - https://github.com/nickdrozd/busy-beaver-stuff/tree/clean-rust
  - https://github.com/nickdrozd/busy-beaver-stuff/tree/clean-rust-no-tcompile

They are identical except that the first one ports a function called `tcompile` and the second one doesn't. The one without `tcompile` passes tests successfully while the one with it segfaults.

Here is the original Python code:

```python
Color = int
State = int
Shift = bool

Slot = tuple[State, Color]
Instr = tuple[Color, Shift, State]
Prog = dict[Slot, Instr | None]

def parse(program: str) -> list[list[Instr | None]]: ...

def tcompile(program: str) -> Prog:
    return {
        (state, color): instr
        for state, instrs in enumerate(parse(program))
        for color, instr in enumerate(instrs)
    }
```

And here is the ported Rust:

```rust
type Color = i32;
type State = i32;
type Shift = bool;

type Slot = (State, Color);
type Instr = (Color, Shift, State);
type Prog = HashMap<Slot, Option<Instr>>;

#[pyfunction]
pub fn parse(program: &str) -> Vec<Vec<Option<Instr>>>

#[pyfunction]
pub fn tcompile(program: &str) -> Prog {
    let mut prog = HashMap::new();

    for (state, instrs) in parse(program).iter().enumerate() {
        for (color, instr) in instrs.iter().enumerate() {
            prog.insert((state as State, color as Color), instr.clone());
        }
    }

    prog
}
```

That `tcompile` function compiles, but something is wrong. It seems like something is going wrong at import time? I'm hoping that there is something obviously wrong that I'm overlooking.

**Comment by nickdrozd** [comment]
Okay, it turns out that the problem was due to Mypyc incorrectly handling a `dataclass`, which is a well-known source of problems for Mypy(c). The `tcompile` function above was not the problem itself, but at import time it led to a chain of imports that exposed the real error.

So if anyone comes across this ticket in the future with the same problem, my suggestion is to check your `dataclass`es.

Thanks for looking, @davidhewitt !

**Comment by davidhewitt** [comment]
Np, pleased we found the solution!
