### ISSUE TITLE
#[pyclass] enums do not retain identity when converted from Rust to Python

### ISSUE THREAD

**Issue by alex** [PyO3/pyo3#3117]
Simple reproducer:

```
#[pyo3::prelude::pyclass]
enum Foo {
    E1,
    E2,
}

#[pyo3::prelude::pyfunction
pub fn get_foo() -> Foo {
    Foo::E1
}
```

if you wire this up, and call it from Python, you'll find that `get_foo() is get_foo()` is `False`.

It would be useful if these always had the same identity, as this would more closely mirror the pure python `enum` module's behavior.

**Comment by adamreichold** [comment]
Is this possibly a duplicate of #3059? (With the resolution #3061 being underway.)

**Comment by alex** [comment]
Yuuuup. Sorry about the news. Apparently 9am is too early for me to know how to search.
