### ISSUE TITLE
Unclear licensing for pyo3-ffi

### ISSUE THREAD

**Issue by puradox** [PyO3/pyo3#3124]
The `pyo3-ffi` crate is [specified](https://github.com/PyO3/pyo3/blob/main/pyo3-ffi/Cargo.toml#L10) as licensed under Apache 2.0, but [`pyo3-ffi/LICENSE`](https://github.com/PyO3/pyo3/blob/main/pyo3-ffi/LICENSE) resembles the [Python 3 license](https://docs.python.org/3/license.html). The README mentions "PyO3 is licensed under the [Apache-2.0 license](https://opensource.org/licenses/APACHE-2.0). Python is licensed under the [Python License](https://docs.python.org/3/license.html)" but the presence of `pyo3-ffi/LICENSE` may imply this particular crate is licensed differently.

For clarification, is the code in the `pyo3-ffi` crate licensed under Apache 2.0 or Python 3.0?

**Comment by davidhewitt** [comment]
I asked Van Lindberg about this, with the following reply:

> You can probably license under Apache+MIT. If you directly copied any extraneous expression (think implementing code) from CPython, then you might have an issue. But if you have only copied what is absolutely necessary for binary compatibility - which is likely considering your implementation is in Rust - then the use of Python's header is fair use under Google v. Oracle and can be licensed as you wish as a new work.

My understanding is that we have done as pure a reproduction of the CPython header files in Rust as is "absolutely necessary for binary compatibility" as per above. So I believe the licence of Apache 2.0 is correct (soon to be dual Apache/MIT, see #2339), like the rest of PyO3.

If the `pyo3-ffi/LICENSE` file is confusing, I suggest we replace it with `pyo3-ffi/ACKNOWLEDGEMENTS` which contains something along the lines of

```
This is a Rust reimplementation of the CPython public header files as necessary for binary compatibility, with additional metadata to support PyPy.

For original implementations please see
https://github.com/python/cpython
https://foss.heptapod.net/pypy/pypy
```
