### ISSUE TITLE
Rust-only methods in #[pymethods] impl

### ISSUE THREAD

**Issue by Cpyte-Engine-Developer** [PyO3/pyo3#3128]
Hello, please add some functionality that will make methods in **#[pymethods]** impl don't visible in python

**Comment by adamreichold** [comment]
You should be able to put those methods into a additional/separate `impl` block without `#[pymethods]` attached. These methods are not visible to Python and are not processed by PyO3 in any way.

**Comment by mejrs** [comment]
Note that you can have multiple impl blocks, unlike in python where you can only have one class definition.
