### ISSUE TITLE
Replace bors-ng by self-hosted instance or switch to GH merge queues

### ISSUE THREAD

**Issue by adamreichold** [PyO3/pyo3#3132]
As indicated by e.g. https://github.com/PyO3/pyo3/pull/3129#issuecomment-1532032570, we need to switch to a self-hosted instance of bors-ng or use GitHub's built-in merge queues soon.

**Comment by davidhewitt** [comment]
Hmmm. It would be simpler for us to not maintain our own infra, so GitHub merge queues seem better to me?

Unfortunately, like bors, you only get a single merge method (e.g. merge, or squash). I asked if it could be changed, and GH saw it but doesn't seem to be in a rush to improve it https://github.com/orgs/community/discussions/46757#discussioncomment-5244498

From a quick Google I just found [Mergify](https://blog.mergify.com/github-pull-request-merge-queue-faq/) which has a free tier for open source, and allows configuration of the merge method per-PR; I wonder if that would be a nice alternative?

**Comment by adamreichold** [comment]
> Hmmm. It would be simpler for us to not maintain our own infra, so GitHub merge queues seem better to me?

Yes, stretched thin as we are, I think this is the path of least effort and we should take that for now. I am not even sure when someone will find the time to remove the bors-ng config and setup GH merge queues though...

**Comment by adamreichold** [comment]
@davidhewitt I am not completely sure, but I think bors did delete the merged branches. Is that something we can enable for the GitHub merge queues as well?

**Comment by davidhewitt** [comment]
I've clicked the checkbox as per https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches - let's see what happens...
