### ISSUE TITLE
Pymethods no longer callable from other pyfunctions?

### ISSUE THREAD

**Issue by jguhlin** [PyO3/pyo3#3163]
### Bug Description

Don't know what's happened, but upgraded to newest pyo3.

Getting this problem
```
41  | pub struct Aligner {
    | ------------------ function or associated item `new` not found for this struct
...
385 |     let mut aligner = Aligner::new();
    |                                ^^^ function or associated item not found in `Aligner`
    |
```

But ::new is defined for Aligner in the #[pymethods] impl. This is from an ergonomic function to call it. Worked in the previous version. 

### Steps to Reproduce

Error can be reproduced by using this library in the 
https://github.com/jguhlin/minimap2-rs/blob/minimap2.26/minimappers2/

Specific code is here:
https://github.com/jguhlin/minimap2-rs/blob/minimap2.26/minimappers2/src/lib.rs

### Your operating system and version

Ubuntu

### Your Python version (`python --version`)

Python 3.10.8

### Your Rust version (`rustc --version`)

rustc 1.71.0-nightly (c4190f2d3 2023-05-07)

### Your PyO3 version

0.18.3

### How did you install python? Did you use a virtualenv?

conda under asdf

**Comment by adamreichold** [comment]
This is definitely still possible and I think the problems of the linked code are elsewhere, e.g. your branch builds after applying the following diff

```diff
diff --git a/minimappers2/src/lib.rs b/minimappers2/src/lib.rs
index 5a8881c..0f45c2c 100644
--- a/minimappers2/src/lib.rs
+++ b/minimappers2/src/lib.rs
@@ -1,3 +1,4 @@
+use std::mem::take;
 use std::num::NonZeroI32;
 use std::sync::{Arc, Mutex};
 
@@ -82,7 +83,7 @@ impl Aligner {
                     r.query_name = Some(seq.id.clone());
                     mappings.push(r)
                 });
-            }spawn
+            }
 
             return Ok(PyDataFrame(mappings.to_df().unwrap()));
         }
@@ -161,12 +162,6 @@ impl Aligner {
         }
     }
 
-    fn rustnew() -> Self {
-        Aligner {
-            aligner: minimap2::Aligner::builder(),
-        }
-    }
-
     /// Set the number of threads for minimap2 to use to build index and perform mapping
     fn threads(&mut self, threads: usize) {
         self.aligner.threads = threads;
@@ -179,7 +174,10 @@ impl Aligner {
 
     /// Use a sequence instead of a file for an index
     fn with_seq(&mut self, seq: &Sequence) {
-        self.aligner.with_seq_and_id(&seq.sequence, &seq.id);
+        let aligner = take(&mut self.aligner);
+        self.aligner = aligner
+            .with_seq_and_id(&seq.sequence, seq.id.as_bytes())
+            .unwrap();
     }
 
     /// Index and save index to output
```

here.

The compiler errors for the missing `new` are triggered by the invalid `rustnew` as far as I can see as those prevent us from produce a valid expansion of the `pymethods` section.
