### ISSUE TITLE
proc-macro should check that __traverse__ takes only &self

### ISSUE THREAD

**Issue by adamreichold** [PyO3/pyo3#3180]
While `call_traverse_impl` ensures that only `&self` is passed to a method implementing the `tp_traverse` slot, the ergonomics if user code tries to workaround this are not ideal. This could be improve if we modify the proc-macro to check the method receiver upfront and emit a detailed error message with a rationale if it is not `&self`.

**Comment by davidhewitt** [comment]
Labelling as good first issue because this is a fairly localised change to the proc macro when handling `__traverse__` implementations. Probably needs to go around the `impl_traverse_slot` function in `pyo3-macros-backend/src/pymethod.rs`.
