### ISSUE TITLE
Memory grows unless GIL is released

### ISSUE THREAD

**Issue by markschl** [PyO3/pyo3#319]
I got a problem, which I'm not sure is a bug, but I haven't found a way to solve it, unfortunately.

Here is some example code:

```rust
use pyo3::prelude::*;

static CODE: &str = "
def main():
    pass
";

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();

    if let Err(e) = run(CODE) {
        e.print(py);
    }
}

fn run(code: &str) -> Result<(), PyErr> {
    let gil = Python::acquire_gil();
    let py = gil.python();

    py.run(code, None, None)?;
    let main = py.import("__main__")?.get("main")?;

    for _ in 0..200000000 {
        main.call0()?;
    }
    Ok(())
}

```

Running this in release mode causes process memory to grow up to gigabytes. I have found that the problem does not occur if the GIL is acquired an released in each iteration of the loop. However, that also means I have to get a reference to the `main` python function every time again (using `py.import("__main__")...`), which causes the code to run *much* more slowly.

Not knowing much about the internals, I don't know if this is a memory leak, or intended behavior. I tried to debug using valgrind as [described here](https://www.j-david.net/2012/07/python-running-valgrind-on-a-c-extension.html), and there is a lot of output compared to very few false positives (still), when running the same code in a native python script. I can post the output here if necessary, but I'm not sure if it is relevant.

I'm running Ubuntu 18.04 with python 3.6.7. Rust version is 1.33.0-nightly (a8a2a887d 2018-12-16), and I'm using pyo3 master (0deaee01ad9d538b9865a578840a4bc18b32c3da).

**Comment by kngwyu** [comment]
See #311

**Comment by markschl** [comment]
Thanks
