### ISSUE TITLE
Cannot stop rust program while running python code

### ISSUE THREAD

**Issue by ktjd123** [PyO3/pyo3#3218]
### Bug Description

When I run python code in fast loop from rust and want to stop the program, python takes interrupt so rust program won't exit.

### Steps to Reproduce

Run python code in Rust

### Your operating system and version

tested in mac, linux

### Your Python version (`python --version`)

Python 3.11.3

### Your Rust version (`rustc --version`)

rustc 1.70.0 (90c541806 2023-05-31)

### Your PyO3 version

0.19.0

### How did you install python? Did you use a virtualenv?

mac with brew

and apt for linux

### Additional Info

Thank you.

**Comment by adamreichold** [comment]
Could you share some code showing what exactly you are doing?

For example, doesn't Python raise an exception when the signal is received? Where is that exception handled?

**Comment by ktjd123** [comment]
Sorry for few information.

I think the CTRL-C is captured at python side, and thought That shouldn't happen since It's blocking input to main process, But I'll investigate more and re-open issue.

Thank you for reply

**Comment by birkenfeld** [comment]
You can disable Python's `SIGINT` handler with
```
signal.signal(signal.SIGINT, signal.SIG_DFL)
```

**Comment by ktjd123** [comment]
@birkenfeld Thank you for your kind help :)
