### ISSUE TITLE
Mutating mapped `Vec` / `HashMap` fields fails silently in Python

### ISSUE THREAD

**Issue by chrisjsewell** [PyO3/pyo3#3231]
### Bug Description

See reproduction below,
it would seem that the generated types are immutable, yet provide mutation APIs (such as `append`) that do not except when called.

### Steps to Reproduce

When creating the following class:

```rust
use pyo3::prelude::*;
use std::collections::HashMap;

#[pyclass]
struct Example {
    #[pyo3(get)]
    vector: Vec<String>,
    #[pyo3(get)]
    hashmap: HashMap<String, String>,
}

#[pymethods]
impl Example {
    #[new]
    fn new() -> Self {
        Self {
            vector: Vec::new(),
            hashmap: HashMap::new(),
        }
    }
}
```

Mutating these fields in Python fails silently, e.g.

```python
from my_module import Example

eg = Example()
eg.vector.append("hi")
print(eg.vector)  # => []
eg.hashmap["a"] = "b"
print(eg.hashmap)  # => {}
```

### Your operating system and version

macOS Ventura 13.3

### Your Python version (`python --version`)

Python 3.8

### Your Rust version (`rustc --version`)

rustc 1.70.0 (90c541806 2023-05-31)

### Your PyO3 version

0.19.0

### How did you install python? Did you use a virtualenv?

conda

### Additional Info

using `maturin develop` to build package

**Comment by adamreichold** [comment]
This is the expected behaviour: Returning `HashMap<String, String>` will create a new `PyDict` containing `PyString`, not some kind of wrapper of the original hash table.

If you want to mutably share data with Python, you need to use the `Py` smart pointer as discussed in https://github.com/PyO3/pyo3/discussions/3223. This is also described in more detail in the FAQ at https://pyo3.rs/v0.19.0/faq#pyo3get-clones-my-field

**Comment by chrisjsewell** [comment]
Ah ok thanks,

This was a little counterintuitive for me, when thinking of it in terms of the equivalent Python attribute semantics.
Perhaps in https://pyo3.rs/v0.19.0/class#object-properties-using-pyo3get-set, this could be more explicitly mentioned, with a link to the troubleshooting section?

**Comment by chrisjsewell** [comment]
would it not be better if `#[pyo3(get)]` converted rust types to their immutable counterparts, e.g. `Vec -> PySequence` `HashMap -> PyMapping`, `HashSet -> PyFrozenSet`?

It seems like this would be more intuitive, in terms of the cloning behaviour?

**Comment by davidhewitt** [comment]
`PySequence` isn't a real type though - in practice our choices are either `list` or `tuple`.

Given that returning `Vec<T>` from a function produces a python `list[T]`, it's got nice simplicity to also do this with `#[pyo3(get)]`.

I have been wondering about a third mode `#[pyo3(bind)]` which would produce an instance of a custom `pyo3_runtime.Vec` class which has functionality like a list but modifies the underlying `Vec<T>` (as long as the class is not `frozen`).

**Comment by chrisjsewell** [comment]
Yeh `#[pyo3(bind)]` definitely sounds of interest here

Anyhow, feel free to close this if you want, I just wanted to give my feedback from coming to PyO3 as a "noob" lol (which is mainly positive thanks!)
