### ISSUE TITLE
pyo3 c++(not threadsafe) mapping

### ISSUE THREAD

**Issue by Omicronlawful** [PyO3/pyo3#3241]
### Bug Description

I want to use rust code in python that is parially written in c++. The problem is that the cxx types do not implement the trait `std::marker::Send`. Is there a way to have the struct on a single thread that isnt sent and only accessed by pyo3. The code is not threadsafe.
### Steps to Reproduce

```
#[pyclass]
struct PyTest {
    pub test: Testing
}
```

### Backtrace

```shell
`*const cxx::void` cannot be sent between threads safely [E0277] Help: within `mytest::ffi::Testing`, the trait `std::marker::Send` is not implemented for `*const cxx::void` Note: required because it appears within the type `[*const void; 0]` Note: required because it appears within the type `Opaque`
```

### Your operating system and version

Arch linux latest

### Your Python version (`python --version`)

Python 3.10

### Your Rust version (`rustc --version`)

rustc 1.69.0 (84c898d65 2023-04-16)

### Your PyO3 version

0.18

### How did you install python? Did you use a virtualenv?

pacman

**Comment by Omicronlawful** [comment]
just made my code threadsafe. probably easier

**Comment by adamreichold** [comment]
Just for anyone running into this, we do provide the [`#[pyclass(unsendable)]`](https://pyo3.rs/v0.19.0/class#must-be-send) for this use case which pins usage of an object (which includes destruction) to a single thread.
