### ISSUE TITLE
Build error after updating unrelated dependencies

### ISSUE THREAD

**Issue by fgimenez** [PyO3/pyo3#3301]
Hi, I have a crate that belongs to a workspace and uses pyo3, after adding an additional crate to the workspace and adding  additional dependencies to other workspace crates I've started getting this error when trying to build the crate with the pyo3 :
```
error[E0277]: `*mut ()` cannot be sent between threads safely
   --> client/bindings/python/src/lib.rs:233:1
    |
233 | #[pyclass(name = "MyClass")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `*mut ()` cannot be sent between threads safely
    |
    = help: within `PyMyClass`, the trait `std::marker::Send` is not implemented for `*mut ()`
    = note: required because it appears within the type `SyncNotSend`
    = note: required because it appears within the type `PhantomData<SyncNotSend>`
    = note: required because it appears within the type `SetCurrentGuard`
    = note: required because it appears within the type `EnterGuard<'static>`
note: required because it appears within the type `PyMyClass`
   --> client/bindings/python/src/lib.rs:234:8
    |
234 | struct PyMyClass {
    |        ^^^^^^^^^^^^^^^
note: required by a bound in `ThreadCheckerStub`
   --> /home/fgimenez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.1/src/impl_/pyclass.rs:894:33
    |
894 | pub struct ThreadCheckerStub<T: Send>(PhantomData<T>);
    |                                 ^^^^ required by this bound in `ThreadCheckerStub`
    = note: this error originates in the attribute macro `pyclass` (in Nightly builds, run with -Z macro-backtrace for more info)
```
No idea how to debug this, does it sound a bell? pyo3 version 0.19.1, let me know if I can provide any additional information, the added dependencies are:
```
anvil = { git = "https://github.com/foundry-rs/foundry", rev = "33acf8ac0e01b468c68301409c709309679602fa" }
ethers = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
revm = "^3.3.0"
rstest = "0.17.0"
tokio = "1.29.1"
```
rstest and tokio were already there but at lower versions.

Any help is very appreciated, thanks!

**Comment by alex** [comment]
It looks like you have a `pyclass`, which has a field that's https://docs.rs/tokio/latest/tokio/runtime/struct.EnterGuard.html

As the error explains, pyclass's need to be `Send` (because in Python, nothing stops you from using an instance from any thread), and `EnterGuard` is not `Send`.

**Comment by alex** [comment]
See https://pyo3.rs/v0.19.0/class#must-be-send for mroe details

**Comment by fgimenez** [comment]
thank you so much for your response @alex ! :heart: 

> As the error explains, pyclass's need to be Send (because in Python, nothing stops you from using an instance from any thread), and EnterGuard is not Send.

ok that makes total sense. but everything was working fine previously, does the error come from bumping tokio from `1.26.0` to `1.29.1`?

> See https://pyo3.rs/v0.19.0/class#must-be-send for mroe details

:pray:

**Comment by alex** [comment]
Yes, you can see that in 1.26, it's `Send`: https://docs.rs/tokio/1.26.0/tokio/runtime/struct.EnterGuard.html but in 1.29.1 it's `!Send` https://docs.rs/tokio/1.29.1/tokio/runtime/struct.EnterGuard.html

**Comment by birkenfeld** [comment]
Since it's a semver break, this was probably unintentional on tokio's side?

**Comment by alex** [comment]
It was intentional: https://github.com/tokio-rs/tokio/commit/e75ca93d30e6d2f7a165882d46d8b55fa3e8cb78

**Comment by fgimenez** [comment]
awesome, thank you so much! I'll take a look at which field in the `pyclass` is causing the error, closing.

> > Since it's a semver break, this was probably unintentional on tokio's side?

> It was intentional: https://github.com/tokio-rs/tokio/commit/e75ca93d30e6d2f7a165882d46d8b55fa3e8cb78

not related to this issue, but if tokio follows semver, shouldn't it have bumped the major version to signal this breaking change?
