### ISSUE TITLE
the file stops responding when assigning a variable

### ISSUE THREAD

**Issue by raisfeld-ori** [PyO3/pyo3#3369]
### Bug Description

i was working on this code:

```rust
#[derive(Debug, Clone)]
#[pyclass]
pub enum CodeType{
    Variable,
    Executable,
    Unknown,
    Statement,
}

#[derive(Debug, Clone)]
#[pyclass]
pub struct ShallowParsedLine{
    pub line_code_type: CodeType,
    pub actual_line: String,
    pub all_spaces: i32,
    pub placement: Option<i32>,
}

#[pymethods]
impl ShallowParsedLine {
    pub fn line_code_type(&self) -> CodeType {self.line_code_type.clone()}
    pub fn actual_line(&self) -> String {self.actual_line.clone()}
    pub fn all_spaces(&self) -> i32 {self.all_spaces.clone()}
    pub fn placement(&self) -> Option<i32> {self.placement.clone()}
}

async fn from_parse(i: usize, line: String) -> ShallowParsedLine {
    let mut line_type = CodeType::Unknown;
    if line.ends_with(")") { line_type = CodeType::Executable; }
    let first_word = line.clone().split_whitespace().next().unwrap_or("").replace(":", "");

    if STATEMENTS.contains(&first_word.as_str().clone()) {line_type = CodeType::Statement;}

    if line.contains("=") {
        let first_equation: usize = line.find("=").unwrap();
        if line.chars().nth(first_equation + 1).unwrap() != '=' {
            if !OPERATORS.contains(&line.chars().nth(first_equation - 1).unwrap()) {
                line_type = CodeType::Variable;
            };
        }
    }

    let mut spaces_found: i32 = 0;
    for letter in line.chars() {
        if letter == ' ' { spaces_found += 1; } else { break }
    }
    return ShallowParsedLine {
        line_code_type: line_type.clone(),
        actual_line: line.to_string(),
        all_spaces: spaces_found,
        placement: Some(i as i32),
    };
}
```
(there is more, but it shouldn't matter)
and for some reason, the code stoped responding, not giving an error or something, it just acted like it's processing something, despite the code taking 0.1 seconds in every other test. it debugged it a bit an  found that on line 32, when i remove `line_type = CodeType::Statement` the code returns to work like normal, i don't think this is an issue with any other parts of my code, so i think this is an error with pyo3

### Your maturin version (`maturin --version`)

1.1.0

### Your Python version (`python -V`)

3.11.3

### Your pip version (`pip -V`)

23.1.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

just copy my code and use `maturin develop`, that should be enough since this is a minimal working example

**Comment by adamreichold** [comment]
> just copy my code and use maturin develop, that should be enough since this is a minimal working example

This does not look like a runnable example. Please provide one with a `Cargo.toml` and `src/main.rs` defining an entry point `fn main() { .. }`.

**Comment by raisfeld-ori** [comment]
first thing  off, i sent the wrong version so please ignore it.
secondly, it seems that the reason was actually that i got an error inside of a tokio thread (which only happend if the line_code_type was CodeType::Statement) so when i used .await on the thread, it just kept on waiting over a thread that had crashed.
