### ISSUE TITLE
python3.8 support

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3#338]
https://docs.python.org/3.8/whatsnew/changelog.html

There are no obvious issues.

Travis has `python: 3.8-dev` available.

AppVeyor has nothing yet, but apparently it will appear here: https://github.com/appveyor/ci

**Comment by ijl** [comment]
I built and tested orjson using pyo3 HEAD against the first 3.8 alpha without issue. 

I just opened a pull request to run 3.8 in Travis CI as an allowed failure.

**Comment by konstin** [comment]
I'll close this because #339 is merged. If something specific breaks with 3.8, just open a new issue!
