### ISSUE TITLE
Add compile tests

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#34]
Because `pyo3` uses unsafe blocks, we need to add compile tests

https://github.com/laumann/compiletest-rs

**Comment by fafhrd91** [comment]
I have a problem with compile tests, to make them pass you need to "cargo clean"

**Comment by messense** [comment]
Because it pass `-L target/debug/deps` to rustc, if you updated rustc, you need to run `cargo clean`

**Comment by fafhrd91** [comment]
but tests pass only when you first time run them, they always fail on second "cargo test"

**Comment by messense** [comment]
Hmm, I didn't notice that, I used `cargo test --test compile_tests`, second run works fine.

**Comment by fafhrd91** [comment]
try just "cargo test"

**Comment by messense** [comment]
I can't, keeps getting the error in #4 then test aborts. No idea why.

```
---- buffer::test::test_array_buffer stdout ----
	thread 'buffer::test::test_array_buffer' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { ptype: <class 'ImportError'>, pvalue: Some(ImportError('dlopen(/usr/local/var/pyenv/versions/3.6.1/lib/python3.6/lib-dynload/array.cpython-36m-darwin.so, 2): Symbol not found: _PyUnicode_AsUnicode\n  Referenced from: /usr/local/var/pyenv/versions/3.6.1/lib/python3.6/lib-dynload/array.cpython-36m-darwin.so\n  Expected in: flat namespace\n in /usr/local/var/pyenv/versions/3.6.1/lib/python3.6/lib-dynload/array.cpython-36m-darwin.so',)), ptraceback: None }', src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by fafhrd91** [comment]
hmm, ok. I'll check

**Comment by fafhrd91** [comment]
lets close this for now.
