### ISSUE TITLE
Continuous benchmarking, try 2

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#3407]
We previously tried running benchmarks in github actions and had a lot of noise as well as not great experience with charts not maintenance of the upstream action.

Recently I have been using https://codspeed.io/ with `pydantic-core` and been quite impressed by how it works. Also I have been in touch with the founder as part of our usage in pydantic so should be easy for us to give feedback if we have any.

If no objections, I'd be up for configuring codspeed in our CI and see what we think. It may be helpful given the work we're doing in performance recently and also potentially for 0.21

**Comment by alex** [comment]
How does cod speed help with the challenge of noisy results in GHA?

**Comment by messense** [comment]
@alex See https://dev.to/codspeed/introducing-codspeed-continuous-performance-measurement-3g73, I think it uses valgrind to do instrumentation: 
https://github.com/CodSpeedHQ/pytest-codspeed/blob/master/src/pytest_codspeed/_wrapper/wrapper.c.

**Comment by davidhewitt** [comment]
Yep that was my understanding too. Ultimately it gives a time measurement rather than instruction count so there's presumably some mathematics going on too.

**Comment by davidhewitt** [comment]
Hmmm so initial reaction is that there is still some volatility which leads to a slightly annoying post on PRs. If we can figure out the sources, great. If it's still just down to the GHA environment then probably I'd rather turn the integration off.

**Comment by davidhewitt** [comment]
I've turned the noise threshold up to 20%, given the variance, and set it to only comment on changes. Hopefully that'll make it a bit less busy.
