### ISSUE TITLE
Update docs with fresher bazel support.

### ISSUE THREAD

**Issue by OliverFM** [PyO3/pyo3#3410]
Hi there!
Right now it is quite a lot of work to get PyO3 working with Bazel, but it is possible. It took me many hours of work to get this setup, and most existing advice online is very out of date, or I couldn't get it to work.

There is an closed issue which links to a repo with bazel rules for PyO3:  https://github.com/PyO3/pyo3/issues/481

However, these rules are pretty outdated and do not work with the current versions of rules_rust.
I would suggest adding a link to my repo where I have got a working example of using PyO3 0.19.2 with rules_rust and python 3.9.

If I find the time, I may try and consolidate this to form a new `rule_pyo3` repo.

[commit with working pyo3 and bazel](https://github.com/OliverFM/pytorch_with_gazelle/commit/b65c35c7bfc57107b61591a6c8222edf778ffbd7).

I would be very happy to make a PR with these changes to the docs.

**Comment by davidhewitt** [comment]
A docs PR would be very much appreciated, thanks for the offer. There's a one-sentence reference to the outdated rules at https://pyo3.rs/v0.19.2/building_and_distribution#manual-builds. If you're willing to replace that with up-to-date information (or even a repo) then that would be greatly appreciated. 👍

**Comment by liningpan** [comment]
Hi @OliverFM,

Your PyO3 setup is really helpful when I'm trying to do something similar. However, I think I have a simpler solution. I was able to get PyO3 to perform auto-detection by setting the `PYO3_PYTHON` env var and providing python files as `build_script_data`. This seems to be the least intrusive way to get PyO3 working.

```bzl
annotations = {
    "pyo3-build-config": [crate.annotation(
        build_script_data = [
            "@python_3_11//:files",
            "@python_3_11//:python3",
        ],
        build_script_env = {
            "PYO3_PYTHON": "$(execpath @python_3_11//:python3)",
        },
    )],
},
```

**Comment by OliverFM** [comment]
@liningpan that looks like it would be much easier to manage than my setup – if that is all the code that you needed to add, I think it is definitely worth including a reference to this as the recommended solution.

I think it is worth keeping the references to the trickier setups (like my one and the older rules_pyo3) since they may work better in some cases, but I don't know enough about bazel or pyo3 to be sure.

**Comment by liningpan** [comment]
I will prepare an example. I think it would be good if PyO3 maintainers (@davidhewitt) could confirm that only the build script `build.rs` for **`pyo3-build-config`** need access to the Python interpreter.

**Comment by liningpan** [comment]
https://github.com/liningpan/pyo3-bazel-example

**Comment by davidhewitt** [comment]
Thanks @liningpan. I'm reasonably sure that `build.rs` for `pyo3-build-config` is the only place which is expected to call the Python interpreter.

Do you think you could make a short example using bazel inside the PyO3 repo, tested on CI? We could test this just with latest bazel and Python version, it would be a way just to document this for future readers and also keep us aware if we ever do something which breaks this assumption.
