### ISSUE TITLE
Docs should mention that it's not possible to derive Rust classes from Python ones

### ISSUE THREAD

**Issue by smheidrich** [PyO3/pyo3#3415]
From the answers to #296 I gather that it's not currently possible to have Rust-implemented pyclasses be subclasses of regular Python classes. As far as I can tell, the docs don't mention this explicitly and the [relevant section](https://pyo3.rs/v0.19.2/class.html) only talks about classes that are available as Rust types (like user-defined pyclasses and the ones that come with PyO3).

In my opinion, it wouldn't hurt to mention this explicitly in the docs, both in the text and in the reference table entry for `extends`. Someone else also requested this in https://github.com/PyO3/pyo3/issues/296#issuecomment-1078791626.

I thought that maybe the reason it isn't mentioned is that this is a limitation of Python extension types in general rather than one of PyO3, but [Python's docs on the issue](https://docs.python.org/3/extending/newtypes_tutorial.html#subclassing-other-types) say only that deriving extension types from built-in rather than custom Python types is the easiest option, not that it's the only one.

**Comment by davidhewitt** [comment]
Discussion of the intent to support this is in #991. It's mostly a question of balancing this against many other priorities for PyO3. I would be happy to have this supported.
