### ISSUE TITLE
py.import("cryptography.hazmat.primitives.asymmetric.rsa") Exception

### ISSUE THREAD

**Issue by CoderYunTang** [PyO3/pyo3#3423]
### Bug Description

let _ = py.import("cryptography.hazmat.primitives.asymmetric.rsa");
Exception 0xc0000005 encountered at address 0x7fffecf60f3b: Access violation reading location 0x00000010

### Steps to Reproduce

1. python -m pip virtualenv venv
2. ./venv/Scripts/activate.bat
3. pip install cryptography
4.let _ = py.import("cryptography.hazmat.primitives.asymmetric.rsa");

### Your operating system and version

Windows 10 

### Your Python version (`python --version`)

Python 3.7.5

### Your Rust version (`rustc --version`)

rustc 1.70.0

### Your PyO3 version

0.19.2

### How did you install python? Did you use a virtualenv?

https://www.python.org/downloads/release/python-375/

**Comment by birkenfeld** [comment]
Please share the full Rust module/executable code to reproduce this.

Also, does the import work if you do it in a Python interpreter? I.e. `python -c "import cryptography.hazmat.primitives.asymmetric.rsa"` within the venv?

**Comment by CoderYunTang** [comment]
This issue does not reproduce on other computers and has been updated to python3.10.15 to resolve it
