### ISSUE TITLE
ImportError: DLL load failed while importing _rust : The specified module could not be found

### ISSUE THREAD

**Issue by CoderYunTang** [PyO3/pyo3#3425]
### Bug Description

Python::with_gil(|py|
{
       let ts = py.import("cryptography.hazmat.bindings._rust");
          if let Err(err) = ts {
              println!("{}", err);
          }
}

ImportError: DLL load failed while importing _rust : The specified module could not be found

Importing with the python interpreter is no problem:
![image](https://github.com/PyO3/pyo3/assets/26742895/699028dc-1622-46ac-b246-f8f9880cab3b)

### Steps to Reproduce

1. python3.11.5
2. windows 10
3. py.import("cryptography.hazmat.bindings._rust");
4. ImportError: DLL load failed while importing _rust : The specified module could not be found

### Your operating system and version

Windows 10 

### Your Python version (`python --version`)

python 3.11.5

### Your Rust version (`rustc --version`)

rustc 1.70.0

### Your PyO3 version

0.19.2

### How did you install python? Did you use a virtualenv?

https://www.python.org/

**Comment by davidhewitt** [comment]
Do you use a virtualenv? This is probably just #1896

**Comment by CoderYunTang** [comment]
The same goes for not using a virtual environment. I've tried a lot of things and they don't work.

**Comment by CoderYunTang** [comment]
I tried it on another computer and it was the same

**Comment by davidhewitt** [comment]
Have you checked what libraries the `cryptography` extension is linked against, and are they available on your PATH when running your program?

**Comment by chatdeschroedinger** [comment]
I had the same issue with a venv on windows with python 3.9.1
The issue was solved by upgrading to python 3.9.7

**Comment by QsageHint** [comment]
I have got a same issue when usign scrapy for web scraping
does anyone help me?

**Comment by QsageHint** [comment]
OS: Windows 10
PythonL 3.9.0
I have create virtual environment using virtualenv (20.25.1), and installed scrapy (2.11.1)
Of course, I have installed MSVC and windows sdk

**Comment by davidhewitt** [comment]
Can you try a newer Python version? It seemed like just above 3.9.1 had a problem and I wonder if we'll see the same thing here.

**Comment by QsageHint** [comment]
Good
I have just installed python  3.9.13 and now it is working well

**Comment by richyk1** [comment]
> Good I have just installed python 3.9.13 and now it is working well

I'm using pyenv so I just upgraded my Python version to 3.10.0 and it seems to have fixed the issue.
I did:
`pyenv install 3.10.0`
`pyenv global 3.10.0`

**Comment by QsageHint** [comment]
yes, I think upgrading is the solution with this issue
