### ISSUE TITLE
Move guide listings into cargo workspace

### ISSUE THREAD

**Issue by Hofer-Julian** [PyO3/pyo3#3435]
Currently, the Rust snippets of the guide are inline in the markdown file. This can be fine, but is somewhat limiting.
While you can run doctests on them, it is a bit inconvenient, and you cannot run linters like clippy on them all.

This is why the Rust book puts each snippet onto its own crate: https://github.com/rust-lang/book/tree/main/listings
For the book I am writing I have good experiences with using a workspace for this, since this way the target dir is shared: https://github.com/gtk-rs/gtk4-rs/tree/master/book/listings

The mdbook feature is documented here: https://rust-lang.github.io/mdBook/format/mdbook.html#including-files

If accepted, I'd be happy to have a look. I count 55 listings with a main function, I would put those into their own crate each.
As a follow-up, a CI job could be added to run `cargo build` and `cargo clippy` on them

**Comment by adamreichold** [comment]
Our Noxfile does have support formatting the examples. I think this could easily be expand to also lint them which I think would be preferable to any manual changes to how we manage our examples. Writing them should easy and automation should take care of the mechanical tasks IMHO.

**Comment by Hofer-Julian** [comment]
> Our Noxfile does have support formatting the examples. I think this could easily be expand to also lint them which I think would be preferable to any manual changes to how we manage our examples. Writing them should easy and automation should take care of the mechanical tasks IMHO.

That's fair, I wasn't aware that you can do this with nox.
Will close this issue then.
