### ISSUE TITLE
Appveyor queue is stuck

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#346]
appveyor queues build but doesn't actually build them anymore. @fafhrd91 since you have access to appveyor, could you check if you can get appveyor working again?

**Comment by fafhrd91** [comment]
could you change appveyor to your account?

**Comment by kngwyu** [comment]
How about migrating to Azure Pipelines?

**Comment by konstin** [comment]
> could you change appveyor to your account?

I can try moving appveyor to my account, but I'll only go through the hassle if something like this happens again (The queue seems to be unstuck now). 

> How about migrating to Azure Pipelines?

I haven't worked with it, but azure pipelines looks really promising!
