### ISSUE TITLE
Error: TypeError: 'Kind' object cannot be converted to 'Kind'

### ISSUE THREAD

**Issue by huskyrobotdog** [PyO3/pyo3#3513]
Complex type conversion seems to go wrong.

Error: TypeError: 'Kind' object cannot be converted to 'Kind'

Rust :
``` rust
#[pyclass]
#[derive(Debug, Clone, PartialEq, EnumString, Display, Serialize, Deserialize)]
#[strum(serialize_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum Kind {
	Spot,
	Contract,
}
```

Python : 
```  python
call() -> List[Tuple[Kind, str, Decimal, Decimal, Decimal]]:
    result = []
    result.append((Kind.Spot,'', Decimal(0), Decimal(0), Decimal(0)))
    result
```

Call :
``` rust
let result = result.as_ref(py).extract()?;
```

**Comment by huskyrobotdog** [comment]
The type I want to get

``` rust
Vec<(Kind, String, Decimal, Decimal, Decimal)>
```

**Comment by adamreichold** [comment]
> Error: TypeError: 'Kind' object cannot be converted to 'Kind'

Could you post the full compiler output. Usually such errors indicate that you use `Kind` instance from two different PyO3-based extensions. (Due to static linking, they do not share types even if their Rust implementations do, i.e. `Kind` from one extension has a different type than the `Kind` from the other.)

**Comment by huskyrobotdog** [comment]
> > Error: TypeError: 'Kind' object cannot be converted to 'Kind'
> 
> Could you post the full ~compiler~interpreter output. Usually such errors indicate that you use `Kind` instance from two different PyO3-based extensions. (Due to static linking, they do not share types even if their Rust implementations do, i.e. `Kind` from one extension has a different type than the `Kind` from the other.)


Export enum as python class via pyo3.
Then use rust to call the python function, and the enum(Kind.Spot) returned by python cannot be converted to Rust enum(Kind::Spot) through `extract`.
Tip: 'Kind' object cannot be converted to 'Kind'

**Comment by davidhewitt** [comment]
Without a full minimal reproduction this just sounds like you're running up against #1444

**Comment by huskyrobotdog** [comment]
> against

Thanks, I probably got it. Types in static libraries are not the same as types from Rust sources.
