### ISSUE TITLE
Container iteration maybe needs to be fallble

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#3523]
The check that size has not changed can lead to a panic. In practice this can happen in downstream code: https://github.com/pydantic/pydantic/issues/7832

Maybe container iteration needs to return results always?

**Comment by adamreichold** [comment]
> In practice this can happen in downstream code: 

From my point of view, whether this is a reason to reconsider the panic depends on whether the issue in pydantic-core can be classified as a logic bug or not. If it is indeed a logic bug, then a panic seems appropriate.

(To be honest, I have a hard time imagining this _not_ being a logic bug as concurrent iteration and modification should hardly depend on user or other external input, but the possibility of this happening or not should be entirely within the purview of the author of a program.)

**Comment by davidhewitt** [comment]
I completely agree that there's a logic bug in pydantic-core, which needs some rethinking.

I think the question here is what the fallout of such a bug should be. IMO a panic is always unfortunate because it brings down the process, so the upside of switching to fallible iteration would be that future logic bugs just raise an exception. The downside would be the churn of the ecosystem and reduced ergonomics, so maybe it's just not worth it.

**Comment by adamreichold** [comment]
I am also not sure whether doing anything but `.unwrap()` on the result is reasonable. (This is what I would in a pure Rust code base to handle a logic bug.) I understand the ergonomics of catching `PanicException` are not good, but I would rather improve that than "downgrade" this into a runtime exception.

**Comment by davidhewitt** [comment]
Let's close this for now then 👍
