### ISSUE TITLE
extract Decimal does not support scientific notation.

### ISSUE THREAD

**Issue by huskyrobotdog** [PyO3/pyo3#3530]
```rust
// conversions/rust_decimal.rs

impl FromPyObject<'_> for Decimal {
    fn extract(obj: &PyAny) -> PyResult<Self> {
        // use the string representation to not be lossy
        if let Ok(val) = obj.extract() {
            Ok(Decimal::new(val, 0))
        } else {
            ///  this code  ↓
            Decimal::from_str(obj.str()?.to_str()?)
                .map_err(|e| PyValueError::new_err(e.to_string()))
        }
    }
}
```

`extract` does not support scientific notation.
Need to be changed to
```rust
"".parse::<Decimal>()
```

**Comment by adamreichold** [comment]
It is not clear what your suggested change would accomplish as `str::parse` is literally a wrapper around `FromStr::from_str`: https://doc.rust-lang.org/stable/src/core/str/mod.rs.html#2309-2311

**Comment by davidhewitt** [comment]
I suppose we could try each conversion in turn?

**Comment by davidhewitt** [comment]
I've labelled as good first issue - someone interested could tackle this as a standalone improvement in `src/conversions/rust_decimal.rs`.

**Comment by dmatos2012** [comment]
This looks like its quite standalone, and if I understand correctly its about ability to use `Decimal` using scientific notation which is currently not supported. 

Thus, I would like to give this a try :)

**Comment by davidhewitt** [comment]
Yep exactly, please go for it!
