### ISSUE TITLE
installation instructions should mention pyenv-virtualenv

### ISSUE THREAD

**Issue by nikomatsakis** [PyO3/pyo3#3549]
### Bug Description

The tutorial says to install pyenv, but doesn't mention you also have to install pyenv-virtualenv (at least on mac) for the instructions to work.

### Steps to Reproduce

* install `pyenv`
* try to run `pyenv activate` -- uh oh!

### Your operating system and version

Mac

### Your Python version (`python --version`)

N/A

### Your Rust version (`rustc --version`)

N/A

### Your PyO3 version

N/A

### How did you install python? Did you use a virtualenv?

pyenv

**Comment by nikomatsakis** [comment]
Probably the wrong label.

**Comment by davidhewitt** [comment]
I think it's fine to call it a docs bug :)

Looks like what's happening is that depending on the install method you choose for `pyenv`, it'll either bundle `pyenv-virtualenv` or require a separate install. I'm guessing you used homebrew, which looks like it requires a separate install.

**Comment by nikomatsakis** [comment]
Correct! It was very confusing for me. Some kind of note saying "this command may require a separate install step" would've been very helpful.

**Comment by davidhewitt** [comment]
Hopefully the words in #3550 help future readers!
