### ISSUE TITLE
Cannot convert object when passing object between crates

### ISSUE THREAD

**Issue by notmgsk** [PyO3/pyo3#3562]
### Bug Description

I have two crates `parent` and `child`. `parent` defines a `Base` class and provides two functions `new_a() -> Base` and `do_thing(b: Base)`. `child` provides a single function `new_b() -> parent::Base`. When calling `parent.do_thing(child.new_b())` (i.e. creating a `Base` in the `child` crate and passing it to the `parent` crate`) I get the following error message

```
TypeError: argument 'b': 'Base' object cannot be converted to 'Base'
```

## crate `parent`

`src/lib.rs`
```rs
use pyo3::prelude::*;

#[pyclass]
#[derive(Clone)]
pub struct Base {}

impl Base {
    pub fn new() -> Self {
        Self {}
    }
}

struct ChildA;

#[pyfunction]
fn new_a() -> Base {
    Base::new()
}

unsafe impl Send for Base {}

#[pyfunction]
fn do_thing(c: Base) {
    todo!()
}

#[pymodule]
fn parent(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Base>()?;
    m.add_function(wrap_pyfunction!(new_a, m)?)?;
    m.add_function(wrap_pyfunction!(do_thing, m)?)?;
    Ok(())
}
```

## crate `child`

`src/lib.rs`
```rs
use pyo3::prelude::*;

pub struct ChildB;

#[pyfunction]
pub fn new() -> parent::Base {
    parent::Base::new()
}

#[pymodule]
fn child(_py: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(new, m)?)?;
    Ok(())
}
```

With both of those built and availble to python, run the following
```python
import parent
import child

# # works
# a = parent.new_a()
# parent.do_thing(a)

# doesn't work
b = child.new()
parent.do_thing(b)
```

### Your operating system and version

Ubuntu 23.04

### Your Python version (`python --version`)

3.8.16

### Your Rust version (`rustc --version`)

rustc 1.71.1 (eb26296b5 2023-08-03)

### Your PyO3 version

0.20.0

### How did you install python? Did you use a virtualenv?

`python3 -m venv .venv`

**Comment by adamreichold** [comment]
Duplicate of #1444

**Comment by adamreichold** [comment]
This is a know limitation of static linkage yielding multiple type objects per extension. Do you think #1444 covers your use case as well and we track this there? If so, I would close this issue to improve the manageability of our bug tracker.

**Comment by notmgsk** [comment]
Ah, that's a shame. Thanks for sharing that with me.
