### ISSUE TITLE
Nox has been broken by #3551

### ISSUE THREAD

**Issue by wyfo** [PyO3/pyo3#3592]
#3551 has removed `nox -s fmt`, but it's still used in noxfile line 14:
```python
nox.options.sessions = ["test", "clippy", "fmt", "docs"]
```
So you get this error:
```
nox > Error while collecting sessions.
nox > Sessions not found: fmt
```

I can fix that in a PR, but I need to ask what to do:
- put back `fmt` session
- remove `fmt` from  `nox.options.sessions`
- replace `fmt` from `nox.options.sessions` by either `rustfmt` or `ruff`, or both.

**Comment by davidhewitt** [comment]
Ah, my mistake. Please add `rustfmt` and `ruff` jobs 👍
