### ISSUE TITLE
do we need NoArgs?

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/PyO3#36]
it is possible to use `()` instead of `NoArgs`

**Comment by messense** [comment]
If we add a

```rust

impl<T: IntoPyTuple> IntoPyTuple for Option<T> {
    fn into_tuple(self, py: Python) -> Py<PyTuple> {
        match self {
            Some(v) => v.into_tuple(),
            None => PyTuple::empty(py)
        }
    }
}
```

We can use `None` instead of `NoArgs`

**Comment by fafhrd91** [comment]
Super! Let's do that

**Comment by messense** [comment]
Unfortunately 

```
error[E0282]: type annotations needed
   --> tests/test_class.rs:118:26
    |
118 |     assert!(typeobj.call(None, None).unwrap().cast_as::<EmptyClassWithNew>().is_ok());
    |                          ^^^^ cannot infer type for `T`

error: aborting due to previous error(s)
```

`call(args, kwargs)` can't use `None` as args because `Python::get_type` can't infer type for `T`. So we stuck with `()` or `NoArgs`.

**Comment by fafhrd91** [comment]
What if you use NoArgs as `T`?

**Comment by fafhrd91** [comment]
Ah, nevermind

**Comment by fafhrd91** [comment]
is it possible to use default generic type parameter?

**Comment by messense** [comment]
I am not what you mean by `default generic type parameter`.

**Comment by fafhrd91** [comment]
https://github.com/rust-lang/rust/blob/master/src/test/run-pass/generic-default-type-params.rs

**Comment by fafhrd91** [comment]
https://github.com/rust-lang/rust/pull/26870

**Comment by messense** [comment]
default generic type parameter seems only allowed in type declaration now.

```
error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions.
   --> src/objectprotocol.rs:250:13
    |
250 |     fn call<A = ()>(&self, args: A, kwargs: Option<&PyDict>) -> PyResult<&PyObjectRef>
    |             ^
    |
    = note: #[deny(invalid_type_param_default)] on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #36887 <https://github.com/rust-lang/rust/issues/36887>

error: aborting due to previous error(s)

error: Could not compile `pyo3`.
```

https://github.com/rust-lang/rust/issues/36887

**Comment by messense** [comment]
If we change `call` signature to

```rust
fn call<A>(&self, args: A, kwargs: Option<&PyDict>) -> PyResult<&PyObjectRef>
    where A: Into<Option<PyTuple>>
```

Use should be able to pass `None`, `Some(PyTuple::xxx)` and `PyTuple::xxx` since `Option` has the following impl since 1.12.0:

```rust
impl<T> From<T> for Option<T>
```

https://doc.rust-lang.org/src/core/option.rs.html#854-858

But that would require user to provide a `PyTuple` object.

**Comment by fafhrd91** [comment]
I think it would reduce usability. i use `IntoPyTuple` much more often, plus `NoArg` is not big deal

**Comment by fafhrd91** [comment]
we can play with associated types, similar to class protocols. but I am not sure if it could be implemented

**Comment by fafhrd91** [comment]
lets close this issue, `NoArgs` is not priority at the moment.
