### ISSUE TITLE
PEP 517 breaks relative dependency in rustapi_module

### ISSUE THREAD

**Issue by pganssle** [PyO3/pyo3#362]
So this is a bit of a problem. With `pip >= 19.0` you are automatically opted-in to using PEP 517 if you have a `pyproject.toml`, and there's no way to get the old behavior of "just install the build dependencies but don't use PEP 517 for the build".

This is a bit of a problem because [`rustapi_module`](https://github.com/PyO3/pyo3/blob/f248aaddbe032aaf35fd46d94e406b4869c32eeb/examples/rustapi_module/Cargo.toml#L11) has an out-of-source dependency on the `pyo3` source root, for obvious reasons, but with PEP 517 the build occurs in a temporary build directory.

I don't know enough about how dependencies are specified in Rust to know the right solution here. For now we can disable PEP 517 by removing `pyproject.toml`.

Reported upstream at pypa/pip#6276 for tracking purposes, though I think we'll probably have to find our own workarounds.

**Comment by pganssle** [comment]
Hmm.. This may not be a PEP 517 thing, I can't get it working at all even with `pip == 18.0` now.

**Comment by konstin** [comment]
I'm fine with just removing `pyproject.toml` for fixing the pyo3 example. For the long term solution (depending on whether this gets fixed in pip itself or not) this issue should be moved to the setuptools-rust repo-

**Comment by pganssle** [comment]
@konstin It may be that `setuptools_rust` needs to change to get this working again, but I think this is actually very specific to *this repository*. In any other repository we wouldn't be specifying an out-of-tree relative dependency. We may want to look into some workarounds.

Playing around with setting the `TMPDIR` variable I've been able to get the error message to change a bit, but I haven't been able to actually fix it.

**Comment by konstin** [comment]
I fully agreed that we should solve the part that affects this repository in this repository. I just wanted to say that depending on pip we might need to split this into two issues where one lives in the setuptools-rust repo.

**Comment by davidhewitt** [comment]
Since the very recently released `pip 20.1` then builds are now done in-place, so the issue described here is resolved!

**Comment by pganssle** [comment]
This _may_ need to be revisited at some point. Seems like `pip` is considering reverting the change to in-tree builds: https://github.com/pypa/pip/issues/7555
