### ISSUE TITLE
Provide fallbacks for datetime-related API when Py_LIMITED_API is enabled

### ISSUE THREAD

**Issue by Tpt** [PyO3/pyo3#3633]
Currently `datetime`-related APIs are only available when the `Py_LIMITED_API` is not enabled.

This includes:
* [PyDate](https://docs.rs/pyo3/latest/pyo3/types/struct.PyDate.html)
* [PyDateTime](https://docs.rs/pyo3/latest/pyo3/types/struct.PyDateTime.html)
* [PyDelta](https://docs.rs/pyo3/latest/pyo3/types/struct.PyDelta.html)
* [PyTime](https://docs.rs/pyo3/latest/pyo3/types/struct.PyTime.html)
* [PyTzInfo](https://docs.rs/pyo3/latest/pyo3/types/struct.PyTzInfo.html)
* [PyDateAccess](https://docs.rs/pyo3/latest/pyo3/types/trait.PyDateAccess.html)
* [PyDeltaAccess](https://docs.rs/pyo3/latest/pyo3/types/trait.PyDeltaAccess.html)
* [PyTimeAccess](https://docs.rs/pyo3/latest/pyo3/types/trait.PyTimeAccess.html)
* [PyTzInfoAccess](https://docs.rs/pyo3/latest/pyo3/types/trait.PyTzInfoAccess.html)
* [timezone_utc](https://docs.rs/pyo3/latest/pyo3/types/fn.timezone_utc.html)

Would a fallback using Python interpreter calls like `py.import('datetime')?.getattr('timezone')?.getattr('utc')` be welcome into PyO3 when `Py_LIMITED_API` is enabled? I think it might make easier for some PyO3 users to use abi3. I am willing to contribute it.

**Comment by davidhewitt** [comment]
Yes I think that would be a useful thing to support 👍

**Comment by adamreichold** [comment]
The `chrono` conversions now work for abi3 builds which is what we decided to pursue here in the end. Hence closing this.
