### ISSUE TITLE
A bug in call method 

### ISSUE THREAD

**Issue by evelas** [PyO3/pyo3#3673]
Its is only at Windows.
Try to execute python code at windows and its is work fine. 
![20-12-2023 12-53-58](https://github.com/PyO3/pyo3/assets/12646159/5aa2a72d-ebd0-4dd2-9dbc-ea8aefdb9208)
Run from cli `python test.py` Print is correct path to Python, 

but then i try exec this with run from rust with pyo3. My sys.executable print path = C:\Users\user\rust-pyo3\target\debug\app.exe. 
![20-12-2023 13-03-27](https://github.com/PyO3/pyo3/assets/12646159/eeefe292-0920-4cc6-8ebc-19ec7da3b3e4)

Why path print it like this?

**Comment by davidhewitt** [comment]
This is expected, `sys.executable` is the binary running, and when you embed Python from Rust in this way, your `app.exe` is indeed the executable which is running.
