### ISSUE TITLE
Add API to call builtin methods

### ISSUE THREAD

**Issue by thedrow** [PyO3/pyo3#372]
~Right now, to call a builtin method you have to evaluate Python code as far as I can see.~
You can also `py.import("builtins")` but is it really necessary?
At the very least, this is a documentation issue.
However I think we should add the `call*()` API to the `Python` struct and lazily load the builtins module when those methods are used.

**Comment by konstin** [comment]
Most builtins are exposed through different functions, e.g. `dict()` as `PyDict::new`. If you're missing a specific function, it likely there there's simply no safe wrapper around the c api function yet.

**Comment by davidhewitt** [comment]
Closing as it's not clear to me what we think we should add here.
