### ISSUE TITLE
Potential default `Hash` implementation for `Py<T>`

### ISSUE THREAD

**Issue by jakelishman** [PyO3/pyo3#3745]
I recently had cause to want to track unique `Py<T>` pointers in a hashset, which led me to do something such as
```rust
let item: Py<PyAny> = ...;
let map = HashMap::<*mut ::pyo3::ffi::PyObject, Py<PyAny>>::new();
map.insert(item.as_ptr(), item);
```
or cast the pointer to an integer - it's largely irrelevant to me since I was just using it as a temporary set-like collection and wasn't going to touch the keys again anyway.

Would this pointer-identity based hashing be a suitable blanket implementation of `Hash` (plus corresponding `Eq`) for `Py<T>`?

I saw some discussion in #2999 that pointed out that one might also have intended hashing and equality based on the underlying Python concepts of hash and equality (which hadn't occurred to me).  ~I imagine that there could also be user confusion with an `Eq` implementation given the Python-space `PyAny::eq` that most `Py<T>` will have access to.~ *edit*: actually, that was a mistake - `Py<PyAny>` of course doesn't directly deref to `PyAny`, and there's no `eq` already on `Py`.

**Comment by alex** [comment]
IMO I don't think it makes sense, given the exact point you make in #2999.

The easiest thing to do is wrap the `Py<PyAny>` in a struct that provides `hash()` based on the semantics you want.

**Comment by jakelishman** [comment]
Sure, I'm fine with that as an answer - in my case, the use of it in a hash set is so simple and localised that even the struct encapsulation is overkill for me.

**Comment by davidhewitt** [comment]
As well as the concerns in #2999, it's worth pointing out that the underlying Python implementations are fallible, whereas the Rust traits aren't.

If there Rust traits could handle fallibility I probably would have wanted to have `Bound<'py, PyAny>` implement the Python analytics.

As it is, I think it's best not to offer these traits and leave it to users to wrap as needed. Though the documentation on this could have an example, I guess.

**Comment by jakelishman** [comment]
No trouble - I'll close this issue as "complete" and thanks for the fast responses!
