### ISSUE TITLE
Consider support for unit variants in complex enums

### ISSUE THREAD

**Issue by mkovaxx** [PyO3/pyo3#3749]
Allow the following:
https://github.com/PyO3/pyo3/blob/d1b072222a9a166b3b7078b8e1121b4a794d12bb/tests/ui/invalid_pyclass_enum.rs#L18-L22

**Comment by davidhewitt** [comment]
My stance remains the same as https://github.com/PyO3/pyo3/pull/3582#discussion_r1443166018 that the difference between complex enums and "simple" enums is enough that it's confusing for users to allow unit enums in complex enums. 

So unless there are new ideas which could move this forwards, I'm inclined to keep the current status quo and worry about other things 😄

**Comment by mkovaxx** [comment]
I tend to agree; this would mostly be a cosmetic improvement that might not be worth the added complexity.

**Comment by davidhewitt** [comment]
In which case let's close this for now, there's many other things on the PyO3 issue tracker which could benefit from attention and don't have such design drawbacks.

**Comment by Molkars** [comment]
Sorry to re-open a closed issue. I respect your reasoning to preserve semantics but I think that it should be up to the user to decide to opt-in. My idea is to add a flag onto the pyclass annotation forcing all unit values to be compiled as complex enums:

```rust
#[pyclass(enumclass)]
enum MyEnum {
    Thing1,
    Thing2,
    Thing3,
    Other(UserDefinedThing),
}
```

The above pattern is relatively common in a large code base that I am working in, we're trying to add python bindings somewhat quickly and this is a large deal-breaker for us at the moment. We cannot convert our unit variants to empty variants for the sake of backwards compatibility and we also cannot port these enums into python without doing so! I am willing to create a PR for this idea if the community is conducive to it.

**Comment by luxedo** [comment]
How troublesome is the unit variant in complex enums? I'm currently investigating a potential breaking change in the API for my users:

```python
MyEnum.Variant1              # Currently I'm using simple enum
MyEnum.Variant1()            # I don't want to break compatibility for my users
MyEnum.Variant2("with args") # I need complex enums because one of the variants now needs an argument
```
```rust
enum MyEnum {
    Variant1,
    Variant2 { arg: String },
}
```

If this makes sense I can try give it a try. Otherwise I'm going for a workaround for now.

**Comment by davidhewitt** [comment]
https://github.com/PyO3/pyo3/pull/3582#discussion_r1443166018 is still the latest thoughts here.
