### ISSUE TITLE
Add Table with conversions between wrapper types

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#376]
We should add a table to the documentation that explains with trait and method to use to convert one wrapper type to another. This is complementary to #374.

For example you use `ToPyObject::to_object` to convert `&PySomeNativeType` to `PyObject` and there's `AsPyRef` to convert `PyObject` and `Py<T>` to `PyRef<T>`s.

**Comment by pganssle** [comment]
You beat me to it, I was going to suggest the same thing.

I was thinking there should be an N x N grid, possibly with color-coded backgrounds to indicate things like "zero cost conversion" and whether the transformation is safe.

**Comment by davidhewitt** [comment]
I'm going to work on this as tidy ups for `0.12`.
