### ISSUE TITLE
Get a reference from `PyRef` with `'p` lifetime

### ISSUE THREAD

**Issue by cmpute** [PyO3/pyo3#3760]
Currently the implementation of [`Deref for PyRef<'p, T>`](https://docs.rs/pyo3/latest/pyo3/pycell/struct.PyRef.html#impl-Deref-for-PyRef%3C'p,+T%3E) will produce a reference that live as long as the `PyRef` instance. However, the reference to the underlying type instance should be available as long as the GIL is hold (if I understand it correctly). Currently it's impossible to obtain a `&'p T` reference from an `PyRef<'p, T>` instance.

I encounter this problem because I want to get and store (temporarily) a reference to a custom pyclass from `&PyAny`. The only way I found is to convert `&PyAny` to `PyRef<MyClass>` first, and then get the reference `&MyClass` from `PyRef<MyClass>`. The problem is that the reference `&MyClass` cannot live longer than `PyRef<MyClass>` currently, which basically means I have to store `PyRef<MyClass>` instead? (Although there might be other ways to obtain the reference to the Rust type, I still think it make sense to add this capability to `PyRef` and `PyRefMut`).

I create [a solution here](https://github.com/cmpute/pyo3/commit/59b8660270cae31d433a8fdbdfacadf75f4bf07a), which adds a method to `PyRef` that returns `&'p T`. I'm not sure if this is a reasonable change, but it seems to solve the problem.

**Comment by cmpute** [comment]
I found the issue in this change, the `PyCell` borrow checker will not work correctly in this way. So maybe the solution is still to store the PyRef instance.

**Comment by davidhewitt** [comment]
If your class is `#[pyclass(frozen)]` and `Sync` then it should be safe to convert `&PyAny` to `&PyCell<T>` and then to `&T` using `PyCell::get`.

(I think will also work the same with `&Bound<PyAny>` -> `&Bound<T>` -> `&T` with `Bound::get`, but that's not implemented yet.)
