### ISSUE TITLE
Cross Compilation of Pyo3 on x86 linux for aarch64 linux and MacOS 

### ISSUE THREAD

**Issue by diptanu** [PyO3/pyo3#3764]
Hi folks, I read the cross compilation section of Pyo3 and still haven't been able to figure out how to compile a binary on x86_64 linux(Ubuntu 22.04) for aarch64 (Linux server arm) and for MacOS ARM (M series). Can I get some concrete steps to do it? Some step by step instructions would help.

**Comment by davidhewitt** [comment]
Are you trying to build a Rust executable or an extension module? If an extension-module, are you using one of `maturin` or `setuptools-rust`?

`maturin` has the best cross-compilation support, though in particular for the macOS build if you can run in GitHub actions on a mac runner that should make things easier...

**Comment by diptanu** [comment]
@davidhewitt I am trying to build a Rust executable which supports multiple version of Python.

**Comment by diptanu** [comment]
@davidhewitt I arrived at a working solution with Cross-Rs, let me know what you think. Might be worth sharing this as an example on the docs to save some time for another soul in the future :) 

cross - https://github.com/tensorlakeai/indexify/blob/main/Cross.toml
and the docker file - https://github.com/tensorlakeai/indexify/blob/main/dockerfiles/Dockerfile.cross
