### ISSUE TITLE
Expected interaction with python virtual environments

### ISSUE THREAD

**Issue by jmrgibson** [PyO3/pyo3#379]
It's quite common to use python virtual environments to control which python interpreter and which packages you are using. 

At the moment, Pyo3 links against the system python installation, and then adds the system-wide site pacakges to the python path when running, ignoring the current virtual environment. 

I realize we can control this using the `SYS_PYTHON_EXECUTABLE` variable, but whats the expected behaviour here? Could/should we make pyo3 detect the presence of a virtual environment, select that as the python to link against, and then only use the virtual environment packages when starting up an interpreter to run python code from rust?

**Comment by konstin** [comment]
Pyo3 does link against the active virtual environment. If that didn't work, please provide the commands needed to reproduce the problem.

> adds the system-wide site pacakges to the python path when running, 

pyo3 doesn't change the python path.
