### ISSUE TITLE
GIL tests are flaky

### ISSUE THREAD

**Issue by Alexander-N** [PyO3/pyo3#386]
The following tests fail randomly, for example in https://travis-ci.org/PyO3/pyo3/jobs/501186502:
* `gil::test::test_owned`
* `gil::test::test_owned_nested`
* `gil::test::test_pyobject_drop`

The reason seems to be that they all take references of the empty Python tuple and make assertions for the expected reference count. This can fail if the tests are executed in parallel.

**Comment by konstin** [comment]
To add a bit more context why this happens: Empty tuples are singletons, i.e. you get the same object every time you ask for an empty (s. https://github.com/python/cpython/blob/234531b4462b20d668762bd78406fd2ebab129c9/Objects/tupleobject.c#L89-L91). This means that those parallel running test all change the reference count of that object, leading to those test failures. A solution would be using a unique object for each test.

**Comment by pganssle** [comment]
This is a similar root cause to #204. See #205 for how this problem was fixed for the GC tests.

**Comment by kngwyu** [comment]
How about using `cargo test -- --test-threads=1`?

**Comment by pganssle** [comment]
That would open is up to other thread safety bugs. We've already found locking bugs in `datetime ` because the tests are run in parallel. I think the right solution is to make the test suite thread safe.
