### ISSUE TITLE
Tidy up Bound API deprecation messages

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#3891]
We recently merged a few deprecation messages with the form

```
part of the deprecated GIL Ref API; to migrate use X instead
```

On stream this morning the agreement from viewers was that it would be easier if these messages just read

```
use X instead
```

and dropped the rest of the message. Users can read up about the API migration in other places, so let's tone down the verbosity.

We have a volunteer from Discord to do this (not sure on GitHub username).

**Comment by dmatos2012** [comment]
Yes, this seems easy enough to just get familiar with py03 codebase. That would be me @davidhewitt. Not sure if anyone assigns in this repo, but ill take care of it. Thanks!

**Comment by davidhewitt** [comment]
We generally are not great at assigning, but that doesn't mean we can't start doing it :)
