### ISSUE TITLE
Discord Invites Are Invalid

### ISSUE THREAD

**Issue by neachdainn** [PyO3/pyo3#3912]
I don't know if this is really the correct place to file this kind of "issue", but all of the Discord links that have been posted (in the README, in the initial discussion about starting a Discord, and in Gitter) all appear to be invalid or expired.

**Comment by davidhewitt** [comment]
Ooof, sorry about that, my mistake. I'll open a PR now, and in the meanwhile, new (non-expiring) link is https://discord.gg/33kcChzH7f
