### ISSUE TITLE
Question: How to pass a mutable reference of a numpy.ndarray?

### ISSUE THREAD

**Issue by flosse** [PyO3/pyo3#394]
I have a 3D numpy array with a lot of data I'd like to manipulate with Rust.
How can I do this?
I'd like to write s.th. like this:
```rust
#[pyfunction]
my_calc(data: &mut Vec<Vec<Vec<f32>>>) -> PyResult<()> {
   // change data
  Ok(())
}   
```
It seems not to work :( How can I do something similar?

**Comment by pganssle** [comment]
@flosse Have you seen the [rust-numpy](https://github.com/rust-numpy/rust-numpy) project? It seems like that would be a good place to start.

**Comment by flosse** [comment]
@pganssle thank you! That's exactly what I need :)
