### ISSUE TITLE
Add PyDict_GetItem method to PyDict type binding

### ISSUE THREAD

**Issue by MarshalX** [PyO3/pyo3#3964]
This will be helpful in micro optimizations where we don't care about errors and we are okay to get `None`. 

The current implementation of `get_item` uses `PyDict_GetItemWithError` which creates a little overhead while taking Python errors. 

https://github.com/PyO3/pyo3/blob/dcba984b51be253cb5d385e72008ee9578807504/src/types/dict.rs#L431-L438

The overhead could be pretty displayed using flame graph:
![image](https://github.com/PyO3/pyo3/assets/15520314/c2f3f7e6-43db-426c-a80b-ac051c06789c)

The right side with `PyErr::take` could gone

The solution is to add new method `get_item_TBD` which will use `PyDict_GetItem` instead

**Comment by davidhewitt** [comment]
For some context, I changed this in #3330. I removed the "infallible" version but perhaps that was too aggressive and we can bring it back with an awkward name and a strong recommendation not to use it except in performance sensitive cases.

It's possible there are ways that we could make error handling overhead lighter, those would need exploration.

**Comment by davidhewitt** [comment]
Possibly relevant: in 3.13 we will have `PyDict_GetItemRef` which will be faster because error and not-present cases will be distinguishable in the return code. https://docs.python.org/dev/c-api/dict.html#c.PyDict_GetItemRef

So a cleaner option might be to just optimise this method on 3.13 once available.

**Comment by davidhewitt** [comment]
Also for freethreaded Python `PyDict_GetItemRef` is strongly recommended to avoid race conditions, which is a reason not to expose an API wrapping `PyDict_GetItem` as it is not thread safe.

**Comment by davidhewitt** [comment]
As of PyO3 0.22.3 we use `PyDict_GetItemRef` on 3.13, so the overhead should now be gone with latest versions of things 🎉
