### ISSUE TITLE
How to return Option<String> value from pyo3 getter method?

### ISSUE THREAD

**Issue by brupelo** [PyO3/pyo3#400]
Yesterday I've spent a considerable ammount of time trying to figure out how to achieve this one, [https://stackoverflow.com/questions/55192023/how-to-return-optionstring-value-from-pyo3-getter-method](https://stackoverflow.com/questions/55192023/how-to-return-optionstring-value-from-pyo3-getter-method), do you have any idea about it?

Thx!

**Comment by kngwyu** [comment]
```rust
use pyo3::prelude::*;
use syntect::highlighting::Theme as _Theme;

#[pyclass]
pub struct Theme {
    wrap: _Theme,
}

#[pymethods]
impl Theme {
    #[getter]
    fn name(&self) -> PyResult<Option<String>> {
        Ok(self.wrap.name.clone())
    }
}

#[pymodule]
fn mcve(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<Theme>()?;
    Ok(())
}
```

**Comment by brupelo** [comment]
Thanks a lot, it works!

**Comment by kngwyu** [comment]
:+1: 
(Yeah I know we have only poor documents, but I (and maybe others too) don't have enough time now, sorry

**Comment by brupelo** [comment]
@kngwyu No worries, just to let you know this project is totally awesome!!! Main problem on my side is mainly I've been using rust for 1 week so I'm pretty much a total newcomer and I've got stuck many times.

I'll be posting questions here once in a while, I assume you're one of the main core-devs, right?

Anyway, once again, tyvm! Your help was unvaluable, yesterday I'd wasted quite of time trying to figure out this issue :)

**Comment by konstin** [comment]
This is the issue tracker for pyo3, please do not use it as general support forum. You can get help on gitter and on stackoverflow. Also please don't delete questions but [self-answer](https://stackoverflow.com/help/self-answer) them so others can profit from the solution as well.
