### ISSUE TITLE
"undefined symbol: PyObject_SelfIter" when loading numpy inside pyo3 loaded via `dlopen`

### ISSUE THREAD

**Issue by rlidwka** [PyO3/pyo3#4000]
### Bug Description

I'm building `pyo3` inside a dynamic library with the idea of loading it on demand when needed. 

When I'm using `dlopen` to load it (via [libloading](https://github.com/nagisa/rust_libloading) or [dlopen2](https://github.com/OpenByteDev/dlopen2) - both provide similar result) to load library that I've built, loading `numpy` inside the code provides `undefined symbol: PyObject_SelfIter` error.

If library is linked at compile time however via `cargo:rustc-link-lib=dylib=mylib`, that works normally.

Can you advice me what is the issue, and what am I doing wrong?

### Steps to Reproduce

1. find a Linux machine with python3 and numpy installed
2. clone this repository: https://github.com/rlidwka/pyo3-issue-4000 (or unpack tarball attached at the bottom)
3. run `cargo build` **in mylib directory** to build `libmylib.so` (which contains code that calls pyo3)
4. run `cargo run --bin mybin1` - that prints "ok" for me
5. run `cargo run --bin mybin2` - that prints an error for me

### Backtrace

```shell
error: ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/bin/python3"
  * The NumPy version is: "1.25.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /home/user/.local/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_SelfIter
```

### Your operating system and version

Ubuntu 22.04 LTS

### Your Python version (`python --version`)

Python 3.10.6

### Your Rust version (`rustc --version`)

rustc 1.79.0-nightly (47ecded35 2024-03-26)

### Your PyO3 version

0.21.0

### How did you install python? Did you use a virtualenv?

apt

### Additional Info

You can find reproduction sample at either of these 2 locations:

 - https://github.com/rlidwka/pyo3-issue-4000
 - [pyo3-issue-4000.tar.gz](https://github.com/PyO3/pyo3/files/14772405/pyo3-issue-4000.tar.gz)

**Comment by davidhewitt** [comment]
I wonder if the problem is that symbols you library are not being made available to the rest of the process by your default call to `dlopen`. Can you try to pass flags to `dlopen`, specifically `RTLD_GLOBAL`? (https://pubs.opengroup.org/onlinepubs/7908799/xsh/dlopen.html)

**Comment by rlidwka** [comment]
> I wonder if the problem is that symbols from your library are not being made available to the rest of the process by your default call to dlopen. Can you try to pass flags to dlopen, specifically RTLD_GLOBAL?

Thanks, that solves it!

I've changed it to the following code, so it works now. Gonna read `dlopen` flags some more to check what they do...

```rs
unsafe {
    let lib = libloading::os::unix::Library::open(
        Some("./target/debug/libmylib.so"),
        libloading::os::unix::RTLD_NOW | libloading::os::unix::RTLD_GLOBAL
    ).unwrap();

    let func: libloading::os::unix::Symbol<extern "C" fn()> = lib.get(b"pytest").unwrap();
    func()
}
```
