### ISSUE TITLE
`PyUnicode_DATA` and related APIs need to be disabled on PyPy

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#4040]
In https://github.com/pydantic/jiter/pull/75 we had to not use `PyUnicode_DATA` for PyPy in a downstream project because it was segfaulting.

Probably all APIs which reach into `PyUnicodeObject` C struct need to be disabled for PyPy. Supported APIs are visible at https://github.com/PyO3/python3-dll-a/blob/main/src/libpypy3.10-c.def#L658-L735

Good first issue for anyone who wants to take a look at `pyo3-ffi` and how we declare the C APIs for our supported Python implementations.

**Comment by dmatos2012** [comment]
I will give this one a try as well :)
