### ISSUE TITLE
expose `GILGuard` for RAII usage with a `map` method

### ISSUE THREAD

**Issue by jimy-byerley** [PyO3/pyo3#4046]
Hello everyone
Do you think it could be acceptable to expose the [`GILGuard`](https://github.com/PyO3/pyo3/blob/a4aea230ed6087a5fccc415d6456c536645e0df1/src/marker.rs#L438) and add it a `map` method like in [`lock_api::MappedMutexGuard`](https://docs.rs/lock_api/latest/lock_api/struct.MappedMutexGuard.html#method.map) ? 
The goal of the guard would be the ability to hold the GIL independently of the scope of a closure, just like with any mutex. And the `map` method could be convenient to transport python bound references along with that guard.

I have a usecase in functional programming where it could help a lot improve the performance

Lets consider the following rust code calling python using the current API
```rust
Python::with_gil(|py| {
    let var = PyStuff::new(py);
    my_long_func(|| var.do_something());
});

// this function is third-party and doesn't know about python
fn long_func<T, F: FnMut() -> T>(f: F) {
    // use `f` many times
    let a = f();
    let b = f();
    // and the rest is without python, but long
    do_something_else(a, b);
}
```

In the above example, the GIL is held much longer than needed, because for `do_something_else()` we do not need to interact with python

Using a GILGuard like a mapped mutex guard would allow the previous example to be improved as the following 
```rust
// new methods to acquire a GILGuard and map it a value
let var = Python::gil().map(PyStuff::new);
my_long_func(move || var.do_something());  // var is owned by the closure and holds the GIL

// this function is third-party and doesn't know about python
fn long_func<T, F: FnMut() -> T>(f: F) {
    // use `f` many times
    let a = f();
    let b = f();
    drop(f);    // the closure is dropped, dropping its guard and the GIL
    // and the rest is without python, but long
    do_something_else(a, b);
}
```
the GIL is held only the necessary time, so other python thread can proceed.

**Comment by adamreichold** [comment]
With the pooled memory management backing the deprecated "GIL refs" API, we cannot expose `GILGuard` because we need to ensure proper nesting. But I guess we could overhaul it as a public API when the `gil-refs` feature and hence `GILPool` itself is disabled. On the other hand, the GIL itself is on the way out so I am not sure whether we should invest in additional API enshrining the current locking discipline.

**Comment by jimy-byerley** [comment]
Yes the GIL is on the way out, I can't wait for a nogil release ! 
So I agree this feature might not be worth it. I will see if I can find time propose a PR but I doubt it.

**Comment by adamreichold** [comment]
> Then there's also the issues that the gil must be acquired and released in the correct order, which is easy with Python::with_gil's scoped api, but not with gilguard.

But wasn't this only required to keep our internal `GILPool` instances in sync? And since we do not need those when the feature `gil-refs` is disabled, all of these failure modes should be impossible, shouldn't they?

**Comment by mejrs** [comment]
> > Then there's also the issues that the gil must be acquired and released in the correct order, which is easy with Python::with_gil's scoped api, but not with gilguard.
> 
> But wasn't this only required to keep our internal `GILPool` instances in sync? And since we do not need those when the feature `gil-refs` is disabled, all of these failure modes should be impossible, shouldn't they?

This is required by the gilstate functions: https://docs.python.org/3/c-api/init.html#c.PyGILState_Ensure

**Comment by adamreichold** [comment]
> This is required by the gilstate functions: https://docs.python.org/3/c-api/init.html#c.PyGILState_Ensure

Ah, thanks! That API is more limited than a general purpose lock due to the thread-local state it modifies and hence exposing `GILGuard` would still be a bad idea even without a `GILPool` backing it.

I think this should indeed be closed as not planned then?

**Comment by davidhewitt** [comment]
I think so, yes. My understanding of this is the same; we removed the API not for the Gil Refs but because we need to guarantee ordering of calls to the underlying API.

Just for completeness with the original example, a third option which works today is to have a short term lock by moving `with_gil` inside the closure:

```rust
my_long_func(|| Python::with_gil(|py| PyStuff::new(py).do_something()));
```

**Comment by jimy-byerley** [comment]
> Just for completeness with the original example, a third option which works today is to have a short term lock by moving with_gil inside the closure

Sure, but this option in the original example means that `long_func` will acquire and release the GIL multiple times (since calling the closure multiple times), which I guess is not good for performance ?

> Furthermore you do not need it. You can express everything with Python::with_gil, although it may sometimes be slightly wordy or annoying.

@mejrs how would you fix the performance issue in the original example then ? Remember ` long_func` is third party in this example and cannot be splitted or call `Python::with_gil`  itself

**Comment by mejrs** [comment]
> Sure, but this option in the original example means that long_func will acquire and release the GIL multiple times (since calling the closure multiple times), which I guess is not good for performance ?

If the gil is available, acquiring it is cheap. Just like most other mutexes.

> @mejrs how would you fix the performance issue in the original example then ? Remember  long_func is third party in this example and cannot be splitted or call Python::with_gil itself

If long_func doesn't know about python, why would it bother dropping the closure early? What if it is refactored to drop it much later? Having short critical sections like davidhewitt suggested is much better and more predictable.
