### ISSUE TITLE
Compilation error implementing dunder (magic) methods (__contains__)

### ISSUE THREAD

**Issue by tokahuke** [PyO3/pyo3#4051]
### Bug Description

Trying to implement `__contains__` for a `pyclass` fails with a compilation error

### Steps to Reproduce

1. Create a `pyclass`.
2. In the `pymethods` impl block, write the following:
```rust
fn __contains__(&self, key: &Bound<PyAny>) -> PyResult<PyObject> {
    todo!()
}
```
3. This fails `cargo check`.

### Backtrace

```shell
error[E0277]: the trait bound `pyo3::Py<pyo3::PyAny>: IntoPyCallbackOutput<i32>` is not satisfied
   --> jyafn-python/src/mapping.rs:54:1
    |
54  | #[pymethods]
    | ^^^^^^^^^^^^ the trait `IntoPyCallbackOutput<i32>` is not implemented for `pyo3::Py<pyo3::PyAny>`
    |
    = help: the following other types implement trait `IntoPyCallbackOutput<Target>`:
              <bool as IntoPyCallbackOutput<bool>>
              <bool as IntoPyCallbackOutput<i32>>
              <usize as IntoPyCallbackOutput<isize>>
              <usize as IntoPyCallbackOutput<usize>>
              <HashCallbackOutput as IntoPyCallbackOutput<isize>>
              <IterNextOutput<T, U> as IntoPyCallbackOutput<*mut pyo3::ffi::PyObject>>
              <IterANextOutput<T, U> as IntoPyCallbackOutput<*mut pyo3::ffi::PyObject>>
              <Result<T, E> as IntoPyCallbackOutput<U>>
            and 3 others
    = note: required for `Result<pyo3::Py<pyo3::PyAny>, pyo3::PyErr>` to implement `IntoPyCallbackOutput<i32>`
note: required by a bound in `pyo3::callback::convert`
   --> /Users/pedroarruda/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.21.0/src/callback.rs:175:8
    |
173 | pub fn convert<T, U>(py: Python<'_>, value: T) -> PyResult<U>
    |        ------- required by a bound in this function
174 | where
175 |     T: IntoPyCallbackOutput<U>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `convert`
    = note: this error originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `jyafn-python` (lib) due to 1 previous error
```

### Your operating system and version

MacOS 12.3.1 (21E258)

### Your Python version (`python --version`)

Python 3.12.0

### Your Rust version (`rustc --version`)

rustc 1.76.0 (07dca489a 2024-02-04)

### Your PyO3 version

0.21.0

### How did you install python? Did you use a virtualenv?

System python, yes, with pipenv.

**Comment by Icxolu** [comment]
`__contains__` is supposed to return a `bool` or `PyResult<bool>`. If you change your function to this
```rust
fn __contains__(&self, key: &Bound<PyAny>) -> PyResult<bool> {
    todo!()
}
```
it starts working again. The signatures of the magic methods is documented over [here](https://pyo3.rs/v0.21.1/class/protocols.html#mapping--sequence-types).  I hope that helps 😃

**Comment by tokahuke** [comment]
Thanks for the docs! But is this a Python limitation? For my usecase, I
_need_ to return something that is not a bool.


Icxolu ***@***.***> schrieb am Sa., 6. Apr. 2024, 14:08:

**Comment by tokahuke** [comment]
Ok, thanks. So the way to go is to create a `.contains` method, then.

Icxolu ***@***.***> schrieb am Sa., 6. Apr. 2024, 15:08:
