### ISSUE TITLE
Unable to mutate nested class values in python

### ISSUE THREAD

**Issue by leeian1011** [PyO3/pyo3#4075]
### Bug Description

I am unsure if this is considered a bug or if this is expected, if it is not a bug please do update the labels accordingly.

Creating two simple pyclass, and nesting one in the other, works fine, however, if I were to try and mutate the nested class' values in python it will not work. I seriously hope this is not a misunderstanding on how python and pyo3 works on my end.

### Steps to Reproduce

- Define two pyclass in rust,
```
use pyo3::prelude::*;
use pyo3::types::{PyFloat, PyString};

#[pyclass(get_all, set_all)]
#[derive(Clone)]
pub struct Test {
    pub object_one: TestStruct,
    pub object_two: TestStruct,
}

#[pymethods]
impl Test {
    #[new]
    fn new() -> Self {
        Self {
            object_one: TestStruct::rust_new(format!("object one"), 69.0),
            object_two: TestStruct::rust_new(format!("object two"), 0.69)
        }
    }
}

#[pyclass(get_all, set_all)]
#[derive(Clone)]
pub struct TestStruct {
    pub value: f64,
    pub name: String
}

impl TestStruct {
    fn rust_new(name: String, value: f64) -> Self {
        Self {
            value,
            name
        }
    }
}

#[pymethods]
impl TestStruct {
    #[new]
    fn new<'p>(name: &'p PyString, value: &'p PyFloat) -> Self {
        Self {
            name: name.to_string(),
            value: value.value()
        }
    }
}

#[pymodule]
fn pyo3_test(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<TestStruct>()?;
    m.add_class::<Test>()?;
    Ok(())
}
```

- maturin dev

- run simple python script to mutate the nested class values

```
import pyo3_test

x = pyo3_test.Test()

print(x.object_one.name) # prints "object one"
x.object_one.name = "new name"
print(x.object_one.name) # Expected: "new name", Result: "object one"
```

### Your operating system and version

Ubuntu 22.04 Jammy

### Your Python version (`python --version`)

3.11.7

### Your Rust version (`rustc --version`)

1.76

### Your PyO3 version

0.19

### How did you install python? Did you use a virtualenv?

miniconda

### Additional Info

Currently using the 0.19 release as the project I am working on is waiting on pyo3_log to support the 0.21 update, the example I gave above is a minimal reproducible example. This can be reproduced on 0.21 as well.

**Comment by adamreichold** [comment]
Please have a look at https://pyo3.rs/v0.21.1/faq#pyo3get-clones-my-field

The property `x.object_one` as generated by `get_all` will return a copy of the field which is possibly why you had to add `#[derive(Clone)]` to `TestStruct` in the first place.

If you want to share ownership of `object_one` with Python code, you need to wrap it with a [`Py` smart pointer](https://docs.rs/pyo3/latest/pyo3/struct.Py.html).

**Comment by leeian1011** [comment]
It seems as though you are right, this is entirely my misunderstanding. Thank you for clarifying and I apologize for the noise!

**Comment by adamreichold** [comment]
> Thank you for clarifying and I apologize for the noise!

Don't worry about it. We are all learning together.
