### ISSUE TITLE
bug: Generated module PyInit releases GIL, then crashes

### ISSUE THREAD

**Issue by amunra** [PyO3/pyo3#4076]
### Bug Description

I've been adding a new module to my existing project.
I'm not using maturin, but instead updated my `setup.py` script.
It compiles and links fine.

My package's structure is as follows once built.

```
src/
    questdb/                           <--- top level module
       __init__.py                     <--- empty
       egress.cpython-311-darwin.so    <--- new PyO3 extension
       ingress.cpython-311-darwin.so   <--- my existing Cython extension
```

Trouble comes if I load this up in a REPL:
```
% python3
Python 3.11.1 (main, Dec 15 2022, 22:07:06) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import questdb.egress
Fatal Python error: PyInterpreterState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: unknown
```

You can see my full code here:
https://github.com/questdb/py-questdb-client/compare/4ea8800..71128e2

If you want to try it out yourself:
```shell
git clone https://github.com/questdb/py-questdb-client
cd py-questdb-client
git checkout 71128e2
./proj build
./proj test
```

But the `lib.rs` file is pretty straight-forward:
```rust
use pyo3::prelude::*;

#[pyfunction]
fn sum_as_string(a: usize, b: usize) -> PyResult<String> {
    Ok((a + b).to_string())
}

#[pymodule]
fn egress(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(sum_as_string, m)?)?;
    Ok(())
}
```

Note that the I've also tried `questdb_egress` to match the lib name, but Python specifically looks for a `PyInit_egress`.

I've done some basic levels investigation (I've got no real experience with PyO3) by desugaring `#[pymodule]` using [`cargo expand`](https://github.com/dtolnay/cargo-expand).

I've then instrumented the resulting code with a log line:

```rust
mod egress {
    #[doc(hidden)]
    pub const __PYO3_NAME: &'static str = "egress\u{0}";
    pub(super) struct MakeDef;
    #[doc(hidden)]
    pub static _PYO3_DEF: ::pyo3::impl_::pymodule::ModuleDef = MakeDef::make_def();
    /// This autogenerated function is called by the python interpreter when importing
    /// the module.
    #[doc(hidden)]
    #[export_name = "PyInit_egress"]
    pub unsafe extern "C" fn __pyo3_init() -> *mut ::pyo3::ffi::PyObject {
        ::pyo3::impl_::trampoline::module_init(
            |py| {
                let has_gil = ::pyo3::ffi::PyGILState_Check();
                eprintln!("_PYO3_DEF.make_module :: (A) has_gil={}", has_gil);
                let res = _PYO3_DEF.make_module(py);
                eprintln!("_PYO3_DEF.make_module :: (B)");
                res
            })
    }
}
```

The output is then:
```
_PYO3_DEF.make_module :: (A) has_gil=1
Fatal Python error: PyInterpreterState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: unknown
```

Tracing this through, it seems to be this line: https://github.com/PyO3/pyo3/blob/721100a9e981391de784022bf564285f772314ea/src/impl_/pymodule.rs#L112

I haven't had a chance to debug this further.

**WILD GUESS**: My guess is that this has to do with the fact that It's a nested extension, rather than a top-level extension.
I've tried changing:
```diff
- pub const __PYO3_NAME: &'static str = "egress\u{0}";
+ pub const __PYO3_NAME: &'static str = "questdb.egress\u{0}";
```

It made no difference.

### Steps to Reproduce

See above.

### Your operating system and version

MacOS 14.3.1 (arm)

### Your Python version (`python --version`)

Python 3.11.1

### Your Rust version (`rustc --version`)

1.77.2

### Your PyO3 version

0.21.1

### How did you install python? Did you use a virtualenv?

pyenv, no virtualenv (my Python code doesn't have any dependencies anyways).

**Comment by birkenfeld** [comment]
I checked out your code and built the module by just calling cargo in the `egress` directory. It imports fine. I didn't want to go through your `./proj` build system to ensure it doesn't do anything untoward (no offense), so I just looked at it, and this looks fishy:
```
    rust_flags = f"-C link-arg=-L{lib_dir} -C link-arg=-l{python_lib}"
    env['RUSTFLAGS'] = rust_flags
```
Extension modules should not link against libpython, at least on Unix. On platforms where it's necessary, `pyo3-build-config` will automatically ensure that on its own.

One possibility stemming from there is that your module links against a different libpython than you're importing it in, so that you have two instances of the interpreter, which then causes all kinds of state chaos.

**Comment by birkenfeld** [comment]
Oh - the best way to find out if the `pyo3` build system is picking up the right interpreter is to set `PYO3_PRINT_CONFIG=1` while building; it will print the build config and then exit.

**Comment by amunra** [comment]
Thanks for taking a look, no closer unfortunately.

I don't blame you for not wanting to run random scripts, but if it helps debug `./proj build` simply calls `setup.py` through a child process as so:

```
python3 setup.py build_ext --inplace
```

The interpreter that's used in `setup.py` and when testing is the same.

```
adam@tempest py-questdb-client % python3
Python 3.11.1 (main, Dec 15 2022, 22:07:06) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
adam@tempest py-questdb-client % which python3 
/Users/adam/.pyenv/versions/3.11.1/bin/python3
```

For sake of completeness, If I print `sys.executable` from within `setup.py` I get the same exact path:
```
/Users/adam/.pyenv/versions/3.11.1/bin/python3
```

It's fair to say there's no cross-version stuff going on.

A simple `cd egress && cargo build --release` fails to link (I'm on an arm Mac, b.t.w.):
```
            _PyBytes_AsString, referenced from:
                pyo3::types::string::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..string..PyString$GT$$GT$::to_string_lossy::hed6f25db41055265 in libpyo3-3791acf91cdee691.rlib[5](pyo3-3791acf91cdee691.pyo3.a426cb02774c716e-cgu.02.rcgu.o)
            _PyBytes_Size, referenced from:
                pyo3::types::string::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..string..PyString$GT$$GT$::to_string_lossy::hed6f25db41055265 in libpyo3-3791acf91cdee691.rlib[5](pyo3-3791acf91cdee691.pyo3.a426cb02774c716e-cgu.02.rcgu.o)
            _PyCMethod_New, referenced from:
                pyo3::types::function::PyCFunction::internal_new::hc5d182335d41fccf in libpyo3-3791acf91cdee691.rlib[7](pyo3-3791acf91cdee691.pyo3.a426cb02774c716e-cgu.04.rcgu.o)
...
```

It is for this reason that I've added the `RUSTFLAGS` logic that you've spotted.
It did solve thie linkage issue.
```
    rust_flags = f"-C link-arg=-L{lib_dir} -C link-arg=-l{python_lib}"
    env['RUSTFLAGS'] = rust_flags
```

Though I suspect it isn't quite right, obviously.

If I export `PYO3_PRINT_CONFIG=1` (nb. I'm not setting special `RUSTFLAGS` here), I get:
```
  -- PYO3_PRINT_CONFIG=1 is set, printing configuration and halting compile --
  implementation=CPython
  version=3.11
  shared=false
  abi3=false
  lib_name=python3.11
  lib_dir=/Users/adam/.pyenv/versions/3.11.1/lib
  executable=/Users/adam/.pyenv/versions/3.11.1/bin/python
  pointer_width=64
  build_flags=
  suppress_build_script_link_lines=false

  note: unset the PYO3_PRINT_CONFIG environment variable and retry to compile with the above config
```

This looks fine to me.

Am I supposed to add some `build.rs` in my `egress` project, by any chance?

**Comment by amunra** [comment]
Fixed!

I stumbled on this helpful piece of doc: https://pyo3.rs/v0.21.1/building-and-distribution#macos

It mentions:

> On macOS, because the extension-module feature disables linking to libpython

I followed its advice and added the following to `.cargo/config.toml`:

```toml
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

in my ingress crate and the issue is now gone.

Now it works!

```
>>> import questdb.egress
>>> questdb.egress.sum_as_string(1030, 204)
'1234'
```

Thanks for your help!

Closing the ticket now.
