### ISSUE TITLE
`PyObject_CallOneArg()` usage triggers assert

### ISSUE THREAD

**Issue by ariebovenberg** [PyO3/pyo3#4093]
### Bug Description

I'm getting an error using `PyObject_CallOneArg()` and I think this may be a bug. Feel free to close this issue if it isn't 👀 

### Steps to Reproduce

a minimal-ish example:

```rust
let zoneinfo_module = PyImport_ImportModule("zoneinfo\0".as_ptr().cast::<c_char>());
let zoneinfo_class =
    PyObject_GetAttrString(zoneinfo_module, "ZoneInfo\0".as_ptr().cast::<c_char>());
let zoneinfo_instance = PyObject_CallOneArg(
    zoneinfo_class,
    PyUnicode_FromString("Europe/Amsterdam\0".as_ptr().cast::<c_char>()),
);
```

this triggers the assert below. Indeed the `n` is set to `9223372036854775809` (max i64 + 1). The function _seems_ to usually get smaller values like `0`, or `3` (corresponding to the number of arguments).

```rust
// abstract_.rs
pub unsafe fn PyVectorcall_NARGS(n: size_t) -> Py_ssize_t {
    assert!(n <= (PY_SSIZE_T_MAX as size_t));
    (n as Py_ssize_t) & !PY_VECTORCALL_ARGUMENTS_OFFSET
}

```

The large value can be traced back directly to `PyObject_CallOneArg`

```rust
// in abstract_.rs
pub unsafe fn PyObject_CallOneArg(func: *mut PyObject, arg: *mut PyObject) -> *mut PyObject {
    assert!(!arg.is_null());
    let args_array = [std::ptr::null_mut(), arg];
    let args = args_array.as_ptr().offset(1); // For PY_VECTORCALL_ARGUMENTS_OFFSET
    let tstate = PyThreadState_GET();
    let nargsf = 1 | PY_VECTORCALL_ARGUMENTS_OFFSET;
    _PyObject_VectorcallTstate(tstate, func, args, nargsf as size_t, std::ptr::null_mut())
}
```

where `1 | PY_VECTORCALL_ARGUMENTS_OFFSET` results in this massive number. Patching  `let nargsf = 1;` gets things working—but it should obviously be derived from `PY_VECTORCALL_ARGUMENTS_OFFSET` in some way.

I'm still pretty new to the C API, so it isn't obvious to me what the answer is 😬. Of course I'd be happy to submit a PR if that'd help 🙂 

### Your operating system and version

MacOS 14.4.1

### Your Python version (`python --version`)

Python 3.12.0

### Your Rust version (`rustc --version`)

1.77.2

### Your PyO3 version

master branch

### How did you install python? Did you use a virtualenv?

```
pyenv virtualenv 3.12.0 foo
pyenv local foo
```

I then added my code to the `string_example` example in the `pyo3` repo

**Comment by birkenfeld** [comment]
Thanks for the report! #4104 should fix this.
