### ISSUE TITLE
Another approach to PyObject handling

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/PyO3#41]
seems custom class implementation works well. Should we try to use same approach for python native types?

idea behind class implementation:

1. developer does not have access to class instance, only to reference, reference is tight to `gil` lifetime
2. to store reference to instance to rust struct, instance ref needs to be converted to `Py<CLS>` instance.

same approach could be used for native objects:

1. access to `PyObject` can be restricted to `&'p PyObject`, `'p` is gil livetime
2. to store ref, it would need to be converted to `Py<PyObject>`. alternative: instead of `Py<PyObject>`, `PyObject` itself can be smart pointer, (it can be universal py pointer),
  but specific classes like `PyList` or `PyTuple` can be converted to `Py<PyTuple>` for storage purpose
  or to `PyObject` pointer.

pros: for native object references: 

1. `PyClone` can be replace with normal `Clone`
2. no need to acquire Gil for reference counting
3. no need for `py` parameter for any function call.

**Comment by fafhrd91** [comment]
@messense

**Comment by messense** [comment]
That's interesting. I would prefer `PyObject` pointer, it seems less confusing. The overall design should focus on safe and ergonomic.

I'm ok with passing `py` parameter around, it actually makes it clear that you are dealing with Python objects, but not opposed to remove it to make function signatures simpler.

**Comment by fafhrd91** [comment]
I don't like `py`, it is to invasive. Because of it we have to create a lot of traits. With standard trait learning curve would be simpler.

**Comment by messense** [comment]
That's right.

**Comment by fafhrd91** [comment]
I played with this approach. in genera it is useful. but it become not very good when
native type returns other native types, it has to return some kind of `Py<PyObject>` instance, which makes everything not very good.

**Comment by fafhrd91** [comment]
some explanation. I want to disallow native object instances in free form. i.e. you can not
specify function that accept `PyString` or `PyTuple`
```rust

fn my_func(&self, py: Python, args: PyTuple) -> PyResult<()>;
```

in my previous attempt I tried to add `lifetime`, so it would look like:

```rust
fn my_func<'p>(&'p self, py: Python<'p>, args: PyTuple<'p>) -> PyResult<()>;
```
but it ended up being very non-ergonomic. first of all any type had to include lifetime. second mirror type required, each native type with lifetime would require type without that just holds reference to `ffi::PyObject`.

there was another attempt that introduced `Py<'p, T>` pointer, it was even less ergonomic.

so what I am trying to now. If I disallow instances at all and allow only references then it seems works much better. i.e 

```rust
fn my_func(&self, py: Python, args: &PyTuple, kwargs: &PyDict) -> PyResult<()>;
```

but we still need ability to store py objects in rust structs, so we need to introduce special pointer
`Py<T>` that needs to be `Sync` and `Send` and we should be able to extract object references:

```rust
impl<T> for Py<T> {
    fn as_ref(&self, py: Python) -> &T;
}
```
that is actually easy, but if py class api can return other py instance, then it becomes a problem.
here is `PyList` api:
```rust

impl PyList {

    fn new(py: Python, items: &[PyObject]) -> Py<PyList>;

    fn get_item(&self) -> PyObject;
}
```

`new` method, because free instances are disallowed we have to return `Py<PyList>`, but if you need to manipulate this list, you would immediately would do something like this:

```rust

let ob = PyList::new(py, &[...]);
let list = ob.as_ref(py);
list.set_item(...);
...
return ob;
```

I closed this ticket because of this annoyance. but then I realized, instead of `Py<T>` can we use reference `fn new(py: Python, items: &[PyObject]) -> &PyList`. in rust we need owner, we can not have free references. so I added simple api that can hold `PyObject` instances and then release all of them when `GIL` object get dropped.

https://github.com/PyO3/PyO3/blob/py-ptr/src/pythonrun.rs#L103


Thoughts? Ideas?

**Comment by messense** [comment]
That's a great explanation.

I was under the impression that mutable global variables are bad? And how is the performance impact?

**Comment by fafhrd91** [comment]
I think performance should be the same. performance could be affected if you would use a lot of `&PyObject` refs otherwise performance should actually increase. in current implementation, PyObject's Drop impl acquire Gil, even if it recursive lock, it should have negative impact

**Comment by fafhrd91** [comment]
so `PyObject` now is just smart pointer, all other native types are available only as references. `py` parameter is removed from most apis. I had to add `PyInstance` (I don't like name) which is just ref PyObject.

I don't really like PyInstance name, any ideas? 

@messense

**Comment by messense** [comment]
I don't like `PyInstance` either. 

`PyObjectRef`, `PyValue`(doesn't make much sense)

**Comment by fafhrd91** [comment]
I like `PyObjectRef` more, I'll change PyInstance to PyObjectRef
