### ISSUE TITLE
Add format linting?

### ISSUE THREAD

**Issue by pganssle** [PyO3/pyo3#412]
This project uses `cargo fmt` to format code, but AFAICT, that's not enforced anywhere, so there need to be a bunch of occasional "clean up the formatting" commits, which can make browsing the commit history (particularly via `git blame`) a bit annoying.

It would be nice to add a required linting job to the Travis CI to enforce the formatting requirements. Ideally every commit in the PR would have to pass IMO, but that can be hard to clean up on rebase.

**Comment by konstin** [comment]
Formatting is already checked on travis ci:

https://github.com/PyO3/pyo3/blob/f75f742c588c7338f1b26503179a949b7e270a4d/ci/travis/test.sh#L7-L10

**Comment by pganssle** [comment]
@konstin Hm... Interesting, for me `cargo fmt` is finding a bunch of formatting changes on master:

```
$ cargo fmt --version
rustfmt 1.1.0-nightly (1427e4c 2019-03-17)
$ git log --oneline -n 1
f75f742c (HEAD -> master, upstream/master) Fix CStr usages
$ cargo fmt --all -- --check | wc -l
233
$ cargo fmt --all -- --check | head -n 6
Diff in /home/nlx5/Documents/Programming/Rust/pyo3/tests/common.rs at line 24:
 #[macro_export]
 macro_rules! py_run {
     ($py:expr, $val:expr, $code:expr) => {{
-
         use pyo3::types::IntoPyDict;
```

Is this something on my end or is the nightly check failing to properly check this?

**Comment by konstin** [comment]
> +'[' Minimum nightly = 'Minimum nightly' ']'
> ./ci/travis/test.sh: line 7: [: too many arguments

It has been broken all the time and `set -ex` didn't catch that :|

Thanks for noticing, I've filed #418 in the hope my bash scripting skills are good enough to fix that

**Comment by konstin** [comment]
Travis log says it's run now.

**Comment by konstin** [comment]
Also successfully fails now: https://travis-ci.org/PyO3/pyo3/jobs/512501385
