### ISSUE TITLE
Problems using manylinux with pyo3

### ISSUE THREAD

**Issue by brupelo** [PyO3/pyo3#413]
I'm trying to figure out how to deploy my pyo3 project to be used on "linux".

As a simple test I've spinned out an updated centos7 box + docker + pyenv + python3.6.4 and I've tried to build this
[https://github.com/gukoff/PyO3-manylinux-bug](https://github.com/gukoff/PyO3-manylinux-bug), when I've run:

    docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /io/build_wheels.sh

I've got these errors:

    [vagrant@localhost PyO3-manylinux-bug]$ sudo docker run --rm -v `pwd`:/io quay.io/pypa/manylinux1_x 86_64 /io/build_wheels.sh
    + mkdir /root/rust-installer
    + curl -sL https://static.rust-lang.org/rustup.sh -o /root/rust-installer/rustup.sh
    + sh /root/rust-installer/rustup.sh '--prefix=~/rust' --spec=nightly -y --disable-sudo
    info: downloading installer
    error: Found argument '--prefix' which wasn't expected, or isn't valid in this context

    USAGE:
        rustup-init [FLAGS] [OPTIONS]

Anyway, reason why I was trying to build that project was with the intention to eventually inject my project there... but i guess my question is, what are the steps to deploy my pyo3 project to be run on as many linux as possible?

Ps1: I've built succesfully my project on centos7 manually
Ps2: I've already asked about it on [stackoverflow](https://stackoverflow.com/questions/55277292/how-to-create-python-binary-extensions-created-with-pyo3-for-linux)
Ps3: I've wasted the whole day trying to figure out and the docs provided here didn't help me too much, that's why I've decided to open this issue
Ps4: Thanks in advance :)

**Comment by kngwyu** [comment]
See https://github.com/PyO3/setuptools-rust or open an issue there.

**Comment by brupelo** [comment]
You give very optimals answers, don't you? Ty! ;)
