### ISSUE TITLE
New example that uses pyo3

### ISSUE THREAD

**Issue by brupelo** [PyO3/pyo3#415]
Today I've uploaded a new project that uses pyo3... I call it [pysyntect](https://github.com/brupelo/pysyntect), I'm mentioning this in case you feel it would be a good idea adding a link to the [examples-and-tooling](https://github.com/PyO3/pyo3#examples-and-tooling) section or even better... a link to [pyblime](https://github.com/brupelo/pyblime) would also be really helpful to send me some traffic from this highly popular project ;)

Thanks!

**Comment by konstin** [comment]
I'd recommend posting on reddit in the relevant subreddit for promoting your project. The Examples and Tooling Section is mostly for crates where the python-rust bridging is the main aspect.

**Comment by brupelo** [comment]
After reading your comment my first reaction was adding a thumbdown icon to your reply as well as considering getting rid of the credit link from this [section](https://github.com/brupelo/pyblime#referencescredits) but then I think twice and I considered that would just be childish, if you don't want to add any link probably you've got your own reasons for not doing so and that's fine.

Thanks for letting me know.
