### ISSUE TITLE
intern macro name is not very descriptive

### ISSUE THREAD

**Issue by Stargateur** [PyO3/pyo3#4171]
[`intern`](https://docs.rs/pyo3/0.21.2/pyo3/macro.intern.html) macro name look weird. Is this an acronyme ? https://www.wordreference.com/enfr/intern

> Interns text as a Python string and stores a reference to it in static storage.
> A reference to the same Python string is returned on each invocation.

**Comment by adamreichold** [comment]
No, this is a proper verb, c.f. https://en.wiktionary.org/wiki/intern#Verb

The technique is called "string interning", c.f. https://en.wikipedia.org/wiki/String_interning

It is the same nomenclature that is used by CPython itself and by various Rust crates, c.f. https://lib.rs/search?q=intern
