### ISSUE TITLE
Missing `__init_subclass__` and `__set_name__` magic methods in the user guide

### ISSUE THREAD

**Issue by Divy1211** [PyO3/pyo3#4180]
### Bug Description

- The `__set_name__` magic method is missing from https://pyo3.rs/v0.21.2/class/protocols#descriptors
- The `__init_subclass__` magic method is also missing from https://pyo3.rs/v0.21.2/class/protocols (Not quite sure which section `__init_subclass__` should go into)

(Details for both methods: https://peps.python.org/pep-0487/#proposal)

Both magic methods seem to work in PyO3, so it looks like it's just the documentation for them that is missing from the user guide. Here's the code that I got to work for reference:

`__set_name__`:
```rs
#[pymethods]
impl MapValidate {
    fn __set_name__(&mut self, _owner: &Bound<'_, PyType>, name: &str) {
        self.name = name.to_string()
    }
}
```

`__init_subclass__`:
```rs
#[pymethods]
impl BaseStruct {
    #[classmethod]
    fn __init_subclass__(cls: &Bound<'_, PyType>) -> PyResult<()> {
        // code here
    }
}
```

### Your operating system and version

Windows 10 Home 22H2 Build 19045.4291

### Your Python version (`python --version`)

`3.10.11`

### Your Rust version (`rustc --version`)

`1.71.1`

### Your PyO3 version

`0.21.2`

### How did you install python? Did you use a virtualenv?

- python.org
- created a venv using `python -m venv venv`

**Comment by davidhewitt** [comment]
This is deliberate, though the docs don't necessarily make it super clear. If it's not in the list in the docs then PyO3 doesn't need to do anything special with it and Python will handle it fine anyway.
