### ISSUE TITLE
Converting a list to a set

### ISSUE THREAD

**Issue by dscorbett** [PyO3/pyo3#427]
I am trying to convert a Python list to a Python set in Rust. I’ve found two ways to do it, but they feel like workarounds. Is there is a better way?

Calling `eval`:
```rust
    let list: &PyAny = list;
    let set: &PyAny = py.eval("set", None, None)?.call((list,), None)?;
```

Calling unsafe functions:
```rust
    let list: &PyAny = list;
    let set_object: PyObject = unsafe {
        PyObject::from_owned_ptr_or_panic(py, PySet_New(list.as_ptr()))
    };
    let set: &PyAny = &set_object.as_ref(py);
```

**Comment by birkenfeld** [comment]
You should be able to get the set type using `PySet::type_object()`, then call it with the list as argument via the  object protocol.

**Comment by davidhewitt** [comment]
As this has been answered, closing for now.
