### ISSUE TITLE
PyO3 missing output upon redirection (edited)

### ISSUE THREAD

**Issue by aleozlx** [PyO3/pyo3#428]
## 🐛 Bug Reports

Missing all output from python side if run in Kubernetes. Hopefully someone can give me some pointers on how stdout/stderr are handled in the pyo3 intepretor, or other doors that I can knock on, although in theory it's using Python C API under the hood is as much as I know. I know use of Kubernetes must be part of the issue, but I wanted to hear from both sides and I believe this is an edge case only occurs when both k8s and py03 are involved.
We tried to use unbuffered io and flush stdio/stderr as well.

Cases we tested:
local machine (5.0.4-arch1-1-ARCH+3.7.2+rustc 1.34.0-nightly (097c04cf4 2019-02-24)) + pyO3 => ok
docker image (ubuntu:18.04 on above system) + pyO3 => ok
k8s (see versions below) + pyO3 => fail
k8s + rust => can print
k8s + python => can print

Here are some results
```
~/Code/sturdy-engine(master*) » cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/sturdy-engine`
==============
Acquire GIL
Modifying sys.path
Importing
call_method1()
0
1
2
3
4
flush_stdio()
Flushing I/O
==============
```

```
~/Code/sturdy-engine(master*) » docker run -it --rm aleozlx/sturdy-engine target/debug/sturdy-engine
==============
Acquire GIL
Modifying sys.path
Importing
call_method1()
0
1
2
3
4
flush_stdio()
Flushing I/O
==============
```

```
~/Code/sturdy-engine(master*) » kubectl create -f main.yml
job.batch/debug-stdout-qp8sd created
~/Code/sturdy-engine(master*) » kubectl logs job.batch/debug-stdout-qp8sd -n bluecheese -f
==============
Acquire GIL
Modifying sys.path
Importing
call_method1()
flush_stdio()
==============
```

All output since call_method1 is missing. In conclusion, we can't get pyo3 to output anything in Kubernetes.

### 🌍 Environment

 - Your operating system and version: ubuntu:18.04 container in Kubernetes 1.12.4 version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"} on CentOS7 3.10.0-957.5.1.el7.x86_64 
 - Your python version: 3.6.7
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: apt & no
 - Your rust version (`rustc --version`): rustc 1.35.0-nightly (53f2165c5 2019-04-04)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Tried 0.5 & 0.6

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the rust code and the python.

This repo is a minimum example:
https://github.com/aleozlx/sturdy-engine/tree/4dacbf6ed9f2b6c56bf0ac58436b2546a979b367

Please also write what exact flags are required to reproduce your results.

**Comment by aleozlx** [comment]
I tried to have PYTHONUNBUFFERED turned on as well, which is usually the fix for Python. Should this env variable be effective to PyO3 as well??
https://github.com/aleozlx/sturdy-engine/blob/4dacbf6ed9f2b6c56bf0ac58436b2546a979b367/main.yml#L19

**Comment by kngwyu** [comment]
You mean you call a python script which includes `print` using PyO3, and then have no output?

**Comment by aleozlx** [comment]
Exactly, except I emphasize this only happens when I wrap the whole thing in a container image and run from Kubernetes. That's why I created that repo for an example. Just to clarify if it wasn't obvious from the minimum example... call is here https://github.com/aleozlx/sturdy-engine/blob/4dacbf6ed9f2b6c56bf0ac58436b2546a979b367/src/main.rs#L43
and print is here https://github.com/aleozlx/sturdy-engine/blob/4dacbf6ed9f2b6c56bf0ac58436b2546a979b367/src/payload.py#L4

I couldn't find anything out of the ordinary that can cause this so far. Any suggestion/points would be appreciated.

**Comment by aleozlx** [comment]
Can anyone please check the strace below and give me some hints to why there weren't write() system calls issued for python codes in the presence of io redirection?

https://github.com/kubernetes/kubernetes/issues/76231#issuecomment-481977489

**Comment by aleozlx** [comment]
See https://github.com/kubernetes/kubernetes/issues/76231
