### ISSUE TITLE
support scipy csc matrix

### ISSUE THREAD

**Issue by Liripo** [PyO3/pyo3#4296]
Is it possible to provide a convenient method to support the conversion of scipy's csc matrix into sprs CsMat?

**Comment by davidhewitt** [comment]
Sorry for the slow reply. I think this is more likely appropriate for `rust-numpy`, or a separate thirdparty crate. PyO3 itself focuses on the Python standard library and very common Rust crates only.

It should be possible to use the new type pattern for user code to define to / from Python conversions.
