### ISSUE TITLE
What is different between pyo3 and Rustpython?

### ISSUE THREAD

**Issue by j209** [PyO3/pyo3#435]
Hi
What is different between pyo3 and [Rustpython](https://github.com/RustPython/RustPython)?
And can we pyo3 in WebAssembly?

**Comment by althonos** [comment]
`Rustpython` is a Python interpreter written in Rust. `pyo3` are bindings to the `CPython` interpreter.

* `Rustpython` and `pyo3` can be both used to run Python programs within a Rust program or library.
* `pyo3` can be used to compile Rust programs into Python extensions that can be used with CPython directly. 

I have no idea about `pyo3` in WebAssembly but I'd say probably not.

**Comment by omerbenamram** [comment]
You could run `RustPython` compiled down to webassembly - which would allow **python code**  to run in the browser (https://rustpython.github.io/demo/).

Or, you could just compile rust code directly to webassembly and run that as well (https://github.com/rustwasm/wasm-pack).

**Comment by thedrow** [comment]
Can we close this issue?

**Comment by kngwyu** [comment]
Yeah, @althonos @omerbenamram thank you for the explanation
