### ISSUE TITLE
Should PySet::new return a PyResult?

### ISSUE THREAD

**Issue by birkenfeld** [PyO3/pyo3#437]
Currently `PySet::new` can panic easily, since not all objects are hashable. I think it would make sense to return a PyResult here.

(For example, `PyDict::from_sequence` or even `PyDict::contains`, where the same restriction applies, return results already.)

On a related note, I'm not sure why `PySet::new` returns a `Py<PySet>` while `PyDict::new` returns a `&PyDict`...

**Comment by konstin** [comment]
This should be a good first issue:
 * Replace `from_owned_ptr_or_panic` with `from_owned_ptr_or_error`
 * Add a test case in the `mod test` at the end of the file that tries to build a set from an unhashable object and ensures there's an error. https://github.com/PyO3/pyo3/blob/86d239e4451a7cb2fc1998e83271517d69fce576/src/types/set.rs#L162 

> On a related note, I'm not sure why PySet::new returns a Py<PySet> while PyDict::new returns a &PyDict...

It should return a `&PyDict`; pyo3 unfortunately contains a few of those inconsistencies.

**Comment by birkenfeld** [comment]
I'll take it. While at it, also change it to return `&PySet`?

**Comment by konstin** [comment]
Yes, that would be good
