### ISSUE TITLE
`signature` does not works for `String` type

### ISSUE THREAD

**Issue by Yosh31207** [PyO3/pyo3#4373]
### Bug Description

Default string value specified by `signature` (example: `#[pyo3(signature=(num, text = ""))]`) works for `&str` but does not work for `String` type. 

```rust
// works fine
#[pyfunction]
#[pyo3(signature=(num, text = ""))]
fn some_func(num: i32, text: &str, opt: Option<i32>) -> PyResult<()> {
    todo!()
}

// fails
#[pyfunction]
#[pyo3(signature=(num, text = ""))]
fn some_func2(num: i32, text: String, opt: Option<i32>) -> PyResult<()> {
    todo!()
}
```

Screenshot of VS Code:
![image](https://github.com/user-attachments/assets/64fc4a38-ad95-486d-8bc2-28aeda839d96)

Is this an intended behavior?

This may be a problem with async since `async fn`  requires `Send + 'static` for parameters.

### Steps to Reproduce

As shown in the description above.

### Your operating system and version

Windows 11 23 H2

### Your Python version (`python --version`)

Python 3.12.4

### Your Rust version (`rustc --version`)

rustc 1.79.0 (129f3b996 2024-06-10)

### Your PyO3 version

0.22.1

### How did you install python? Did you use a virtualenv?

I installed Python via winget. I use `venv`.

**Comment by Icxolu** [comment]
This is the intended behavior. The signature attribute just takes Rust expressions which should evaluate to the given type. For your String example you could use
```rust
#[pyfunction]
#[pyo3(signature=(num, text = String::new(), opt = None))]
fn some_func2(num: i32, text: String, opt: Option<i32>) -> PyResult<()> {
    todo!()
}
```
or 
```rust
#[pyfunction]
#[pyo3(signature=(num, text = String::from("Some other default string."), opt = None))]
fn some_func2(num: i32, text: String, opt: Option<i32>) -> PyResult<()> {
    todo!()
}
```

**Comment by Yosh31207** [comment]
@Icxolu
Thank you! I close this because my question was resolved.
