### ISSUE TITLE
Can't return a tuple from async function

### ISSUE THREAD

**Issue by dolezvo1** [PyO3/pyo3#4400]
### Bug Description

I'm new to PyO3 so this may completely be on me, but what I'm experiencing is that I can't seem to be able to return a tuple from an async function correctly. My Rust function looks something like this, although I also tried returning `PyResult<PyTuple>`, and the result seemed to be the same:

```rust
#[pymethods]
impl T1 {
  pub async fn stuff(&self) -> PyResult<(T2, T3)> {
    other_stuff().await
  }
}
```

My Python code looks something like this:

```python
tuple = await t1.stuff()
print(tuple)
```

The issue is that when I do this, the `tuple` seems to be only the first element of the tuple, the second one gets lost. When I tried doing the following, I actually got an error which didn't make a lot of sense (something like `tokio 1.x must be running`):

```python
t2, t3 = await t1.stuff()
print(t2, t3)
```

In the end I settled for returning a dict of the stuff I wanted to return, which works, but isn't as nice.

Admittedly I'm not completely sure if it really is a bug with PyO3 or rather with Python interpreter, but I was hoping you would know more about this.

### Your operating system and version

Linux 6.6.40 x86_64

### Your Python version (`python --version`)

Python 3.12.4

### Your Rust version (`rustc --version`)

rustc 1.79.0

### Your PyO3 version

0.22

### How did you install python? Did you use a virtualenv?

I think it was already installed

**Comment by dolezvo1** [comment]
It actually seems to be the same case with `#[pyfunction]`s. When I define the functions like this:

```rust
#[pyfunction]
fn function1() -> PyResult<(u8, u8)> {
    Ok((3,4))
}

#[pyfunction]
async fn function2() -> PyResult<(u8, u8)> {
    Ok((5,6))
}
```

and use this simple Python invocation:

```python
print(my_mod.function1())
print(await my_mod.function2())
```

I get this result, which definitely seems unexpected to say the least:

```
(3, 4)
5
```

**Comment by dolezvo1** [comment]
Just looking at the `cargo expand` resul, can't say anything immediately suspicious would be popping up for me. I'll try to find out whether I can insert debug printouts in there somehow.

```rust
#[allow(non_snake_case)]
unsafe fn __pyfunction_function1<'py>(
    py: ::pyo3::Python<'py>,
    _slf: *mut ::pyo3::ffi::PyObject,
) -> ::pyo3::PyResult<*mut ::pyo3::ffi::PyObject> {
    let _slf_ref = &_slf;
    let function = function1;
    #[allow(clippy::let_unit_value)]
    let result = {
        let ret = function();
        ::pyo3::impl_::wrap::map_result_into_ptr(
            py,
            ::pyo3::impl_::wrap::OkWrap::wrap(ret)
                .map_err(::core::convert::Into::<::pyo3::PyErr>::into),
        )
    };
    result
}

#[allow(non_snake_case)]
unsafe fn __pyfunction_function2<'py>(
    py: ::pyo3::Python<'py>,
    _slf: *mut ::pyo3::ffi::PyObject,
) -> ::pyo3::PyResult<*mut ::pyo3::ffi::PyObject> {
    let _slf_ref = &_slf;
    let function = function2;
    #[allow(clippy::let_unit_value)]
    let result = {
        let ret = {
            let future = function();
            ::pyo3::impl_::coroutine::new_coroutine(
                {
                    static INTERNED: ::pyo3::sync::Interned = ::pyo3::sync::Interned::new(
                        "function2",
                    );
                    INTERNED.get(py)
                },
                None,
                None,
                async move { ::pyo3::impl_::wrap::OkWrap::wrap(future.await) },
            )
        };
        ::pyo3::impl_::wrap::map_result_into_ptr(
            py,
            ::pyo3::impl_::wrap::OkWrap::wrap(ret)
                .map_err(::core::convert::Into::<::pyo3::PyErr>::into),
        )
    };
    result
}
```

**Comment by dolezvo1** [comment]
I was able to reproduce it when using a fresh clone of PyO3 master branch, but other than that I have no insights as to why it might be happening.

**Comment by birkenfeld** [comment]
Found the problem, and there is an easy solution, however it's not clear to me if a fix at a more fundamental level is needed instead.

In short, this patch is the fix, which you can try out already if you want:
```diff
diff --git a/src/coroutine.rs b/src/coroutine.rs
index f2feab4af..652292c78 100644
--- a/src/coroutine.rs
+++ b/src/coroutine.rs
@@ -95,7 +95,7 @@ impl Coroutine {
         match panic::catch_unwind(panic::AssertUnwindSafe(poll)) {
             Ok(Poll::Ready(res)) => {
                 self.close();
-                return Err(PyStopIteration::new_err(res?));
+                return Err(PyStopIteration::new_err((res?,)));
             }
             Err(err) => {
                 self.close();
```

(I'll prepare a pull request with test and raise the more general question there as well.)

**Comment by Icxolu** [comment]
But running `next(function2())` (so manually polling the future) does return the correct tuple inside the `StopIteration`
```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
File f:\Rust\pyo3-scratch\test.py:2
      [1](file:///F:/Rust/pyo3-scratch/test.py:1) #%%
----> [2](file:///F:/Rust/pyo3-scratch/test.py:2) next(function2())

StopIteration: (5, 6)
```
Is it expected to have this wrapped in a tuple again?

**Comment by birkenfeld** [comment]
While the printout of the StopIteration looks the same in both cases, they're not equivalent. This will show you the real thing:
```python
try:
    next(function2())
except StopIteration as err:
    print(err.args)
```

**Comment by birkenfeld** [comment]
I think this is because the stringification of the exception applies a reverse logic to PyErr_CreateException, omitting the tuple parentheses if there is only a single item in `args`.

**Comment by birkenfeld** [comment]
Or, even simpler to see:
```python
print(StopIteration(1,2), StopIteration((1, 2)))
```

**Comment by Icxolu** [comment]
I'm still not sure if I get it
```python
try:
    next(function2())
except StopIteration as err:
    print(err.args)
```
outputs `(5, 6)`

while
```python
await function2()
```
outputs `5`

Shouldn't `args` be the thing returned by await?

---

And `print(StopIteration(1,2), StopIteration((1, 2)))` ouputs `(1, 2) (1, 2)`

Should I see a difference here?

(Python 3.12)

**Comment by birkenfeld** [comment]
No, `exc.args[0]` is the thing that is considered the "result" from the coroutine. Or, rather `exc.value` which is the same thing, see https://github.com/python/cpython/blob/fda6bd842a2b93a501526f1b830eb900d935ac73/Objects/exceptions.c#L618

And no, you shouldn't see a difference; this was to demonstrate that while the traceback from `next()` looks the same before and after the patch, the actual exceptions are different. In the first case, `args` is `(1,2)` and in the second `((1,2),)`. The second is what's needed for the case here.

**Comment by Icxolu** [comment]
Ah, in that case it makes sense 👍 Thank's for the clarification, I guess I went in with the wrong assumption 🙃

**Comment by dolezvo1** [comment]
I've been able to confirm it works for me now, thank you so much! Would you happen to be able to make a rough estimate when this fix could be released in a stable version?

**Comment by davidhewitt** [comment]
Unless there's several fixes backing up, I will probably leave this to 0.23 to release, which is probably 1-2 months away. This is still an experimental feature after all, though I would like to get it more stable soon!

**Comment by dolezvo1** [comment]
Of course, I fully expected something like that. Thank you!
