### ISSUE TITLE
Implement and Document retrieving the type of an object 

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#445]
There should be documented way to get the static type (i.e. the `T`) and the actual runtime type for `Py<T>`, `PyRef<T>`, `PyRefMut<T>`. Afaik not all of this is implemented yet, but this needs a closer look.

This is a follow-up to my first failed attempt in #424

**Comment by davidhewitt** [comment]
@konstin I'm just janitoring the backlog and realised I'm not sure exactly what API you're suggesting we design / implement here. Any chance you recall what this issue is asking for?

**Comment by davidhewitt** [comment]
Closing for now, if this was going to be a useful idea, someone please come along and ask for it!
