### ISSUE TITLE
`PyObjectInit` should be private (and sealed)

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#4552]
`PyObjectInit` trait is an implementation detail. We should remove it from the public API. If it's needed in macros, we'll move it inside `src/impl_/`.

https://github.com/PyO3/pyo3/pull/4518#issuecomment-2348518282

**Comment by cesarmg1980** [comment]
Hey @davidhewitt can I give it a look ?

**Comment by davidhewitt** [comment]
Please go for it; as far as I know nobody is working on this.

**Comment by Cheukting** [comment]
If this is not done yet, I am happy to follow up

**Comment by cesarmg1980** [comment]
I was about to start working on this.

On 10 Oct 2024, at 10:13 AM, Cheuk Ting Ho ***@***.***> wrote:



If this is not done yet, I am happy to follow up
