### ISSUE TITLE
`text_signature` not available for `#pyclass`

### ISSUE THREAD

**Issue by piotryordanov** [PyO3/pyo3#4586]
### Bug Description

I expect to be able to add the `text_signature` to the `pyclass`, but it's failing.
Running pyo3 version 0.22.3.

### Steps to Reproduce

```
#[pyclass(text_signature = "(index=1)")]
#[derive(Debug, Clone)]
pub struct Signal {
    pub index: i32,
}
```

### Backtrace

```shell
error: expected one of: `crate`, `dict`, `eq`, `eq_int`, `extends`, `freelist`, `frozen`, `get_all`, `hash`, `mapping`, `module`, `name`, `ord`, `rename_all`, `sequence`, `set_all`, `subclass`, `unsendable`, `weakref`
```
```


### Your operating system and version

arch

### Your Python version (`python --version`)

3.10.12

### Your Rust version (`rustc --version`)

1.71.1

### Your PyO3 version

0.22.3

### How did you install python? Did you use a virtualenv?

python env is managed by rye

### Additional Info

_No response_

**Comment by davidhewitt** [comment]
`#[pyo3(text_signature = "(index=1)"]` should go on your `#[new]` function since PyO3 0.19.

**Comment by piotryordanov** [comment]
Ah that solves it. Thx for the fast reply.

What confused me was that it's still mentioned as a valid option in [here](https://pyo3.rs/main/class#constructor) and [here]( https://docs.rs/pyo3/latest/pyo3/attr.pyclass.html)

**Comment by piotryordanov** [comment]
@davidhewitt I tried the change you suggested, but for some reason, it's not propagatd to python.

```rs
#[pymethods]
impl Signal {
    /// This is a signal that does xyz
    #[new]
    #[pyo3(text_signature = "(index)")]
    fn new(index: i32) -> Self {
        Signal { index }
    }
```

And in python, the signature for `__new__` shows as:
```py
($type, *args, **kwargs)
```

**Comment by davidhewitt** [comment]
The text signature ends up just below the class header, rather than on the `__new__` help, e.g.:

```
Help on class Foo in module pyo3_scratch:

class Foo(builtins.object)
 |  Foo(index, /)                         <----- here
```

To put it on `__new__`, would require the same kind of solution as in #4326
