### ISSUE TITLE
Bump minimal versions of range dependencies

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#4614]
As a follow up to #4604, it's probably time to go through our range dependencies in the `Cargo.toml` and bump these a bit. e.g. `hashbrown` 0.9 is about 4 years old, and barely downloaded. It looks like hashbrown 0.11 is where the download counts pick up, so I think we can bump to there for sure. MSRV works with 0.14, so we could even go higher.

Labelling as good first issue, I think this would be a nice cleanup to land in 0.23 if someone is interested.

Range dependencies in `Cargo.toml`:
- [ ] `hashbrown` (to 0.11 or maybe even 0.14)
- [ ] `chrono-tz` (needs analysis)
- [ ] `eyre` (needs analysis)
- [ ] `indexmap` (needs analysis)
- [ ] `num-complex` (needs analysis)

**Comment by SeanAverS** [comment]
Hi, 

I'm interested on working on this. Could I please be assigned? Thanks.

**Comment by davidhewitt** [comment]
Done in #4617
