### ISSUE TITLE
CI Builds are failing due to editable install

### ISSUE THREAD

**Issue by pganssle** [PyO3/pyo3#462]
Currently the CI builds are all red because `rustapi_module` has a `pyproject.toml`, and something is invoking `pip install -e` (see [error here](https://travis-ci.org/PyO3/pyo3/jobs/523877773#L880)).

This is related to pypa/pip#6434. I think pinning `pip` to an older version (I think `pip<19.0`) should temporarily fix the issue while we work out what to do. I'm not entirely sure why anything is doing an editable install, though.

**Comment by gaborbernat** [comment]
https://github.com/PyO3/pyo3/blob/master/tox.ini#L11 sets develop mode one, which in practice means editable install 👍
