### ISSUE TITLE
How to import a @classmethod of a Python class into Rust. 

### ISSUE THREAD

**Issue by siddharthAktivoLabs** [PyO3/pyo3#465]
# python
 module -> demohello.py

class Demo
    @classmethod
     def say_hello()
       return "Hello World"

# In Rust
 
  let demohello_mod = py.import('demohello');
  let output = demohello_mod.call(py, 'Demo.say_hello', NoArgs, None);

# ISSUE: 
I am not able to access classmethod defined in python
But defining the same func outside of class works.

**Comment by althonos** [comment]
Shouldn't your class method take at least a `cls` argument ? Otherwise you may want a `staticmethod` instead.
