### ISSUE TITLE
no way to disable implicit equality warning for enum

### ISSUE THREAD

**Issue by trim21** [PyO3/pyo3#4687]
### Bug Description

I have a pyclass+enum to generate a enum class, and I want it to behavoie like `enum.Enum`, so I write a `__eq__` method to support both `Booking.STRICT == Booking.STRICT` and `Booking.STRICT == "STRICT"`, so I use `#[pyclass]` only

And it cause a warning ``warning: use of deprecated constant `base::Booking::__pyo3__generated____richcmp__::DEPRECATION`: Implicit equality for simple enums is deprecated. Use `#[pyclass(eq, eq_int)` to keep the current behavior.`` and there is no way to disable it.

```rs
#[pyclass]
#[derive(PartialEq)]
pub enum Booking {
    STRICT,
    #[allow(non_camel_case_types)]
    STRICT_WITH_SIZE,
    None,
    AVERAGE,
    FIFO,
    LIFO,
    HIFO,
}

#[pymethods]
impl Booking {
    // make it behave like enum.Enum
    #[getter]
    fn name(&self) -> &str {
        return self.__str__();
    }

    #[getter]
    fn value(&self) -> &str {
        return self.__str__();
    }

    // to support both `Booking.STRICT == Booking.STRICT` and `Booking.STRICT == "STRICT"`
    fn __eq__(&self, other: &Bound<'_, PyAny>) -> bool {
        if let Ok(s) = other.extract::<&str>() {
            return s == self.__str__();
        }

        if let Ok(b) = other.downcast::<Self>() {
            let other = &*b.borrow();
            return self == other;
        }

        return false;
    }

    fn __str__(&self) -> &str {
        match self {
            Booking::STRICT => "STRICT",
            Booking::STRICT_WITH_SIZE => "STRICT_WITH_SIZE",
            Booking::None => "None",
            Booking::AVERAGE => "AVERAGE",
            Booking::FIFO => "FIFO",
            Booking::LIFO => "LIFO",
            Booking::HIFO => "HIFO",
        }
    }
}
```

### Steps to Reproduce

copy paste code and build with pyo3 0.22.6

```text
task: [build] cargo build
   Compiling beancount v0.0.0 (C:\Users\Trim21\proj\beancount)
warning: use of deprecated constant `base::Booking::__pyo3__generated____richcmp__::DEPRECATION`: Implicit equality for simple enums is deprecated. Use `#[pyclass(eq, eq_int)` to keep the current behavior.
  --> src\base.rs:84:1
   |
84 | #[pyclass]
   | ^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in the attribute macro `pyclass` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `beancount` (lib) generated 1 warning                                                                                                                            
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.33s

```

### Your operating system and version

win10

### Your Python version (`python --version`)

Python 3.12.7

### Your Rust version (`rustc --version`)

rustc 1.82.0 (f6e511eec 2024-10-15)

### Your PyO3 version

0.22.6

### How did you install python? Did you use a virtualenv?

scoop, yes

**Comment by davidhewitt** [comment]
Ouch. I prefer to give users two versions for deprecation (i.e. remove in 0.24), unless there's a really good reason to rip out sooner. 

What happens if you put `#[pyo3(eq, eq_int)]` on the class to silence the warning, and keep your explicit `__eq__` method too? I have a feeling there's a chance we might end up just respecting your `__eq__` as higher priority than our generated code. Or does it lead to a compile failure?

You might also be able to workaround by adding `#![allow(deprecated)]` at the top of the file; that's a bit sad though :(

**Comment by Icxolu** [comment]
> What happens if you put `#[pyo3(eq, eq_int)]` on the class to silence the warning, and keep your explicit `__eq__` method too? I have a feeling there's a chance we might end up just respecting your `__eq__` as higher priority than our generated code. Or does it lead to a compile failure?

This fails to compile, which I believe is on purpose (and a good thing) to make users aware that they have specified (possibly) contradicting implementations.

> You might also be able to workaround by adding `#![allow(deprecated)]` at the top of the file; that's a bit sad though :(

This should work. But I agree is pretty sad.

**Comment by trim21** [comment]
`#![allow(deprecated)]` works, but I'm hopoing I still get warning for other deprecated API...

**Comment by davidhewitt** [comment]
I managed to find a way to silence the warning automatically if `__eq__` is provided! #4692
