### ISSUE TITLE
Error on importing module created with PyModule::new()

### ISSUE THREAD

**Issue by JasperBRiedel** [PyO3/pyo3#471]
## 🐛 Bug Reports

Hi,

I believe I've found an issue with importing modules created with `PyModule::new()`.

Could I please have some clarification of what the behavior of `PyModule::new()` and `Python.import()` should actually be in the case below.

See below for environment details and code to reproduce the `ModuleNotFoundError`.

Thanks,
Jasper

### 🌍 Environment

 - Operating system and version: `Arch Linux x86_64 5.0.9-arch1-1-ARCH`
 - Python version: `Python 3.7.3`
 - How did you install python: `pacman -S python3`
 - Your rust version (`rustc --version`): `rustc 1.36.0-nightly (00859e3e6 2019-04-29)`
 - pyo3 version: `0.7.0-alpha.1`

### 💥 Reproducing

cargo.toml
```toml
[package]
name = "test-modules-pyo3"
version = "0.1.0"
authors = ["JasperBRiedel"]
edition = "2018"

[dependencies]
pyo3 = "0.7.0-alpha.1"
```
main.rs
```rust
use pyo3::prelude::*;

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();

    PyModule::new(py, "hello").unwrap();

    match py.import("hello") {
        Ok(_) => println!("Works as I expected!"),
        Err(e) => {
            println!("Failed to find the module I created?");
            e.print(py);
        }
    }
}
```

Execution and output
```sh
aquila-rift::jasper::test-modules-pyo3::$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/test-modules-pyo3`
Failed to find the module I created?
ModuleNotFoundError: No module named 'hello'
```

**Comment by birkenfeld** [comment]
This is expected, creating a new module will only give you a module object with the correct name. The python import mechanism, which looks at files on disk (mostly) doesn't know about it. This is the same with modules created on Python with `types.ModuleType()`.

Instead, to use such modules as if they were imported, you add them to `sys.modules` yourself using (the equivalent of) `sys.modules["name"] = module`.

**Comment by JasperBRiedel** [comment]
I've created a function to provide the behavior I needed, to be used in conjunction with PyModule::new().

I've added it below as a reference for anyone else trying to achieve the same as me.

```rust
    fn add_module(py: Python, module: &PyModule) {
        py.import("sys")
            .expect("failed to import python sys module")
            .dict()
            .get_item("modules")
            .expect("failed to get python modules dictionary")
            .downcast_mut::<PyDict>()
            .expect("failed to turn sys.modules into a PyDict")
            .set_item(module.name().expect("module missing name"), module)
            .expect("failed to inject module");
    }
```
