### ISSUE TITLE
Generated classes are part of the builtin module

### ISSUE THREAD

**Issue by rth** [PyO3/pyo3#474]
Related to the pickle support #100 , as mentioned by @althonos ,
> PyO3 exposes all classes as part of the builtins module, because the import mechanism has not been properly implemented, so pickle tries to use builtins.MyClass and fails with the error you reported.

This is also discussed in the following test, 

https://github.com/PyO3/pyo3/blob/9f2afbc3cc6cceca8d9bc2fdfd3236032e4b9577/tests/test_class_basics.rs#L70-L73

Once `__module__` it is set to `builtin`, it cannot be changed in an obvious way (at least I have not found one). Using [the example class](https://github.com/PyO3/pyo3/blob/master/guide/src/class.md#constructor),
```py
       cls = MyClass()
       cls.__module__ = "correct_name"
E   TypeError: can't set attributes of built-in/extension type 'MyClass'
```

it would be nice if there way some way to manually set the module name.

Also setuptools-rust does have the module name provided by the user for each `RustExtension` , but doesn't seem to be assigning it?

**Comment by Alexander-N** [comment]
This was changed in https://github.com/PyO3/pyo3/commit/c71c116f29d2c6a7ec9293ff10da886e034a8614#diff-d3dec314b1956210565bd5849a91e770. I don't see a problem in setting the module to the first one which initializes the class. This seems analogous to when I import a class in Python, then its `__module__` attribute does not change to the module it was imported in.

@konstin How about we revert to the old behavior?

@rth It might be possible to subclass in Python and set `__module__` there.

**Comment by rth** [comment]
> It might be possible to subclass in Python and set __module__ there

Thanks @Alexander-N ! You are right that works, but I'm hoping for some alternative solution that wouldn't require subclassing every single pyo3 generated class.

**Comment by konstin** [comment]
I'm fine with reverting to the old behaviour if that unbreaks pickle, however we should document in the guide that module name depends on where the class was first used.

Ideally we should also add an option to set the module manually, but that's independent of the default.
