### ISSUE TITLE
Unable to Release GIL in Python with `ta-lib` (via Rust Bindings)

### ISSUE THREAD

**Issue by gitctrlx** [PyO3/pyo3#4804]
Hello pyo3 team, 

I hope this message finds you well! I have encountered an issue with releasing the GIL when using `pyo3` to bind `ta-lib` C functions through Rust bindings, and I was hoping to get some insights or guidance from your team.

## Description

I am using `ta-lib` for technical analysis, and I have successfully bound the `TA-Lib` C library to Rust using `rust-bindgen`, which is a wrapper around the C library. I then used `pyo3` to bind the Rust code to Python, with the goal of releasing the Global Interpreter Lock (GIL) when performing calculations in Python. This would allow concurrent threads to execute in parallel during `ta-lib` computations, which should improve performance.

However, despite using `pyo3`'s `allow_threads` functionality, I have observed that the GIL is not being released during the execution of `ta-lib` functions. This results in thread blocking and no performance improvement when using multiple threads. I was expecting that with proper GIL release, the `ta-lib` computations would run concurrently, leading to a significant speedup.

Here are the key points of my setup:

1. **Binding `ta-lib` (C library)**: I am using the C library version of `TA-Lib`, as found in the [official `ta-lib` GitHub repository](https://github.com/TA-Lib/ta-lib/tree/main).
2. **Rust Bindings**: I have bound the `ta-lib` C library to Rust using `rust-bindgen`, which is utilized in the [`ta-lib-rust`](https://github.com/CLevasseur/ta-lib-rust) crate to create a Rust interface to the C library.
3. **Python Bindings with `pyo3`**: I used `pyo3` to bind the Rust code to Python, with the intention of using `pyo3`'s `allow_threads` functionality to release the GIL during `ta-lib` calculations.

## Problem

Even though I am calling `allow_threads` in `pyo3` to release the GIL during the `ta-lib` function calls, Python threads are still blocked, and the GIL is not being released during the computation. This results in no performance gain when running multiple threads in parallel.

### 1. Rust code to bind `ta-lib` C functions:

```rust
use numpy::ndarray::{ArrayD, ArrayViewD};
use talib_sys::{TA_Integer, TA_MAType, TA_Real, TA_RetCode, TA_MA};

/// Compute Simple Moving Average (SMA) using TA-Lib C bindings
///
/// # Arguments
/// * `period` - The time period for SMA calculation
/// * `close_prices` - Input array of closing prices as NumPy array
///
/// # Returns
/// * `ArrayD<TA_Real>` - Output array containing SMA values
///
/// # Implementation Details
/// This function leverages TA-Lib's optimized C implementation for SMA calculation.
/// It uses zero-copy access to the input NumPy array for maximum performance.
pub fn sma_talib(
    period: u32,                       // period for SMA calculation
    close_prices: ArrayViewD<TA_Real>, // NumPy array for close prices
) -> ArrayD<TA_Real> {
    // Convert the NumPy array to a Rust slice for zero-copy access
    let close_prices: &[TA_Real] = close_prices
        .as_slice()
        .expect("Failed to get slice from array");

    // Prepare the output buffer to store the SMA results
    let mut out = ArrayD::<TA_Real>::zeros(vec![close_prices.len()]);

    // Initialize the output begin and size
    let mut out_begin: TA_Integer = 0;
    let mut out_size: TA_Integer = 0;

    unsafe {
        // Call TA-Lib C function to compute the SMA
        let ret_code = TA_MA(
            0,                             // index of the first close to use
            close_prices.len() as i32 - 1, // index of the last close to use
            close_prices.as_ptr(),         // pointer to the first element of the input array
            period as i32,                 // period of the SMA
            TA_MAType::TA_MAType_SMA,      // type of the moving average (SMA)
            &mut out_begin,                // set to index of the first close to have an SMA value
            &mut out_size,                 // set to the number of SMA values computed
            out.as_mut_ptr(),              // pointer to the output array
        );

        match ret_code {
            TA_RetCode::TA_SUCCESS => out,
            _ => panic!("TA-Lib computation failed with error code: {:?}", ret_code),
        }
    }
}
```

```rust
mod indicators;
use indicators::sma::sma_talib as ta_sma_talib;

use numpy::{IntoPyArray, PyArrayDyn, PyReadonlyArrayDyn};
use pyo3::prelude::*;
use pyo3::{types::PyAnyMethods, PyResult, Python};

/// Calculate SMA without holding Python's GIL
#[pyfunction]
#[pyo3(name = "sma_nogil")]
fn sma_nogil(data: PyReadonlyArrayDyn<'_, f64>, period: usize) -> PyResult<Py<PyArrayDyn<f64>>> {
    Python::with_gil(|py| {
        // Validate inputs first before releasing GIL
        if period == 0 {
            return Err(PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Period cannot be 0",
            ));
        }
        if let Ok(len) = data.len() {
            if len < period {
                return Err(PyErr::new::<pyo3::exceptions::PyValueError, _>(
                    "Input data length must be greater than or equal to period",
                ));
            }
        }
        // Convert Python array to owned Rust array
        let array_view = data.as_array();

        // Release GIL and compute with owned data
        let result = py.allow_threads(move || ta_sma_talib(period as u32, array_view));
        let result = result.into_pyarray(py);
        Ok(Py::from(result))
    })
}

/// A Python module implemented in Rust.
#[pymodule]
fn tapy(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(sma_nogil, m)?)?;
    Ok(())
}

```

### 2. Python testing code:

```python
import numpy as np
import time
from talib_rust import sma_nogil
from concurrent.futures import ThreadPoolExecutor


def calculate_sma_chunk(args):
    chunk, period = args
    return sma_nogil(chunk, period)


if __name__ == "__main__":
    # Test with 100 million data points
    prices = np.array([10.0] * 1000000)
    period = 20  # SMA period length

    # Get CPU count for parallel processing
    num_cpus = 16
    chunk_size = len(prices) // num_cpus

    # Test with single large calculation using talib
    start_time = time.time()
    result_talib = sma_nogil(prices, period)
    talib_time = time.time() - start_time
    print(f"Talib time: {talib_time:.4f}s")

    # Test with parallel calculation using talib_rust
    start_time = time.time()

    # Split array into chunks using read-only views
    chunks = [
        prices[i : i + chunk_size].view() for i in range(0, len(prices), chunk_size)
    ]

    # Process chunks in parallel
    with ThreadPoolExecutor(max_workers=num_cpus) as executor:
        args = [(chunk, period) for chunk in chunks]
        results = list(executor.map(calculate_sma_chunk, args))

    # Combine results
    result_talib_rust = np.concatenate(results)

    talib_rust_time = time.time() - start_time
    print(f"talib_rust parallel time: {talib_rust_time:.4f}s")

    # Compare performance
    speedup = (talib_time / talib_rust_time - 1) * 100
    print(f"\n[INFO] Parallel talib_rust is {speedup:.1f}% faster than Talib")


```

### 3. Expected behavior:

I expected that, with the use of `allow_threads` in `pyo3`, the GIL would be released during the call to `ta_sma` within `sma_nogil`, and that multiple threads would be able to run concurrently without being blocked by the GIL. This would allow me to benefit from multi-threaded computation in Python.

### 4. Actual behavior:

Despite using `allow_threads`, Python threads are still blocked during the execution of `ta_sma`, and the GIL is not released during the computation. As a result, there is no improvement in performance when running the program with multiple threads.

## Questions:

1. Is there something in the `ta-lib` C functions (such as `TA_MA`) that prevents the GIL from being released, even when using `allow_threads` in `pyo3`?
2. Is there a known issue with the `ta-lib-rust` bindings when it comes to releasing the GIL, or is there an additional step I need to take in order to successfully release the GIL during computations?
3. Should I handle the GIL differently when interacting with C libraries in `pyo3`, or is there an alternative approach I should use to ensure the GIL is properly released during multi-threaded execution?

## References:

- [TA-Lib C library](https://github.com/TA-Lib/ta-lib/tree/main)
- [ta-lib-rust bindings](https://github.com/CLevasseur/ta-lib-rust)
- [rust-bindgen](https://github.com/rust-lang/rust-bindgen)

Thank you for your help, and I look forward to any suggestions you may have.

**Comment by Icxolu** [comment]
> Despite using `allow_threads`, Python threads are still blocked during the execution of `ta_sma`, and the GIL is not released during the computation. As a result, there is no improvement in performance when running the program with multiple threads.

Are you actually sure that is the case? From the benchmark you provided I believe this is quite hard to tell, because it uses different algorithms. The chunking and recombining in the parallel case may add significant overhead, which will effect the timings.

To clearly see whether the GIL gets release I would run `sma_nogil` twice, something like this:
```python
# sequential
start_time = time.time()
result_talib1 = sma_nogil(prices, period)
result_talib2 = sma_nogil(prices, period)
end_time = time.time() - start_time
print(f"sequential time: {end_time :.4f}s")

# parallel:
start_time = time.time()
with ThreadPoolExecutor(max_workers=num_cpus) as executor:
    f1 = executor.submit(sma_nogil, prices, period)
    f2 = executor.submit(sma_nogil, prices, period)
    res1 = f1.result()
    res2 = f2.result()
end_time = time.time() - start_time
print(f"parallel time: {end_time :.4f}s")
```
If `sma_nogil` releases the GIL, the parallel time should be roughly half of the sequential time. This can also be verified by measuring these two simple functions:
```rust
#[pyfunction]
fn sleep_gil(secs: u64) {
    std::thread::sleep(Duration::from_secs(secs));
}

#[pyfunction]
fn sleep_nogil(py: Python<'_>, secs: u64) {
    py.allow_threads(|| std::thread::sleep(Duration::from_secs(secs)));
}
```
