### ISSUE TITLE
Compiling with Bazel - Documentation

### ISSUE THREAD

**Issue by Sythanis** [PyO3/pyo3#481]
As per discussion in Gitter I want to share my bazel `BUILD` file used in my monorepo to compile `pyo3` if anyone find that interesting :) `rules_rust` and `cargo raze` are required to compile this, together with platform installed Python. Still working with linking to the static python. 
```
  "//visibility:public",
])

licenses([
  "notice", # "Apache-2.0"
])

load(
    "@io_bazel_rules_rust//rust:rust.bzl",
    "rust_library",
    "rust_binary",
    "rust_test",
)

rust_library(
    name = "pyo3",
    crate_root = "src/lib.rs",
    crate_type = "lib",
    edition = "2018",
    srcs = glob(["**/*.rs"]),
    deps = [
        "//third_party/cargo:inventory",
        "//third_party/cargo:libc",
        "//third_party/cargo:mashup",
        "//third_party/cargo:num_traits",
        "//third_party/cargo:pyo3cls",
        "//third_party/cargo:spin",
        "//third_party/sys_libs/zlib"
    ],
    rustc_flags = [
        "--cap-lints=allow",
        "--cfg=Py_3_5",
        "--cfg=Py_3_6",
        "--cfg=Py_3_7",
        "--cfg=Py_3",
        "--cfg=py_sys_config=\"WITH_THREAD\"",
        "-lpython3.7m"
        # TODO: After static linking is fixed
        # "-Lthird_party/python/linux_x86_64/lib",
        # "-lstatic=python3.6m",
    ],
    data =  [
        "//third_party/python:python3",
    ] + glob(["encodings/**"]),
    version = "0.6.0",
    crate_features = [
        "default",
    ],
)
```
This currently links to platform python 3.7. Change `-lpython3.7m` to your platform library.
I have also linked to statically compiled python, where next two lines should be uncommented, however this conflicts with the local bazel python tools and cannot be used at the same time.

Hope this is helpful for anybody :)

**Comment by konstin** [comment]
Thank you for the example! I don't have any experience with bazel, but I'd be happy to add that to the "Building and Distribution" chapter of the guide. Would you like to make a pull request?

**Comment by LegNeato** [comment]
@synthanis do you have an example including a rust pyo3 lib in a python library or python binary?

**Comment by TheButlah** [comment]
I've just made a repo to provide bazel rules for a pyo3 extension, along with compiling pyo3. Please give it a look and try it out - any feedback is appreciated. I am very inexperienced with cargo raze, but I believe my solution works with the latest version of pyo3 - `0.11.1`

https://github.com/TheButlah/rules_pyo3

**Comment by davidhewitt** [comment]
Thanks! I've added a PR just to pop a link to that repo in the guide.
