### ISSUE TITLE
When specifying None as a default value for an argument, the attribute panics

### ISSUE THREAD

**Issue by thedrow** [PyO3/pyo3#486]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: Ubuntu 18.04
 - Your python version: 3.7.2
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: pyenv, yes
 - Your rust version (`rustc --version`): rustc 1.36.0-nightly (af98304b9 2019-05-11)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` I'm using 0.6.0. I haven't tried master.

### 💥 Reproducing

```rust
    #[pyclass]
    struct UUID {
    }

    #[pymethods]
    impl UUID {
        #[new]
        #[args(hex=None, bytes=None, bytes_le=None, fields=None, int=None)]
        fn new(
            obj: &PyRawObject,
            hex: Option<&str>,
            bytes: Option<Py<PyBytes>>,
            bytes_le: Option<Py<PyBytes>>,
            fields: Option<Py<PyTuple>>,
            int: Option<u64>,
        ) {}
}
```

The result is the following error:
```
error: custom attribute panicked --> src/lib.rs:17:5 | 17 | #[pymethods] | ^^^^^^^^^^^^ | = help: message: called `Option::unwrap()` on a `None` value
```

**Comment by Alexander-N** [comment]
None is not allowed as attribute value since it is not a [literal](https://docs.rs/syn/1.0.5/syn/enum.Lit.html). But since None is the default anyway I think it will work if you remove the whole `args` line.

**Comment by thedrow** [comment]
In that case, how do you specify positional arguments?

**Comment by Alexander-N** [comment]
The positions correspond to the order of definition. That said, giving argument="None" should probably work anyway, I'll see if I can provide a fix.
