### ISSUE TITLE
support exceptions in #[new] functions

### ISSUE THREAD

**Issue by robtfm** [PyO3/pyo3#488]
Currently in #[new] functions we are given a `obj: &PyRawObject` and asked to initialise it. 

We can raise an exception, but only by `my_exception.restore(Python::acquire_gil().python())`. 

When we return from the #[new] function, regardless of whether an exception is raised (or whether `obj.init()` has been called), the result is still passed back to python.

From the spec, if we set an exception we should return NULL instead of a valid pointer. Returning non-null loses the exception type we set and a generic SystemError is thrown, the interpreter says something like:

> 
> ValueError: can't initialize
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<input>", line 2, in <module>
> SystemError: <class 'YourPyClass'> returned a result with an error set

Can we please have some way to set exception and return NULL to the interpreter, like a `obj.fail(my_exception)` method or similar? Or just check exception state and return NULL if set?

Thanks

**Comment by poros** [comment]
I am hitting this one in https://github.com/flavray/pyo3avro-rs/issues/16, too. +1

**Comment by althonos** [comment]
You should be able to make a `#[new]` function return `PyResult<()>` instead of `()`, and return a `PyErr` if you need to. Example [here](https://github.com/fastobo/fastobo-py/blob/master/src/py/xref.rs#L242) where I check the type of items in an iterator in the constructor of my Python wrapper.

**Comment by kngwyu** [comment]
As @althonos says we can return `PyResult` from almost all pymethods.
E.g., 
```rust
   #[new]
    fn __new__(obj: &PyRawObject, input: String) -> PyResult<()> {
        match SchemaRs::parse_str(&input) {
            Ok(schema) => Ok(obj.init(Schema { schema })),
            Err(e) => Err(PyErr::new::<exceptions::ValueError, _>(format!("{}", e.as_fail()))),
        }
    }
```
(from the code where @poros refers this issue

**Comment by poros** [comment]
Worked like a charm, thanks! :)
