### ISSUE TITLE
How to wrap a struct with lifetime parameter?

### ISSUE THREAD

**Issue by lochbrunner** [PyO3/pyo3#502]
## 🐛 Bug Reports

This is different to [issue 246](https://github.com/PyO3/pyo3/issues/246).

### 🌍 Environment

 - Your operating system and version: **4.15.0-50-generic #54-Ubuntu SMP**
 - Your python version: **Python 3.6.8**
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: **Anaconda 64bit**
 - Your rust version (`rustc --version`): **rustc 1.34.0-nightly (e1c6d0057 2019-02-22)**
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` **version: 0.7.0**

### 💥 Reproducing

When using a struct with lifetime as follow:

```rust
use pyo3::prelude::*;

#[pyclass]
struct MyClass<'a> {
    r: &'a u32,
}
```

results in the compiler error:

> error[E0106]: missing lifetime specifier
   --> pycore/src/trace.rs:114:8
    |
114 | struct MyClass<'a> {
    |        ^^^^^^^ expected lifetime parameter  
> error: aborting due to previous error

Using dependency:

```toml
[dependencies]
pyo3 = {version = "0.7.0", features = ["extension-module"]}
```

**Comment by kngwyu** [comment]
It's not allowed now since it's *really* difficult to handle the lifetime from Python side.

**Comment by birkenfeld** [comment]
For illustration, the issue is that as a pyclass, the object has to be passed into Python code. For that, it has to be put onto the Python heap, at which point the lifetime is out of control of Rust and the borrow checker.  It can be kept alive potentially indefinitely by Python references.

**Comment by birkenfeld** [comment]
That said, the error could be a lot clearer :)

**Comment by kngwyu** [comment]
> That said, the error could be a lot clearer :)

Agreed :+1:

**Comment by lochbrunner** [comment]
@birkenfeld I thought so already...

**Comment by konstin** [comment]
PR with better error message has been merged

**Comment by chrisrossi** [comment]
Is there a workaround for the fundamental issue here? If I need to wrap a struct from a pure-Rust library that uses lifetimes, how do I do that, short of rewriting the pure-Rust library to work within PyO3 limitations? Is there some clever hack/indirection to get around this limitation?

**Comment by adamreichold** [comment]
You could only unsafely [`transmute`]() `MyStruct<'a>` into `MyStruct<'static>` and store that inside a `#[pyclass]`. Of course, it will then be your responsibility to ensure that the correct lifetimes will be applied during usage. (Generally speaking, this seems unlikely to work as the lifetime `'a` in `MyStruct<'a>` suggests that it references data stored elsewhere. This relationship can just not be managed automatically using the Python heap.)

**Comment by imgurbot12** [comment]
Sorry to necro this thread again, but is there documentation on the best way to translate structs with existing lifetimes? Say for example I have a parser that produces the following struct:

```rust
struct Foo<'a> {
  a: u8,
  b: &'a str,
}
```

I could theoretically copy all of the data into owned equivalents that could then be converted:

```rust
#[pyclass]
struct PyFoo {
  a: u8,
  b: String,
}

impl From<Foo> for PyFoo {
  fn from(value: Foo) -> Self {
     Self {
       a: value.a,
       b: value.b.to_owned()
     }
  }
}
```

but is this the best strategy? That would seemingly create a double-conversion as `pyclass` does whatever magic it needs to do in order to share the data with python slowing whatever gains are left after copying all the relevant data. Is there some strategy to defining a class in python using "native types" to avoid a double conversion?

Trying to do something like this only raises an error `UnsafeCell<PyObject> cannot be shared between threads safely`:

```rust
#[pyclass]
pub struct PyFoo {
    pub a: PyInt,
    pub b: PyString,
}
```

Is there a way to define a class or just pass something ad-hocly via the `IntoPyObject` trait?

**Comment by davidhewitt** [comment]
Maybe you're looking for 

```rust
#[pyclass]
pub struct PyFoo {
    pub a: Py<PyInt>,
    pub b: Py<PyString>,
}
```

**Comment by imgurbot12** [comment]
@davidhewitt that seems to be exactly what I'm looking for, thanks for your response!

I would assume using these pyo3 types avoids any sort of additional conversion then when passing them into the python runtime hopefully right? My intention here is to provide an interface to the zero-copy parser with as little performance loss as possible.
