### ISSUE TITLE
Question on Loading Python imports/objects

### ISSUE THREAD

**Issue by ericmcbride** [PyO3/pyo3#522]
I have searched over the issues and documentation trying to find a hint or answer.  Im wanting to initialize the imports of a python instance one time, and an object in memory, and be able to call a function in rust, that will do the processing I want, but I do no want to load the imports every time the function needs to be called and I also may have a large object id like to hold in memory.  Can I have an initialization function that can just load up the imports and the object?

**Comment by ijl** [comment]
`std:sync::Once` can be used to initialize.: https://doc.rust-lang.org/std/sync/struct.Once.html

**Comment by kngwyu** [comment]
I think it's better to pass a dict which contains modules.
E.g.,
```rust
fn function(py: Python<'_>, locals: &'_ PyDict) {
    py.run("~", Some(locals), ...)
}
```
