### ISSUE TITLE
`wrap_pyfunction!` does not work cross-crate

### ISSUE THREAD

**Issue by nagisa** [PyO3/pyo3#527]
Trying to wrap a function from another crate ends up with the following error

```
error[E0425]: cannot find value `__pyo3_get_function_pose_from_pose_parts` in this scope
  --> src/lib.rs:21:23
   |
21 |         m.add_wrapped(pyo3::wrap_pyfunction!(other_crate::some_pyfunction))?;
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

It is likely that this limitation could be lifted somehow.

**Comment by kngwyu** [comment]
Now we expect an argument of `wrap_pyfunction!` is one wrapped by `#[pyfunction]` decorator.
`__pyo3_get_function_pose_from_pose_parts` is the name of the wrapper funtion that `#[pyfunction]` generates.

And, I think it's really difficult to automatically generate wrapper functions for outer functions.

**Comment by davidhewitt** [comment]
#2091 - I've just had a "brain blast" which finally makes this work!
