### ISSUE TITLE
`getter`s do not support specification of `py: Python` argument

### ISSUE THREAD

**Issue by nagisa** [PyO3/pyo3#528]
Regular methods support automagical `py: Python` argument, however if these methods have the `#[getter]` attribute applied to them, this magic disappears and there is no way to obtain reference to `Python`, making getters like these impossible to write:

```rust
#[getter]
fn foo<'p>(&self, py: Python<'p>) -> &'p PyList {
    PyList::new(py, self.inner.foo.iter())
}
```

**Comment by kngwyu** [comment]
Good catch, thanks.
