### ISSUE TITLE
MaybeUninit::uninit().assume_init() is undefined behavior

### ISSUE THREAD

**Issue by ExpHP** [PyO3/pyo3#536]
https://github.com/PyO3/pyo3/blob/83d0ac4e70f1c622925470ba234b23cfafaa7d35/src/gil.rs#L303-L306

This is explicitly noted in the MaybeUninit docs as undefined behavior (`std::mem:;unintialized` was deprecated for a reason!).  The correct solution is to store `[MaybeUninit<T>; BLOCK_SIZE]` in the type, and to only call `assume_init()` on individual items that are known to be initialized.

(also unrelated:  the current implementation of `ArrayList<T>` is not safe for T that have destructors due to its use of indexed assignment instead of `ptr::write`.  It should have a `T: Copy` bound to reflect this)

**Comment by ExpHP** [comment]
To make matters even worse, you're using it for `NonZero<*mut T>`, a type which has invalid bit patterns!

(not that that makes a difference; `mem::MaybeUninit::uninit().assume_init()` is equally UB for *all types!*  I just found this... *interesting*)

**Comment by kngwyu** [comment]
Currently it's used just to avoid warnings for `mem::uninitialized` so yeah, maybe we should fix this.
But hmm :thinking: , now I have no good idea to make this module sound.

**Comment by kngwyu** [comment]
Good catch, thanks.

**Comment by kngwyu** [comment]
Closed via #537 for now
