### ISSUE TITLE
Send trait requested for Python::allow_threads

### ISSUE THREAD

**Issue by jimy-byerley** [PyO3/pyo3#538]
I'm making a library that uses non-thread-safe objects in python-wrapped objects, one of them is a `Rc<glium::Context>` (the opengl context wrapper)
But since the Python::allow_threads requests the `Send` trait, it's not possible to use the `Rc<glium::Context>` while releasing the gil. I read in the pyo3 source code that the `Send` trait was used only to prevent from moving the Py object within the closure. Is possible to use an other marker trait than Send for Python::allow_threads ?

working code:
```rust
#[pyclass]
struct MyData {
    internal:  Arc<Mutex<Rc<Context>>>,    // Rc<Context> doesn't implement `Send`
}

#[pymethods]
impl MyData {
    fn do_something(&mut self, ... ) -> PyResult<()> {
          // do some preparations
          // ...
          self.internal.lock().unwrap().some_methods());
          Ok(())
    }
```
failing code:
```rust
#[pyclass]
struct MyData {
    internal:  Arc<Mutex<Rc<Context>>>,   // Rc<Context> doesn't implement `Send`
}

#[pymethods]
impl MyData {
    fn do_something(&mut self, ... ) -> PyResult<()> {
          // do some preparations
          // ...
          let gil = Python::acquire_gil();
          let py = gil.python();
          py.allow_threads(|| {        
                   // compilation fails because self.internal doesn't implement `Send` as requested by `allow_threads`
                   self.internal.lock().unwrap().some_methods());  
                   });
          Ok(())
    }
```

**Comment by nagisa** [comment]
If making pyo3 sound is an eventual goal, this API must continue to use `Send`.

**Comment by jimy-byerley** [comment]
I'm trying to understand why `Send` is necessary here, as it's a trait for thread-sharable objects and `allow_threads` doesn't execute the closure un a separated thread. I mean: If it's to prevent python to use these data in a bad thread (for example, an openGL data used from out of the graphic thread), it's not safe to allow it in the method's body (in a `#[pyfunction]`). As Python can execute this method from everywhat thread it want.
For situations where using the structure's data in multiple threads is safe, then request `Send` is not necessary because the closure execution takes place in the same thread as the whole method.

If I'm missing something in my interpretation: would it be a question to rust's developpers to make Arc<Mutex<T>> always Send ?

**Comment by nagisa** [comment]
The threads can be created on the Python side, and `allow_threads` allows them to execute concurrently. If `allow_threads` did not require `Send`, `pyo3` would allow one to concurrently operate on a data that does not support it, leading to data races.

Data races is the first item in the list of [behaviours considered undefined](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust.

**Comment by jimy-byerley** [comment]
Yes, but the object is not properly "sent bt threads", plus arc<mutex> avoid data race on what is inside

**Comment by davidhewitt** [comment]
NB. We might be able to one day achieve this without `Send` using a custom [opt-in built-in trait (aka auto trait)](https://doc.rust-lang.org/unstable-book/language-features/optin-builtin-traits.html) such as `PyGILSafe`. But for now we don't have this, so need to continue use `Send`.

**Comment by davidhewitt** [comment]
With the `nightly` feature we now use an `Ungil` trait, however this doesn't work on stable. There's not much further progress we can make on this for now unless opt-in built-in traits make progress in upstream Rust, so I will close this issue.
