### ISSUE TITLE
Rename `PYTHON_SYS_EXECUTABLE`

### ISSUE THREAD

**Issue by konstin** [PyO3/pyo3#539]
We should rename `PYTHON_SYS_EXECUTABLE` to something more more understandable like `PYO3_INTERPRETER`. The new name is up for bikeshedding.

pyo3 should continue to support both the `PYTHON_SYS_EXECUTABLE` and the new variable for some time, and we need to migrate setuptools-rust and pyo3-pack.

**Comment by davidhewitt** [comment]
Closed via #1039
