### ISSUE TITLE
python3 int <-> num_bigint support

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#543]
See also #124

**Comment by Askaholic** [comment]
I implemented this for grins a while ago: https://gitlab.com/Askaholic/pyrusty.

However, it was my experience that the rust extension module using BigInt was noticeably slower than the python big integer implementation. I was testing this using the baby step giant step algorithm for finding a discrete logarithm.

**Comment by programmerjake** [comment]
> I implemented this for grins a while ago: https://gitlab.com/Askaholic/pyrusty.
> 
> However, it was my experience that the rust extension module using BigInt was noticeably slower than the python big integer implementation. I was testing this using the baby step giant step algorithm for finding a discrete logarithm.

I would guess python is faster because it optimises for single-word numbers, whereas `BigInt` doesn't really (it uses `Vec` internally instead of something like `SmallVec`)

**Comment by programmerjake** [comment]
See also: https://github.com/rust-num/num-bigint/issues/36
