### ISSUE TITLE
Segmentation fault when unwrapping a PyResult

### ISSUE THREAD

**Issue by Alexander-N** [PyO3/pyo3#559]
Calling .unwrap() on a `PyResult` causes a segfault.

### 🌍 Environment

 - Your operating system and version: Ubuntu 18.10
 - Your python version: 3.6.7
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: apt
 - Your rust version (`rustc --version`): rustc 1.38.0-nightly (83e4eed16 2019-07-14)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` yes

### 💥 Reproducing

```rust
use pyo3::PyResult;
use std::net::TcpListener;

fn connect() -> PyResult<bool> {
    TcpListener::bind("127.0.0.1:80")?;
    Ok(true)
}

fn main() {
    connect().unwrap();
}
```

**Comment by Alexander-N** [comment]
I guess some kind of initialization for the exception type is missing. The following panics as expected:

```rust
use pyo3::prelude::*;

fn fails() -> PyResult<(u32)> {
    Ok("not an integer".parse::<u32>()?)
}

fn main() {
    // Removing these lines causes a segfault
    let gil = Python::acquire_gil();
    let _py = gil.python();

    fails().unwrap();
}
```

**Comment by konstin** [comment]
Seems like `PyErr` is calling the ffi functions without acquiring the GIL first.
