### ISSUE TITLE
`PyDict` should expose a wrapper over `PyDict_GetItemWithError`

### ISSUE THREAD

**Issue by nagisa** [PyO3/pyo3#565]
Currently `PyDict::get_item` wraps `PyDict_GetItem` and returns an `Option::None` when the key is missing or an exception occurs. It makes code incapable to differentiate between the two scenarios and code like this likely incorrect:

```
dict.get_item("key").ok_or_else(|| KeyError::py_err("key"))?;
```

**Comment by davidhewitt** [comment]
Marking for part of possible collections improvements in 0.15
