### ISSUE TITLE
Documentation generating for python module

### ISSUE THREAD

**Issue by ToriTyler** [PyO3/pyo3#568]
We are building some projects using Pyo3, mainly exposing some functions from our original rust project to Python. While we are doing so, we come across some issue regarding documentation generation of our projects. 

We want to generate documentations for the python module we built based upon Pyo3, ideally in form of Read the Docs, but we haven't found the best way of doing so. 

The tricky part is, for example, in our project, some `struct` could bears the name: `PyFoo`, but it is a class in python module, and named 'Foo'.

I'm thinking maybe we can generate `JSON` file from its `rustdoc` first, and then use `Sphinx` generate docs from the `JSON` .

Any advice or experience?

**Comment by althonos** [comment]
@TylorJY: I have a working example where I build documentation with Sphinx using a Python module built with PyO3: https://fastobo.rtfd.io. I am using `automodule` and `autoclass` to build the doc from the docstrings in the Rust code.

The code is at https://github.com/fastobo/fastobo-py, hope it helps!

**Comment by TylorJY** [comment]
> @TylorJY: I have a working example where I build documentation with Sphinx using a Python module built with PyO3: https://fastobo.rtfd.io. I am using `automodule` and `autoclass` to build the doc from the docstrings in the Rust code.
> 
> The code is at https://github.com/fastobo/fastobo-py, hope it helps!

Thanks ! It helps a lot!

**Comment by TylorJY** [comment]
@althonos Thanks, helps a lot!!
