### ISSUE TITLE
Error running word-count example

### ISSUE THREAD

**Issue by RKennedy9064** [PyO3/pyo3#571]
## 🐛 Bug Reports
Currently receiving this error when trying to run the word-count example. Am I missing a step in the build process?
```
C:\Users\kennedy-ryan\source\repos\pyo3\examples\word-count>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from word_count import search_py, WordCounter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kennedy-ryan\source\repos\pyo3\examples\word-count\word_count\__init__.py", line 1, in <module>
    from .word_count import WordCounter, count_line
ModuleNotFoundError: No module named 'word_count.word_count'
```

### 🌍 Environment

 - Your operating system and version: Windows 7 Enterprise Service Pack 1
 - Your python version: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: From the Windows installer (https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe)
 - Your rust version (`rustc --version`): rustc 1.38.0-nightly (2d1a551e1 2019-08-08)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Using the master branch as of todays date.

### 💥 Reproducing

```
git clone https://github.com/PyO3/pyo3.git
cd pyo3\examples\word-count
python setup.py install
python
from word_count import search_py, WordCounter
```

**Comment by omac777** [comment]
Problem:
```
python3
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import word_count
>>> WordCounter("/home/davidm/Downloads/pyo3/examples/word-count/tests/test_word_count.py").search("import")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'WordCounter' is not defined
```

SOLUTION:
```
>>> word_count.WordCounter("/home/davidm/Downloads/pyo3/examples/word-count/tests/test_word_count.py").search("import")
3
```

**Comment by RKennedy9064** [comment]
Thanks, I'll try doing a normal build and calling the module from it. So when would setuptools-rust or pyo3-pack be needed then? When making a wheel for someone else to install?

**Comment by RKennedy9064** [comment]
@omac777 Thanks for the tips and example. I was able to get it working by using cargo build --release. The only other change I needed to do was rename the dll to pyd.
