### ISSUE TITLE
Potential issue with __setitem__

### ISSUE THREAD

**Issue by RKennedy9064** [PyO3/pyo3#577]
## 🐛 Bug Reports

Are there currently any known issue for `__setitem__`? I've been implementing PySequenceProtocol and am having trouble with `__setitem__`. I've implemented `__getitem__`, as well as `__len__` and they seem to be working correctly. When I try to assign a value using `__setitem__`, it gives me an error of `TypeError: 'Record' object does not support item assignment`. Below is an example of my current code, along with the output. Am I missing something obvious related to `__setitem__`? Any help would be greatly appreciated.

### 🌍 Environment

 - Your operating system and version: Windows 10
 - Your python version: 3.7.4
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Windows Installer
 - Your rust version (`rustc --version`): 
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Currently using the master branch.

### 💥 Reproducing

```
#[pyclass]
#[derive(Debug, Default)]
pub struct Record {
    fields: Vec<String>,
}

#[pyproto]
impl PySequenceProtocol for Record {
    fn __getitem__(&self, idx: isize) -> PyResult<&'p str> {
        match self.fields.get(idx as usize) {
            Some(item) => Ok(item),
            None => Err(IndexError::py_err(format!("index out of bounds: {}", idx))),
        }
    }

    fn __setitem__(&mut self, idx: isize, value: &str) -> PyResult<()> {
        self.fields[idx as usize] = value.to_string();
        Ok(())
    }

    fn __len__(&self) -> PyResult<usize> {
        Ok(self.fields.len())
    }
}

>>> dir(record)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

Record { fields: ["Test", "Test", "Test"] }
>>> record[0]
'Test'
>>> len(record)
3
>>> record[0] = 'Another test'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Record' object does not support item assignment
```

**Comment by kngwyu** [comment]
Hmm, I didn't know that.
I'm going to check it in this weekend.
