### ISSUE TITLE
Broken links on pyo3.rs

### ISSUE THREAD

**Issue by skreimeyer** [PyO3/pyo3#593]
A few links in the documentation on pyo3.rs are broken. The ones I found are as follows:

Get Started:
- https://pyo3.rs/v0.8.0/examples/word-count

Type Conversions:
- https://docs.rs/pyo3/0.8.0/pyo3/trait.ToPyObject.html
- https://docs.rs/pyo3/0.8.0/pyo3/struct.PyObject.html
- https://docs.rs/pyo3/0.8.0/pyo3/types/trait.IntoPyDict.html

Python Exceptions:
- https://docs.rs/pyo3/0.8.0/pyo3/struct.PyErr.html
- https://docs.rs/pyo3/0.8.0/pyo3/struct.PyErr.html#method.restore
- https://docs.rs/pyo3/0.8.0/pyo3/struct.PyErr.html#method.from_instance
- https://docs.rs/pyo3/0.8.0/pyo3/struct.Python.html#method.is_instance
- https://docs.rs/pyo3/0.8.0/pyo3/types/struct.PyType.html#method.is_instance
- https://docs.rs/pyo3/0.8.0/pyo3/prelude/type.PyResult.html
- https://docs.rs/pyo3/0.8.0/pyo3/struct.PyErr.html
- https://docs.rs/pyo3/0.8.0/pyo3/trait.PyErrArguments.html
- https://docs.rs/pyo3/0.8.0/pyo3/exceptions/index.html

Python Module:
- https://pyo3.rs/master/overview.html

Python Class:
- https://docs.rs/pyo3/0.8.0/pyo3/class/basic/trait.PyObjectProtocol.html
- https://docs.rs/pyo3/0.8.0/pyo3/class/gc/trait.PyGCProtocol.html
- https://docs.rs/pyo3/0.8.0/pyo3/class/iter/trait.PyIterProtocol.html

Parallelism:
- https://docs.rs/pyo3/0.8.0/pyo3/struct.Python.html#method.allow_threads

Links to https://github.com/PyO3/pyo3-pack redirect to https://github.com/PyO3/maturin which is good, but it would probably be good to replace the link text for clarity.

**Comment by konstin** [comment]
That happen because I travis ci published the updated documentation, but I didn't want to published to crates.io, which updates docs.rs, before travis had passed. That should fix itself once docs.rs built the new release.

**Comment by skreimeyer** [comment]
Does docs.rs normally take a few days to update? I haven't published any documentation there myself, so I don't actually know. Also, I think in the case of the links to https://pyo3.rs/master/overview.html and https://pyo3.rs/v0.8.0/examples/word-count these links are to sections of the documentation that have been changed or moved.

**Comment by konstin** [comment]
I've never checked how long it normally takes, but there's the docs.rs build queue: https://docs.rs/releases/queue. Overwiew and the example are indeed broken and should but fixed.
