### ISSUE TITLE
#question: Rc<RefCell<pyclass>>

### ISSUE THREAD

**Issue by inv2004** [PyO3/pyo3#600]
Hello,

Are there any way to have IntoPy for Rc<RefCell<#[pyclass]>> struct ?

Trying to avoid the following error
```rust
the trait `pyo3::IntoPy<pyo3::Py<pyo3::types::PyTuple>>` is not implemented for `(std::cell::Ref<'_, player::py_full::Control>,)`
```

Thank you,

**Comment by kngwyu** [comment]
Sorry for my ignorance of this issue, but is it solved?

**Comment by inv2004** [comment]
Yes, Thank you.

I found that this works fine:
```
#[pyclass]
struct PyCtrl {
    ctrl: Rc<RefCell<Ctrl>>
}
```

**Comment by kngwyu** [comment]
That's nice, thank you for sharing the workaround.
