### ISSUE TITLE
Failed compiling the first example

### ISSUE THREAD

**Issue by JoeHsiao** [PyO3/pyo3#601]
### 🌍 Environment
 - Your operating system and version: Windows 10
 - Your python version: 3.7.3
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:  miniconda with no virtualenv.
 - Your rust version (`rustc --version`): 1.36.0
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` YES. I tried both 0.8.0 from crates.io and the master repo on github.

### 💥 Reproducing

Please provide a [minimal working example](https://stackoverflow.com/help/mcve). This means both the rust code and the python.
```
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

fn main() -> PyResult<()> {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let sys = py.import("sys")?;
    let version: String = sys.get("version")?.extract()?;
    let locals = [("os", py.import("os")?)].into_py_dict(py);
    let code = "os.getenv('USER') or os.getenv('USERNAME') or 'Unknown'";
    let user: String = py.eval(code, None, Some(&locals))?.extract()?;
    println!("Hello {}, I'm Python {}", user, version);
    Ok(())
}
```
Error message
```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000aa2c (most recent call first):
error: process didn't exit successfully: `target\debug\pyo3-test.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```
Please also write what exact flags are required to reproduce your results.

**Comment by kngwyu** [comment]
:thinking:

**Comment by JoeHsiao** [comment]
It's actually working when I use Windows command line. The one that was not working was on git bash.

**Comment by JoeHsiao** [comment]
I was wrong. "cargo +nightly build" works, but not "cargo +nightly run".

**Comment by JoeHsiao** [comment]
The solution is adding PYTHONHOME and PYTHONPATH in environment variables.
