### ISSUE TITLE
[More documentation] Loading and using python functions

### ISSUE THREAD

**Issue by efugier** [PyO3/pyo3#602]
Can someone help me put together a full minimal example ?

I think it would be great to include it in the Readme in the "using python from rust" section which clearly lacks content.

It would create the basis for an app with the logic written in rust which rely on a few python functions. An example use case could be a machine learning (where almost everything is done with python libs) based app with some heavy post treatment that would benefit from being done in rust.

Here's my failed attempt :

`main.rs`
```rust
use std::include_str;
use pyo3::prelude::*;

fn main() -> PyResult<()> {
    let python_functions = include_str!("python-functions.py");

    let gil = Python::acquire_gil();
    let py = gil.python();

    py.eval(python_functions, None, None)?;

    let code = "test()";
    let res : String = py.eval(code, None, None)?.extract()?;


    println!("{}", res);

    Ok(())
}
```
`python_functions.py`
```python
def test():
    return "hello"
```

it gives me `Error: PyErr { type: Py(0x7ff14324ed60, PhantomData) }` which isn't really a workable error.

The next step is to make a **function that takes parameters** and we'll be set !

**Comment by kngwyu** [comment]
I think rust-numpy crate has [a better example](https://github.com/rust-numpy/rust-numpy#execute-a-python-program-from-rust-and-get-results), but yeah, we need good examples in this area.

**Comment by efugier** [comment]
Thanks for pointing this out, it explains how to correctly output errors and that's useful.

However I think something is still off: when the code in the script relies on multiple lines it fails with a syntax error even though there is none (the script is correct and runs with python).

**Comment by kngwyu** [comment]
`eval` only accepts Python's expression(≒ one liner).
So if you want to run long code, you can use [`py_run`](https://pyo3.rs/master/doc/pyo3/macro.py_run.html) or so but it returns `None`.

**Comment by efugier** [comment]
That's exactly the type of thing that the documentation is lacking, explaining basic high level stuff on what is used to do what. Thanks !

I'll make a PR as soon as I get some free time.

**Comment by kngwyu** [comment]
Also, I wrote an example to get an Python object using `Python::run`.
```rust
    use pyo3::types::{IntoPyDict, PyDict, PyList};
    let gil = Python::acquire_gil();
    let py = gil.python();
    let ret_dict = [("ret", 3)].into_py_dict(py);
    py.run(
        r#"
l = [8, 7, 3, 4, 5]
l.sort()
ret = l
"#,
        None,
        Some(ret_dict),
    );
    let list: &PyList = ret_dict.get_item("ret").unwrap().downcast_ref().unwrap();
    let ret: Vec<i32> = list.extract().unwrap();
    assert_eq!(&ret, &[3, 4, 5, 7, 8]);
```

**Comment by konstin** [comment]
I think might actually want `PyModule::from_code` instead of `eval` or `run`. I'd be happy if someone contributed examples to the guide on how to use `PyModule::import` and `PyModule::from_code`.

**Comment by kngwyu** [comment]
@konstin 
I updated #603 to include `PyModule::from_code`, please check it.

**Comment by abrcdf1023** [comment]
Hello guys I also has trouble in the example of using PyModule.
The piece of code is not work properly.
```rust
use pyo3::{prelude::*, types::{IntoPyDict, PyModule}};
let gil = Python::acquire_gil();
let py = gil.python();
let activators = PyModule::from_code(py, "
def relu(x):
    return max(0.0, x)

def leaky_relu(x, slope=0.01):
    return x if x >= 0 else x * slope
", "activators.py", "activators")?;
let relu_result: f64 = activators.call1("relu", (-1.0,))?.extract()?;
assert_eq!(relu_result, 0.0);
let kwargs = [("slope", 0.2)].into_py_dict(py);
let lrelu_result: f64 = activators
    .call("leaky_relu", (-1.0,), Some(kwargs))?
    .extract()?;
assert_eq!(lrelu_result, -0.2);
```

And I'm keep getting this error message, do I miss something?

![螢幕快照 2019-10-06 20 01 00](https://user-images.githubusercontent.com/12894459/66268847-1785b600-e874-11e9-858d-c9f3c60f0fc3.png)

**Comment by kngwyu** [comment]
Please use `PyResult<()>`  instead of `Result<(), ()>` and return `Ok(())`.

**Comment by Alexander-N** [comment]
Closed by #603.

**Comment by Delanii** [comment]
I am still a little confused about this part of using py3o. How can I load a simple `.py` script file? Even the easiest of examples:

```script.py
print("Hello")
```

```pyembed.rs
fn hello_script(py:Python) -> PyResult<()> {
    let my_file_name = "src/python/helloPython.py";
    let script = PyModule::from_code(py, None, my_file_name, None)?;
    Ok(())
}
```

But this doesnt work because it seems that all arguments of `PyModule::from_code` are to be strings, so should I load the file and covert its contents to string, or is there any more elegant solution?

**Comment by davidhewitt** [comment]
If you don't want to load the file yourself, you're probably looking for `PyModule::import`.

**Comment by Delanii** [comment]
Hello @davidhewitt ,
which `PyModule::import` method are you referring to? I have searched here: 

https://pyo3.rs/master/python_from_rust.html 

and here: 

https://docs.rs/pyo3/0.13.2/pyo3/all.html 

and did not find anything.
I admit I am a beginner, so I am sorry if it is obvious, but as a beginner I need function definition, and what arguments it expects, to be able to use it.

**Comment by davidhewitt** [comment]
https://docs.rs/pyo3/0.13.2/pyo3/prelude/struct.PyModule.html#method.import

**Comment by Delanii** [comment]
@davidhewitt If I undestand correctly this part of the guide: 

https://pyo3.rs/master/module.html

the loaded `#[pymodule]` has to be shared dynamic library file. I dont have that. I want to load only simple python script that should be ran by embedded interpreter ...
So I guess the only solution is to load that `.py` file, more precisely its contents, as one giant string and feed that to `PyModule::from_code()` function ...

**Comment by birkenfeld** [comment]
`PyModule::import` is not restricted to modules implemented in Rust; it is the same as writing `import foo` in Python code.  So if your, let's say, `foo.py` file is findable via `sys.path`, you can import it using `PyModule::import("foo")`.

**Comment by ShaneEverittM** [comment]
> `PyModule::import` is not restricted to modules implemented in Rust; it is the same as writing `import foo` in Python code. So if your, let's say, `foo.py` file is findable via `sys.path`, you can import it using `PyModule::import("foo")`.

What if it isn't? What if I want to just import a module in the current directory? What if I have a virtual environment from which I'd like to import?

**Comment by birkenfeld** [comment]
Well, you do the same as you would in Python to make `import foo` work: usually, to add its location to `sys.path`.

For the virtualenv case, you usually need to activate it, setting up the environment before starting your binary.
