### ISSUE TITLE
Feedback on the improved C API for Python proposal

### ISSUE THREAD

**Issue by rth** [PyO3/pyo3#605]
As you may know, there is a proposal to improve the C API for Python at https://pythoncapi.readthedocs.io/ . 

Feedback from projects that may benefit from it is implicitly requested [here](https://pythoncapi.readthedocs.io/roadmap.html#players). If you have any comments on it, or about possible resulting [optimization ideas](https://pythoncapi.readthedocs.io/optimization_ideas.html) that could benefit PyO3, showing some sign of interest at https://github.com/pythoncapi/pythoncapi or on the linked mailing list could be worthwhile. 

Otherwise feel free to close this issue.

**Comment by kngwyu** [comment]
Thank you for letting us know that. I didn't know the proposal.
Though now I have nothing I can propose, it would also benefit us to think about our *ideal* Python C API.

**Comment by davidhewitt** [comment]
I'm going to close this for now, as we haven't given feedback in two years (although an improved API would benefit us).
