### ISSUE TITLE
How to extract from a list of Python objects of different types into Rust

### ISSUE THREAD

**Issue by VictorCoder123** [PyO3/pyo3#606]
I see PyO3 has implemented `FromPyObject` trait for lots of basic Python types to translate python objects to Rust but I have no ideas how to deal with it when it comes to a list of objects of different types like `A`, `B`, `C` I have defined below. What should I fill the question mark in Rust code for the arguments in constructor?

```Rust
// class A, B, C are all defined as pyclass.
impl C {
    fn new(obj: &PyRawObject, arguments: Vec<?>) {}
}
```

```python
# Python code
a = A()
b = B()
c1 = C([a])
c2 = C([a, b, c1])
```

**Comment by althonos** [comment]
Do you need an arbitrary number of arguments or between 0 and 3? 

Check the `#[args]` macros in the book (https://pyo3.rs) you may find more information about how to define function arguments :wink:

**Comment by birkenfeld** [comment]
I think `Vec<&PyAny>` should be ok when you expect a list of arbitrary Python objects.

If you really require a "an A, a B and then a C" it's better to either have them as individual arguments, as @althonos said, or accept a tuple instead of a Vec.

**Comment by VictorCoder123** [comment]
I need an arbitrary number of arguments and that's why I have to use list instead of tuple.

If I use `Vec<&PyAny>` as the argument then how can I decide the type of items in the list as they can be either A, B or C.

**Comment by althonos** [comment]
You could do something like:
```rust
#[pymethods]
impl C {
    #[new]
    #[args(args="*")]
    fn new(obj: &PyRawObject, args: &PyTuple) -> PyResult<()> {
        for arg in args.iter() {
            if let Ok(a) = arg.cast_as::<A>() {
                // do something with your a
            } else if let Ok(b) = args.cast_as::<B>() {
                // do something with your b
            } else if let Ok(c) = args.cast_as::<C>() {
                // do something with your c
            } else {
                let msg = format!("expected A, B or C, found {}", arg.get_type().name());
                return TypeError::into(msg);
            }
        }
        Ok(())
    }
```

This makes the constructor usable in a way that follows the Python ergonomics:
```python
a = A()
b = B()
c1 = C(a)
c2 = C(a, b, c1)
```

**Comment by althonos** [comment]
If you *really* need to have the arguments in a collection, you should consider using `PyIterator` to allow any iterable to be passed as an argument to your class, e.g.:
```
#[pymethods]
impl C {
    #[new]
    fn new(obj: &PyRawObject, args: &PyAny) -> PyResult<()> {
        for res in PyIterator::from_object(obj.py(), args)? {
            let arg = res?;
            if let Ok(a) = arg.cast_as::<A>() {
                // do something with your a
            } else if let Ok(b) = args.cast_as::<B>() {
                // do something with your b
            } else if let Ok(c) = args.cast_as::<C>() {
                // do something with your c
            } else {
                let msg = format!("expected A, B or C, found {}", arg.get_type().name());
                return TypeError::into(msg);
            }
        }
        Ok(())
    }
}
```
which lets you do:
```python
a = A()
b = B()
c1 = C([a])
c2 = C((a, b, c1))
```

**Comment by VictorCoder123** [comment]
Fantastic! Thank you for helping me out.
