### ISSUE TITLE
How to return a list of Rust objects of different types back into Python?

### ISSUE THREAD

**Issue by VictorCoder123** [PyO3/pyo3#607]
This is a follow-up question to #606 and the problem I have is that now I want to implement a python function in Rust that will return a list of instances of different types like `A`, `B` and `C` but I don't know what should be the right type to put in `PyResult`. I have tried to use enum type that enumerates three types but the new type can't be annotated as `pyclass` so it can't be converted between Rust and Python. Any better ideas to deal with it? 

```rust
// class A, B, C are all defined as pyclass.
impl C {
    fn my_function(&self) -> PyResult<?>{
        let a = A {};
        let b = B {};
        let c = C {};
        let mut list = vec![a, b, c];
        // Now I want to return the list back into the python environment, 
        // so I would expect I can get a python list that has instances of different types.
    }
}
```

**Comment by althonos** [comment]
You don't have to be as accurate for returning a value to `Python`, so you can simply return a `Vec<PyObject>`, and manually call `to_object` on your values:
```rust
#[pymethods]
impl C {
    fn my_function(&self) -> PyResult<Vec<PyObject>>{
        let gil = Python::acquire_gil();
        let py = gil.python();

        let a = A {};
        let b = B {};
        let c = C {};
        Ok(vec![a.to_object(py), b.to_object(py), c.to_object(py)])
    }
}
```

**Comment by VictorCoder123** [comment]
Thank you!
