### ISSUE TITLE
How to cast PyAny into HashMap in Rust

### ISSUE THREAD

**Issue by VictorCoder123** [PyO3/pyo3#610]
Things become more tricky when I tried to convert HashMap between Python and Rust that the default conversion is not implemented so I cannot cast a python dictionary into HashMap in Rust with the error saying `PyTypeInfo` trait is not implemented for `HashMap<A, B>`.

I have also tried to change the type of input argument to `HashMap<A, B>` but still cannot make it work with the error saying `FromPyObject` trait is not implemented for `HashMap<A, B>`

```Rust
// A and B are both annotated as pyclass 
fn my_function(&self, input: &PyAny) -> PyResult<PyObject> {
    if let Ok(map) = input.cast_as::<HashMap<A, B>>() {
    }
}

fn my_function(&self, input: HashMap<A, B>) {}
```

**Comment by sebpuetz** [comment]
This is probably most easily implemented with a wrapper type that you define in your own crate. 

This assumes that your method takes a `PyDict`with keys for which `K` implements `FromPyObject` and its values can be extracted as `V`:

~~~Rust
struct PyMap<K, V>(HashMap<K, V>);

impl<'a, K, V> FromPyObject<'a> for PyMap<K, V> where K: FromPyObject<'a> + Hash + Eq, V: FromPyObject<'a> + Hash + Eq {
    fn extract(ob: &'a PyAny) -> PyResult<Self> {
        if let Ok(dict) = ob.downcast_ref::<PyDict>() {
            Ok(PyMap(dict.items().extract::<Vec<(K, V)>>()?.into_iter().collect::<HashMap<_,_>>()))
        } else {
            TypeError::py_err("dict expected").into()
        }
    }
}
~~~

**Comment by Alexander-N** [comment]
`FromPyObject` was added for `HashMap` in #702.
