### ISSUE TITLE
WindowsAppStore initially set dummy interpreter

### ISSUE THREAD

**Issue by namuyan** [PyO3/pyo3#619]
## 🐛 Bug Reports
If users install Anaconda3 or normal python from official site, cannot find correct **python interpreter**. These days Windows10 updated, WindowsAppStore initially make `python.exe` and `python3.exe` but those EXE open shop for recommend install!

We must install Python from Microsoft app store?
caused: https://github.com/PyO3/pyo3/blob/master/build.rs#L28
path: `C:\Users\name\AppData\Local\Microsoft\WindowsApps\python.exe`

### 🌍 Environment

 - Your operating system and version: Windows10 64bit
 - Your python version: python3.6
 - How did you install python?: Anaconda3
 - Your rust version (`rustc --version`): 1.40.0-nightly (898f36c83 2019-10-10)
 - Are you using the latest pyo3 version? 0.8.1 stable

### Solutions
1. dummy exe don't show version by `python --version`. use it?
2. manually setup python path?
good ways?

**Comment by kngwyu** [comment]
Wow :fearful:

**Comment by namuyan** [comment]
merged, reopen if problem occurred.
