### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by liquidscorpio** [PyO3/pyo3#628]
The README.md file links to https://docs.rs/pyo3/0.8.1/pyo3/ as API documentation for stable but it is not working. Not sure what exactly went wrong but the docs for 0.8.0 are still working - https://docs.rs/pyo3/0.8.0/pyo3/.

![Screenshot from 2019-10-14 22-57-41](https://user-images.githubusercontent.com/4113784/66770791-1983f080-eed6-11e9-9ffe-e557bc293305.png)

**Comment by programmerjake** [comment]
I didn't see pyo3 in docs.rs build-failed list, though I could have missed it

**Comment by liquidscorpio** [comment]
As posted in the OP, here is the failing link - https://docs.rs/pyo3/0.8.1/pyo3/.

**Comment by programmerjake** [comment]
to clarify, I had meant that it may be a problem with docs.rs if the build didn't fail but didn't show up. maybe they somehow lost the release notification?

**Comment by gilescope** [comment]
Docs are there now. @liquidscorpio crates.rs takes a while to catch up - it's not expecting us all to be releaseing new and updated crates so frequently. #GrowingPains 

Move to close.

**Comment by programmerjake** [comment]
> Docs are there now. @liquidscorpio docs.rs takes a while to catch up - it's not expecting us all to be releaseing new and updated crates so frequently. #GrowingPains

the docs for v0.8.1 are still not there, all that happened is that v0.8.2 was published and docs.rs didn't break this time (v0.8.2 has been on docs.rs for a while).

In my experience, docs.rs usually runs a build within a few minutes of a new crate version being published.

I think all that's needed is to ask docs.rs to rerun the build for v0.8.1, which probably spuriously failed.

**Comment by kngwyu** [comment]
docs.rs sometimes fails, and it's best not to be too serious about it.
