### ISSUE TITLE
#[pymethods] - skip (do not wrap) certain methods in the impl

### ISSUE THREAD

**Issue by liquidscorpio** [PyO3/pyo3#633]
From the [guide](https://pyo3.rs/v0.8.1/class.html#instance-methods):

> PyO3 generates Python compatible wrappers for **all functions** in this block with some variations, like descriptors, class method static methods, etc.

Is there some way to skip certain functions when `#pymethods` is used over an `impl`? Example:

```rust
#[pyclass]
struct Foo {
   bar: i32
}

#[pymethods]
impl Foo {
     // Wrap this and expose to python
     fn add_5(&self) -> i32 {
          self.bar + 5
     }
     // But skip this when wrapping and **do not** expose to python?
     fn add_2(&self) -> i32 {
          self.bar + 2
     }
}
```

Is it possible to tell PyO3 to skip wrapping `add_2` as noted in the example above?

**Comment by birkenfeld** [comment]
That's not necessary, since you can just write another impl block without the `pymethods` attribute.

**Comment by liquidscorpio** [comment]
Thanks, @birkenfeld! Going to try this out later and close this one if it works.

**Comment by kngwyu** [comment]
Yeah, 
```rust
#[pymethods] 
impl A {}

impl A {}
```
would work.
