### ISSUE TITLE
release version 0.8.2

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#638]
I'm nearly ready to publish a new version of [`algebraics`](https://crates.io/crates/algebraics) that includes support for Python bindings -- the release is blocked on there being a released version of PyO3 that includes `BigInt` <-> `PyLong` conversions.

Feel free to edit as needed to add blocking issues, etc.

**Comment by kngwyu** [comment]
I released it now.

**Comment by programmerjake** [comment]
Thanks!

**Comment by programmerjake** [comment]
For those who are interested, I released `algebraics` v0.1.2 which includes Python support to both [crates.io](https://crates.io/crates/algebraics) and [PyPI](https://pypi.org/project/algebraics/)
