### ISSUE TITLE
Use of Python::allow_threads

### ISSUE THREAD

**Issue by sebpuetz** [PyO3/pyo3#640]
## 🐛 Bug Reports

Not really a bug, but anyways: The guide has a section on parallelism that states that `allow_threads` allows parallelism through e.g. rayon. The code in the example demonstrates

~~~Rust
        let count = py.allow_threads(move || {
            contents
                .par_lines()
                .map(|line| count_line(line, &search))
                .sum()
        });
~~~

is faster than:

~~~Rust
let result = contents.lines().map(|line| count_line(line, &needle)).sum();
~~~

which makes absolute sense. 

The point I'm getting at is, that `allow_threads` is not required in any way to run `.par_lines()` and changing `search_sequential` to the following makes it run as fast as the version with `allow_threads`:

~~~Rust
    /// Searches for a word in a classic sequential fashion
    fn search_sequential(&self, needle: String) -> PyResult<usize> {
        let contents = fs::read_to_string(&self.path)?;

        let result = contents
            .par_lines()
            .map(|line| count_line(line, &needle))
            .sum();

        Ok(result)
    }
~~~

![image](https://user-images.githubusercontent.com/30175181/67432401-825e1d80-f5e6-11e9-85b0-6b339913a789.png)

What is the actual use-case of `allow_threads` then?

**Comment by programmerjake** [comment]
`allow_threads` allows other python code to run concurrently on other threads, since otherwise the GIL would block the other python threads.

**Comment by sebpuetz** [comment]
Might just be my limited knowledge about Python, but do you mean other code as in Python code running in different subprocesses? Or how could the Python code proceed before the ffi call returns?

The following fn renders the process entirely unresponsive, so I don't see such an effect on the currently running process:

~~~Rust
#[pyfunction]
fn never_return() {
    let gil = Python::acquire_gil();
    Python::allow_threads(gil.python(), || {
        loop{}
    });
}
~~~

**Comment by programmerjake** [comment]
> Might just be my limited knowledge about Python, but do you mean other code as in Python code running in different subprocesses?

I mean python code running different threads (yes, python [supports multithreading](https://docs.python.org/3/library/threading.html#thread-objects), but it's not commonly used due to the GIL only allowing one thread at a time to execute python code).

> Or how could the Python code proceed before the ffi call returns?

it doesn't in the current thread, but it can in other threads.

**Comment by sebpuetz** [comment]
Thanks for the explanation!

**Comment by Askannz** [comment]
I was also confused about `allow_threads()`, I think the API documentation could really use an improvement there.

If my understanding is correct, calling `py.allow_threads(|| { ... })` consumes the marker object `py`, preventing further calls from the Python interpreter. However, at the same time, it releases the GIL and allows other Python threads to run while it executes the given closure.

**Comment by Askannz** [comment]
By the way, it seems this function is not safe, because I can trigger a segfault with it : https://github.com/PyO3/pyo3/issues/649

Maybe I'm just using it wrong, but in this case it should be marked `unsafe` and have some additional documentation.

**Comment by kngwyu** [comment]
This function is **not** for executing Python codes in a multi-threading situation.
See [my explanation](https://github.com/PyO3/pyo3/issues/649#issuecomment-546604769).

Basically you shouldn't call any Python function in the closure.
I agree that our documentation has many rooms for improving, but let's discuss it in #649.
