### ISSUE TITLE
How to get the type/name of a PyObject / PyAny at runtime

### ISSUE THREAD

**Issue by sebpuetz** [PyO3/pyo3#646]
Is there a straight forward way to get the PyType of a given object? E.g. when implementing `FromPyObject` the rust type is `PyAny` and I'd like to be verbose about why conversion failed or what type was passed.

I know how to check whether a given `PyObject` or `PyAny` is of a specific type `T`, but I'd like to get the name of this unspecified type or its PyType.

**Comment by kngwyu** [comment]
If `T` implements `PyTypeInfo`, you can do it by `T::is_instance`.
But I think we don't have a safe API for getting type objects now.
(Though you can do it by unsafe code, by
```rust
obj.as_ptr().ob_type
```
)

**Comment by birkenfeld** [comment]
Or by calling the respective Python code (`type(x)`) I assume.

**Comment by sebpuetz** [comment]
> And if you want to get the type object, you can use ObjectProtocol::get_type.

Oh wow, my IDE didn't show this method for `&PyAny` and I apparently missed the implementation. Thanks!
