### ISSUE TITLE
Make rerunning build on env variables change an optional feature

### ISSUE THREAD

**Issue by zimond** [PyO3/pyo3#656]
Currently `pyo3` reruns every time when several environment variable changed. This does not co-op well with IDE tools like `rls` or `rust-analyzer`. As they could change the variables to ensure cargo tools in PATH whenever code changes happen, if `pyo3` is included as a dependency, a crate will re-compile right from pyo3 every time, wasting all the cached compilations.

I cannot find a good way to resolve this problem. So I'm suggesting that maybe the re-run logic in `build.rs` could be covered by a feature gate, so users that are bothered by this behavior (like me) could manually turn off this logic.

Thanks

**Comment by davidhewitt** [comment]
@zimond if this is still a problem for you, can you give an example of an environment variable which frequently changes which causes you a problem?

**Comment by zimond** [comment]
Oh this cannot be reproduced now. I'm closing this issue
