### ISSUE TITLE
Implement the buffer protocol safely

### ISSUE THREAD

**Issue by jimy-byerley** [PyO3/pyo3#657]
Hi ! 
I'm using rust as backend for a python module I'm working on, to get high performances on mesh operations. The data is owned by some rust `Vec`s but I would like to expose its content to python, to make possible extend the module with pure python (or at least to get some data points).

So I'm trying to implement the buffer protocol for my structs. I seen [this page in pyo3](https://pyo3.rs/master/doc/pyo3/class/buffer/trait.PyBufferProtocol.html#method.bf_getbuffer). But it relies on pointers so it's unsafe. 
But the buffer protocol is not incompatible with pyo3's safety since i read [in the python doc](https://docs.python.org/3/c-api/typeobj.html#buffer-structs) that the `memoryview` object kept a hook on the viewed object

Is there a way to safely implement the buffer protocol for rust objects exposed by a `#[pyclass]` statement ?

**Comment by kngwyu** [comment]
Sorry, I'm saying about `class/buffer.rs` where `PyBufferProtocol` is.
Though `PyBuffer` also can be changed a bit...(e.g., it can have lifetime `py`)

**Comment by davidhewitt** [comment]
This is now tracked in #1884 as part of the move to `#[pymethods]`.
