### ISSUE TITLE
Question: Is it possible to debug into Rust code from a python IDE e.g. PyCharms?

### ISSUE THREAD

**Issue by PierreHenry63** [PyO3/pyo3#665]
Hello, 
Many thanks for developing this library, I'm just getting started but it looks awesome.

My questions is: is it possible to debug into Rust from a python IDE such as PyCharms?

Many thanks,
Pierre Henry

**Comment by kngwyu** [comment]
I don't think it's possible because *Python C-extension* is binary(e.g., .so) file.
So when you type `import rust_extension` in Python code, it loads binary file, which has no link to the source Rust code.
