### ISSUE TITLE
Documenting to rustup nightly

### ISSUE THREAD

**Issue by chitalian** [PyO3/pyo3#670]
Where can we put that we need the nightly build of rust?

This issue is a bit of an extension of [Issue #5](https://github.com/PyO3/pyo3/issues/5) but I still found myself needing to do
`rustup toolchain install nightly`
`rustup default nightly`
in order to get this module working. 

Can we make note of this in the Readme somewhere or is this issue already fixed?

**Comment by jakecurran** [comment]
If you already have a nightly toolchain installed, you can use `rustup override set nightly` to force nightly for your current directory only, or use `cargo +nightly ...` every time.

**Comment by chitalian** [comment]
gotcha, can I put this in the README? I found it helpful

**Comment by kngwyu** [comment]
I think [this official link](https://doc.rust-lang.org/book/appendix-07-nightly-rust.html?highlight=nightly#rustup-and-the-role-of-rust-nightly) is better.

**Comment by kngwyu** [comment]
https://github.com/PyO3/pyo3#usage
Now it has a link to the guide
