### ISSUE TITLE
Default implementation of `PyNativeType::py` is unsound.

### ISSUE THREAD

**Issue by nagisa** [PyO3/pyo3#671]
Using `PyNativeType::py` it is possible to obtain a `Python` instance inside an entirely unlocked interpreter, which could make python programs that rely on GIL for soundness, unsound.

The reproducer below relies on the fact that you can pass an value of `PyAny` into a `Python::allow_threads` closure and then obtain another instance of `Python` from previously captured `PyAny`.

### 🌍 Environment

 - Your operating system and version: not applicable
 - Your python version: not applicable
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: not applicable
 - Your rust version (`rustc --version`): not applicable
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: using 0.8.2, but there are no changes in the relevant area of code

### 💥 Reproducing

```rust
fn foo(py: Python, a: PyObject) {
    let any1 = a.cast_as::<pyo3::types::PyAny>(py).unwrap();
    let any2 = a.cast_as::<pyo3::types::PyAny>(py).unwrap();
    py.allow_threads(|| {
        let stray_py = pyo3::PyNativeType::py(any1);
        stray_py.allow_threads(|| {
            let stray_py = pyo3::PyNativeType::py(any2);
            stray_py.allow_threads(|| {
            });
        });
    })
}

let gil = pyo3::Python::acquire_gil();
let py = gil.python();
foo(py, py.None());
```

**Comment by kngwyu** [comment]
Thank you.
I made `PyAny` !Send in #655.
Can you reproduce this by the latest master?

**Comment by nagisa** [comment]
Yeah #655 seems to fix this.

**Comment by nagisa** [comment]
FWIW I think this deserves a rustsec issue and also perhaps we should cut a new release sooner rather than later.
