### ISSUE TITLE
A fix for rustc MacOS linking issue

### ISSUE THREAD

**Issue by jeff-davis** [PyO3/pyo3#677]
https://github.com/rust-lang/rust/pull/66204/

I filed that PR which would eliminate the need for the ``-unresolved dynamic_lookup`` to be specified for MacOS builds. Comments welcome.

**Comment by davidhewitt** [comment]
Unfortunately I see that ticket was closed, so I'm also going to close this one here.

It would be great to find a way to not need additional flags to build on MacOS. Please do keep us posted if you find a solution!
