### ISSUE TITLE
jemallocator & pyo3 ?

### ISSUE THREAD

**Issue by NotSqrt** [PyO3/pyo3#678]
Hello,

I'm trying to use jemallocator in my pyo3 extension (20% speed up in my `cargo test`, so very interesting !), but I couldn't get it to work:
https://github.com/gnzlbg/jemallocator/issues/142

My lib is based on https://github.com/PyO3/rust-numpy/tree/master/examples/simple-extension, 
and I followed instruction from https://crates.io/crates/jemallocator

Reproduction: https://github.com/NotSqrt/rust-numpy/commit/408a5469f5697f4dd0dd6ab57e0f3c38acca36a9

```bash
python3 setup.py develop
python3 -c "import rust_ext"
```
fails with:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/rust-numpy/examples/simple-extension/rust_ext/__init__.py", line 1, in <module>
    from .rust_ext import *  # noqa
ImportError: /home/user/rust-numpy/examples/simple-extension/rust_ext/rust_ext.cpython-36m-x86_64-linux-gnu.so: cannot allocate memory in static TLS block
```

Any tips ? Any idea whether it's even possible to change the allocator in a `cdylib` ?
Thanks !

**Comment by NotSqrt** [comment]
https://github.com/jemalloc/jemalloc/issues/937 seems related

**Comment by NotSqrt** [comment]
It seems `jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}` will be enough !

**Comment by kngwyu** [comment]
Thank you for sharing the workaround.
