### ISSUE TITLE
Drop support for python3.5

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3#685]
python3.5 has been "security fixes only" for a while: https://www.python.org/downloads/release/python-356/

Support for it should at some point be dropped.

There are 45 `cfg` gating on python3.6+ , 14 on 3.7+, and 9 on 3.8+, with differences in datetime, asyncio, modules, and the FFI. It would be nice to reduce complexity.

The last few PyPy releases have upgraded to 3.6.

**Comment by davidhewitt** [comment]
@kngwyu what's your opinion on this? If you're in favour of dropping support, I could prepare a quick PR sometime over the holidays.

**Comment by kngwyu** [comment]
I think we need to hear users' voices before dropping support.

**Comment by davidhewitt** [comment]
👍 do we have a channel for getting user feedback? The gitter? Wait to see if users respond on this ticket?

**Comment by programmerjake** [comment]
I think we shouldn't drop support for python 3.5 yet since it is the default Python 3 version on Ubuntu 16.04 which is still supported till April 2021.

**Comment by davidhewitt** [comment]
That's a good enough reason to me to keep 3.5 support for now!

**Comment by gilescope** [comment]
Push to close this issue out then?

**Comment by davidhewitt** [comment]
Agreed. We can open a new ticket after April 2021.

**Comment by rth** [comment]
> I think we shouldn't drop support for python 3.5 yet since it is the default Python 3 version on Ubuntu 16.04

At the same time, with Ubuntu 20.04 LTS released this April,  Ubuntu 16.04 LTS is now 3 LTS versions away. A limit has to be put somewhere. As far as I understand, current PyO3 users are not necessarily tied much to legacy software version (since they were happy to run on rust nightly until recently), and there isn't a huge user base yet.

 So I think it would make sense limiting to support to either 2 LTS Ubuntu versions or just follow CPython EOL (assuming it's compatible with PyPy releases). Supporting more has maintenance and development costs, particularly with Python 3.9 that would need to be supported from October.

**Comment by davidhewitt** [comment]
Numpy 1.19.0 dropped support for Python 3.5, so perhaps it's now already a time to reconsider whether we should continue supporting it.

I think we should have at least one version of pyo3 which compiles on stable Rust before we drop support, but I don't see harm in reopening this issue and potentially tagging it for `0.12`.

**Comment by althonos** [comment]
Python3.5 EOL is September 2020, so I think it's good if it can be supported it until then without effort. If it needs any additional effort, I see no problem in dropping it

**Comment by davidhewitt** [comment]
> Python3.5 EOL is September 2020

Interesting. Depending on how long we take to finish `0.12`, perhaps the version after that then would be closer to September. I'll leave in the `0.12` milestone for consideration and we can always push it back a version if things look likely to release before September.

**Comment by rth** [comment]
> Python3.5 EOL is September 2020

Could you provide a link to it? [PEP 478](https://www.python.org/dev/peps/pep-0478/) mentions as last security release 3.5.10 final: July 12, 2020 and I assume that also means EoL?

**Comment by althonos** [comment]
> > Python3.5 EOL is September 2020
> 
> Could you provide a link to it? [PEP 478](https://www.python.org/dev/peps/pep-0478/) mentions as last security release 3.5.10 final: July 12, 2020 and I assume that also means EoL?

https://devguide.python.org/#status-of-python-branches

By default, the EOL for a Python version is exactly 5 years after its first release, and Python 3.5 came out on 2015-09-13.

**Comment by davidhewitt** [comment]
Looks like eol is assumed to be 5 years after initial release unless it is announced otherwise:

https://endoflife.date/python

**Comment by davidhewitt** [comment]
As the 0.12 release is probably coming soon this month, I'm going to move this into the 0.13 milestone. As 0.13 will likely be after the eol date, I think we can definitely drop support for Python 3.5 as part of 0.13.
