### ISSUE TITLE
Release version including support for #[text_signature]

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#689]
I am ready to publish [simple-soft-float 0.1.0](https://salsa.debian.org/Kazan-team/simple-soft-float) 
 to crates.io but am blocked on needing a released version of PyO3 that includes support for
`#[text_signature]` #675

**Comment by kngwyu** [comment]
Released it now.

**Comment by programmerjake** [comment]
Published to crates.io: [simple-soft-float 0.1.0](https://crates.io/crates/simple-soft-float/0.1.0)
