### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#7]

**Comment by messense** [comment]
I think we could upload `cargo doc` generated documentation to `gh-pages` branch in Travis CI master branch build.

Or if we publish this crate to crates.io then we can simply use docs.rs: https://docs.rs/pyo3

**Comment by fafhrd91** [comment]
We need to write new documentation. Publishing is not a problem

**Comment by messense** [comment]
Yeah, after `pypt`r landed, it's getting a little confusing when to use `PyObject`, when to use `Py<'p, PyObject>'`, when to use `PyPtr<PyObjectMarker>` and when to use `pptr<'p>`.

Some documentation to clarify them would be great. Also the examples in `README.md` may need to be updated.

**Comment by fafhrd91** [comment]
@messense could you help me with documentation?

**Comment by messense** [comment]
Sure. So what do we want for documentation? I think we need to write a user guide and add more docs to APIs. For guide we need to make a outline.

**Comment by fafhrd91** [comment]
user guide and more docs for apis, sounds good

**Comment by messense** [comment]
I think [mdBook](https://github.com/azerupi/mdBook) could be a great choice to write user guide. I'll try it.

**Comment by messense** [comment]
I'd like to divide the user guide to the following chapters:

1. Overview: Very much like current `README.md`
2. Getting Started: A tutorial to create a simple project including implementing classes, methods, functions and hopefully object protocols as well as some error handling code.
3. Module: how to init a module and add setuptools support
4. Exception: how to define and use Python exceptions in Rust code and how to transform Rust erros to Python exceptions.
5. Function: how to write and register functions.
6. Class: how to write and register classes, how to implement object protocols on them.
7. Maybe more about object protocols, like `async`, `await` support

What do you think?

**Comment by fafhrd91** [comment]
very good plan. I like it.

**Comment by messense** [comment]
I'd like to make sure user guide examples actually compile, waiting for https://github.com/azerupi/mdBook/pull/340 to land.

**Comment by fafhrd91** [comment]
sure

**Comment by fafhrd91** [comment]
@messense if you have any docs, let's just commit. mdbook fix does not matter at the moment

**Comment by messense** [comment]
Didn't write any more docs when #41 was ongoing. I'll need to read through #42 then get back to this.

**Comment by messense** [comment]
Do we really need to reexport `Py_hash_t` and `Py_ssize_t`? They should be accessible throught `ffi::Py_hash_t` and `Py_ssize_t`.

Should we hide `argparse` module from API documentation? It seems not to be directly used by end user.

**Comment by fafhrd91** [comment]
Good point on both. I agree

**Comment by radhikasundararaman24** [comment]
Hello: Are you looking for some documentation help? I'm a programming technical writer and would be interested to know more about your documentation needs.

**Comment by konstin** [comment]
Closing in favor of #306
