### ISSUE TITLE
ImportError undefined symbol when loading .so calling Python from Rust

### ISSUE THREAD

**Issue by gdesmott** [PyO3/pyo3#700]
### 🌍 Environment

 - Your operating system and version: Fedora 31
 - Your python version: 3.7.5
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: dnf package
 - Your rust version (`rustc --version`): `rustc 1.42.0-nightly (0de96d37f 2019-12-19)`
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Reproduced with `0.8.4` and c8cb3adc23d297955bf8a08be19976fdb11e3a76

### 💥 Reproducing

You'll need to install Tensorflow and fetch my test code in order to reproduce:

- `pip install tensorflow==1.14.0`
- `git clone https://github.com/gdesmott/pyo3-bug.git`
- `cd pyo3-bug`
- `rustup override set nightly`

First check that `pyo3` is able to import Tensorflow from the Rust executable (`src/bin/test.rs`):
- `cargo run`
- TensorFlow should display some `FutureWarning` but you shouldn't get any error.

Now let's try to run the exact same code but from a `.so` file instead:

- `cargo build`
- `gcc test.c -ldl`
- `./a.out`

You should get this error:

```
Traceback (most recent call last):
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib64/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyExc_RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib64/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/cassidy/.local/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyExc_RuntimeError


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by davidhewitt** [comment]
The problem is that your `a.out` binary is not linked against Python, and so when the Python c extensions are being loaded they cannot find the Python C API symbols. We can see this from the output of `ldd`:

    $ ldd ./a.out
        linux-vdso.so.1 (0x00007fff9dbcf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff75d5e7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff75d1f6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff75d9ed000)

You have three options on how to solve this:
- Manually link in the python shared library by changing your `gcc` invocation:

       gcc ./test.c -ldl -Wl,--no-as-needed -lpython3.7m

- Manually add the python shared library to the global symbol table by opening it with `dlopen` before your other `dlopen` call:

       assert (dlopen("/usr/lib/x86_64-linux-gnu/libpython3.7m.so", RTLD_LAZY | RTLD_GLOBAL));
       handle = dlopen("./target/debug/libbadger.so", RTLD_LAZY);

- Link against the rust library, which will automatically pull in the correct python as a dependency:

       // test2.c
       void test_badger();

       int main (void) {
         test_badger ();
         return 0;
       }

   Compile `test2.c` with:

       gcc test2.c -L target/debug/ -lbadger -Wl,-rpath target/debug

The third option is probably best unless you absolutely must use runtime dynamic linking.

**Comment by gdesmott** [comment]
Thanks for your reply @davidhewitt.

Actually yes, I do need runtime dynamic linking. I'm implementing a GStreamer plugin in Rust which is built as a shared `.so`. So I'd need a way to force the linking on Python from the plugin itself, not the application. What would the right way to do that then?

**Comment by davidhewitt** [comment]
Ah, I see - in which case the second option is probably the way to go. If you call `dlopen` in your plugin initialisation code with the `RTLD_GLOBAL` flag then the Python library symbols should become accessible for python c extensions to load.

In Rust, I think it'll be something like this:

    extern {
        fn dlopen(filename: *const libc::c_char, flags: libc::c_int) -> *mut libc::c_void;
        fn dlclose(handle: *mut libc::c_void) -> libc::c_int;
    }

    const RTLD_GLOBAL: libc::c_int = 0x00100;
    const RTLD_LAZY: libc::c_int = 0x00001;

    // make sure this path is null-terminated
    const libpython: &'static str = "/path/to/libpython3.7m.so\0";
    let handle = dlopen(libpython.as_ptr(), RTLD_GLOBAL | RTLD_LAZY);
    assert!(!handle.is_null());

You'll need to make sure your Rust project is linking against libdl. (e.g. with a [links](https://doc.rust-lang.org/cargo/reference/manifest.html#the-links-field-optional) entry in your `Cargo.toml`)

**Comment by gdesmott** [comment]
Great, that works! Thank you so much for your help.

For the record here is the exact code I used:

```rust
fn init() {
    use libc;

    extern "C" {
        fn dlopen(filename: *const libc::c_char, flags: libc::c_int) -> *mut libc::c_void;
        fn dlclose(handle: *mut libc::c_void) -> libc::c_int;
    }

    const RTLD_GLOBAL: libc::c_int = 0x00100;
    const RTLD_LAZY: libc::c_int = 0x00001;

    // make sure this path is null-terminated
    const LIBPYTHON: &'static str = "/usr/lib64/libpython3.7m.so\0";
    unsafe {
        let handle = dlopen(LIBPYTHON.as_ptr() as *const i8, RTLD_GLOBAL | RTLD_LAZY);
        assert!(!handle.is_null());
    }
}
```
