### ISSUE TITLE
Add async example to guide

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#701]
It's not trivial to write an `await`-able object in Rust which behaves as Python expects. Should I add an example to the guide to show how to do this?

**Comment by LegNeato** [comment]
@davidhewitt yes please!

**Comment by tsturzl** [comment]
This would help me, right now I'm getting around this by spawning a thread in rust and then polling a channel for the thread's result on an interval to not block asyncio's event loop. It seems really dirty, and at this point it would almost seem as though running my Rust code as another service and communicating with it over a socket would be better. It would be nice if I could just build a wheel distribution and package it with my python than managing another system without doing anything really hacky.

**Comment by davidhewitt** [comment]
Thanks for the interest! A quick update for those watching:

At the moment I'm prioritising some other pieces in pyo3 - how we get to stable, improving APIs and fixing soundness issues. I plan to pick this ticket up after those are wrapped up. My hope would be to add first-class support for Python futures, either as part of the `pyo3` core or as a `pyo3-futures` crate.

If any interested community member wants to make this happen sooner, I'm happy to review code and mentor / bounce ideas off. I haven't thought about the implementation very much, though my knowledge of async in Python combined with the example of `wasm-bindgen-futures` is where I plan to start from.

**Comment by ThibaultLemaire** [comment]
In the meantime, if you're interested in async examples, take a look at @ChillFish8's [Async-PyO3-Examples](https://github.com/ChillFish8/Async-PyO3-Examples#async-pyo3-examples).

It has helped me a lot in understanding how Python's awaitable objects work, and how you can implement them in Rust.

**Comment by ThibaultLemaire** [comment]
> My hope would be to add first-class support for Python futures, either as part of the pyo3 core or as a pyo3-futures crate.

I'd like to take a stab at that. In fact I have some throw-away but promising code locally that let's Rust futures be driven by asyncio's loop.

Where do you want to continue this discussion @davidhewitt ?

**Comment by davidhewitt** [comment]
I would recommend checking out and giving feedback on [`pyo3-asyncio`](https://github.com/awestlake87/pyo3-asyncio), which @awestlake87 has built and is almost ready to share with everyone (pending a release of pyo3 master). See also #1274

**Comment by awestlake87** [comment]
Just to update people, I think it's likely that I'll merge [my PR to support other runtimes](https://github.com/awestlake87/pyo3-asyncio/pull/3) before the official release on crates.io. If you're thinking about trying it out in your projects in the meantime, I'd recommend using the `other-runtimes` branch for now.

**Comment by ThibaultLemaire** [comment]
OK, so, I decided to go my separate way and try and see how far I could push my idea before taking a look at what @awestlake87 had made to see if we would end up with something similar. I now have something working (which I'm publishing [here]() as is, until I find the time to write something cleaner), and I'll try to find the time to take a serious look at [`pyo3-asyncio`](https://github.com/awestlake87/pyo3-asyncio) and the discussions over at #1274.

(I am focusing solely on calling async Rust code from Python so I expect my scope to be much smaller of course.)

**Comment by davidhewitt** [comment]
This was merged in #1415. (Thanks all involved!)
