### ISSUE TITLE
Please add a working example for PyContextProtocol and PyIterProtocol

### ISSUE THREAD

**Issue by brmmm3** [PyO3/pyo3#707]
When I try to implement a context manager class with the following code:
#[pyclass]
struct Counter {
    exit_called: bool,
}

#[pyproto]
impl<'p> PyContextProtocol<'p> for Counter {
    fn __enter__(&mut self) -> PyResult<i32> {
        Ok(42)
    }

    fn __exit__(
        &mut self,
        ty: Option<&'p PyType>,
        _value: Option<&'p PyAny>,
        _traceback: Option<&'p PyAny>,
    ) -> PyResult<bool> {
        let gil = GILGuard::acquire();
        self.exit_called = true;
        if ty == Some(gil.python().get_type::<ValueError>()) {
            Ok(true)
        } else {
            Ok(false)
        }
    }
}

I get the following errors:
error[E0119]: conflicting implementations of trait `pyo3::class::context::PyContextEnterProtocolImpl` for type `Counter`:
   --> src/lib.rs:238:1
    |
238 | #[pyproto]
    | ^^^^^^^^^^
    |
    = note: conflicting implementation in crate `pyo3`:
            - impl<'p, T> pyo3::class::context::PyContextEnterProtocolImpl for T
              where T: pyo3::class::context::PyContextProtocol<'p>;

error[E0119]: conflicting implementations of trait `pyo3::class::context::PyContextExitProtocolImpl` for type `Counter`:
   --> src/lib.rs:238:1
    |
238 | #[pyproto]
    | ^^^^^^^^^^
    |
    = note: conflicting implementation in crate `pyo3`:
            - impl<'p, T> pyo3::class::context::PyContextExitProtocolImpl for T
              where T: pyo3::class::context::PyContextProtocol<'p>;

It would be nice to have a working example for PyContextProtocol and PyIterProtocol in examples.

**Comment by kngwyu** [comment]
They need `#![feature(specialization)]`
