### ISSUE TITLE
Failing to make module on MacOS inside Blender

### ISSUE THREAD

**Issue by diegogangl** [PyO3/pyo3#709]
## 🐛 Bug Reports

Hi guys, I'm working on a Python module to be used in a Blender addon. I'm getting a weird panic with MacOS Catalina. The weird thing about it is that if I run Blender from the command line it loads fine, but if I run it from the icon/dock something in `pyo3::derive_utils::make_module` fails.

Python version is 3.7.4 bundled with Blender, and I have confirmed that it's the same version running on both situations. I don't know much about MacOS but there shouldn't be any difference on how it's run, right? Could enviroment variables make pyo3 fail?

Here's the backtrace (`pangu.so` is my module)

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6a0a97fa __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6a16bbc1 pthread_kill + 432
2   libsystem_c.dylib             	0x00007fff6a030ab6 __abort + 139
3   libsystem_c.dylib             	0x00007fff6a030a2b abort + 135
4   pangu.so                      	0x0000000134e33939 std::sys::unix::abort_internal::h6717f22b70679bc4 + 9
5   pangu.so                      	0x0000000134e31c70 std::sys_common::util::abort::h1dd17fd3c0d65cf7 + 80
6   pangu.so                      	0x0000000134e32c53 rust_panic + 99
7   pangu.so                      	0x0000000134e32bed std::panicking::rust_panic_with_hook::h4a09e69cd55e5140 + 589
8   pangu.so                      	0x0000000134e32689 rust_begin_unwind + 169
9   pangu.so                      	0x0000000134e5162c core::panicking::panic_fmt::h504df364bc4c5c34 + 44
10  pangu.so                      	0x0000000134e51709 core::result::unwrap_failed::h6f0ff48485ebd7be + 121
11  pangu.so                      	0x0000000134e08a6a pangu::pangu::hf0851a193c56c6ff + 218
12  pangu.so                      	0x0000000134e02d83 pyo3::derive_utils::make_module::h9760a9aa3677d944 + 147
13  org.blenderfoundation.blender 	0x000000010ec53d83 _PyImport_LoadDynamicModuleWithSpec + 579
14  org.blenderfoundation.blender 	0x000000010ec537d3 _imp_create_dynamic + 355
15  org.blenderfoundation.blender 	0x000000010eb5cfcd _PyMethodDef_RawFastCallDict + 605
16  org.blenderfoundation.blender 	0x000000010eb5ca78 PyCFunction_Call + 200
```

### 🌍 Environment

 - Your operating system and version: MacOS Catalina 10.15.2
 - Your python version: 3.7.4 (bundled with Blender)
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: No, it's bundled with Blender
 - Your rust version (`rustc --version`):  1.41.0-nightly
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` 0.8.2

**Comment by davidhewitt** [comment]
@diegogangl sorry for the slow response. Are you able to provide a minimal example of a pyo3 extension module which exhibits this problem in blender?

**Comment by diegogangl** [comment]
Hey, no problem! I should be apologizing, I found out this was an issue with launchd not giving my logger an stdout (or something like that) and I forgot to close here.
