### ISSUE TITLE
Create a Rust struct from a Python object

### ISSUE THREAD

**Issue by danielvschoor** [PyO3/pyo3#710]
I'm sorry if this has been answered somewhere, or explained in the documentation, if it has, please point me in the right direction.

I cannot seem to figure out a way to either access a Python object (passed as an argument to a Rust function)'s attributes in Rust or to create new struct from the Python object.
For example, I have an already initialized Python object (and I can't create it in Rust):
```python
class Unit:
	def __init__(self, armor, health, weapon):
		self._armor = armor
		self._health = health
		self._weapon = weapon
unit = Unit(10,100, Weapon('ground'))
```
which I would then pass to Rust. My questions are:

 1. How do I access the attributes like `_armor` from a Rust function/`pymethod`?
 2. Do I need to create a `#[pyclass]` `Unit` struct in Rust and if so, how would I map the attributes from the Python object to the struct's variables? How would I deal with an attribute that is an object as well (like `Weapon`)?
 3. If I need to pass the object as `PyAny` or `PyObject`, how would I implement the `FromPyObject` trait for the non-`#[pyclass]` `Unit` struct to map the attributes?
 4. Extra question: I have enums in Python as well enums in Rust that are identical, is it possible to pass the Python enum and match it to the relevant Rust enum?
 
 This is for creating an extension module for Python. 
 Please let me know if my questions are not clear enough

**Comment by kngwyu** [comment]
Just call it using, say, [PyModule::call](https://docs.rs/pyo3/0.8.5/pyo3/prelude/struct.PyModule.html#method.call)

**Comment by danielvschoor** [comment]
Thank you for your response. I ended up using 

```rust
    fn extract(ob: &'source PyAny) -> PyResult<Unit> {
        unsafe {
            let py = Python::assume_gil_acquired();
            let obj = ob.to_object(py);
            Ok(Self {
                x: obj.getattr(py, "armor")?.extract(py)?,
                y: obj.getattr(py, "health")?.extract(py)?,
                etc.``` 

which I saw on [gitter](https://gitter.im/PyO3/Lobby)
