### ISSUE TITLE
PySet is not iterable

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/pyo3#715]
As per [the docs](https://docs.rs/pyo3/0.8.5/pyo3/types/struct.PySet.html) (and reproduced with pyo3 v0.8.5, python 3.7, ubuntu) `PySet` is not an iterator.

Therefore `for element in my_set {` throws an error.

I tried wrapping the set in `PyList::new` but got `the trait std::iter::ExactSizeIterator is not implemented for &pyo3::types::PySet`.

Is there a good reason to prevent iteration over sets? If not could it be added, also is there a workaround for now?

**Comment by davidhewitt** [comment]
It seems to me that it is reasonable for `PySet` to implement this. (Have opened a PR.)

For now you can use `for element in my_set.iter()? {` thanks to the `ObjectProtocol` trait.

**Comment by samuelcolvin** [comment]
`PySet.iter` isn't documented as it is on `PyList`
