### ISSUE TITLE
Is it possible to run multiple instances of the interpreter in parallel in different threads? (python in rust)

### ISSUE THREAD

**Issue by kajogo777** [PyO3/pyo3#728]
I noticed even if I spawn threads, then change sys.path, it ends up having the same value in both threads!

**Comment by kajogo777** [comment]
The idea is to have an isolated Python runtime and GIL for every thread spawned by Rust

**Comment by kngwyu** [comment]
> The idea is to have an isolated Python runtime and GIL for every thread spawned by Rust

It is not impossible... but unfortunately, I think it's really difficult in the current implementation :roll_eyes:

**Comment by kajogo777** [comment]
I tried to dig through the code and found out the lock is global

Thanks for your answer!
