### ISSUE TITLE
Replace FromPyObject with std::convert::TryFrom

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#73]
@messense objections?

**Comment by messense** [comment]
That would be awesome. Utilize std traits should reduce learning curve.

**Comment by fafhrd91** [comment]
It is not possible to implement `TryFrom` for `Vec<T> where T: TryFrom<PyObjectRef>`
So it is pretty useless.

**Comment by fafhrd91** [comment]
add added `TryFrom` implementation, but we can not drop `FromPyObject` because of sequence conversion.
