### ISSUE TITLE
AsPyRef is stripped down, not in changelog

### ISSUE THREAD

**Issue by birkenfeld** [PyO3/pyo3#738]
The `AsPyRef` trait was stripped down considerably; methods `with`, `with_mut`, `into_py`, `into_mut_py` are gone.

The changelog should mention how to rewrite code using them, or if removal was an oversight they should be reinstated.

**Comment by kngwyu** [comment]
Thank you.
Now I'm not sure *why they exist* so need to check them. 
But anyway I will fix it until the non-alpha release.

**Comment by birkenfeld** [comment]
I was using them to access instances of a Rust object that were behind a `Py<T>` pointer.

If there is better or newer way, let me know :)

**Comment by birkenfeld** [comment]
Any news on this?

**Comment by davidhewitt** [comment]
There's a soundness problem; because `Py<T>` is a shared pointer, we need to be careful about getting `&mut T` from a `Py<T>`.

I think in the we really need to have `RefCell`-like semantics, where `Py<T>` will have `.borrow()`, `.borrow_mut()`, `.try_borrow()` and `.try_borrow_mut()` methods.

**Comment by kngwyu** [comment]
Just a reference for readers: https://docs.rs/pyo3/0.8.5/pyo3/trait.AsPyRef.html
@birkenfeld 
I'm OK to retrieve `with` and `with_mut`. Are they sufficient?
`into_py` has a confusing name and I think it should be under another trait.

@davidhewitt 
`Py<T>` can handle all Python pointers(including `PyDict` or so) and I'd rather enhance `PyClassShell` in that direction.

**Comment by birkenfeld** [comment]
@davidhewitt you're right; this cannot be allowed like it was. A RefCell like functionality with runtime checking would be very nice.

@kngwyu `with` is probably also served by `as_ref`? `with_mut` needs a safer alternative, "somehow" :)

**Comment by kngwyu** [comment]
Now `AsPyRef::as_ref` is changed to return `&PyCell`.
For PyCell, please see [the guide](https://pyo3.rs/master/class.html#pycell-and-interior-mutability).

**Comment by birkenfeld** [comment]
Great, thanks!
