### ISSUE TITLE
Rust ICE when attribute is escaped like r#type

### ISSUE THREAD

**Issue by ethanhs** [PyO3/pyo3#743]
### 💥 Reproducing

If you have code like

```rust
#[pyclass]
struct Test {
    #[pyo3(get, set)]
    r#type: i64
}
```
Rust ICEs:
```
  Compiling twitter v0.1.0 (C:\Users\ethanhs\abserde\build\abserde\twitter)
thread 'rustc' panicked at '`"set_r#type"` is not a valid identifier', src\librustc_expand\proc_macro_server.rs:333:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (b5a3341f1 2020-01-20) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 -C lto -C codegen-units=1 -C target-cpu=native --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `twitter`.

To learn more, run the command again with --verbose.
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release --`

🔗 Found pyo3 bindings
🐍 Found CPython 3.7 at C:\Users\ethanhs\AppData\Local\pypoetry\Cache\virtualenvs\abserde-1LDqkpmO-py3.7\Scripts\python.exe
error: custom attribute panicked
   --> src\lib.rs:484:1
    |
484 | #[pyclass(dict)]
    | ^^^^^^^^^^^^^^^^
    |
    = help: message: `"set_r#type"` is not a valid identifier


error: aborting due to previous error
```

It seems that it can't handle identifiers like `set_r#type`. I will report the ICE upstream but I think pyo3 should be able to support escaped keywords as attributes.

**Comment by davidhewitt** [comment]
Thanks, does indeed look like a bug in our proc macro code. I'll push a fix soon.

**Comment by ethanhs** [comment]
That would great! Thanks.

Do you know if it will make it into 0.9.0? I'm currently pulling from master but I'd like to use a release :)

**Comment by davidhewitt** [comment]
That would be one for @kngwyu. He's quite busy atm so I'm not sure exactly when he plans to release `0.9.0`.

I'm expecting to push the fix by the end of the weekend, which I would guess is before the release is done.

**Comment by kngwyu** [comment]
@ethanhs 
Thank you for reporting that!
@davidhewitt 
Thank you for the fix!

> Do you know if it will make it into 0.9.0? I'm currently pulling from master but I'd like to use a release :)

0.9.0-alpha.1 is already released(just in case you didn't notice it...), but for non-alpha release, we have a [milestone](https://github.com/PyO3/pyo3/milestone/3).
