### ISSUE TITLE
Implement mathematical operators for `PyLong`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#748]
e.g. `PyLong + PyLong`, `PyLong << PyLong`.

Seems like because `&'a PyLong` has a GIL reference it is perfectly reasonable to do this.

**Comment by pganssle** [comment]
I can sorta see why this would seem appealing to do for the sake of completeness, but I think that manipulating `PyLong` objects in Rust verges on being an anti-pattern, particularly when we already have a dependency on `num-bigint`.

I could be wrong in how people intend to use PyO3, but when I recommend it to people, I usually say that it's useful for:

1. Writing Python bindings for Rust libraries, in which case you really are just translating the output of the Rust library into Python types, and shouldn't need to do any manipulations on the numbers.

2. Speeding up the slow parts of your Python, in which case my intuition is that it usually makes sense to convert from `PyLong` to Rust-native integer types at the input, do the numerical manipulation in Rust, then convert back to `PyLong` at the end.
  I suppose in some ways it depends on the relative costs of wrapping and unwrapping Python numeric types vs the savings of doing mathematical manipulations in Rust. It's probably worth doing some benchmarks to see if we can come up with any common-ish scenarios where direct mathematics on `PyLong` objects would be faster.

This could all just be my lack of imagination, though. The same arguments might be made for doing all math in C when writing C Python extensions, but the [number protocol](https://docs.python.org/3/c-api/number.html) does exist for doing this sort of thing, so evidently it is useful in at least some cases.

Note: I'm not saying that it should be impossible to do this sort of thing, but if it's *usually* a bad idea to do it, we may want to try to make the ergonomics proportional to how frequently it *should* be done. If a lot of people are just throwing types in their function signatures until something compiles and using `BigInt` or `i64` would almost always be faster and better than `&'p PyLong` when doing mathematical operations, it makes sense to not implement the mathematical operators even if the semantics would be completely unambiguous and natural.

**Comment by davidhewitt** [comment]
I agree with what you're saying. However I'm not sure it's possible to convert `BigInt` to `&'p PyLong` via the Python C Api, except possibly via string serialisation. I don't claim to know whether it faster than just working directly with `&'p PyLong` objects once that overhead is taken into account - probably it still is.

FWIW this question came up in Gitter where a user had a "go big int" in `[u8]` form and wanted to convert it to `PyLong`, via `for byte in bytes: result = result << 8 + byte`

C++'s `pybind11` actually implements these operators for the equivalent of pyo3's `PyAny`: https://github.com/pybind/pybind11/blob/4f72ef846fe8453596230ac285eeaa0ce3278bb4/include/pybind11/pytypes.h#L125-L144

I guess if we did similar for pyo3, these operators would all return some kind of `PyResult`.

**Comment by programmerjake** [comment]
@davidhewitt see BigInt conversion code:

https://github.com/PyO3/pyo3/blob/fb17d5e82f302f09b6611ac608edd1ce37504703/src/types/num.rs#L273-L326

**Comment by davidhewitt** [comment]
👍 thanks, I was not aware that existed!

**Comment by davidhewitt** [comment]
For the moment I'm going to back out on this idea - if anyone else comes asking for it with a use case then we can revisit.
