### ISSUE TITLE
Importing Python random lead to an error

### ISSUE THREAD

**Issue by maximdanilchenko** [PyO3/pyo3#762]
Hi!

### 🌍 Environment

 - Your operating system and version:

macOS Mojave 10.14.6
 - Your python version: 

Tested on 3.8.1 and 3.6.10
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?:

I use pyenv
 - Your rust version (`rustc --version`):

rustc 1.43.0-nightly (58b834344 2020-02-05)
 - Are you using the latest pyo3 version? Have you tried using latest master?

0.8.4 and master both have this issue 

### 💥 Reproducing

```rust
fn main(){
    let gil = Python::acquire_gil();
    let py = gil.python();
    match py.import("random") {
            Err(e) => e.print(py),
            Ok(x) => {},
        }
}
```

```
Traceback (most recent call last):
  File "/Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: dlopen(/Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so, 2): Symbol not found: __PyLong_GCD
  Referenced from: /Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/maksim.danilchenko/.pyenv/versions/3.6.10/lib/python3.6/lib-dynload/math.cpython-36m-darwin.so
```

**Comment by maximdanilchenko** [comment]
https://github.com/PyO3/pyo3/issues/742#issuecomment-577332616 - fixes it, but anyway it is not common way to Install pyenv:)

**Comment by kngwyu** [comment]
Thank you!
I'll add a note for this on README and the guide.

**Comment by movermeyer** [comment]
It may be obvious, but this isn't limited to `random`. You can also reproduce it with `datetime`, and `math`.

**Comment by kngwyu** [comment]
I'm still not sure how to deal with pyenv problem.
@movermeyer 
If you have any idea, please comment to #763

**Comment by davidhewitt** [comment]
I am wondering whether it's possible to detect a misconfigured `pyenv` in `build.rs`.

I have MBP I can use to test sometime. No promises on exactly when.

**Comment by ethanhs** [comment]
The sysconfig module `CONFIG_ARGS` variable has the command line, so it seems simple to check if that contains "--enable-shared"
