### ISSUE TITLE
persistent PyModule and the GilGuard

### ISSUE THREAD

**Issue by mikedilger** [PyO3/pyo3#774]
I'm trying to better understand how to use a PyModule that keeps persistant data that I call into from time to time from rust.  I've got it working currently w/o persistant data (AFAIK), but everytime I need to call into it I do the following

````rust
let gil = Python::acquire_gil();
let py = gil.python();
PyModule::from_code(...)
// then I call the function here
````

I'm not sure if the PyModule keeps any state as it is being recreated every time I call it (I suppose I could test, I presume it's not)

If I create the PyModule and just hang onto it, the GILGuard must remain.  But I don't want to keep the GIL locked.

Any advice for this situation?  Thanks.

**Comment by mikedilger** [comment]
It does seem to be persisting state, even though we rebuild the PyModule from code every time.  So that's interesting.  I'm still not sure if this is how I should be structuring my code.

On shutdown, the __del__ functions are not getting run on python objects.  Is there something I need to do to get it to shutdown cleanly?

**Comment by kngwyu** [comment]
(Though it's not persistent) We have `Py` wrapper for 'not-GIL-bounded' Python objects.
```rust
let module: Py<PyModule> = {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let mod_ = PyModule::from_code(...);
    mod_.into() // master
    // unsafe { Py::from_owned_pointer(mod.as_ptr()) } // for released version
};
```
`module` is reased when another `GILGuard` is released.

**Comment by davidhewitt** [comment]
I'm not sure whether the python interpreter will cache the module when built in this way.

> I'm still not sure if this is how I should be structuring my code.

What are you trying to do? Perhaps we can advise how to structure your code to achieve what you want.

**Comment by mikedilger** [comment]
Thanks for the replies.  I've got something working, but I think it's not good as it stands.

I'm needing to send firebase messages to IOS and Android phones using google's firebase API from a long running rust server process running as a production service.  Google has complicated their API to the level that you practically need to use their libraries at this point, so I've moved off of their deprecated web API and am using their python library "firebase-admin" because python is my second favorite language (I might have to use go or java if this won't work).

This library has an `initialize_app()` function and a `delete_app()` function and runs multithreaded and is not `pickle`able. I am currently creating the module, initializing it, sending messages, deleting it, and letting the module fall out of scope... for every message sent.  That works, but seems abusive of the underlying API, OAuth2, etc.

If I do what @kngwyu shows, might I run into deadlocks with the GIL?  Might the module drop out of scope at seemingly random times as other code paths interact with the GIL?  A couple years ago when using rust and python together with a previous crate I had exactly that problem.  I locked the GIL in my code longterm thinking I was the only one, only to discover the OpenSSL system libraries call into python and also attempt to use the GIL.

If pyo3 is not ready for this kind of use, that would also be good information to have.  This is for a live in-production system and I'm starting to consider using another language (node.js, java, python, go, and .NET are the options available).

**Comment by kngwyu** [comment]
>  Might the module drop out of scope at seemingly random times as other code paths interact with the GIL? 

No.  Module is released after `Py<PyModule>` drops and another `GILGuard` is released.

**Comment by pganssle** [comment]
> On shutdown, the `__del__` functions are not getting run on python objects. Is there something I need to do to get it to shutdown cleanly?

By the way, to be clear, `__del__` is not guaranteed to be called, and you should almost certainly not be implementing `__del__`. I imagine that's expected and not necessarily related to any caching behavior or anything PyO3 is doing.

**Comment by mikedilger** [comment]
> No. Module is released after `Py<PyModule>` drops and another `GILGuard` is released.

Oh. That makes more sense than what I was thinking.

> By the way, to be clear, `__del__` is not guaranteed to be called, and you should almost certainly not be implementing `__del__`. I imagine that's expected and not necessarily related to any caching behavior or anything PyO3 is doing.

Did not know that.

I suppose I'll get a `Py<PyModule>` then and keep it.  Thanks for all the advice.

**Comment by davidhewitt** [comment]
Anything else you want from us on this topic? Otherwise I suggest you close this ticket and join us on the Gitter channel. There's a lot more devs than just us maintainers there so you'll get faster answers to your questions :smile:
