### ISSUE TITLE
PyBuffer::release calls ffi::PyBuffer_Release twice on the same buffer

### ISSUE THREAD

**Issue by oconnor663** [PyO3/pyo3#776]
The `PyBuffer::release` method calls `ffi::PyBuffer_Release` internally. Because it takes `self` by value, it then immediately drops `self`, and `PyBuffer::drop` calls `ffi::PyBuffer_Release` again. I think this kind of defeats the purpose of `release`, which is allowing the caller to pass in their `py` argument to avoid re-acquiring the GIL. More importantly, it looks like it violates the requirements described in Python's [Buffer Protocol docs](https://docs.python.org/3/c-api/buffer.html):

> Successful calls to `PyObject_GetBuffer()` must be paired with calls to `PyBuffer_Release()`, similar to `malloc()` and `free()`. Thus, after the consumer is done with the buffer, `PyBuffer_Release()` must be called exactly once.

Should this be fixed with `mem::forget` or similar?

**Comment by davidhewitt** [comment]
Thanks for the catch. Did you come across this in a crash or some other repro we can use to make a test?

I would probably suggest just calling `std::mem::drop(self)` in `PyBuffer::release` to be explicit.

**Comment by oconnor663** [comment]
I only saw it reading the code. As far as I can tell, it does not trigger a crash. Looking at the upstream CPython source, [here's what I see](https://github.com/python/cpython/blob/master/Objects/abstract.c#L726-L738):

```c
void
PyBuffer_Release(Py_buffer *view)
{
    PyObject *obj = view->obj;
    PyBufferProcs *pb;
    if (obj == NULL)
        return;
    pb = Py_TYPE(obj)->tp_as_buffer;
    if (pb && pb->bf_releasebuffer)
        pb->bf_releasebuffer(obj, view);
    view->obj = NULL;
    Py_DECREF(obj);
}
```

So it looks like `view->obj` gets nulled out, which would cause the second call to short-circuit rather than doing anything explosive. The Python docs make it sound like we shouldn't rely on this always being the case, but I guess I'd be surprised if they changed it. I have no idea what PyPy does.

Still, it seems like the purpose of `release` is to avoid the performance hit of `Python::acquire_gil()` in the destructor? If we call `mem::drop`, we'll still be paying that cost. Or is that cheaper than I think it is?

**Comment by oconnor663** [comment]
Just put up an example fix. Not sure how I would test this though.

**Comment by davidhewitt** [comment]
Thanks very much for providing the PR. Have followed up on that thread.
