### ISSUE TITLE
Simplify `FromPyPointer`

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#781]
There are so many methods in this trait. Is there a reason why we don't just have 

    unsafe fn from_owned_ptr(py: Python<'p>, ptr: *mut ffi::PyObject) -> PyResult<&'p Self>;
    unsafe fn from_borrowed_ptr(py: Python<'p>, ptr: *mut ffi::PyObject) -> PyResult<&'p Self>;

As the only trait method. And then just let users choose if they want to `.ok()`, `.unwrap()`, or `.expect()` this, instead of all the `_or_opt`, `_or_panic` etc.

_Originally posted by @davidhewitt in #770_

**Comment by kngwyu** [comment]
We use a special panic implementation that calls `ffi::PyErr_Print` so I'd rather remove only `from_owned_ptr_or_opt`.

**Comment by davidhewitt** [comment]
Ok. I think after #492 is addressed we will probably find that the custom panic implementation is not necessary. So let's wait with this until #492 is done.

**Comment by davidhewitt** [comment]
`FromPyPointer` has been removed with the GIL Refs.
