### ISSUE TITLE
Implementation of PyLayout::get_ptr for native types is broken

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#782]
It's returning the address of the local variable `self`, which then is destroyed when the function returns:

https://github.com/PyO3/pyo3/blob/fee755adbea01504d12cd858e2705608c10163a4/src/pycell.rs#L28-L30

Several of the other implementations appear to be broken in the same way.

Demo code:
```rust
pub struct S(u64);
pub struct PyAny;

impl S {
    pub unsafe fn get_ptr(&self) -> *mut PyAny {
        // body copied from implementations of PyLayout::get_ptr
        (&self) as *const &Self as *const _ as *mut _
    }
}

fn main() {
    let a = [S(0), S(0)];
    for i in &a {
        let i: &S = i; // i is of type `&S`
        // note objects' address is different
        dbg!(i as *const _);
        // totally broken: note same address printed for different objects
        // also, address computed is before the beginning of either object
        dbg!(unsafe { i.get_ptr() });
    }
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=a3dcd56c0819933eb33f2fc09c4d048b))

Output:

```
   Compiling playground v0.0.1 (/playground)
    Finished release [optimized] target(s) in 0.45s
     Running `target/release/playground`
[src/main.rs:16] i as *const _ = 0x00007ffe69ee9cf0
[src/main.rs:19] unsafe { i.get_ptr() } = 0x00007ffe69ee9ce8
[src/main.rs:16] i as *const _ = 0x00007ffe69ee9cf8
[src/main.rs:19] unsafe { i.get_ptr() } = 0x00007ffe69ee9ce8

```

**Comment by programmerjake** [comment]
This can be regression tested for by seeing if `get_ptr()` returns an in-bounds pointer.

**Comment by davidhewitt** [comment]
Thanks for reporting.

I'm a little concerned that the existing regression tests did not pick this up. From what you're showing above, _any_ test that exercises this code reads the wrong memory, so I would hope that at least one test would have gone awry as a result..

**Comment by kngwyu** [comment]
The key point is `PyCell` is always on Python heap.
So `&PyCell` **always refers an address of Python heap**.

**Comment by kngwyu** [comment]
The problem is `&PyCell` simply a pointer but `&PyAny` is a pointer to a pointer, so when trying to make them have the same method, this kind of confusion happens.
