### ISSUE TITLE
Restore support for `&Class` and `&mut Class` as arguments

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#786]
> We can't implement FromPyObject for them. You can use PyRef<T> and PyRefMut<T> as arguments.

Agreed we can't implement `FromPyObject` for them. It would be nice if we can find another way for the generated wrappers to support `&Class` and `&mut Class` arguments - by calling `.try_borrow()` in the wrapper, perhaps, like we can do for `&self`.

_Originally posted by @davidhewitt in https://github.com/PyO3/pyo3/issues/785#issuecomment-593813961_

**Comment by kngwyu** [comment]
I'm experimenting an idea to change our generated method call(`_slf.#fname(#name1, #name2, ...)` to `_slf.#fname(&*#name1, &*#name2, ...)` only when an arg(e.g., `#name1`) has a reference type.
Though I'm not sure it's possible now :thinking:
