### ISSUE TITLE
Argument specification by function attribute can be ambiguous

### ISSUE THREAD

**Issue by kngwyu** [PyO3/pyo3#794]
For example, we can do 
```rust
    #[args(a, "*", c = 3)]
    fn get&self, a: i32, b: i32, c: i32) -> PyResult<i32> { ... }
```
, where the position of separator is ambiguous.
And it's also problematic that here we can use unrelated idents like
```rust
    #[args(a, "*", d = 3)]
    fn get&self, a: i32, b: i32, c: i32) -> PyResult<i32> { ... }
```

**Comment by davidhewitt** [comment]
Fixed by the new `#[pyo3(signature = (...)]` option which replaces `#[args]` and doesn't allow for ambiguity.
