### ISSUE TITLE
Translating futures into generators

### ISSUE THREAD

**Issue by Michael-F-Bryan** [PyO3/pyo3#80]
What are your thoughts on being able to translate a future into something like a python generator or async function? 

It'd probably be tricky because of lifetimes and cpython interpreter internals, but I reckon having a way to do asynchronous things transparently between Rust and Python would be pretty cool.

**Comment by fafhrd91** [comment]
Is this https://github.com/PyO3/tokio what you are talking about?

**Comment by Michael-F-Bryan** [comment]
Does that allow you to convert a normal Rust function returning a `Future` into a python coroutine? I think PyO3/tokio is more concerned with creating an async event loop in Rust and dealing with Python coroutines, whereas I'm talking about the opposite direction.

Perhaps it may be better to wait for [async/await and generators][aa] to become less experimental and on the path towards stabilization though...

[aa]: https://internals.rust-lang.org/t/help-test-async-await-generators-coroutines/5835/29

**Comment by fafhrd91** [comment]
Yes, you can convert rust's future to python async function. And remember you still need event loop to run async python and async rust and to be able to run both in same thread you need pyo3/tokio

**Comment by Michael-F-Bryan** [comment]
That's awesome! It looks like the feature already exists so I'll close this issue. It might be a good idea to mention that in the user guide, but it's great that something like this already exists. 

The use case I was thinking of is where you might have some Python code which spins off a bunch of really expensive Rust functions (say you're doing some numerical calculations or whatever), then it can periodically `poll()` the Rust future to see if it's still running, updating some sort of progress bar or updating a GUI in the meantime.
