### ISSUE TITLE
Expose python version for cfg()

### ISSUE THREAD

**Issue by ijl** [PyO3/pyo3#803]
pyo3 uses `[cfg(Py_3_6)]` etc., which is set in `build.rs` as `println!("cargo:rustc-cfg=Py_3_...`. Could this exposed to projects that use pyo3? There is a note in the file about being able to use flags to read these values, but that's left from cpython-rust some time ago and doesn't seem to work.

**Comment by pganssle** [comment]
IIRC there wasn't an easy way to do this at compile time when I wanted to do it for the test module in Python, so I ended up passing it in the config files [via `setup.py`](https://github.com/PyO3/pyo3/blob/759dbeaed79907b7b9a8a406b5e0f4bcdebc512c/examples/rustapi_module/setup.py#L59-L70).

That was added in #200, but the reasoning isn't obvious in that ticket. I don't know enough about this sort of thing to know if there's a better solution, but when I looked into it, those `cfg` flags are set by the flags passed to `rustc`, and PyO3 generates them for its own invocation in `build.rs`. IIRC I couldn't come up with a good way to expose that information to downstream projects at compile time, but I agree that it would be useful if it's possible.

**Comment by ijl** [comment]
Ok, maybe it'd be appropriate to build into maturin. That invokes rustc (and can set cfg) and already has the information available from its checks on the python environment.

**Comment by davidhewitt** [comment]
... should I move this ticket to maturin?

**Comment by ijl** [comment]
I looked into it and there's no way for another crate to specify this to another crate. It must be done through build.rs in the crate using pyo3. It would be best I think to specify a recipe of ~20 lines rather than try to create an API through env vars as cpython-rust does.

**Comment by kngwyu** [comment]
>  It would be best I think to specify a recipe of ~20 lines rather than try to create an API through env vars as cpython-rust does.

I think it's good to create a separate crate and use it from maturin and pyo3's build.rs
