### ISSUE TITLE
release non-alpha version of 0.9

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#808]
release non-alpha version of 0.9

**Comment by kngwyu** [comment]
https://github.com/PyO3/pyo3/pull/797#issuecomment-596486595

... but it's OK to release 0.9 soon since it looks we can't merge #797 now

**Comment by davidhewitt** [comment]
Yes I think even after we merge we might want time to adjust the implementation. I'm happy to wait for 0.10 for a while for that.

**Comment by kngwyu** [comment]
OK, then I'll release 0.9 after fixing the test breakage in the latest nightly
