### ISSUE TITLE
[Question] Function returning float or int

### ISSUE THREAD

**Issue by apcamargo** [PyO3/pyo3#815]
I'm writing a function that counts the number of words in a text. Depending on a boolean argument, the function can return absolute or relative counts (int or float, respectively).

If this was a pure Rust function, I could just use an enum:
```rust
enum FloatOrInt {
    Int(i32),
    Float(f64)
}
```

However, there's no way of using this strategy when developing a Python function with PyO3.

Is there any way of writing a Python function that can return a int or a float, depending on a boolean input?

Thanks!

**Comment by kngwyu** [comment]
Please use `PyObject` as return type, like:
```rust
#[pyfunction]
fn float_or_int(py: Python, is_float: bool) -> PyObject {
    if is_float {
        0.0f32.into_py(py)
    } else {
        0.into_py(py)
    }
}
```

**Comment by davidhewitt** [comment]
It would be worth noting that it's quite common in Rust to just make these two different functions, e.g. `count` and `count_relative`, instead of overloading the return type like you suggest.

**Comment by apcamargo** [comment]
@davidhewitt But in case I want to expose a single function to Python I would have to write a third functionthat wraps the other two, right? In this case, I'd still have to return a int or float.

**Comment by davidhewitt** [comment]
Yes, if you only want a single function in Python then you would have to wrap the other two. Or just expose two functions to Python ;)
