### ISSUE TITLE
initialize_type_object and non null terminated description str

### ISSUE THREAD

**Issue by tmontaigu** [PyO3/pyo3#821]
I am opening an issue here, but i don't know if this should have been posted on rust-numpy instead.
as its a probem between rust-numpy and pyo3.

While trying rust-numpy I encountered a bug which made rust  panic with:
`thread '<unnamed>' panicked at 'An error occurred while initializing class SliceBox'`

I found than an issue is open at https://github.com/PyO3/rust-numpy/issues/97

So I tried to look into it and so I cloned the rust-numpy repo, ran :
```
cargo +nightly test
test result: ok. 35 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

```
cargo +nightly test --release 

---- forder_into_pyarray stdout ----
thread 'forder_into_pyarray' panicked at 'An error occurred while initializing class SliceBox', tests\to_py.rs:1:1

[...omitted...]
---- usize_dtype stdout ----
thread 'usize_dtype' panicked at 'An error occurred while initializing class SliceBox', tests\to_py.rs:1:1

test result: FAILED. 8 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out
```
I think the problem comes from 
https://github.com/PyO3/pyo3/blob/6d16d0bbcf770623858462944a9d2d3b493bcc0f/src/pyclass.rs#L99

Since rust str are not NULL terminated and that CPython [expects a null terminated str](https://docs.python.org/fr/3/c-api/typeobj.html#c.PyTypeObject.tp_doc) there will be some problems in some cases. (Moreover, the documentation of DESCRIPTION const does not say that
the &'static str must be null terminated)

https://github.com/PyO3/pyo3/blob/6d16d0bbcf770623858462944a9d2d3b493bcc0f/src/type_object.rs#L109

And in rust-numpy the `SliceBox` DESCRIPTION is not null terminated.

Adding a null byte at the end of the SliceBox DESCRIPTION fixes the issue.
Doing something like this on pyo3 side fixes the problem
```Rust
 // PyPy will segfault if passed only a nul terminator as `tp_doc`.
    // ptr::null() is OK though.
    if T::DESCRIPTION == "\0" {
        type_object.tp_doc = ptr::null();
    } else {
        type_object.tp_doc = T::DESCRIPTION.as_ptr() as *const _;
        if let Some(c) = T::DESCRIPTION.chars().last() {
            if c == '\0' {
                type_object.tp_doc = T::DESCRIPTION.as_ptr() as *const _;
            } else {
                let description = CString::new(T::DESCRIPTION).expect("Module description must not contain NULL byte");
                type_object.tp_doc = description.as_ptr();
            }
        } else {
            type_object.tp_doc = ptr::null();
        }
    };

```

**Comment by kngwyu** [comment]
Thank you! 
Indeed this should be checked.
