### ISSUE TITLE
Wrong format error diagnostics

### ISSUE THREAD

**Issue by gilescope** [PyO3/pyo3#823]
In https://github.com/PyO3/pyo3/blob/6998660ca43c8a39c0e2f01541da418e3c731e86/pyo3-derive-backend/src/pyclass.rs we have errors like:
```
  "Wrong 'name' format",
```

It would be appreciated if they could say things like Got an X but expected a Y.

**Comment by kngwyu** [comment]
Thanks.
Looks easy to fix.
