### ISSUE TITLE
exit code: 0xc0000135, STATUS_DLL_NOT_FOUND

### ISSUE THREAD

**Issue by hyousef-rusty** [PyO3/pyo3#825]
I'm at `Win 10` and got the mentioned error while testing your example:

```rust
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

fn main() -> Result<(), ()> {
    let gil = Python::acquire_gil();
    let py = gil.python();
    main_(py).map_err(|e| {
        // We can't display python error type via ::std::fmt::Display,
        // so print error here manually.
        e.print_and_set_sys_last_vars(py);
    })
}

fn main_(py: Python) -> PyResult<()> {
    let sys = py.import("sys")?;
    let version: String = sys.get("version")?.extract()?;
    let locals = [("os", py.import("os")?)].into_py_dict(py);
    let code = "os.getenv('USER') or os.getenv('USERNAME') or 'Unknown'";
    let user: String = py.eval(code, None, Some(&locals))?.extract()?;
    println!("Hello {}, I'm Python {}", user, version);
    Ok(())
}
```

**Comment by davidhewitt** [comment]
Hi @hyousef-rusty can you provide more detail about how you installed Python, your python version, and also how you are building and running the example?

**Comment by davidhewitt** [comment]
Closing as not enough information to diagnose. This is likely an installation issue rather than a pyo3 bug.

**Comment by fenhl** [comment]
I have this issue too when setting `$env:PYO3_PYTHON = "py"`. I installed Python 3.9.0 using the “download for Windows” installer from the Python website, added it to PATH, and verified that `py` is Python 3.9.0.

**Comment by fenhl** [comment]
Fixed after updating Visual Studio and rebooting. Not sure which part was the actual fix though.

**Comment by davidhewitt** [comment]
I would guess rebooting. Windows uses the PATH environment variable to locate shared libraries, and your changes to PATH may not have propagated to all processes until after a reboot.
