### ISSUE TITLE
Support exporting Rust enums to Python (old school / without data)

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#834]
Following suggestion this is a subset of #417 to focus just on exporting Rust enums without data to Python. These should be fairly straightforward to support - we could borrow inspiration from C++'s `boost.Python` and `pybind11`. We might also want compatibility with the Python `enum` library.

**Comment by programmerjake** [comment]
I have some messy code that you can use as a reference (originally mentioned in #417): https://salsa.debian.org/Kazan-team/simple-soft-float/-/blob/e19291a0b8eb17e9b52c09b8e670bf0fe3244989/src/python_macros.rs

**Comment by davidhewitt** [comment]
I'm nominating this for `0.12`.

**Comment by gilescope** [comment]
Jake's code looks like a good starting place. Has anyone had a go at it? Happy to test out PRs. I could have a crack at it myself but I think the PR would need a fair bit of hand holding...

**Comment by davidhewitt** [comment]
I haven't had a go yet, but I plan to have a go soon unless someone else opens a PR sooner!

**Comment by stillinbeta** [comment]
I made an attempt (#1045), but I got frustrated by the amount of boilerplate and traits required.

**Comment by davidhewitt** [comment]
As we've got a fair bit to release in 0.12 I'm going to move this to the 0.13 milestone

**Comment by Legend-of-iPhoenix** [comment]
Are there any recommended workarounds for the time being? I was considering just adding a python implementation, but I really don't want to have to maintain two copies of the same code in my project :)

**Comment by davidhewitt** [comment]
You could construct a `#[pyclass]` with a bunch of `#[classattr]` to represent all the variants.

It's worth pointing out that #1045 is nearly there, just needs a willing person to rebase and finish it off.

**Comment by b05902132** [comment]
So when I was rebasing #1045, I found there are two ways to implement #834:

- The origin PR implements each variant as a subclass of the enum, and the reviewers suggests [not to do that](https://github.com/PyO3/pyo3/pull/1045/commits/3cc9d7fa80ccc26d371efda99e957a92924f1a52#r467628540). But I think if we plan to implement #417 and #1714, then we should implement  `pyenum` this way. According to [PEP634](https://www.python.org/dev/peps/pep-0634/#class-patterns),  class patterns in Python are actually just a series of `isinstance` check. If each variant is a subclass of the enum, then we already support a small subset of class patterns, and this may lead us toward supporting Python pattern matching. Going down this way needs more design works. I can think of two issues:
  - `SomeEnum.Variant1` will have to be a Python class, that means at Python side we still need to write `x = SomeEnum.Variant1()` or `case SomeEnum.Variant1():` even when no variants carry data.
  - `pyenum` will behave a lot like `pyclass`, like relationships between Rust `enum` and `struct`, and we will need to think about how to avoid code duplication. 

- Or we can just implement C-style enums. But when we eventually implement #417, our Rust enum will correspond to two complete different constructs, depending on whether your enum carries data. I think it's confusing and easy to misuse. If we want to implement C-style enums, I think we should pick a different macro name, e.g. `pycenum`, so our user won't expect `pyenum` to behave like a Rust enum, and in the future we can use `pyenum` to support Rust enum using Python pattern matching.

**Comment by b05902132** [comment]
> * The origin PR implements each variant as a subclass of the enum, and the reviewers suggests [not to do that](https://github.com/PyO3/pyo3/pull/1045/commits/3cc9d7fa80ccc26d371efda99e957a92924f1a52#r467628540). But I think if we plan to implement [Support exporting Rust enums to Python (full ADTs) #417](https://github.com/PyO3/pyo3/issues/417) and [Support for PEP 622 structural pattern matching #1714](https://github.com/PyO3/pyo3/issues/1714), then we should implement  `pyenum` this way. According to [PEP634](https://www.python.org/dev/peps/pep-0634/#class-patterns),  class patterns in Python are actually just a series of `isinstance` check. If each variant is a subclass of the enum, then we already support a small subset of class patterns, and this may lead us toward supporting Python pattern matching. 

Just figured out  [value pattern](https://www.python.org/dev/peps/pep-0634/#value-patterns) supports matching against a variable. Maybe the best design is: If a variant contains no data, then it's just a Python `int`; otherwise it's a Python `class`.
