### ISSUE TITLE
Property methods cannot take self as a PyRef

### ISSUE THREAD

**Issue by thequux** [PyO3/pyo3#837]
I would like to be able to write code like the following:

```rust
#[pyclass]
struct Proxy {
    parent: Py<Foo>,
}

#[pyclass]
struct Foo {}

#[pymethods]
impl Foo {
    #[getter]
    fn proxy(slf: PyRef<Self>) -> Proxy {
        Proxy {
            parent: slf.into(),
        }
    }
}
```

However, this currently fails with the following error:
```
error: Getter function can only have one argument of type pyo3::Python
  --> src/lib.rs:12:20
   |
12 |     fn proxy(slf: PyRef<Self>) -> Proxy {
   |                   ^^^^^^^^^^^
```

(For completeness, this should also apply to setters, as well as support all of the other wrapper types for Python objects)

**Comment by kngwyu** [comment]
Yeah, I really agree with that it's bad.
But since everything around `__dunder__` is designed before `PyRef` or `PyCell`, it's hard to integrate them.
