### ISSUE TITLE
use rust-skeptic

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#84]
we should test readme and book with https://github.com/budziq/rust-skeptic

**Comment by althonos** [comment]
I would advise in using [`docmatic`](https://github.com/assert-rs/docmatic) instead, as `skeptic` cannot be used as a test dependency but must be used as a dev dependency, meaning the end-users of the `pyo3` crate would need to compile `skeptic`even when they are not running tests.

I'll propose a PR to see how nicely I can get `docmatic` to play.

**Comment by althonos** [comment]
Closed with #142.
