### ISSUE TITLE
__radd__ etc don't get called if __add__ is also defined

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#844]
If we make a class like this:

```rust
#[pyclass]
#[derive(Debug)]
struct RhsArithmetic {}

#[pymethods]
impl RhsArithmetic {
    #[new]
    fn new() -> RhsArithmetic {
        RhsArithmetic {}
    }
}

#[pyproto]
impl PyNumberProtocol for RhsArithmetic {
    fn __mul__(lhs: PyRef<'p, Self>, rhs: &PyAny) -> PyResult<String> {
        Ok(format!("MUL"))
    }
    fn __rmul__(&self, other: &PyAny) -> PyResult<String> {
        Ok(format!("RMUL"))
    }
}
```

Then both `1 * rhs` and `rhs * 1` call the function in the `tp_as_number.nb_mul` slot. As of #839 this will be our `__mul__` implementation above (and never `__rmul__`).

And specifically it will call it with the arguments in the same order as invoked. So from above, we will have `__mul__(1, rhs)` and `__mul__(rhs, 1)`.

This is problematic, because `__mul__` as defined above will raise a `TypeError` if the first argument is not `Self`.

We saw this behaviour reported on Gitter. All three of the below will currently be calling `__mul__`, which is why the second will `TypeError`:

```
>>> rhs * 1.0
'MUL'
>>> 1.0 * rhs # should call __rmul__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError
>>> rhs * rhs
'MUL'
```

I am thinking that instead of doing [this](https://github.com/PyO3/pyo3/blob/1aa4ae82847ec418791419ff74f54e5b5f85b30f/src/class/number.rs#L650), if both `__mul__` and `__rmul__` are defined we should be creating a wrapper function which calls the correct function depending on the type of the first argument.

The implementation of [`PyNumber_Add`](https://github.com/python/cpython/blob/224481a8c988fca12f488544edd2f01c0af2a91d/Objects/abstract.c#L999) suggests that we should return `Py_NotImplemented` from this wrapper function if there is a type error, so that `sq_concat` is given a chance to be called also.

**Comment by programmerjake** [comment]
Similar logic in [`PyNumber_Multiply`](https://github.com/python/cpython/blob/224481a8c988fca12f488544edd2f01c0af2a91d/Objects/abstract.c#L1030)

**Comment by davidhewitt** [comment]
From a quick search I think the equivalent logic for classes defined in Python is in [this macro](https://github.com/python/cpython/blob/05e4a296ecc127641160a04f39cc02c0f66a8c27/Objects/typeobject.c#L6180)

**Comment by kngwyu** [comment]
This is difficult for our current protocol implementation, but after rewriting it without specialization, I think we can implement this.

**Comment by davidhewitt** [comment]
I'm nominating this for `0.12`.

**Comment by davidhewitt** [comment]
@kngwyu just a heads up; I'm assigning this to you after the discussion in #1072 so that others don't spend time taking a stab at this while you're working on an implementation :)
