### ISSUE TITLE
#[pyo3(get,set)] causes `cargo test` to fail

### ISSUE THREAD

**Issue by aeshirey** [PyO3/pyo3#845]
Including the `#pyo3(get,set)` or `#[getter(i)]` for a pyclass causes `cargo test` to fail.

I would assume that this is such a common thing to use that it's perhaps a documentation issue and not a bug, but I'm not sure how to allow cargo tests with my code that has getters and setters.

### 🌍 Environment

 - Your operating system and version: Windows 10 with WSL running Ubuntu 18.04.4 LTS
 - Your python version: 3.6.9
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Stock version included in Ubuntu
 - Your rust version (`rustc --version`): rustc 1.44.0-nightly
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` 0.9.1, also tried with 0.9.0-alpha1

### 💥 Reproducing

src/lib.rs:

```rust
use pyo3::prelude::*;

#[pyclass]
struct MyStruct {
    #[pyo3(get, set)]
    i: u32,
}

/* Problem also occurs if this is used instead of the above #[pyo3(get,set)]:
#[pymethods]
impl MyStruct {
    #[getter(i)]
    fn get_i(&self) -> u32 {
        self.i
    }
}
*/

#[pymodule]
fn tests_and_getters(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<MyStruct>()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

The code compiles without a problem (since cfg(test) isn't applicable), but running `cargo test` generates errors. Here's the content of the error with the very irrelevant, verbose parts omitted:

    error: linking with `cc` failed: exit code: 1
      |
      = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "...
    ...
    ...
    = note: /home/user/rust/gettertest/target/debug/deps/tests_and_getters-94c0ceb1fd2ab0ef.hra3dhvd2c210xh.rcgu.o: In function `pyo3::err::PyErr::restore':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/err.rs:345: undefined reference to `PyErr_Restore'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.0.rcgu.o): In function `pyo3::err::PyErr::new_type':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/err.rs:209: undefined reference to `PyErr_NewException'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.0.rcgu.o): In function `pyo3::err::panic_after_error':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/err.rs:552: undefined reference to `PyErr_Print'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.13.rcgu.o): In function `pyo3::ffi::object::Py_DECREF':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/ffi/object.rs:931: undefined reference to `_Py_Dealloc'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.13.rcgu.o): In function `pyo3::ffi::object::Py_None':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/ffi/object.rs:973: undefined reference to `_Py_NoneStruct'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.15.rcgu.o): In function `<pyo3::exceptions::RuntimeError as pyo3::type_object::PyTypeObject>::type_object':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/exceptions.rs:218: undefined reference to `PyExc_RuntimeError'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.4.rcgu.o): In function `pyo3::types::num::<impl pyo3::conversion::IntoPy<pyo3::object::PyObject> for u32>::into_py':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/types/num.rs:132: undefined reference to `PyLong_FromLong'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.7.rcgu.o): In function `pyo3::gil::prepare_freethreaded_python::{{closure}}':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:39: undefined reference to `Py_IsInitialized'
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:48: undefined reference to `PyEval_ThreadsInitialized'
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:43: undefined reference to `PyEval_ThreadsInitialized'
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:57: undefined reference to `Py_InitializeEx'
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:62: undefined reference to `PyEval_InitThreads'
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:68: undefined reference to `PyEval_SaveThread'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.7.rcgu.o): In function `<pyo3::gil::GILGuard as core::ops::drop::Drop>::drop':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:112: undefined reference to `PyGILState_Release'
          /home/user/rust/gettertest/target/debug/deps/libpyo3-a88cb910efc8a664.rlib(pyo3-a88cb910efc8a664.pyo3.5vmrdar7-cgu.7.rcgu.o): In function `pyo3::gil::GILGuard::acquire':
          /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.9.1/src/gil.rs:253: undefined reference to `PyGILState_Ensure'
          collect2: error: ld returned 1 exit status

**Comment by kngwyu** [comment]
I'm sorry but this is a long-lasting bug.
See https://github.com/PyO3/pyo3/releases/tag/v0.6.0 for the workaround.
