### ISSUE TITLE
Add an example of lib with args/kwargs function, not only primitive sum of integers

### ISSUE THREAD

**Issue by pashinin** [PyO3/pyo3#87]
I can't find any example of how can I use `*args` and `**kwargs` in a function in lib.rs

**Comment by fafhrd91** [comment]
here some docs https://pyo3.github.io/pyo3/guide/class.html#method-arguments

it should be similar for `#[pyfn(m, "sum_as_string", "your extra arguments")]`

**Comment by pashinin** [comment]
Thank you. That's how it should be I think:
```
#[pyfn(m, "function_name", args="*", kwargs="**")]
```
