### ISSUE TITLE
Shared crate to locate Python

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#870]
A shared utility crate to locate python would help us in `build.rs` as well as other crates in the ecosystem. As first suggested on Gitter:

> @gilescope:matrix.org Also I wonder if we could create a where’s wally crate but for python. There seems to be quite a few rust applications trying to find python. I think it would be great to centralise that problem in a single crate - E.g.: https://github.com/vadimcn/vscode-lldb/blob/master/adapter2/loader/find_python.rs

**Comment by davidhewitt** [comment]
For anyone interested in picking this up, I started extracting some of the pyo3 build script to a new crate here: https://github.com/davidhewitt/python-config

**Comment by kngwyu** [comment]
1. Is there any demand for doing that?
2. maturin also has [Python detection code](https://github.com/PyO3/maturin/blob/v0.8.2-alpha.1/src/metadata.rs). It can be beneficial if we can share that. cc: @konstin

**Comment by konstin** [comment]
I think the question is what you want to find: Only the current python or all available python interpreter?

**Comment by davidhewitt** [comment]
I think there's a number of uses:
- we can ensure maturin and pyo3 detect the same python versions
- for multiprocessing the interpreter needs to be set, maybe this crate can help there
- @gilescope originally requested
- third-party code might want it. Who knows!

Also detecting all the configuration such as Python build flags and architecture is complicated. Putting it in a shared crate will make the pyO3 build.rs much simpler to maintain.

> I think the question is what you want to find: Only the current python or all available python interpreter?

Agreed, and I think it's good to put interfaces to both in the shared crate. The current implementation I built just enumerates a few possible python interpreters.

**Comment by davidhewitt** [comment]
This now exists inside this repo as `pyo3-build-config`.
