### ISSUE TITLE
Compile Error With Extension-Module On MacOS 10.13

### ISSUE THREAD

**Issue by dkao1978** [PyO3/pyo3#88]
I've attempted the library example in the Readme and was unable to compile with nightly-2017-10-17, nightly-2017-10-01. I was able to get it to compile and working in Linux. This was compiled against pyo3 0.2.2. If I remove

``
features = ["extension-module"]
``

the library compiles but it does not import.

``
  = note: Undefined symbols for architecture x86_64:
            "__Py_NoneStruct", referenced from:
                pyo3::python::Python::None::h24f8768b80a0a81e in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo314.rust-cgu.o)
            "_PyExc_TypeError", referenced from:
                _$LT$pyo3..objects..exc..TypeError$u20$as$u20$pyo3..typeob..PyTypeObject$GT$::type_object::h7851d6317651b6a8 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo35.rust-cgu.o)
            "_PyList_GetItem", referenced from:
                pyo3::objects::list::PyList::get_item::hc5ef1ef5b66671bb in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo313.rust-cgu.o)
            "_PyUnicode_AsUTF8AndSize", referenced from:
                pyo3::objects::string::PyString::data::h5c8ace712ae3cc69 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo315.rust-cgu.o)
            "_PyUnicode_FromStringAndSize", referenced from:
                pyo3::objects::string::PyString::new::h4ab413f69a967659 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo315.rust-cgu.o)
            "_PyLong_AsLong", referenced from:
                pyo3::objects::num3::_$LT$impl$u20$pyo3..conversion..FromPyObject$LT$$u27$source$GT$$u20$for$u20$i64$GT$::extract::hc46a9c8ced7cb5f5 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo39.rust-cgu.o)
            "_PyDict_Items", referenced from:
                pyo3::objects::dict::PyDict::items::h7a798b03cc809164 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo39.rust-cgu.o)
            "_PyList_Size", referenced from:
                pyo3::objects::list::PyList::len::ha45313f91ec59217 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo313.rust-cgu.o)
            "_PyDict_GetItem", referenced from:
                pyo3::objects::dict::PyDict::get_item::_$u7b$$u7b$closure$u7d$$u7d$::h4909d93f7269fd99 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo39.rust-cgu.o)
            "_PyCFunction_NewEx", referenced from:
                hello::init_mod::hef61a068ad24b933 in hello.hello15.rust-cgu.o
            "_PyErr_Print", referenced from:
                pyo3::err::panic_after_error::h8117ddfd49652b5e in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo30.rust-cgu.o)
            "_PyUnicodeDecodeError_Create", referenced from:
                pyo3::objects::exc::UnicodeDecodeError::new_err::h4fbed25f5ab76f60 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo35.rust-cgu.o)
            "_PyErr_Fetch", referenced from:
                pyo3::err::PyErr::fetch::h59d7d194dfe93c56 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo30.rust-cgu.o)
            "_PyExc_OverflowError", referenced from:
                _$LT$pyo3..objects..exc..OverflowError$u20$as$u20$pyo3..typeob..PyTypeObject$GT$::type_object::h07d6354da6fbb3bc in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo35.rust-cgu.o)
            "_PyErr_Occurred", referenced from:
                pyo3::err::PyErr::occurred::he35fc269dae3c6b5 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo30.rust-cgu.o)
            "_PyErr_PrintEx", referenced from:
                pyo3::err::PyErr::print::h79f4b608f21ba21c in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo30.rust-cgu.o)
            "_PyExc_SystemError", referenced from:
                _$LT$pyo3..objects..exc..SystemError$u20$as$u20$pyo3..typeob..PyTypeObject$GT$::type_object::hf68f0a8fb061234f in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo35.rust-cgu.o)
            "__Py_Dealloc", referenced from:
                pyo3::python::Python::xdecref::h65127a7a056c5a6d in hello.hello7.rust-cgu.o
                pyo3::pythonrun::ReleasePool::release_pointers::h899f6b6aeb488859 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo315.rust-cgu.o)
                pyo3::pythonrun::ReleasePool::drain::h724f881520f1e616 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo315.rust-cgu.o)
                pyo3::python::Python::xdecref::he3eca63eafbf8183 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo314.rust-cgu.o)
            "_PyErr_Restore", referenced from:
                pyo3::err::PyErr::restore::hb44e13569b08a81e in hello.hello3.rust-cgu.o
                pyo3::err::PyErr::restore::h49b2e59db877b7eb in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo30.rust-cgu.o)
            "_PyModule_Create2", referenced from:
                pyo3::ffi3::modsupport::PyModule_Create::h975d08c4a9d765c5 in hello.hello6.rust-cgu.o
            "_PyEval_InitThreads", referenced from:
                _PyInit__foo in hello.hello15.rust-cgu.o
            "_PyDict_Size", referenced from:
                pyo3::objects::dict::PyDict::len::he66500cf0fc78f12 in libpyo3-f4c712131680aca6.rlib(pyo3-f4c712131680aca6.pyo39.rust-cgu.o)
            "_PyObject_SetAttr", referenced from:
                _$LT$T$u20$as$u20$pyo3..objectprotocol..ObjectProtocol$GT$::setattr::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h5daff24384e3d329 in hello.hello9.rust-cgu.o
                _$LT$T$u20$as$u20$pyo3..objectprotocol..ObjectProtocol$GT$::setattr::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hfc1e89190dad2179 in hello.hello9.rust-cgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
``

**Comment by fafhrd91** [comment]
I can not reproduce this problem.  did you activate python3 environment?

try to build this example https://github.com/PyO3/pyo3/tree/master/examples/word-count

>> python ./setup.py bdist_wheel

**Comment by dkao1978** [comment]
The word-count example worked. I used setup.py for the example in Readme and that finally worked.

Any reason why this works out of the box in Linux but requires setup.py on Mac? Just trying to understand how the build process works.

**Comment by fafhrd91** [comment]
on osx you have to use "-C link-arg=-undefined -C link-arg=dynamic_lookup" linker arguments
setuptools-rust adds those automatically

**Comment by jalexvig** [comment]
@fafhrd91 Where can those linker arguments be added? Would be nice if there was a complete (end-to-end) example on the README for macs.

**Comment by fafhrd91** [comment]
you have to use those arguments for rustc. setuptools-rust already does it for you

**Comment by jalexvig** [comment]
I assume you mean `cargo rustc build -Clink-arg=-undefined -Clink-arg=dynamic_lookup`?

But I am getting the following error (same error when I add those args to `~/.cargo/config`):

```
error: failed to parse manifest at `/Users/alex/learn/rust/py03/add_ints/Cargo.toml`

Caused by:
  virtual manifests do not specify [lib]
```

**Comment by fafhrd91** [comment]
here is python code that builds build command https://github.com/PyO3/setuptools-rust/blob/master/setuptools_rust/build.py#L95

**Comment by anentropic** [comment]
I'm here for the same error

I am trying to follow the various bits of contradictory info in the docs at https://pyo3.rs/v0.13.2/

I have:
```toml
[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
```

in my `Cargo.toml`

(although https://pyo3.rs/v0.13.2/building_and_distribution.html shows a different example like
```
[features]
default = ["pyo3/extension-module"]
```
...)

when I `cargo build` it blows up with:
```
            "_PyModule_Create2", referenced from:
                pyo3::ffi::modsupport::PyModule_Create::he78d125b81a01306 in myproject.sjk3j4fux4bxd33.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The answers mention something called `setuptools_rust` but I'm not sure what Im supposed to do with it

I am playing dumb a bit because I can find the solution in a comment on another issue here https://github.com/PyO3/pyo3/issues/172#issuecomment-401612673 

...but wouldn't it be great if that info was published in the docs somewhere prominent?

**Comment by davidhewitt** [comment]
The cargo config necessary is in [the bottom of this section in the README](https://github.com/PyO3/pyo3#using-rust-from-python).

But yikes - I'd totally missed that the guide has some _super_ outdated example cargo config - I'll update that!

**Comment by anentropic** [comment]
ok cool, but I wasn't looking at the README as I assumed the docs were more comprehensive

**Comment by davidhewitt** [comment]
That's fair. By the way, if you're interested in testing the latest and greatest, #1539 is a PR I was just in the process of testing which should remove the need for you to set any config at all.

**Comment by anentropic** [comment]
That PR looks good

Also, I apologise sincerely for the tone of my previous comment.

This project is awesome and I am very grateful for it 👍
