### ISSUE TITLE
Idiomatic way to destructure a PyErr

### ISSUE THREAD

**Issue by KaiserKarel** [PyO3/pyo3#898]
How would one convert a PyErr into something like

```
#[derive(Debug)]
pub enum Error {
    Python {
        msg: String,
        exception: ExceptionType
    }
   ....
}
```

I'd like to be able to nicely display exceptions, including custom ones; and possibly match against standard ones as well.

**Comment by davidhewitt** [comment]
Hi @KaiserKarel , the pyO3 api is a little under-developed for PyErr; I think we plan to add more in the future, ideas and feedback are welcome.

For now the best route is probably to grab the `pvalue` and `ptype` fields directly from the PyErr struct and do what you need with them.

**Comment by KaiserKarel** [comment]
Alright!
