### ISSUE TITLE
attribute access and `py: Python` parameter

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/PyO3#9]
when developer defines new class, pyo3 actually rewrite code of struct, so for example:

```rust
#[py:class]
struct MyCLS {
  data: i32
}
```
becomes:
```rust
struct MyCLS {
  _unsafe_inner: PyObject
}

struct MyCLS_Storage {
  data: i32
}

impl MyCLS {
  fn data(&self, py: Python) -> &i32 {...}
  fn data_mut(&self, py: Python) -> &mut i32 {...}
}
```

I think this is confusing. first of all access to attribute is not obvious and plus all apis are polluted with `py: Python`.

as a note, we do this because we actually store data on PyObject instance, and all memory for `MyCLS` is managed by python.

also we create special `MyCLS::create_instance()` method that accepts all attributes.

here is some idea:

```rust

struct PyPtr<T> {
   inner: ffi:PyObject,
   _t: PhantomeData<T>
}

struct Py<'p T> {
   inner: ffi:PyObject,
   _t: PhantomeData<&'p GILGuard>,
}

impl<T> PyPtr<T> {
  fn as_ref(&self, py: Python<'p>) -> Py<'p T>;
  fn into_ref(self, py: Python<'p>) -> Py<'p T>;
}

impl<'p> Py<'p> {
  fn as_ref() -> &'p T;

  fn as_ptr(&self) -> PyPtr<T>;
  fn into_ptr(self) -> PyPtr<T>;
}

impl<'p> Deref for Py<'p> {
  fn deref(self) -> &'p T;
}

```
I am not sure if this going to work.

**Comment by fafhrd91** [comment]
@ohanar I'd like to know your opinion

**Comment by fafhrd91** [comment]
also, we wouldn't need `create_instance` anymore, it could be just

```rust
impl<'p T> Py<'p T> {
    fn new(py: Python, inst: T) -> Py<'p T>;
}
```

**Comment by fafhrd91** [comment]
wip https://github.com/PyO3/PyO3/tree/pyptr

**Comment by ohanar** [comment]
I'm a little confused on your intent. Is the plan to make (as an example) the signature:
```
fn __getitem__(&self, py: Python, key: Key) -> Self::Result;
```
now
```
fn __getitem__(&self, key: Key) -> Self::Result;
```
?

If so, how could you use functionality that require the GIL in the body of the `__getitem__`?

One thing that I would hope that this would bring is the removal of the `MyClass_Storage` struct, and instead a `MyClass_Wrapper` struct. I think it is confusing to have the struct layout to be completely altered by any attribute (unless of course it is a `repr` attribute which is specifically for that purpose).

**Comment by fafhrd91** [comment]
I introduced two pointers PyPtr<T> (not gil) and Py<'p, T> ('p is tight to gil)

here how you create Py<T> 
```rust
from_borrowed_ptr<'p, T>(py: Python<'p>, ptr: *mut ffi::PyObject) -> Py<'p, T>```

**Comment by fafhrd91** [comment]
here is code https://github.com/PyO3/PyO3/blob/pyptr/src/pyptr.rs#L50
so you should never work with `T` directly only with refs, otherwise `T` is not managed by python.

but problem is different, I cannot make refs work with associated types

example:
```rust

impl class::basic::PyObjectProtocol for PyCLS {
    
    fn __getattr__<'a>(&'a self, name: &'a PyCLS) -> PyResult<()> {
        println!("__getattr__");
        Ok(())
    }
}

impl<'a> class::basic::PyObjectGetAttrProtocol<'a> for PyCLS
{
    type Name = &'a PyCLS;
    type Result = PyResult<()>;
}
```

I can not generate "wrap" callback

**Comment by fafhrd91** [comment]
I think problem right now with this constrain

```rust
impl<'p, T> Py<'p, T> where T: BaseObject<Type=T> + PyTypeObject
```

**Comment by ohanar** [comment]
That doesn't address all possible uses of the GIL. For instance, how would you handle the following line of code if the signature doesn't include a Python parameter:
```rust
Err(PyErr::new_lazy_init(
    py.get_type::<NotImplementedError>(),
    Some("not implemented for foo".to_py_object(py)),
))
```

(As a separate thought, I'm unhappy with how verbose python error handling is currently.)

**Comment by fafhrd91** [comment]
I think `PyErr::new_lazy_init` is fine without GIL, we need GIL when we do `err.restore(py)`
eventually I want to remove PyObject and use only `PyPtr<T>`

**Comment by ohanar** [comment]
Yes, the lazy init is fine without the GIT, but the arguments are not (call to `py.get_type` and a call to `to_py_object`, although maybe the latter will go away)

**Comment by fafhrd91** [comment]
I this approach going to work, then we can change api. 

more importantly, I can not make protocols work with references.

**Comment by fafhrd91** [comment]
seems this approach work. amount of boilerplate code reduced significantly.
only one trait needs to be implemented for rust `struct`
https://github.com/PyO3/PyO3/blob/pyptr/src/class/typeob.rs#L13

example:
```rust

struct PyCLS {
    num: i32,
}

impl pyo3::class::typeob::PyTypeInfo for PyCLS {
      type Type = PyCLS;

      fn size() -> usize {
          (Self::offset() as usize) + std::mem::size_of::<PyCLS>()
      }

      fn offset() -> isize {
          let align = std::mem::align_of::<PyCLS>();
          let bs = <pyo3::PyObj as pyo3::class::typeob::PyTypeInfo>::size();
          ((bs + align - 1) / align * align) as isize
      }

      fn type_name() -> &'static str {
          "PyCLS"
      }

      fn type_object() -> &'static mut pyo3::ffi::PyTypeObject {
          static mut TYPE_OBJECT: pyo3::ffi::PyTypeObject = pyo3::ffi::PyTypeObject_INIT;
          unsafe { &mut TYPE_OBJECT }
      }
  }
}
```
that is it. now it is possible to construct it and send to python code. that is exactly what `#[py:class]` does https://github.com/PyO3/PyO3/blob/pyptr/pyo3cls/src/py_class.rs

here is example how to create new instance:
```rust

let gil = Python::acquire_gil();
let py = gil.python();
    
let inst = py.init(PyCLS {num: 10}).unwrap();
    
let d = PyDict::new(py);
d.set_item(py, "inst", p).unwrap();
py.run("print(inst)", None, Some(&d)).unwrap();
```

**Comment by fafhrd91** [comment]
I need someone to review my changes, I am not entirely sure that my implementation is right

**Comment by messense** [comment]
I think creating a pull request would be easier to review.

**Comment by fafhrd91** [comment]
I don't think PR makes sense in this case. This branch is full re-write, it touches all files

**Comment by messense** [comment]
I just think that it would be easier to discuss on a specific code diff in a pull request. Currently it's scattered over many commits makes it hard to find and comment on them.

**Comment by fafhrd91** [comment]
ok, that makes sense

**Comment by fafhrd91** [comment]
#11

**Comment by fafhrd91** [comment]
this is done

**Comment by fafhrd91** [comment]
I've try to port async-tokio to new system and it seems not very ergonomic. I am removing pyptr implementation from native type. I still need to decide what to do with custom classes.

**Comment by fafhrd91** [comment]
I think, we still can use new system, but we need to create mirror type for each python class,
i.e. PyString<'p> and PyStringPtr.

**Comment by ohanar** [comment]
I was thinking, what if you implement the protocols for `PyPtr<T>` rather than for `T`? That way you could avoid having to pass in the extra py argument, and since `PyPtr<T>` derefs to `T`, it should still be convenient to use.

**Comment by fafhrd91** [comment]
in that case it should be PyPtr<'p, T>, which is the problem.

problem is how to store PyObject pointer in rust structs. storing anything with lifetime is not very useful.
idea is to create two type per class, one with `'p` and one without. so if you need to use python api
you use `PyStringPtr::unpark(py) -> PyString<'p>`, and opposite, if you need to store pointer to object `PyString<'p>::park() -> PyStringPtr`. `'p` is fine if you handle python call in-place and store refs to py objects anywhere.

**Comment by fafhrd91** [comment]
just pushed changes with ptr types

**Comment by ohanar** [comment]
Why not just have park be the drop behavior of `PyString<'p>`? Akin to a mutex lock guard?

**Comment by fafhrd91** [comment]
main reason is to be able to store py objects in rust structures

**Comment by fafhrd91** [comment]
seems even with separate pointers it is not very ergonomic.
