### ISSUE TITLE
Cannot implement __format__

### ISSUE THREAD

**Issue by fenhl** [PyO3/pyo3#910]
## 🐛 Bug Reports

The code below fails to compile with the following error:

```
error[E0119]: conflicting implementations of trait `pyo3::class::basic::FormatProtocolImpl` for type `Spam`:
  --> src/lib.rs:12:1
   |
12 | #[pyproto] impl PyObjectProtocol for Spam {
   | ^^^^^^^^^^
   |
   = note: conflicting implementation in crate `pyo3`:
           - impl<'p, T> pyo3::class::basic::FormatProtocolImpl for T
             where T: pyo3::class::basic::PyObjectProtocol<'p>;
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

### 🌍 Environment

 - Your operating system and version: macOS Catalina 10.15.4
 - Your python version: Python 3.7.7
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: Homebrew, no virtualenv
 - Your rust version (`rustc --version`): rustc 1.45.0-nightly (7ced01a73 2020-04-30)
 - Are you using the latest pyo3 version? Have you tried using latest master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?` Yes (version 0.9.2) and yes.

### 💥 Reproducing

Cargo.toml:

```toml
[package]
name = "pyo3-test"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.pyo3]
#version = "0.9.2"
git = "https://github.com/PyO3/pyo3"
features = ["extension-module"]
```

lib.rs:

```rust
use pyo3::{
    PyObjectProtocol,
    prelude::*
};

#[pyclass] struct Spam {}

#[pymethods] impl Spam {
    #[new] fn new() -> Spam { Spam {} }
}

#[pyproto] impl PyObjectProtocol for Spam {
    fn __format__(&self, format_spec: &str) -> PyResult<String> {
        Ok(format_spec.into())
    }
}

#[pymodule] fn pyo3_test(_: Python<'_>, m: &PyModule) -> PyResult<()> {
    m.add_class::<Spam>()?;
    Ok(())
}
```

Compiled using `cargo +nightly rustc --release -- -C link-arg=-undefined -C link-arg=dynamic_lookup`.

**Comment by kngwyu** [comment]
Please use `#![feature(specialization)]`
