### ISSUE TITLE
networking?

### ISSUE THREAD

**Issue by itdaniher** [PyO3/pyo3#92]
Hello!

Is it presently possible to hand off a socket from Python to Rust? I'm looking to optimise a daemon built in Python by passing an open connection from Python setup/init code to Rust for bandwidth-intensive streaming.

Thanks!

**Comment by fafhrd91** [comment]
Do you use unix? Then you can get file descriptor and then construct TcpStream from fd in rust

You can also check this project https://github.com/PyO3/tokio it has several example how to handle sockets in python and rust

**Comment by itdaniher** [comment]
I was considering something like that FD trick, thanks for the suggestion! I'll also take a closer look at tokio.

Cheers!
