### ISSUE TITLE
Help with pyfunction and custom error types.

### ISSUE THREAD

**Issue by ffranr** [PyO3/pyo3#944]
Hello, if possible, may I please have some help with using `#[pyfunction]`?
I would like to use `#[pyfunction]` and the `?` operator on a `Result` from a third-party crate.

My code looks a bit like this:

```rust
type Result<T> = std::result::Result<T, CustomError>;

#[pyfunction]
fn foo() -> Result<()> {
    // `?` correctly converts error to CustomError
    // because of `impl std::convert::From<another_crate::Error> for CustomError`
    another_crate::func()?;
    Ok(())
}
```

I would like to keep using the `?` operator. If I were to change `Result<()>` to `PyResult<()>` the `another_crate::Error` type wont convert correctly to `pyo3::PyErr`. None of those error types are defined in my crate.

`#[pyfunction]` causes the following error:
```plaintext
the trait bound `pyo3::object::PyObject: pyo3::conversion::FromPy<std::result::Result<(), CustomError>>` is not satisfied
```

What can I do to fix this problem?

BTW, this works:
```rust
#[pyfunction]
fn foo() -> Result<()> {
    another_crate::func()?;
    Ok(())
}

#[pyfunction]
fn foo_wrapper() -> PyResult<()> {
    foo()?;
    Ok(())
}
```
But I would like to avoid having to need `foo_wrapper()`.

Thank you for your help.

**Comment by birkenfeld** [comment]
I don't know how hard it would be to support Results with errors other than `PyErr` via another trait, but I imagine that the errors for wrong usage would suffer.

TBH, the wrapper solution doesn't really look so bad to me, you can write it more streamlined like this:
```
#[pyfunction]
fn foo() -> PyResult<()> {
    fn inner() -> Result<()> {
        another_crate::func()?;
        Ok(())
    }
    inner().map_err(From::from)
}
```

**Comment by ffranr** [comment]
Ah yes of course, that's a good idea! Thank you for reply @birkenfeld !

I've gone with a close variant of your idea (capturing variables from `foo` scope):
```rust
#[pyfunction]
fn foo() -> PyResult<()> {
    || -> Result<()> {
        another_crate::func()?;
        Ok(())
    }().map_err(From::from)
}
```
