### ISSUE TITLE
How to adapt a Python object to a required trait

### ISSUE THREAD

**Issue by Nateckert** [PyO3/pyo3#946]
Hi,

I am trying to expose a Rust function to Python.
This function is a bit particular, as it takes as argument a Rust struct satisfaying a trait.
I tried to create the interface in Rust, but I cannot make it work and I am not even sure my attempt is in the right direction. Could you point me to the right part of the documentation in order to be able to achieve what I am looking for ?
If I can make it work, I'll contribute to the user guide as I think it might be useful to others.

### 🌍 Environment

 - Your operating system and version:
 - Your python version: Python 3.6.10
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: conda env
 - Your Rust version (`rustc --version`): rustc 1.45.0-nightly (a74d1862d 2020-05-14)
 - Your PyO3 version: 10.1
 

### 💥 Reproducing

The function I want to expose is the `solve` function. It takes as input a `Model`.
I attempt to make a wrapper around the Python object with an `UserModel` struct holding a reference to a `PyAny` object and implement the trait's required methods assuming Python object has methods with the same names.

The compiler does not like the lifetimes parameters which is a bummer as I wanted to avoid copying the object.
If I remove them, the issues are the following :
```
- #[pymethods]: error[E0277]
    - the trait bound `pyo3::types::any::PyAny: pyo3::conversion::FromPyObject<'_>` is not satisfied
- self.model.call_method("set_variables", list, None).unwrap();
    - error[E0277]: the trait bound `pyo3::instance::Py<pyo3::types::tuple::PyTuple>: pyo3::conversion::FromPy<pyo3::object::PyObject>` is not satisfied
- #[pyfunction]
    - error[E0277]: the trait `pyo3::pyclass::PyClass` is not implemented for `&std::vec::Vec<f64>`
```

```
use pyo3::prelude::*;
use pyo3::wrap_pyfunction;
use pyo3::types::PyAny;

pub trait Model {
    fn set_variables(&mut self, var: &Vec<f64>);
    fn get_results(&self) -> Vec<f64>;
    fn compute(&mut self);
}

fn algorithm_step(old_result: &Vec<f64>, old_guess: &Vec<f64>) -> Vec<f64> {
    // Do some clever estimation
    // This is a dummy example
    let mut new_guess = Vec::new();
    for (i, _elt) in old_result.iter().enumerate() {
        new_guess.push(old_result[i] - old_guess[i]);
    }
    new_guess
}

pub fn solve<T: Model>(init: &Vec<f64>, model: &mut T) {
    model.set_variables(init);
    model.compute();

    let mut results = model.get_results();
    let old_guess = init;

    let mut iter = 0;

    while iter < 10 {
        iter += 1;
        let new_guess = algorithm_step(&results, &old_guess);
        model.set_variables(&new_guess);
        model.compute();
        results = model.get_results();
    }
}

#[pyclass]
struct UserModel<'a> {
    model: &'a PyAny
}

#[pymethods]
impl<'a> UserModel<'a> {
    #[new]
    pub fn new(model: &'a PyAny) -> Self {
        UserModel { model }
    }
}

impl<'a> Model for UserModel<'a> {
    fn set_variables(&mut self, var: &Vec<f64>) {
        let gil = Python::acquire_gil();
        let py = gil.python();
        let list = var.to_object(py);
        self.model.call_method("set_variables", list, None).unwrap();
    }
    fn get_results(&self) -> Vec<f64> {
        let gil = Python::acquire_gil();
        let py = gil.python();
        self.model.call_method("get_results", (), None).unwrap().extract().unwrap()
    }
    fn compute(&mut self) {
        let gil = Python::acquire_gil();
        let py = gil.python();
        self.model.call_method("compute", (), None).unwrap();
    }
}

#[pyfunction]
fn my_function(init: &Vec<f64>, model: &mut UserModel) {
    solve(init, model);
}

#[pymodule]
fn module_with_functions(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_pyfunction!(my_function)).unwrap();

    Ok(())
}
```

Thanks in advance !

**Comment by davidhewitt** [comment]
@Nateckert there's a lot going on in your issue so I'm not sure exactly what you're asking, but I'll focus on this bit.

To store `PyAny` in a struct you need to store it as a `Py<PyAny>` smart pointer. The difference is that `Py<PyAny>` is independent of the GIL, you can't do anything to it without first supplying the GIL, whereas `&'a PyAny` is tied to the GIL lifetime (the lifetime `'a`).

So your `UserModel` should be:

```
#[pyclass]
struct UserModel<'a> {
    model: Py<PyAny>
}
```

To get `&PyAny` from `Py<PyAny>`, use the `.as_ref()` method, which takes the `Python` GIL token as an argument.

Does that help you head in the right direction?

**Comment by Nateckert** [comment]
Thanks for the help, it is definitely heading me into the right direction.

However, I have some small issues with the basic method calls. I tried this basic code with either `to_object` or `into_py` but I get the compiler error: `the trait pyo3::conversion::FromPy<pyo3::object::PyObject> is not implemented for pyo3::instance::Py<pyo3::types::tuple::PyTuple>`: 

```
use pyo3::prelude::*;
use pyo3::types::PyAny;

fn set_variables(var: Vec<f64>, py_model: Py<PyAny>) {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let list: PyObject = var.to_object(py);
    //let list: PyObject = var.into_py(py);
    let my_model = py_model.as_ref(py);
    my_model.call_method("set_variables", list, None).unwrap();
}
```

**Comment by birkenfeld** [comment]
The argument to `call_method` needs to be a tuple of arguments, so `call_method("set_variables", (var,), None)` should do it without further `to_object` or `into_py` conversion.

**Comment by Nateckert** [comment]
Hi,

I managed to make it work how I intended it ! Thanks a lot for the help.
I made a small contribution to the documentation on the parts I struggled with: https://github.com/Nateckert/pyo3/tree/doc_trait_exposition

I also wrote an appendix C to the guide.

However I have some remaining questions:
- I was wondering if adding `crate-type = ["cdylib"]` to the cargo.toml file changed anything to the crate for user not using the Python bindings. Does it changes the performance or other aspects in any ways ? (Except the added required dependancies to PyO3 and to Rust nightly)
- Am I correct to assume that we cannot pass references in-between Rust and Python ? I tried first to interface a function have as signature `fn(&Vec<f64>)` and it did not worked.
- In the appendix, I also tried to add the `[#classmethod]` annotations and it did not work. I was wondering what was the use case for that. 

Last but not least, is there a specific branch I should target for the pull request ?

Thanks a lot !

**Comment by davidhewitt** [comment]
Great news @Nateckert ! For any PRs please target the `master` branch.

In reponse to your questions:

> I was wondering if adding crate-type = ["cdylib"] to the cargo.toml file changed anything to the crate for user not using the Python bindings. Does it changes the performance or other aspects in any ways ? (Except the added required dependancies to PyO3 and to Rust nightly)

Yes, it will mean that other Rust projects using your library will have to link against the `.so` file rather than include your library directly as normal. You might want to consider using both `crate-type = ["cdylib", "rlib"]` so that Rust users can use the `rlib` (the default lib crate type) - but I have to confess I'm not sure if that comes with other downsides...

> Am I correct to assume that we cannot pass references in-between Rust and Python ? I tried first to interface a function have as signature fn(&Vec<f64>) and it did not worked.

Yes, `Vec` does not exist in Python so pyo3 will always have to create a new `Vec` from the python list before calling your function. Maybe as a convenience we could pass you a reference to that new `Vec`. At least at the moment it helps make the cost of making the new `Vec` more obvious.

For `#[pyclass]` it is possible to use references from Python to Rust.

> In the appendix, I also tried to add the [#classmethod] annotations and it did not work. I was wondering what was the use case for that.

`#[classmethod]` is supposed to do the same as `@classmethod` would in Python. Can you open an issue with the code which "did not work" as this could be a bug?

**Comment by Nateckert** [comment]
Thanks for the answers !

For the `#[classmethod]`, I thought it was just working with any methods of a class. I didn't realize it was the equivalent of the `@classmethod` decorator in Python.
I added that part in the guide.
