### ISSUE TITLE
Audit Py<T> methods for GIL safety

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3#949]
As part of the invariant that `Py<T>`'s data can only be accessed when the GIL is locked, all the member functions should either acquire the GIL or take a GIL token as an argument. [`Py::get_refcnt`](https://pyo3.rs/master/doc/pyo3/struct.Py.html#method.get_refcnt) and several of the `unsafe` functions doesn't appear to lock the GIL internally.

Note that it _is_ Undefined Behavior to read the reference count using a plain memory read (what `ffi::Py_REFCNT` does) while a different thread is concurrently modifying it, making `get_refcnt` have safety issues.

_Originally posted by @programmerjake in https://github.com/PyO3/pyo3/pull/948#issuecomment-637353345_

Proposed actions to resolve this:

- Add `Python` token as an argument to all safe function that require the GIL.
- Add `# Safety` documentation to all unsafe functions that require the GIL. (Or alternatively add `Python` token argument to them too.)

**Comment by programmerjake** [comment]
There are similar issues for [`PyObject::get_refcnt`](https://pyo3.rs/master/doc/pyo3/struct.PyObject.html#method.get_refcnt) and probably other member functions.
