### ISSUE TITLE
Exposing PyClass for import 

### ISSUE THREAD

**Issue by SerialDev** [PyO3/pyo3#96]
I have had some trouble with importing a struct and its related implemented methods.
Is there any particular pattern I should follow to import from python. 
I have worked with functions fine thus far.
```
#[py::class]
struct test{}

ImportError: dynamic module does not define module export function (PyInit_collectors)


```

**Comment by fafhrd91** [comment]
What version on python do you use?

**Comment by fafhrd91** [comment]
Did you define your module with `#[py::modinit]`?

Here is example https://github.com/PyO3/pyo3/blob/master/examples/word-count-cls/src/lib.rs#L86

**Comment by fafhrd91** [comment]
re-open if you will still get error

**Comment by SerialDev** [comment]
Thanks I had not noticed add_class which is found in that example. That solves the problem

 m.add_class::<RS>()?;
