### ISSUE TITLE
nan == nan is True when other is the same object as self

### ISSUE THREAD

**Issue by tamuhey** [PyO3/pyo3#985]
## 🐛 Bug Reports

When reporting a bug, please provide the following information. If this is not a bug report you can just discard this template.

### 🌍 Environment

 - Your operating system and version: MacOS Mojave 10.14.6
 - Your python version: 3.7.4
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: virtualenv
 - Your Rust version (`rustc --version`): 1.46.0-nightly (feb3536eb 2020-06-09)
 - Your PyO3 version: 0.10
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: Yes

### 💥 Reproducing

```rust
use pyo3::prelude::*;

fn main() {
    let gil = Python::acquire_gil();
    let py = gil.python();
    let a = py.eval("float('nan')", None, None).unwrap();
    // nan == nan must not be Equal, but this test fails.
    assert_ne!(a.compare(a).unwrap(), std::cmp::Ordering::Equal);
}
```

This will fail with the below command

```
$ cargo run
```
```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `Equal`,
 right: `Equal`', src/main.rs:8:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is the repo to reproduce: https://github.com/tamuhey/pyo3_nan_bug

**Comment by kngwyu** [comment]
Thanks, looks it is because of the pointer comparison at https://github.com/python/cpython/blob/3.8/Objects/object.c#L789 :thinking:

**Comment by tamuhey** [comment]
so, is it a cpython's bug?

**Comment by kngwyu** [comment]
https://docs.python.org/3/c-api/object.html?highlight=pyobject_richcomparebool#c.PyObject_RichCompareBool
Looks like that it's intended.

**Comment by tamuhey** [comment]
So `PyObject_RichCompareBool` is not consistent with `PyObject_RichCompare`... very tricky.
Thanks for info!
